.github/coverage.sh
.github/workflows/test.yml
README.md

Added test to fail if code coverage is less than 80%
Added ability to manually kick off a workflow from ui
Upload coverage to coveralls
Add code coverage badge to readme
Not sure why github actions isnt running on this pr but since i was testing this code in a private repo i think i have to merge this to get them to start running. Then on future pr's it will work.

github workflow

---

.github/workflows/changelog.yaml

I tested the changelog generation on a repository with a master branch and forgot to set it to "main" when I put it back into WEGO

fix target branch for changelog

---

test/acceptance/test/acceptance_suite_test.go
test/acceptance/test/utils.go

This PR sets the default timeout for eventually assertions to 1 minute.

set eventually default timeout to 1 min

---

test/acceptance/test/smoke_tests.go
test/acceptance/test/utils.go

Changed the test script to make code more reusable

Refactor test script

---

.github/workflows/deploy.yml
.github/workflows/test.yml

The action we were using to start `kind` only worked on Linux; the new one _should_ work on Mac. The explicit kind node image was also remove which should help.

Switch kind action for darwin support

---

.github/workflows/deploy.yml
test/acceptance/test/core_operations_test.go

This PR removes the test from the deploy path (which builds on both OSes) until we can set up kind differently.

The kind GitHub action we're using doesn't work on Darwin

---

.github/workflows/release.yaml

The release process seems to be failing trying to find a previous release. This removes the "since-latest-release" flag to see if it will work for the first release.

try to fix release failure

---

cmd/wego/flux/cmd.go
pkg/cmdimpl/add.go
test/acceptance/test/smoke_tests.go

We no longer need to use `--` after a flux command.

Disabling argument parsing on flux command

---

.github/workflows/release.yaml

There was an error that unshallow didnt make sense with a fetch depth of 0. According to goreleaser docs fetch depth needs to be set so lets hope this works.

fix release try 2

---

.github/workflows/docker_scan.yaml
.github/workflows/test.yml
package-lock.json

Fixes the broken build on main. From slack:
> the issue is that snyk is looking at the package-lock.json file during a golang job, which is kinda weird. There are "forced" reconciliations that happen on install to avoid vulnerabilities that Snyk doesn't pick up because it doesn't do the install.
This PR removes the offending UI stuff from a job that scans golang files.

Update snyk job to handle npm deps

---

Makefile
cmd/wego/add/cmd.go
pkg/cmdimpl/add.go
pkg/cmdimpl/add_test.go
test/acceptance/test/core_operations_test.go

In order to wrap the `.Add()` action in a HTTP server, we will need the individual steps to return errors instead of exiting the program. This PR is a first pass at that behavior.
We may need to pass in an `io.Writer` to capture logs in the future, but for now logging via `fmt` is probably fine.

Change .Add() to return an error

---

.github/pull_request_template.md

I tend to ask similar questions on many of the PRs I review and thought others might do the same. So I thought having a PR template might help streamline our reviews.

Add initial pr template.

---

cmd/wego/main.go
cmd/wego/version/cmd.go
test/acceptance/test/smoke_tests.go

Added a version check that runs after every command and adds flux version to version command.  https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/189

Add version check on every command

---

cmd/wego/main.go
cmd/wego/status/cmd.go
pkg/cmdimpl/add.go
pkg/cmdimpl/status.go
test/acceptance/test/add_tests.go

- change on wego add and wego status to be:
wego app add
wego app status
- Fixes to support two ways of defining an application location
1.- using url flag
2.- using the location argument
Easier for the user and it avoid sthe need of having a repo cloned so it can be added.
Tests were manually with the different options involved. For `wego app add ` in the first scenario I used only the URL and a second one using just the location argument. All results were as expected.
Changes in the use of add and status:
`wego add` --> `wego app add...`
`wego status` -- > `wego app status...`

Added subcommand app and fixes on giving the app location

---

cmd/wego/add/cmd.go
pkg/cmdimpl/add.go
pkg/cmdimpl/add_test.go

Added ability to add helm manifest through helm repo. 
Unit tests and tested myself
Command looks like `wego app add . --url=https://grafana.github.io/helm-charts --name=graf1  --chart=loki`

helm repo source

---

.github/workflows/test.yml
cmd/wego/add/cmd.go
pkg/cmdimpl/add.go
pkg/cmdimpl/add_test.go
pkg/fluxops/fluxops.go
pkg/utils/commands.go
test/acceptance/test/add_tests.go
test/acceptance/test/install_tests.go
test/acceptance/test/utils.go

- We no longer create a wego repository
- no more "private" flag
- We have three automation config options:
- none (only place automation in cluster; no persistent storage)
- URL (place automation in external repository -- like our old default but no auto-creation), 
- "" (use the user's app repository)
- Dry run test correctly handles new git client
**Why?**
This is the design favored by the CTO that she will demo at GitOps days
- Tested locally
- Added unit tests
N/A
Yes, the getting started guide will need to be updated

Support all three config modes

---

pkg/cmdimpl/add.go
pkg/cmdimpl/add_test.go
pkg/git/git.go
pkg/git/gitfakes/fake_git.go
pkg/git/gogit.go
pkg/git/gogit_test.go

We no longer gather up all files in a user's repo when committing .wego contents. This isn't the final solution. It wasn't clear how to avoid committing files already in the index. With this change, though, only files in the index will be picked up.
**Why?**
We shouldn't update the user's repository behind her back
Tested locally and new gogit unit test

Don't add files in user repo to commit when committing .wego contents

---

cmd/wego/add/cmd.go
pkg/cmdimpl/add.go

We now use a generated deploy key for flux but allow specification of an ssh key to talk to git repositories over ssh. 
**Why?**
By default, darwin does not store the user's default ssh key in the ssh-agent so we need to allow it to be specified.
It's tested every time we run `wego app add` (particularly on darwin)

Look in well known locations for ssh key file or allow the user to specify it's path on the command line

---

.goreleaser.yml

Use only one arch for each os type

Avoid multiple arch builds on an os competing

---

Makefile

Makefile target "install" sends wego binaries to ${GOPATH}/bin instead of .../weave-gitops/bin/
**Why?**
Original binary output wasn't in most developers PATH
Ran `make install` and verified that binaries are correctly being installed in ${GOPATH}
Users who've previously used `make install` should migrate binaries from old path to ${GOPATH)
There are currently no documents covering this.

Make install should put binaries in "${GOPATH}/bin"

---

pkg/git/gogit.go
pkg/git/gogit_test.go

Filters for commit now use only the file path relative to the root of the repo.
It was using an absolute path resulting in the filters skipping files from .wego folder.
I tested it manually using dot and absolute path as the location argument.

Fixed app add using path

---

.github/workflows/release.yaml

Now that we have multiple release, we want the release notes to only contain changes since the previous release.
The `-since-latest-release` flag to `github-release-notes` was removed earlier due to it failing if there was no prior release. Now we're adding it back.
**Why?**
So the release notes for Weave GitOps accurately reflect the latest changes.
I will test it by generating a test release once it is in place.
No
No

Limit changes in release notes to changes since the previous release

---

cmd/wego/add/cmd.go
go.mod
go.sum
pkg/services/app/add.go

- Fixes #357 
- When the user's private key is encrypted, it now prompts a message asking for the password
**Why?**
- wego failed to proceed without the private key password
- `wego app add --branch main --path kustomize --name my-app --url ssh://git@github.com/stefanprodan/podinfo.git --dry-run`

Reading private key password

---

pkg/services/gitops/uninstall.go
pkg/services/gitops/uninstall_test.go

- closes #400 
- Checking if wego is installed before uninstalling
**Why?**
- To avoid unclear error when trying to delete wego resources
- in a clean cluster run `wego gitops uninstall`

Early exit if wego is not installed when uninstalling

---

pkg/gitproviders/common.go
pkg/gitproviders/common_test.go
pkg/gitproviders/gitprovidersfakes/fake_git_provider_handler.go
pkg/services/app/add.go
pkg/services/app/add_test.go

Also, check if deploy key exists before creating flux secret...
- We were attempting to create a deploy key at the top of `Add`, before we determined the source type. Deploy keys are not meaningful for helm repositories, so the creation failed
- We created a flux secret for the deploy key before determining if the key already existed; this overwrote the secret containing the key in the cluster but we did not associate the new key with the repository
**Why?**
To fix the use of helm repositories and ensure we did not corrupt the flux secret for the repo if we added another app.
Tested locally
No
No

Do not attempt to create deploy key for helm repositories

---

pkg/cmdimpl/status.go
pkg/cmdimpl/status_test.go

fixes #371 
- We now match the explicit app name rather than just looking for a prefix
- We now tell the user that no app was found if we get no matches rather than an obscure error
**Why?**
To make status more useful for the user
Tested locally
No
No

Fix status when multiple kustomizations or helm releases share a prefix

---

pkg/gitproviders/cache/github.yaml
pkg/gitproviders/cache/gitlab.yaml
pkg/gitproviders/common.go
pkg/gitproviders/common_test.go
pkg/kube/kube.go
pkg/kube/kubefakes/fake_kube.go
pkg/services/app/add.go
pkg/services/app/add_test.go

We now recreate a deploy key if the cluster does not have a matching secret
**Why?**
If a user recreates her cluster, it will fail if the app repo has already been used and has an existing deploy key
Unit tests
No
No

Fix a fresh cluster with a repo that already has a deploy key

---

Makefile
go.mod
go.sum
tools/tools.go

`make unit-tests` will now work on a completely clean environment.
`make clean` will now remove the ui/dist embed files
**Why?**
When cloning a new version of the repo the unit-tests would fail due to the missing ui/dist directory needed for embedding. This will make it easier for new developers.
I ran the make commands locally.
No
No

Update make unit-tests and clean targets

---

pkg/kube/kube.go
pkg/services/gitops/install.go
pkg/services/gitops/install_test.go

- fixes #395 
- Properly checking cluster status in the install command
**Why?**
- wego was returning a misleading message when it couldn't talk to the cluster.
`kind delete cluster --name wego`
`wego gitops install`

Properly checking cluster status in the install command

---

pkg/services/app/add.go

We no longer consult the source type parameter when deciding whether or not to create a deploy key in the external repo case. For a helm repository, we were failing to create a deploy key, even though the config repository is necessarily a git repository.
**Why?**
To correct the behavior when adding an upstream helm repository with an external configuration repository
I tested it locally and there will be a new acceptance test going back shortly (which exposed the issue).
No
No

The external config repository is always SourceTypeGit -- we shouldn't use the source type parameter

---

.github/workflows/docker_scan.yaml
Makefile

Adds some specificity to the `Makefile` to avoid rebuilding UI assets on every `make unit-tests`. Also refactors to be smarter about building assets in general.
Edit: The scope has expanded to remove the Docker Scan job, as it was superfluous. I chatted with @josecordaz about it before proceeding.

Skip building UI on unit-tests target

---

.github/workflows/nightly.yaml

the default timeout for nightly jobs
**Why?**
As the acceptance test suite is getting richer, it needs a bit more time to complete in nightlies.

remove timeout restrictions

---

api/v1alpha1/application_types.go
go.mod
pkg/services/app/add.go
pkg/services/app/add_test.go
pkg/services/app/app_suite_test.go
pkg/services/app/get_test.go

Changes our templating implementation to use the struct. This will ensure that any changes to the CRD will be reflected in the file that gets applied/saved.
The scope of this PR has expanded to move the `app_test` package into the `app` package to allow for testing private functions. This was necessary to add test coverage for things like the app hash label.
Shout-out to @bigkevmcd for the `cmp` package for struct comparison

Use go struct and yaml marshalling for adding applications

---

pkg/kube/kube.go
pkg/kube/kube_test.go

We now decide whether or not we can talk to the cluster by actually checking for an error message indicating that we can't
**Why?**
The check for the `core-dns` deployment was unreliable; not every cluster has it running
unit tests
The nightly will also test this
No
No

Check for an error directly indicating we couldn't talk to the cluster

---

go.mod
go.sum
pkg/gitproviders/common.go
pkg/gitproviders/common_test.go
pkg/gitproviders/gitprovidersfakes/fake_git_provider_handler.go
pkg/services/app/add.go
pkg/services/app/add_test.go
test/acceptance/test/add_tests.go
test/acceptance/test/utils.go

addresses https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/374 outputs the pr link to the cli output.
use the cli output to merge the pr in the test

add prlink to cli output

---

doc/adr/0004-no-repo-creation.md

Added a new ADR documenting the decisions to forgo repo creation
**Why?**
We have encountered many environments that prohibit repo creation in their git organization
N/A
N/A
N/A

Document decision to forgo repo creation

---

.github/workflows/deploy.yml
.github/workflows/nightly.yaml

Related to #450 
The `nightly` and `deploy` jobs had old `make` targets and were failing without a `clean` to trigger a full build.

Add makefile clean to workflows

---

cmd/wego/app/status/cmd.go

SilenceUsage and SilenceError were both incorrectly indent in the `cmd/wego/app/status/cmd.go`
**Why?**
General hygiene 
Compiled and validated use of the `wego app status` command (which worked previously despite the indentation issue)
NO
NO

fix_indentation_issue

---

.github/workflows/release.yaml

Now that we don't always download dependencies, the release process failed as it wasn't getting a flux binary from which to obtain a version. This adds the `-B` flag so that we always download.
**Why?**
So releasing will work
Built a release in a fork
No
None.

Add -B to "make dependencies" so the release process has a flux binary from which to get a version

---

pkg/services/app/add.go

Changed the grammar on a couple of error messages in app add path.  Also, we had an error message that was incorrect.  Additionally, I replaced errors.wrap with fmt.Errorf in the file.
**Why?**
The error message as written was confusing and one was incorrect.  Replaced the errors.Wrap with the standard go error wrapping.
Executed the unit tests.
no
N/A

Fix grammar error message

---

pkg/kube/kube.go
pkg/kube/kube_test.go

Sanitized the cluster names, which comply now with RFC 1053 naming used by K8s
**Why?**
Creating clusters with invalid cluster names would cause failures
Create unit-test case for this with a number of examples.
Probably should add language about the validation possibly changing the cluster name in weave-gitops-docs

Sanitize cluster name

---

pkg/services/app/add.go
pkg/services/app/add_test.go
pkg/services/app/app.go
pkg/services/app/status.go
pkg/services/app/status_test.go

Closes #507 
We were declaring `SourceType` and `DeploymentType` in both the `wego` package, as well as in the `services/app` package. This removes the `services/app/ declarations in favor of the `wego` ones.

Use wego pkg constants instead of redeclaring

---

cmd/wego/app/add/cmd.go

The `--source-type` arg was added naively here #497 . We already fill out this parameter elsewhere by detecting the `--chart` argument

Remove source-type CLI arg

---

pkg/kube/kube_test.go
pkg/services/app/add.go

Fix #532 
It now sanitize config repository urls when `chart` parameter is passed in.
**Why?**
Using different formats on repository config urls was causing auth issues in flux when trying to clone them. 
Manually adding two helm charts using different url formats. It worked as expected.

532 Sanitize config url for helm cases

---

pkg/flux/flux.go
pkg/flux/flux_test.go
pkg/git/gitfakes/fake_git.go
pkg/gitproviders/gitprovidersfakes/fake_git_provider.go
pkg/gitproviders/provider.go
pkg/gitproviders/provider_test.go
pkg/services/app/add.go
pkg/services/app/add_test.go

Resolves #551 
If a user provides a public repository to wego, we no longer create a deploy key; instead, we hand `flux create source git` an `http` URL and don't create a secret
**Why?**
It's basically wrong to require creation of an unnecessary key and the current exclusive use of ssh URLs prevents adding an app from an upstream public repository (like sock-shop) for which we have no associated SSH keys.
Manually adding the sock-shop app from the `github.com/microservices-demo/microservices-demo.git` repository
Users would not have to change anything but some scenarios would now work that would have failed in the past
No

Don't create a deploy key for a public repository

---

pkg/server/server_test.go
pkg/server/suite_test.go
tools/testcrds/kustomize.toolkit.fluxcd.io_kustomizations.yaml
tools/testcrds/source.toolkit.fluxcd.io_buckets.yaml
tools/testcrds/source.toolkit.fluxcd.io_gitrepositories.yaml
tools/testcrds/source.toolkit.fluxcd.io_helmcharts.yaml
tools/testcrds/source.toolkit.fluxcd.io_helmrepositories.yaml

The "sigs.k8s.io/controller-runtime/pkg/envtest" library provides the ability to test against a closer-to-reality version of kubernetes. It will catch certain classes of bugs around creating objects and validating object spec/labels/annotations, etc.
We already use this in the `kube` pkg tests, so no additional setup is required.

Use k8s env when doing server tests

---

cmd/wego-server/main.go
go.mod
go.sum
pkg/logger/logger.go
pkg/middleware/middleware.go
pkg/server/server.go
pkg/server/server_test.go
pkg/vendorfakes/logr/fake_logger.go

Closes #515 
Adds middleware to log when error messages occur. In development mode, a human-readable stack trace is printed on `log.Error`:
In prod mode, this will be a one-line log entry.
@luizbafilho I won't pretend to understand how these log levels are supposed to work. I doubt the objective is to do the `Debug`, `Warn` and `Error` levels like I have done here. Any guidance on the subject is appreciated.
Unit tests for the middleware were added to the `server` package. It wasn't clear to me how to test the middleware logic outside of a generated gPRC server. Yet another instance of gRPC making everything slightly harder. As a result, concerns are not as separated as they would be ideally, at least we have the coverage.
Also if there is a way to do this style of logging: `status=400 …

Add API server logging  middleware

---

api/v1alpha1/application_types.go
cmd/wego/app/add/cmd.go
cmd/wego/main.go
manifests/crds/wego.weave.works_apps.yaml
pkg/flux/flux.go
pkg/flux/flux_test.go
pkg/flux/fluxfakes/fake_flux.go
pkg/services/app/add.go
pkg/services/app/add_test.go
pkg/utils/common.go

Resolves #472 
We now support passing `--helm-release-target-namespace <ns>` to specify the namespace in which to deploy a helm chart. We also apply standard Kubernetes validation to all namespace arguments.
**Why?**
It's unreasonable to ask users to edit their generated `HelmRelease` resources to add a target namespace and that isn't even possible in the `config=NONE` case.
Unit tests and installed `sock-shop` from a helm chart; prior to the fix, all the pods were in the `wego-system` namespace.
No changes to user environments are required.
The new argument should be documented in the CLI reference.

add --helm-release-target-namespace for helm releases and validate all namespaces

---

cmd/wego/app/add/cmd.go
go.mod
go.sum
package-lock.json
pkg/auth/auth.go
pkg/auth/github.go
pkg/auth/github_test.go
pkg/git/git.go
pkg/git/gitfakes/fake_git.go
pkg/git/gogit.go
pkg/gitproviders/provider.go
pkg/gitproviders/provider_test.go
pkg/osys/osys.go
pkg/services/app/add.go
pkg/services/app/app.go
pkg/utils/common.go
pkg/utils/common_test.go

Adds an authentication flow to the `wego app add` command.
Key notes:
* Removes the `ssh` key lookup entirely from the `add` command. Instead, we use a personal access token or temporary access token obtained via the CLI auth flow. Other `git` operations can be done with the deploy key that we push up.
* Lays the ground work for other Git Provider auth flows to be added
* This represents the first step to enabling API/UI auth
**To test, ensure you unset your `GITHUB_TOKEN` env variable**
Here is what the user will see when they run the command without a `GITHUB_TOKEN` set:
```
$ wego app add .
Visit this URL to authenticate with Github:
https://github.com/login/device
Type the following code into the page at the URL above: 82AB-434E
Waiting for authentication flow completion...
```
Then …

Add Github Auth Device Flow

---

.github/workflows/repostats.yaml

Fixes: #534
Following largely fluxcd/community#109 to allow us to track information of how many clones/stars/etc weave-gitops gets.
If we want additional repos to be tracked, this can be done easily.
We need to add an empty branch called 'github-repo-stats' to get this set up.

Add GH Workflow for github-repo-stats

---

doc/adr/0001-record-architecture-decisions.md
doc/adr/0002-api-definitions-grpc.md

Start of ADRs on API standardisation
**Why?**
Recommendation to make it easier to build standard, interoperable clients.

Initial ADR for API definitions with gRPC.

---

cmd/wego/flux/cmd.go
test/acceptance/test/flux_tests.go

Resolves #615 
The `wego flux` command wasn't reading Stdin so flux commands that prompted the user failed. Now the command has Stdin, Stdout, and Stderr attached.
**Why?**
So that interactive flux commands will work correctly
I ran the bug scenario by hand before and after
No
No

Connect Stdout and Stderr to "wego flux" commands

---

cmd/wego/app/remove/cmd.go

Resolves #641 
We no longer panic if `wego app remove` is called with no arguments
Tested by hand as we don't have unit tests for the cobra command wrappers; in this case, we now use cobra facilities to require that at least one argument is present.
No
No

Use cobra to require at least one argument for remove

---

pkg/utils/common.go
pkg/utils/common_test.go

Resolves #576 
`utils.WaitUntil` is now a wrapper around a `timedRepeat` function that accepts a time updater. The tests use reliable addition-based updaters while `utils.WaitUntil` passes in:
```
func(currentTime time.Time) time.Time {
time.Sleep(poll)
return time.Now()
},
```
**Why?**
So that unit tests won't fail due to an unusual timing delay
The unit tests were updated to test the actual repeat and check functionality with reliable updaters.
No
No

Make wait tests reliable by abstracting out the time update

---

.github/workflows/release.yaml
Makefile
package.json
ui/App.tsx
ui/hooks/__tests__/navigation.test.tsx
ui/hooks/navigation.ts
ui/lib/theme.ts
ui/pages/ApplicationDetail.tsx

Closes #625 
Ensures we don't directly rely on the URL so that components can be used in any environment.
Also adds a `typedefs` job to publish typescript types to the `npm` module.

Ensure exported components don't reference the URL directly

---

test/acceptance/test/utils.go

Closes: 
Using a regular expression to ignore the differences on default paths when using `git init`
**Why?**
When initializing folders using `git init`, it returns different paths for different scenarios:
- Running tests locally returns `Initialized empty Git repository in /private/tmp/wego-test-app-l0obud5k/.git/`, notice `/private`
- Running tests on PRs returns `Initialized empty Git repository in /tmp/wego-test-app-l0obud5k/.git/`, notice `/temp`
- Running tests on Nightly returns `Initialized empty Git repository in /tmp/wego-test-app-l0obud5k/.git/`, notice `/private`
Manually locally and using tests suites triggered by CI.

Remove check to differentiate between /private or /tmp

---

package.json

- package.json specified ^4.11
- package-lock.json specifies 4.12
- 4.12 introduced new stuff we're now using (`createTheme` instead of `createMuiTheme`)
Closes: #689 
Material-ui version in package.json now better reflects the code dependencies.
**Why?**
So we can consume the npm package more easily in other projects without them having to override things.
`npm install` and check `package-lock.json` hasn't changed

Aligns material-ui versions in lock/package.json

---

package.json

Closes: #690 
Splits parcel build into multiple build targets, the library one now exposes commonjs and doesn't bundle react and node_modules.
**Why?**
As far as I understand it `parcel` infers how you want to build something based on what package.json looks like.
- If `main` is declared in `package.json` then it flips into "library mode" https://v2.parceljs.org/features/targets/#library-targets and builds commonjs artifacts
- However if `main` is declared then you get funny build errors when trying to build the wego UI..
I'm not sure if you can have a single package.json that builds for ui _and_ library. (?) There are build flags that you can pass to `parcel build` to customize things, but some required options are missing like `outputFormat: commonjs`.
Using `targets` …

Adds multiple build targets and configurations to package.json

---

.github/workflows/upgrade-flux.yaml

Closes #377 
Uses the `GITHUB_TOKEN` default to create a PR on a cron job.

Remove token arg

---

ui/components/LoadingPage.tsx
ui/components/Page.tsx
ui/index.ts

The UI is also exporting the `useApplications` hook and `LoadingPage` now. 
Updated Loader style to match what we do in WE in terms of wrapping content. 
**Why?**
The export is needed in WE to have access to the number of applications.
The LoadingPage will be used in WE instead of what we have atm to ensure consistency.

Add useApplications to the UI exports

---

cmd/wego/gitops/cmd.go
pkg/apputils/utils.go
pkg/kube/kubehttp.go
pkg/services/gitops/gitops_suite_test.go
pkg/services/gitops/install_test.go
pkg/services/gitops/uninstall.go
pkg/services/gitops/uninstall_test.go
test/acceptance/test/install_tests.go

Closes: #677 
`wego gitops uninstall` used to check for a complete wego installation before continuing. This prevented removing a partial installation.
**Why?**
So a failed installation can be undone
Unit and integration tests
No
No

Update "wego gitops uninstall" to run to completion even if original install failed

---

Makefile
package-lock.json

There was an issue where `npm ci` seemed to not run `force-resolutions` as expected. This change makes it explicitly called in the `make all` target.
`force-resolutions` is used to avoid security vulnerabilities in our JS third-party packages.

Fix non-deterministic behavior between `npm i` and `npm ci`

---

.github/workflows/test.yml
.gitignore
Makefile
test/library/libtest.dockerfile
test/library/test.sh
ui/index.ts

Closes #691
Adds a test that will report when the "public" API for `wego` go libraries break consuming implementations.
To test, rename something like the `server.DefaultConfig()` function and see the `make lib-test` target fail with an exit code of 2.
Uses this repo as a reference implementation: https://github.com/weaveworks-gitops-test/wego-library-test
Output looks like this when something breaks the API contract:

Add dockerized library integration tests

---

pkg/flux/flux.go
pkg/flux/logs_test.go
pkg/flux/setup.go
pkg/osys/osys.go
pkg/osys/osysfakes/fake_osys.go

Closes: #757 
We now allow the flux binary used during `weave-gitops` setup to be specified via an environment variable so that the `weave-gitops` code can be used as a library. The flux binary is currently stored as an embedded binary which does not propagate when pulled via `go.mod`. After pulling the code as a module, setting `WEAVE_GITOPS_FLUX_BIN_PATH` to point at a flux binary will cause the referenced binary to be installed for use by weave-gitops.
**Why?**
To allow the code to be used as a library
Unit tests
No
No

Allow flux binary to be overridden via an environment variable at setup time

---

pkg/flux/bin/flux
pkg/flux/bin/go_embed_fs_cannot_be_empty.txt
pkg/flux/setup.go

Closes: #757 
Switch `go:embed` from `[]byte` to file-system.
- So we can deal w/ flux being missing at runtime instead of build time
- This allows us to build weave-gitops as a dep as flux will always be missing in that context.
**Why?**
Before this change we see this error:
```bash
git clone https://github.com/weaveworks-gitops-test/wego-library-test.git
vim go.mod # remove replace directive
go get -d github.com/weaveworks/weave-gitops@a92de7749f97e36ca52784b7480e59820b988fba
go build main.go
../../go/pkg/mod/github.com/weaveworks/weave-gitops@v0.2.6-0.20210914212909-a92de7749f97/pkg/flux/setup.go:11:12: pattern bin/flux: no matching files found
```
If the filesystem is completely empty we still get:
```bash
go get -d …
```

Switch `go:embed` to use a file-system to check flux binary at runtime rather than build time

---

pkg/services/auth/auth.go
pkg/services/auth/auth_test.go

Closes: #758 
- Removing visibility validation when creating deploy keys
**Why?**
we were not able to clone via ssh without an ssh key, which only works in public repositories if using the HTTP endpoint.
To overcome that I removed the repository visibility check that avoids uploading the deploy key to the repo, so it doesn't fail, and even if cloning worked we would have hit another issue when using the auto-merge flag since it would be required anyway to have an ssh key to push code. 

Removing visibility validation

---

ui/components/DirectedGraph.tsx

Fixes a problematic `new` statement that was giving `parcel` issues parsing and bundling the file.

Disambiguate dagred3 graph creation

---

.github/workflows/release.yaml
Makefile

This undoes the beginning of moving our UI image to `gitops-app` from `wego-app`. There are a variety of other things to update in that move.
**Why?**
So that a released version works correctly
There are current no tests that are affected by this as the image is only pushed during release. The wego-app deployment always fails with an `ErrImagePull` (this should be fixed with the addition of `garden.io`)
No
No

Leave image as wego-app until we completely purge "wego"

---

.github/workflows/release.yaml
.github/workflows/test.yml
Dockerfile
manifests/manifests.go
manifests/manifests_test.go
pkg/services/gitops/install.go

Having an `ErrImagePull` state on a pod seems to slow down tests by double. This fix ensures a `latest` tag is pushed during a release (although users should be discouraged from using that tag).
For acceptance tests, they will pull down the `latest` tag for now as a stop gap. I have already pushed a `latest` image from my laptop so that we don't have to wait for a release for the tag to be present.
Also fixes an error in the FE docker image build where `npm install` was being used incorrectly.

Pass version to deployment template as argument

---

.github/workflows/upgrade-flux.yaml

We will realistically only upgrade flux once per release, and we release every two weeks. A once-a-week check should be fine. This cron expression is `At 00:00 on Sunday.`

Only check for flux upgrades once a week

---

manifests/crds/wego.weave.works_apps.yaml
manifests/wego-app/deployment.yaml
manifests/wego-app/role-binding.yaml
manifests/wego-app/role.yaml
manifests/wego-app/service-account.yaml
manifests/wego-app/service.yaml
test/acceptance/test/add_tests.go
test/acceptance/test/utils.go

Added assertion to integration test using non-default ns to make sure it fails when error output is not empty
Closes: #776 
Removed wego-system ns from wego-app manifests
**Why?**
It was causing an error at installation time when using a namespace different from the default
Manually and  by fixing the integration test for this particular case

Removed namespace from wego-app manifests

---

.github/workflows/release.yaml
.goreleaser.yml

`goreleaser.yaml` still had "wego" as the binary name. Docker push `tags:` is a CSV list

Fix goreleaser binary and docker push job

---

pkg/services/auth/auth_suite_test.go
pkg/services/auth/auth_test.go

On recommendation from @hiddeco, Uses a lighter `fake` client. Hopefully reduces the incidents of `cannot listen: port already in use'

Use fake k8s client instead of full etcd cluster

---

cmd/gitops/ui/run/cmd.go
pkg/services/auth/auth.go

Closes #812 
The `gitops ui run` command wan't using the latest application handler where we have all of our auth middleware. This would have been missed when testing with the API server and dev frontend.

Fix Github auth when running from `wego ui run`

---

README.md

Closes: #826 
Updated the README to point to the license scan report instead of the project
**Why?**
Linking to the project requires users to log in to see the report.  Linking to the report allows them to see a preview of the report and download a complete version.
Previewed the readme file, copied the link to the report, opened an incognito window, pasted the link, viewed and downloaded the report
No
None - other than this is an update to the README.

Link to license scan report instead of the project

---

go.mod
pkg/services/auth/github.go
pkg/services/auth/github_test.go

Closes: #782
Adds logic to retry after a `slow_down` message from GH, with a back off interval. This required a more significant refactor to make it more easily testable. This [clock](https://github.com/benbjohnson/clock) package was very useful for mocking out time.

Fix Github device-flow retry logic and add test coverage

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/get/cmd.go
cmd/gitops/get/credentials/cmd.go
cmd/gitops/get/templates/cmd.go
pkg/adapters/http.go
pkg/adapters/http_test.go
pkg/capi/capi.go
pkg/capi/capi_test.go

Closes: weaveworks/weave-gitops-enterprise#92
Add `gitops get credentials` command
**Why?**
This is part of the ongoing effort to move enterprise commands into the gitops binary.
Tested locally + unit tests
A new command will appear: `gitops get credentials`
Follow-up PRs are needed to update the docs accordingly.

Add `gitops get credentials` command

---

cmd/gitops/app/cmd.go
cmd/gitops/main.go
cmd/gitops/resume/app/cmd.go
cmd/gitops/resume/cmd.go
cmd/gitops/suspend/app/cmd.go
cmd/gitops/suspend/cmd.go
test/acceptance/test/add_tests.go

Part of: #858  
`gitops app pause` becomes `gitops suspend app`
`gitops app unpause` becomes `gitops resume app`
**Why?**
This is part of the decision to change commands from `noun verb` to `verb noun`
Tested locally
CLI breaking changes: 
- `gitops app pause` has become `gitops suspend app`
- `gitops app unpause` has become `gitops resume app`
Should be updated automatically

Move `app pause`/`app unpause` to `suspend app`/`resume app` respectively

---

cmd/gitops/app/cmd.go
cmd/gitops/get/app/cmd.go
cmd/gitops/get/cmd.go
test/acceptance/test/add_tests.go
test/acceptance/test/help_tests.go
test/acceptance/test/utils.go

Part of: #858  
`gitops app list` becomes `gitops get apps`
**Why?**
This is part of the decision to change commands from `noun verb` to `verb noun`
Tested locally
CLI breaking change: `gitops app list` has become `gitops get apps`
Should be updated automatically

Move `app list` to `get apps`

---

pkg/services/gitops/install.go
pkg/services/gitops/install_test.go

Closes: #993 
* #993 
The beta install command wasn't writing the gitops runtime file into the repo
**Why?**
Need the GitOps runtime stored in the system directory for the cluster.  It's needed to track changes.
Added new unit tests
No
No

FIx beta install to create the GitOps runtime file

---

.github/ISSUE_TEMPLATE/bug_report.md

Update bug issue template to use label `bug`
**Why?**
Auto-assign the bug label when someone chooses that template.
N/a
n/a

Upd bug template to use label 'bug'; ask for flux logs

---

cmd/gitops/app/cmd.go
cmd/gitops/get/cmd.go
cmd/gitops/get/commits/cmd.go
test/acceptance/test/add_tests.go

Closes: #858 
`gitops app <app-name> get commits` becomes `gitops get commits <app-name>`
**Why?**
This is part of the decision to change commands from `noun verb` to `verb noun`
Tested locally
CLI breaking change: `gitops app <app-name> get commits` has become `gitops get commits <app-name>`
Should be updated automatically

Move `app <app-name> get commits` to `get commits <app-name>`

---

pkg/kube/kubehttp.go
pkg/kube/kubehttp_test.go

Closes: #979 
- Replacing `_` with `-` to comply with https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
**Why?**

Replacing undescore with dashs on cluster names

---

tools/update-docs.sh

Closes:
- #973 
The CLI commands are no longer at the top level of the docs; instead, they are under a "CLI Reference" menu item
**Why?**
To make the docs easier to read and navigate
A separate forked repository
No
These are the updates.

Move auto-generated CLI reference under "CLI Reference" menu item

---

pkg/kube/kubehttp.go
pkg/kube/kubehttp_test.go

- Fixes running add-app in-cluster
Closes: #976 
Returns a clusterName if running in cluster instead of a URL
**Why?**
clusterName is interpolated into secret names and other things, URLs break k8s name validation and so breaks the add-app functionality when running in-cluster.
Unit tests!

Fixes add-app in wego-server

---

ui/components/CommitsTable.tsx
ui/components/__tests__/CommitsTable.test.tsx
ui/pages/ApplicationDetail.tsx

Closes #943 
GitHub authorization now properly refreshes the commits table, and removes false authentication error. 
`authSuccess` is now passed as a prop to `CommitsTable`, and included in the commit request `useEffect` dependency array!

Commits show up in UI after authentication success

---

Makefile
README.md
cmd/gitops/root/cmd.go
test/acceptance/test/install_tests.go
ui/pages/ApplicationAdd.tsx

Closes #898 
Changes the description of the namespace field in the UI (ApplicationAdd), as well as the --namespace flag in gitops/root + README.

Clarify the description of "namespace" in the UI and CLI

---

go.mod
go.sum
test/acceptance/test/add_tests.go
test/acceptance/test/ui_tests.go

Changed the way `webDriver` is initialized for MacOS
**Why?**
MacOS now comes with selenium 4 by default in github actions. To have successful test runs, we need to initialize `webDriver` instance differently — depending on the OS in which the test is running. This only affects the UI tests.

Fix selenium for macOS on nightly

---

pkg/gitproviders/provider.go
pkg/gitproviders/provider_org_test.go
pkg/gitproviders/provider_user_test.go

Closes: #1048 
Updated error message.
From:
```
Error: failed to get git clients: error setting up deploy keys: error uploading deploy key: error uploading deploy key multiple errors occurred:
- POST https://api.github.com/repos/stefanprodan/podinfo/keys: 404 Not Found []
- the requested resource was not found
```
To: 
```
Error: failed to get git clients: error setting up deploy keys: error uploading deploy key: no permissions to access this repository or repository doesn't exists
```
**Why?**
There was confusion when distinguishing between if there were not enough permissions and if the repository does not exist.
Added unit tests

Updated error message when hit "not found error" in gitprovider

---

pkg/services/gitopswriter/gitopswriter.go
pkg/services/gitopswriter/writer_add_test.go

Closes: #1062 
We now select the correct default branch before cloning an external config repository
**Why?**
To work correctly with repositories that use different default branches (such as old GitHub ones with `master`)
- Manual tests
- New unit tests
No
No

1062 - Use the correct default config branch for auto-merge

---

.github/actions/run-acceptance-test/action.yml
pkg/services/app/add_test.go
pkg/services/auth/auth.go
pkg/services/auth/auth_test.go
pkg/services/automation/automation_test.go
pkg/services/automation/generator.go
pkg/services/gitops/install.go
test/acceptance/test/add_tests.go
test/acceptance/test/install_tests.go
test/acceptance/test/scripts/kind-multi-cluster.sh
test/acceptance/test/ui_tests.go
test/acceptance/test/utils.go
test/integration/server/add_test.go

Closes: #810 
- Added acceptance test that creates multiple clusters and deploys an app from a single repository to both clusters
- Updated how secret names are generated (removed cluster name and added git provider name)
In the past, we attempted to remove deploy keys that were no longer being used so we included the cluster name in the deploy key name (allowing the deploy key for a single cluster to be removed while leaving others intact). We no longer remove deploy keys and all generated deploy keys have the same name: `wego-deploy-key`. The name genericizing (generification?) process was never extended to the secret names themselves, however, which still included cluster names. This caused no problems until we started trying to deploy an application into multiple …

Add acceptance test for bug #810 and update how secret names are generated

---

package-lock.json
package.json

Closes:  2 dependabot issues
parcel and jest in package.json and package-lock.json
**Why?**
GitHub reported vulnerabilities with ansi-html, and set-value which are used by the older versions of these packages.
I ran the UI manually against my GitOps cluster and ran the UI tests locally.
N/A
N/A

Update jest, parcel for dependabot notice

---

pkg/services/auth/auth.go
pkg/services/auth/auth_test.go
pkg/services/factory.go

Closes: #1050 
Avoid creating deploy key when running `add app` using `--dry-run` flag
**Why?**
To avoid the error "deploy key already exists" when adding the app without `dry-run` flag
Manually and adding a unit test.

Create empty ssh key for git client to avoid creating real deploy keys when using dry-run.

---

.github/actions/run-acceptance-test/action.yml
.github/actions/setup-ssh/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yaml
.github/workflows/test.yml

Copied over the ssh known_hosts fix from https://github.com/weaveworks/weave-gitops-enterprise/pull/312. This fix is in response to https://github.blog/2021-09-01-improving-git-protocol-security-github/. 
If the pipeline passes its good.

Add custom ssh key setup to fix actions

---

ui/App.tsx
ui/components/__tests__/CommitsTable.test.tsx
ui/components/__tests__/GithubDeviceAuthModal.test.tsx
ui/components/__tests__/Page.test.tsx
ui/components/__tests__/RepoInputWithAuth.test.tsx
ui/contexts/AppContext.tsx
ui/hooks/__tests__/applications.test.tsx
ui/hooks/__tests__/auth.test.tsx
ui/hooks/__tests__/navigation.test.tsx
ui/lib/test-utils.tsx
ui/pages/ApplicationDetail.tsx
ui/pages/__tests__/ApplicationDetail.test.tsx

Closes #1034 
A button handling the SyncApplication request has been added to ApplicationDetail, along with unit tests and numerous test-utils changes to facilitate mocking the API. Button is disabled while call is being made, but this state is not held on refresh. 
https://user-images.githubusercontent.com/65822698/142294107-7c1f4078-a35c-4a77-bb54-36f4a5dd696e.mov

Add SyncApplication Button to UI

---

pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go

- We remove the `wego-app.yaml` as that functionality is provided by EE.
- Add a new kustomization that syncs the capi path
**Why?**
- Last pieces of the directory structure ADR that specifies capi paths
- Manually

Adds capi-app when upgrading

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/add/clusters/cmd_test.go
cmd/gitops/cmderrors/errors.go
cmd/gitops/delete/clusters/cmd.go
cmd/gitops/delete/clusters/cmd_test.go
cmd/internal/provider.go
pkg/adapters/http.go
pkg/capi/capi.go
pkg/clusters/clusters.go
pkg/testutils/testutils.go

Closes: weaveworks/weave-gitops-enterprise#203
- Refactored out code that returns the git provider token (either via an env var or via the git provider auth flow)
- Pass the git provider token to the API via an HTTP header
**Why?**
This is so that the Weave GitOps Enterprise API can make calls to the git provider on behalf of the end user.
Tested locally + unit tests
N/A
N/A

Pass user token to API via an HTTP header

---

pkg/clusters/clusters.go
pkg/clusters/clusters_test.go

Closes: 
Updated the if condition for Creation PR status
**Why?**
To ignore printing PR for statuses other than creation and deletion

Ignore showing clusters PR url for statuses other than creation/deletion

---

Makefile
pkg/flux/bin/go_embed_fs_cannot_be_empty.txt

Puts back a file needed to build as a go module originally introduced in https://github.com/weaveworks/weave-gitops/pull/765
**Why?**
It was probably removed as part of a `make clean`, so make sure to preserve that file when doing a `make clean`
Pointing a consumer at this branch

Adds back file required for consuming as a go module

---

pkg/server/server.go

Closes: 
Interpret integer as seconds
**Why?**
It was interpreting the integer as milliseconds instead of seconds, causing unauthorized errors as the token only had a few seconds of validity. 
I manually added an app via UI, getting the next message afterwards:

Fixed adding a Gitlab app via UI

---

cmd/gitops/upgrade/cmd.go
pkg/upgrade/upgrade.go

Closes: #1136 
Changed help text relating to upgrade command and use of ProfileVersion to simply Version
Make it clearer to end users what the intent behind the flag is rather than expose internals.
Relying on existing testing
renamed flag in `upgrade` command from `--profile-version' to `--version`. 
[Complete](https://github.com/weaveworks/weave-gitops-docs/pull/160)

changes ProfileVersion to Version

---

pkg/upgrade/upgrade.go

- Don't try and delete a file for now
- This is okay as we sorted out https://github.com/weaveworks/weave-gitops/pull/1099
Closes: https://github.com/weaveworks/weave-gitops/issues/1124
Don't try and delete the wego-app.yaml for now. Its not causing any issues and now no longer raises reconciliation errors.
**Why?**
go-git-provider gitlab doesn't support deleting files w/ `nil` (maybe it works with an empty string?)
manually

Fixes `gitops upgrade` with gitlab

---

.github/workflows/test.yml
go.mod
test/integration/server/add_test.go
test/integration/server/helpers/fetcher.go
test/integration/server/helpers/helpers.go

Adds some much needed test coverage for GitLab. Only covers the Merge Request case (not auto-merge).
These tests have reached a tipping point IMO and need to be refactored into a table-style test to reduce some of the repetition. I will handle that in another PR, as getting the coverage is more important than making them DRY.

Add integration test coverage for adding an app in a GitLab repo

---

pkg/server/server.go
pkg/services/auth/gitlab_test.go
pkg/services/auth/types/token.go
pkg/services/auth/types/token_test.go
pkg/services/auth/types/types_suite_test.go

Closes: 
Changes to the field `ExpiresIn` in `TokenResponseState`:
- Renamed from `ExpiresIn` to `ExpiresInSeconds`
- Changed type from `int64` to `time.Duration`
Added coverage to the function `SetGitlabTokenResponse`
**Why?**
To communicate better what that field is for.
Added unit tests

Adjustments to field ExpiresIn in TokenResponseState structure

---

Makefile
test/acceptance/test/version_tests.go

- Container builds _in the container_ and doesn't use go-releaser and so
doesn't have a version.Version
`version.Version` is set when building `gitops` using `make bin` (used for local dev and inside the published container).
**Why?**
So that capi cluster bootstrapping doesn't show an imagepullerror as the version is used to generate the deployment.image when running `gitops install`
`docker build -t...`

Fixes `gitops install` wego-app.yaml deployment when running in container

---

.github/workflows/release.yaml
pkg/services/auth/github_test.go

Don't do NPM publish or docker image push if the release doesn't succeed.
Also updates package-lock.json.

Avoid running other release jobs if goreleaser does not complete

---

.github/workflows/release.yaml

Release job was using some node version other than 14.x

Set explicit node version

---

ui/components/Alert.tsx
ui/components/Button.tsx
ui/components/ConditionsTable.tsx
ui/components/DataTable.tsx
ui/components/Layout.tsx
ui/components/Modal.tsx
ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/lib/theme.ts
ui/pages/ApplicationAdd.tsx
ui/stories/DataTable.stories.tsx
ui/stories/Modal.stories.tsx

Parts of #1096 are completed in this PR - some parts are exclusive to Enterprise and are not fixed here. 
Closes #777 
Closes #914 
Theme colors - adds primary and text keys to customized mui palette, fixing black and grey text, light blue buttons, and AddApplication switch color
Aligns tables in ApplicationDetail with widths array prop
Removes Account Icon until functionality is added

Add and Implement Theme Colors

---

.github/workflows/nightly.yaml
test/acceptance/test/add_tests.go
test/acceptance/test/utils.go

- Add a skip tag on a test that will _only_ skip running for **Nightly Tests**
- Add a minor enterprise test case that checks for error message generated for missing entitlements file 
**Why?**
- The skipped test was trying to create another kind cluster to test multiple cluster deployment. Since nightly tests run on single standing EKS/GKE clusters, the test kept failing. 
- We needed a test that would check error messages for missing entitlement file during `gitops upgrade`

Add negative tests for GitOps Enterprise

---

.github/workflows/release.yaml

Closes: 
Adds the version dropping the `v` from the git tag to the docker tag we should now have both being pushed:
- ghcr.io/weaveworks/wego-app:v1.2.3
- ghcr.io/weaveworks/wego-app:1.2.3
**Why?**
- Avoid issues with deployment templates
- Keeps version reporting consistent
- I haven't, we need to push a release to test it out.

Adds the semver tag to the docker build

---

ui/lib/fonts.ts

The bold was listed as regular weight, and vice versa, which made the
UI bold everywhere except for in headers.
Closes: 
Fix which version of proxima-nova is considered bold and which one isn't
**Why?**
The bold font was listed as regular, while the regular font was listed as bold - that made the whole UI bold, except for in headers and other places of emphasis.
Looking at the UI
No
No

Invert boldness in font definitions

---

ui/App.tsx
ui/__tests__/library.test.tsx
ui/components/Button.tsx
ui/components/GithubAuthButton.tsx
ui/components/GithubDeviceAuthModal.tsx
ui/components/GitlabAuthButton.tsx
ui/components/__tests__/GithubAuthButton.test.tsx
ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
ui/contexts/AppContext.tsx
ui/contexts/GithubAuthContext.tsx
ui/hooks/applications.ts
ui/hooks/auth.ts
ui/hooks/common.ts
ui/lib/types.ts
ui/lib/utils.ts
ui/pages/ApplicationDetail.tsx
ui/pages/ApplicationRemove.tsx
ui/pages/__tests__/ApplicationDetail.test.tsx

Closes: #1082 
Adds a remove page as well as some multi-step status information:
Notes:
* Removes a bunch of complex state logic from the app detail page
* This is a stop gap until we want to add fancier confirmation inputs
* The code for this is a bit meh and can be improved, but I ran out of time before PTO
* This will likely change once we have remove-via-PR

Add app remove page

---

manifests/manifests.go
manifests/manifests_test.go
pkg/services/gitops/install.go
pkg/services/gitops/uninstall.go
pkg/services/gitops/uninstall_test.go

Failure here: https://github.com/weaveworks/weave-gitops/actions/runs/1572147230
```
pkg/services/gitops/uninstall.go:35:28: undefined: manifests.GenerateWegoAppManifests
pkg/services/gitops/uninstall.go:35:63: undefined: manifests.WegoAppParams
make: *** [Makefile:55: bin] Error 2
```
works now:
```
make bin
go build -ldflags "-X github.com/weaveworks/weave-gitops/cmd/gitops/version.BuildTime=2021-12-13_14:35:09 -X github.com/weaveworks/weave-gitops/cmd/gitops/version.Branch=main -X github.com/weaveworks/weave-gitops/cmd/gitops/version.GitCommit=2aad1a5c -X github.com/weaveworks/weave-gitops/pkg/version.FluxVersion=0.21.0 -X github.com/weavewo
rks/weave-gitops/cmd/gitops/version.Version=v0.5.1-rc3-7-g2aad1a5c" -o bin/gitops cmd/gitops/*.go
```

Fix uninstall build error

---

pkg/services/gitops/install.go

This Log message here, breaks the output of validateWegoInstall.
https://github.com/weaveworks/aws-marketplace/runs/4500418327?check_suite_focus=true
Results in a generated output in case dry run is used such as this:
```
► Validating Weave Gitops installation
---
apiVersion: v1
kind: Namespace
metadata:
labels:
app.kubernetes.io/instance: wego-system
app.kubernetes.io/part-of: flux
app.kubernetes.io/version: v0.21.0
name: wego-system
---
```

Fix broken validation output from dry-run

---

pkg/git/git.go
pkg/services/app/add_test.go
pkg/services/gitops/install.go
pkg/services/gitopswriter/gitopswriter.go
pkg/services/gitopswriter/writer_remove_test.go

Closes: #1213  
* #1213 
Instead of assuming the relative path between applications and apps, calculate it.
**Why?**
EKS clusters sometimes have a path separator in their name and this was causing an issue with Kustomize
Added unit tests and existing tests will validate that existing functionality still works.
Yes.
No

Add support for cluster names with path separators

---

.github/workflows/test.yml
test/acceptance/test/add_tests.go
test/acceptance/test/flux_tests.go
test/acceptance/test/help_tests.go
test/acceptance/test/install_tests.go
test/acceptance/test/profiles_test.go
test/acceptance/test/testsuite_common_test.go
test/acceptance/test/ui_tests.go
test/acceptance/test/utils.go
test/acceptance/test/version_tests.go
test/integration/server/add_test.go
test/integration/server/suite_test.go

Fails faster and more clearly this way
Before:
```
make integration-tests
KUBEBUILDER_ASSETS="/home/jake/weave/weave-gitops/tools/bin/envtest" CGO_ENABLED=0 go test -v ./test/integration/...
=== RUN   TestServerIntegration
Running Suite: Server Integration
=================================
Random Seed: 1638813585
Will run 6 of 6 specs
• Failure [0.008 seconds]
AddApplication
/home/jake/weave/weave-gitops/test/integration/server/add_test.go:33
GitLab
/home/jake/weave/weave-gitops/test/integration/server/add_test.go:423
via merge request
/home/jake/weave/weave-gitops/test/integration/server/add_test.go:424
adds with no config repo specified [It]
/home/jake/weave/weave-gitops/test/integration/server/add_test.go:425
Unexpected error:
<*fmt.wrapError | 0xc000df6a80>: {
msg: "could not create …
```

Check environment variables are set before running integration/acceptance tests

---

api/v1alpha1/application_types.go
manifests/crds/wego.weave.works_apps.yaml

Closes: 
- Revert field name from config_repo to config_url in wego app CRD
**Why?**
- Avoid breaking changes
- I used `gitops` version 0.5.0 to create a config repo and then I used that repo in install with this branch changes.
- I added an app using the UI with a config repo.
Both scenarios result in app deployments.

Revert field name from config_repo to config_url in wego app CRD

---

pkg/server/internal/logger.go

By skipping the caller, the output shows the calling function instead
of the logging wrapper.
Closes: #1238 
* #1238 
Added a skip caller option to the creation of the logger used in the API server.
**Why?**
By skipping the caller, the output shows the code making the call to the logger instead of the logger.
I Ran `gitops ui run` and checked the output
Output now looks like - 
>2021-12-15T16:14:18.523-0700    INFO    app/add.go:107  Adding application:
2021-12-15T16:14:18.523-0700    INFO    app/add.go:108  Name: mypdi
2021-12-15T16:14:18.523-0700    INFO    app/add.go:109  URL: ssh://git@github.com/palemtnrider/podinfo-deploy.git
2021-12-15T16:14:18.523-0700    INFO    app/add.go:110  Path: ./
2021-12-15T16:14:18.523-0700    INFO …

Configure zapr logger to skip the caller

---

ui/components/DirectedGraph.tsx
ui/components/Input.tsx
ui/components/ReconciliationGraph.tsx
ui/lib/theme.ts

Closes: #1189 
Mouse wheel scroll on ApplicationDetail graph is disabled. Instead, a slider allows the user to zoom in and out, with the percentage displayed below. The graph also now starts in the center!!

Improve Graph Zoom Functionality

---

go.mod
go.sum

Fixes a vulnerability in `image-spec`: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMOPENCONTAINERSIMAGESPECSPECSGOV1-1922832

Fix for image-spec vuln

---

pkg/services/auth/auth.go
pkg/services/auth/auth_test.go
test/acceptance/test/add_tests.go

Closes: #1111 
- Avoids uploading key in public repos
**Why?**
- gitops was erroring out when using public repos
- manual and unit tests

Avoid uploading key in public repos

---

ui/pages/ApplicationAdd.tsx

Closes #1241
This is a quick fix for Gitlab.com, it will not support custom domains. Doing it well will require a larger effort to change what is returned from `.Add()`: https://github.com/weaveworks/weave-gitops/issues/1264
I tried to do it from the backend, but it would have been a pretty large undertaking for a change that has not been reviewed/refined by the team.

Navigate to gitlab merge requests on app add

---

pkg/server/server.go
ui/lib/types.ts
ui/pages/ApplicationRemove.tsx

Closes: #1190
Closes: #1191 
Fixes display of 500 errors in `RemoveApplication` and only initiates polling on remove request instead of on page load.

Fixes Polling Errors on Remove Page

---

ui/components/PollingIndicator.tsx
ui/pages/Applications.tsx

Closes: #1246
The "last updated 30 seconds ago" was too prominent and was more trouble than it was worth - removed in favor of just having the spinner appear every thirty seconds.

Remove Polling Message on Applications Page

---

.github/actions/run-acceptance-test/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yaml
test/acceptance/README.md

Added `CHECKPOINT_DISABLE` env on all test jobs
**Why?**
To avoid interfering with the statistics that keep track of the number of downloads customers are making for `Weave-GitOps`

Disable checkpoint for all CI jobs

---

pkg/server/auth/auth.go
pkg/server/config_getter.go
pkg/server/config_gettter_test.go
pkg/server/handler.go
pkg/server/server.go
pkg/server/server_options.go
pkg/server/server_test.go
pkg/server/suite_test.go
test/integration/server/suite_test.go

Part of: #1092  
Instead of creating a fetcher initially when an `ApplicationsServer` is created, we create it when the HTTP request is handled so that we can use existing middleware to determine the identity of the user making the request. Following that, we can assume the identity of that user when making calls to the Kubernetes API.
There are three abstractions on interest that are introduced in this PR: `ConfigGetter`, `ClientGetter` and `FetcherFactory`:
- `ConfigGetter`: this is a low level abstraction that can be used to create a `*rest.Config` after inspecting the `context.Context`.
- `ClientGetter`: this is used to create a `client.Client` from a `*rest.Config`. It complements `ConfigGetter` and it allows for using a fake Kubernetes client in tests.
- …

Refactor ListApplications to create fetcher at the time of the request

---

.github/workflows/release.yaml

- E.g. `docker run wego-app install` will create a deployment for
wego-app with an image tag of a git hash instead of the tagged release
version.
- Github doesn't checkout tags by default so can only report the hash.
**Why?**
So we can run `docker run wego-app install` and not end up with an ImagePullError in the wego-app deployment:
```
Normal  BackOff  3m26s (x4039 over 15h)  kubelet  Back-off pulling image "ghcr.io/weaveworks/wego-app:15349f1"
```
e.g. this is caused by version being wrong
```
$ docker run ghcr.io/weaveworks/wego-app:v0.6.0 version
Current Version: 15349f1
GitCommit: 15349f1
BuildTime: 2021-12-16_19:24:51
Branch: HEAD
Flux Version: v0.21.0
```
Have not tested this, but assume it works similarly to the go-releaser task, in that we need to pull …

Fixes version reported by the `gitops` binary in the `wego-app` docker image in a tagged release

---

ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/__tests__/__snapshots__/Page.test.tsx.snap

Closes: #1256 
Specifying the height of `<Main />` to be 100% allows `<NavContainer />` to extend through the whole page. Also had to change the background color to white <|:^}
Screenshot shows it extending past the Commits in App Detail - which is where it used to stop.

Extends Nav height to match Content

---

go.mod
go.sum
pkg/services/automation/cluster_generator.go
pkg/upgrade/upgrade.go

- #1297 introduced a version of ggp that breaks on-prem support
- This PR upgrades to ggp that includes https://github.com/fluxcd/go-git-providers/pull/141 which fixes on-prem-gitlab support. 
- It also adds support for older wg installations that might not have a kustomization.yaml file present
**Why?**
For on-prem things!
`gitops upgrade` before:
```
Error: failed to get git clients: error setting up deploy keys: failed check for existing deploy key: error getting user repo reference for owner XXXX, repo demo-01, error getting user repository domai
n "https://XXXX" not supported by this client: the client doesn't support handling requests for this domain
```

Upgrades to a ggp w/ the on-prem-gitlab fix

---

.dockerignore
Dockerfile
tools/download-deps.sh

Change download-deps to not interact with git - it doesn't need git,
and docker builds shouldn't contain git.
Add a bunch more entries to dockerignore - this cuts out hundreds of megs
of build context.
Remove `make clean` from the Dockerfile. We shouldn't copy cleanable
state into the docker image in the first place. In this case, it seems
we run make clean to run git clean to remove the flux binary - so I
just added the flux binary to the dockerignore instead.
Reorder the Dockerfile and be more explicit, in order to cache more -
go changes now only makes the go code recompile.
**Why?**
Before this change, almost every change caused `make docker` to run
for 90-100s on my machine, because almost all caches were always
invalidated.
After this change, go changes only take …

Make docker builds faster

---

pkg/services/automation/automation_test.go
pkg/services/automation/cluster_generator.go

Put the file `wego-app.yaml` into `kustomization.yaml`
**Why?**
While the wego-app resources were installed at cluster creation time,
they wouldn't be upgraded by changing the manifest. I found this unexpected.
I made a PR before: https://github.com/ozamosi/gitops-config/pull/6/files
and after: https://github.com/ozamosi/gitops-config/pull/5/files
The difference is in  `.weave-gitops/clusters/kind-regression-test-cluster-{0,1}/system/kustomization.yaml` where `wego-app.yaml` is only included in the "after" PR.
I'm not really familiar with the code in this repo, so if there's anywhere I should put an automated test, please advise.
The code I'm changing seems to have originated in #1141 - assuming this wasn't a problem in 0.6.0, …

Include weave-gitops in resources managed by weave-gitops

---

ui/components/CommitsTable.tsx
ui/components/Link.tsx

Closes: #1210
Added `newTab` prop to the Link component which allows toggling of the` target='_blank'` attribute of the <a> element

Links to commits open new tab

---

pkg/server/server.go
pkg/server/server_test.go
pkg/server/suite_test.go
test/integration/server/suite_test.go

Part of: #1092  
Instead of creating a Kubernetes `client.Client` when an `applicationsServer` is created, we create it when the HTTP request is handled so that we can use existing middleware to determine the identity of the user making the request. Following that, we can assume the identity of that user when making calls to the Kubernetes API.
**Why?**
The end goal is to execute calls to the Kubernetes API on behalf of the authenticated user.
Updated existing unit tests + manually
Not yet, still behind a feature flag.
Not yet, still behind a feature flag.

Refactor application endpoints to get `client` at the time of the request

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/delete/clusters/cmd.go
cmd/gitops/install/cmd.go
cmd/internal/provider_test.go
pkg/flux/flux_test.go
pkg/gitproviders/provider_org_test.go
pkg/gitproviders/provider_user_test.go
pkg/gitproviders/repo_url.go
pkg/gitproviders/repo_url_test.go
pkg/server/internal/provider_test.go
pkg/server/server.go
pkg/services/app/add.go
pkg/services/app/commit.go
pkg/services/applicationv2/fetcher.go
pkg/services/auth/auth.go
pkg/services/auth/auth_test.go
pkg/services/automation/automation_test.go
pkg/services/automation/generator.go
pkg/services/factory.go
pkg/services/gitops/install.go
pkg/services/gitopswriter/writer_add_test.go
pkg/upgrade/upgrade.go
test/acceptance/test/utils.go
test/integration/server/add_test.go

Closes: #1278 
Revert changes made in https://github.com/weaveworks/weave-gitops/pull/1249. I left in the changes for the acceptance tests because they were good tests to keep in. 
**Why?**
Manually and unit tests

Add deploy key for public repo

---

pkg/services/auth/github_test.go

The previous fix to these tests (#1314) doesn't seem to have permanently fixed this problem, so let's disable these tests again for now to unblock the build, then look into a more permanent fix later.

Re-disable GitHub auth flow tests

---

pkg/testutils/testutils.go

The test suites for some of our packages spin up parts of a Kubernetes cluster using the `envtest` library, so that we have something more solid than mocks to test against. One problem this was causing was that running tests for both the `kube` and `server` packages at once would cause one of those test suites to fail.
Side-note: it's possible to reproduce this problem a little more efficiently by spinning up a fake web server to sit on port 8080, for example using Python's built-in web server:
python3 -m http.server 8080
After some digging, I found out that the reason for this is that both environments were trying to spin up a Prometheus metrics handler listening on port 8080. If they both tried to do this at once, one would fail, causing the entire test suite for that package to fail …

Fix flaky test by disabling Prometheus metrics

---

Makefile
package-lock.json
package.json
pkg/server/suite_test.go
test/integration/server/add_test.go
test/integration/server/remove_test.go
test/integration/server/suite_test.go
tools/download-deps.sh

A bit of a grab-bag PR ahead of a release; fixes some linting issues and ensures CI stays consistent with the local job.

Use Makefile job for linter and update package.json before release

---

cmd/gitops/add/app/cmd.go
cmd/gitops/app/status/cmd.go
cmd/gitops/beta/cmd/add/app.go
cmd/gitops/beta/cmd/install.go
cmd/gitops/delete/app/cmd.go
cmd/gitops/get/app/cmd.go
cmd/gitops/get/commits/cmd.go
cmd/gitops/install/cmd.go
cmd/gitops/resume/app/cmd.go
cmd/gitops/suspend/app/cmd.go
cmd/gitops/upgrade/cmd.go
go.sum
pkg/server/config_getter.go
pkg/server/server.go
pkg/server/server_options.go
pkg/server/server_test.go
pkg/server/suite_test.go
pkg/services/factory.go
pkg/services/factory_test.go
pkg/services/servicesfakes/fake_factory.go
test/integration/server/remove_test.go
test/integration/server/suite_test.go

Part of: #1092 
To get an instance of `kube.Kube` a `Factory` was used that was initialised during application startup with a `*rest.Config`. The responsibility of getting a `kube.Kube` instance now lies with the `KubeGetter` which reads the `*rest.Config` during an HTTP request and uses it to impersonate the call to the Kubernetes API.
**Why?**
The end goal is to execute calls to the Kubernetes API on behalf of the authenticated user.
Updated existing unit tests + manually
Not yet, still behind a feature flag.
Not yet, still behind a feature flag.

Get kube client during HTTP request

---

.github/workflows/test.yml

CI running on our `v2` branch was causing issues. We have a separate, simplified CI workflow for that branch.

Only run tests when PRing to main

---

cmd/gitops-server/main.go
cmd/gitops/cmderrors/errors.go
cmd/gitops/ui/run/cmd.go
cmd/gitops/ui/run/cmd_test.go
pkg/server/profiles.go
pkg/server/profiles_test.go

Part of: #1092
Updated profile endpoints to request a `client.Client` during an HTTP request.
**Why?**
The end goal is to execute calls to the Kubernetes API on behalf of the authenticated user.
Updated existing unit tests
Not yet, still behind a feature flag.
Not yet, still behind a feature flag.

Update profile endpoints to request a `client.Client` during an HTTP request

---

README.md

Missed this in the release steps

Fix readme version number

---

.github/workflows/release.yaml

We use the 
```
- name: Unshallow
run: |
git fetch --prune --unshallow
git fetch --tags -f
```
trick instead of the `depth: 0` trick to get the git `HEAD` at the correct tag reference so that `git describe` works
**Why?**
We tried to fix this in https://github.com/weaveworks/weave-gitops/pull/1293 but it didn't work
In another repo: https://github.com/foot/github-actions-examples
on tagging and pushing `v0.0.2`:
- `checkout` with no args: `9361784`
- `checkout` with `depth: 0`: `v0.0.1-1-g9361784`
- `checkout` with `git fetch --prune --unshallow && git fetch --tags -f` : `v0.0.2`
---
The new bug: 0.6.1 is completely missing a version:
```
$ docker run ghcr.io/weaveworks/wego-app:v0.6.1 version
Current Version:
GitCommit:
BuildTime: …
```

Report correct version when building docker image on-release

---

tools/dependencies.toml
tools/download-deps.sh

Closes: #1369
Install tilt directly, rather than using `curl | bash`
**Why?**
`docker build` fails otherwise as it uses (not installed or configured) `sudo`.
Tested locally with `docker build` on Arch Linux & Mac OS, x86_64. I can't test the `make` targets directly as they refuse to build in a clean chroot, and I don't currently have time to figure out which dependencies are missing.
**Other**
I am not familiar enough with your build env to determine which fix is correct: caa497548c5fd1db9eb6493e2f175c550903604c or 0acba92265176c8ccd8ea9870caf52c20a2c673d.

Tilt install fix

---

pkg/services/auth/github_test.go

Closes: #1199
As best as I can tell, the flakiness here was coming from two places:
1. Plain ol' data races, where we were sharing a variable between threads, updating it one thread and reading it in another. Sometimes these wouldn't happen in the right order, causing failures.
2. Race conditions when interacting with the `clock` library, where (for example) we would kick off a piece of code that we knew would call `Sleep`, call `runtime.Gosched` to give it a chance to execute, and then tell the `clock` library to advance time. It looks like these, again, weren't always happening in order.
A bunch of the complexity here stems from the fact that we're poking our clock from one end with the `Sleep` function, then poking it from the other end to tell it time has advanced. Since all we're …

Restructure GitHub auth test to remove flakiness

---

.github/workflows/test.yml

This is largely based on [similar work in other Weaveworks projects][1], but with a bit of extra information that will hopefully be useful to folks who want to investigate the failure.
[1]: https://github.com/search?q=org%3Aweaveworks+action-slack-notifier&type=code
There are a few bits of this workflow that I don't love: the `jq` hackery to extract the first line of the commit message isn't particularly pleasant, but I couldn't see anything exposed by GitHub that gives us just the commit's subject line. Telling `jq` to JSON-encode the commit subject also feels like a bit of a hack, but these are the perils of telling GitHub how to write YAML that writes JSON that writes Slack's custom `mrkdwn` syntax.
If we want to add any more context to these messages (for instance, which bits of the …

Notify Slack when the `main` branch build fails

---

.github/workflows/label.yaml
core/server/sources.go
tools/download-deps.sh

Left over from a v2 rebase. We use the `depdencies.toml` file to handle install `tilt` now.
Also removes the label check from CI for the `v2` branch.

Remove merge conflict marker after bad rebase and remove label job

---

pkg/models/manifest.go
pkg/models/manifest_test.go
pkg/services/gitops/install.go
pkg/services/install/install_test.go
test/acceptance/test/add_tests.go
test/acceptance/test/utils.go

- Kustomization controller complains about a missing profiles.yaml
Add an empty `profiles.yaml` file so that the system kustomzation can reconcile.
```json
{
"level": "error",
"ts": "2022-02-07T11:10:21.828Z",
"logger": "controller.kustomization",
"msg": "Reconciliation failed after 31.707953ms, next try in 1m0s",
"reconciler group": "kustomize.toolkit.fluxcd.io",
"reconciler kind": "Kustomization",
"name": "kind-test-upgrade-system",
"namespace": "wego-system",
"revision": "main/ae43a6151d0f4c368a3abc352f6349837b91561e",
"error": "kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'profiles.yaml': open /tmp/kind-test-upgrade-system4030199120/.weave-gitops/clusters/kind-test-upgrade/system/profiles.yaml: no such file or …
```

Fixes system kustomization reconciling if no profiles installed

---

.github/workflows/scan.yaml

Run snyk against javascript, go, and use the CLI directly to scan both                                                    
in one invocation.                                                                                                        
Also run snyk against docker (separately, in parallel). It's a bit                                                        
slow right now, but a) I expect to speed this up later b) we'll have                                                      
to build the docker image anyway, and the scan takes about a second                                                       
extra c) this is still faster than the v2 pipeline.       
Upload the snyk test results to github even if they fail - otherwise …

Use snyk for js, go & docker, upload results properly

---

Makefile
README.md
Tiltfile

Tilt install assume you already have a working cluster. That's not really needed.
Now that we have acceptance test change how we handle the image in the real deployment yaml file, we can bootstrap a dev environment and then let tilt take over so it monitors all files.
This is now working with a booted up dev cluster from 0 -> 100 without running anything before hand just this:
```
TEST_CONFIG_REPO=ssh://git@github.com/Skarlso/gitops-training.git make cluster-dev
```
There is also a convenient make target to clean everything up: `make clean-dev-cluster`.
Do people would like to have an option to disable the bootstrap part and still use tilt with an existing cluster?
Closes https://github.com/weaveworks/weave-gitops/issues/1406

Modify the local build to install and configure tilt for first runners

---

.github/workflows/v2.yml

Closes: Nothing
Changing the name attribute values for the V2 GitHub Actions CI workflow and job.
**Why?**
Setting them to unambiguous values in order to figure out how those values must be represented in the repo's TF template branch protection rule statements.
It needs to be tested on GitHub.
Should not have any effect on the release.
No.  These only apply to the GitHub actions and subsequently the TF templates for this repo.

Seb change v2 check names

---

.github/workflows/deploy.yml
test/acceptance/test/scripts/kind-cluster.sh

```
STEP: Given I have a brand new cluster with a long cluster name
time="2022-02-09T10:56:11Z" level=info msg="Creating a kind cluster "
Create a new kind cluster with name 
./scripts/kind-cluster.sh: 22: [[: not found
Registry Host: kind-registry
ERROR: failed to create cluster: node(s) already exist for a cluster with the name "kind"
time="2022-02-09T10:56:11Z" level=info msg="Failed to create kind cluster"
time="2022-02-09T10:56:11Z" level=fatal msg="exit status 1"
```
https://github.com/weaveworks/weave-gitops/runs/5123765368?check_suite_focus=true
switching to `bash` should fix this. Also removes unneeded creating of a kind cluster in the buildup, since each test creates its own cluster

change kind-cluster script to bash

---

cmd/gitops/flux/cmd.go
website/docs/cli-reference/gitops_flux.md

It is called `gitops` CLI now.
This is a duplicate of #1425, by @kingdonb. Unfortunately, some bits of our test suite that are required for merging don’t work when run against a forked repo.

clean up docs references to `wego` CLI

---

.github/workflows/v2.yml
Makefile

I had a go test that was failing in CI but not locally, and I had to
wait for all that javascript stuff to happen - do both at the same
time, I want the answer Now!

ci: Run go & js tests in parallel

---

cmd/gitops/version/cmd.go
pkg/flux/flux.go
pkg/flux/fluxfakes/fake_flux.go

Removes the flux version check when running `gitops version` command. We are removing the flux binary from weave-gitops so as part of decoupling flux and gitops we need to remove the checks on flux.
**Why?**

Cleanup version

---

test/acceptance/test/add_tests.go

Closes: 
Pended the failing smoke test on main `SmokeTestLong - Verify that gitops can deploy multiple apps one with private and other with public repo (e2e flow) `
**Why?**
Main is broken
NA
NA
NA

Pend failing smoke test

---

website/README.md

The workflow YAML file this links to is called `docs`, rather than `documentation`.
Note: this is a PR against the `main` branch. We don’t need to mirror it against `v2` yet, as the `website` directory doesn’t exist over there.

Fix workflow link in the `website` README

---

doc/release-process.md

If the release process actually is straightforward, we don't really gain much from saying it's straightforward, because people can see how straightforward it is. If, on the other hand, the release process *isn't* straightforward, saying it is will only make people feel bad when they struggle to understand or follow it, and will discourage them from speaking up and calling attention to problems.

Stop describing releases as straightforward

---

.github/workflows/scan.yaml

I copy-pasted entirely the wrong thing - the snyk upload of container
issues was absolutely broken.
This copy-pastes the right thing, so uploads actually do uploads. I've
run it myself without the if condition, and it does work now and
upload what I expect.

Fix the scan pipeline upon merges 

---

test/acceptance/test/add_tests.go
test/acceptance/test/utils.go

A couple of the acceptance tests were failing due to short waits. I've increased the wait time to a reasonable amount and removed skip tag from those failing tests.
**Why?**
GitOps takes around 60s to reconcile — so I've set the wait time to that.

Resolve wait times issues for tests

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/add/profiles/cmd.go
cmd/gitops/update/profiles/profiles.go
cmd/internal/flags.go
pkg/services/profiles/add.go
pkg/services/profiles/add_test.go
pkg/services/profiles/profiles.go
pkg/services/profiles/update.go
pkg/services/profiles/update_test.go

Closes: #1311
TODO: looking into updating acceptance test to check the PR settings, but might be overkill
You can now configure the title, commit message, descripton and branch a PR is created on for `add/update` profiles
**Why?**
so you can customise the PR to meet your company standards. Also brings the PR flags in-line with what is available for `add cluster`
manually:
add:
```
bin/gitops add profile --name podinfo --version 6.0.0 --namespace wego-system --cluster kind-e4xmcn --config-repo git@github.com:weaveworks-gitops-test/test-app-229w99at.git --base my-pr-branch --branch main --commit-message comitme --description "dogs>cats" --title="golden retreivers are the best"
► getting available profiles in kind-e4xmcn/wego-system
► created Pull …
```

Add option for configuring PR settings in add/update profile

---

pkg/server/auth/auth.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go

Closes: https://github.com/weaveworks/weave-gitops-enterprise/issues/407
Added a new /logout endpoint to be called by FE for cookie deletion.
**Why?**
Part of Auth implementation.
Tested locally + unit tests.

Add logout endpoint

---

go.mod
go.sum

Related to: #1503  
This upgrades the version of go-checkpoint. The new version has absolutely no code changes.
Yes, this clear-the-way PR is against main. It's supposed to be against main. Snyk's github integration only works against the default branch.
**Why?**
This is a bit of a stab in the dark to try to get the snyk github
integration working (part of #1503) - apparently we can't have
dependencies without go.mod files?
There are checkpoint tests already, and this changes literally no code. I did try dumping the response from checkpoint to see that it's still returning "sensible" values.

Upgrade weaveworks/go-checkpoint to version with go.mod

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/delete/clusters/cmd.go
cmd/internal/provider.go
cmd/internal/provider_test.go

Removed the auth flow from cluster add/delete cmd's. Core is removing git auth but enterprise still needs a git token to create PR's. For now I have left in getting the token from the env variable. I also left in all the code for gitProvider. It isnt needed for add/delete but profiles is using it and that is a problem for another task.
**Why?**

Update cluster cmd

---

Makefile

CI started to build javascript in the go bits. Don't!
Instead, just drop an empty file so the frontend embedding won't fail
if we haven't built the frontend. Really, this shouldn't be embedded
and just stored in the docker image, but future work...

Make CI faster again

---

Makefile
Tiltfile
test/acceptance/test/scripts/kind-cluster.sh
tools/deploy-local-registry.sh
tools/kind-with-registry.sh
tools/wego-app-dev.yaml

Closes: 
- Added validation with creating registry
**Why?**
- We used to use port 5000 for the local registry. But the current script uses port 5001 and only creates the registry if it is running. But if the register is using different ports from what tilt is expecting then tilt won't be able to push to the registry. 
- Manually

Added validation to registry script

---

.github/workflows/test.yml

Our gitlab user has got themselves banned, so our gitlab tests can't
run, so temporarily disable the tests that are currently failing
because of it.
This should be reverted when weaveworks/corp#2502 is resolved.

Turn off gitlab acceptance tests

---

Makefile

Three reasons:
* It would let us ship docker images with effectively nothing but our
binary in it. Take that, docker vuln security scans! (not included here)
* It helps with local development when your OS is running a newer
glibc than the tilt image.
* We've already been running tests with CGO_ENABLED=0. I'm aware
there's some stuff that works differently between cgo and no-cgo,
but then we should test with that, shouldn't we?

make: Turn off cgo everywhere

---

cmd/gitops/ui/run/cmd.go
go.mod
go.sum
pkg/server/auth/auth.go
pkg/server/auth/auth_test.go

Closes: #1090 
Added basic rate limit for requests to `/sign_in` endpoint
**Why?**
To protect the endpoint from a high volume of login attempts 
Manually
N/A
N/A

Rate limit login requests

---

cmd/gitops-server/cmd/cmd.go
cmd/gitops-server/cmd/cmd_test.go
cmd/gitops-server/main.go

I think I might have run an extra autoformatter on main.go, and it
removed the cmd import because the module name and the import path
didn't match. Make them match.
This also ended up reindenting everything - this is just running
goimports which I thought was just gofmt with import fixing, so I'm
not sure why this didn't complain before.

Fix module names in gitops-server

---

ui/App.tsx
ui/components/AutomationsTable.tsx
ui/components/DataTable.tsx
ui/components/InfoList.tsx
ui/components/Interval.tsx
ui/components/KubeStatusIndicator.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourceDetail.tsx
ui/components/Text.tsx
ui/components/__tests__/DataTable.test.tsx
ui/pages/v2/GitRepositoryDetail.tsx
ui/pages/v2/KustomizationDetail.tsx

Part of #1520 
A GitRepo that is working:
One that is in an error state:

Add GitRepositoryDetail page

---

Makefile

Fix `make local-docker-image`
Fix default docker registry
Fix which image has the FLUX_VERSION argument sent to it

Fix a couple of docker target problems

---

ui/components/AutomationsTable.tsx
ui/components/Breadcrumbs.tsx
ui/components/DataTable.tsx
ui/components/Layout.tsx
ui/components/Link.tsx
ui/components/Page.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/Text.tsx
ui/components/__tests__/Breadcrumbs.test.tsx
ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/contexts/AppContext.tsx
ui/lib/nav.ts
ui/pages/v2/FluxRuntime.tsx

Closes: #1509 
Adds Breadcrumbs component, and should also fix some errors caused by data tables mixing with the new sorting pr.

Move Breadcrumbs and reconfigure for V2Routes

---

ui/components/DataTable.tsx

Fixes an issue where a string can be `undefined` but we still call `.localeCompare` on it.

Fix error on calling .localeCompare on undefined in Datatable

---

.github/workflows/deploy.yml
.github/workflows/frontend.yaml
.github/workflows/scan.yaml
.github/workflows/test.yml
Makefile
README.md

Closes: #1477 
* Added documentation for the tools used in the makefile
* Fixed bug due to missing plugins for `buf`
* General clean up
**Why?**
This should improve the developer experience and make understanding various workflows easier.
As much as possible changes have been tested (albeit only on a mac)

Clean makefile

---

website/docs/gitops-dashboard.md

Otherwise the `$`s are escaped.

docs: Ensure secret literal is quoted properly

---

ui/components/Breadcrumbs.tsx
ui/lib/nav.ts

I wasn't getting an error - but based on seeing an error in our pairing yesterday I thought I'd go ahead and move the useLocation usage inside Breadcrumbs.

Fix useLocation hook use in nav.ts

---

cmd/gitops/check/cmd.go
pkg/flux/flux.go
pkg/flux/fluxfakes/fake_flux.go
pkg/services/check/check.go
pkg/services/check/check_test.go

I removed the flux check from the check cmd. I also changed the kubernetes check to no longer use flux to validate it. It is now getting the kubernetes version by running kubclt cmd. I copied the validation code from flux. We will have to keep the supported kubernetes version up to date in the code now. 
**Why?**
The flux binary will no longer exist in the code so this command needed to change.

Remove flux check from check cmd

---

ui/components/AutomationsTable.tsx
ui/components/KubeStatusIndicator.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
ui/pages/v2/KustomizationDetail.tsx

Closes #1593 
Closes #1586
Closes #1585
Fixes the color and bold-ness of the status indications:
Also fixes the overflow when they are shown in a table:
Moves `Applied Revision` to the Info section for better consistency:

Fix KubeStatusIndicator overflow and color

---

README.md
Tiltfile
api/v1alpha1/application_types.go
pkg/server/auth/server.go
tools/dev-manifests/helm_watcher_role.yaml
tools/dev-manifests/helm_watcher_role_binding.yaml
tools/dev-manifests/role-binding.yaml
tools/dev-manifests/role.yaml
tools/dev-manifests/service-account.yaml
tools/dev-manifests/wego-app.yaml

This is not a "finished product", I am simply doing the bare minimum to
unblock people and make life easier while I tidy some things up.
Here I am just adding some more manifests to the `Tiltfile`; I have
stashed these in `tools/dev-manifests` for now, but this may change.
Either way people will not notice as they are just running `make
cluster-dev`.
The manifests under `manifests/wego-dev` are technically out of use as
we move onto a Helm Chart install flow, but I am leaving them there for
now as I tinker, plus I know other people are working on the Helm bit so
I am staying out of their way.
I have also left the SuperUser and the "stripping out the service
account" bit for now, as they do not need to be in place to unblock
people. They are next on my list.
Closes …

fix: smooth out v2 dev process

---

charts/weave-gitops/templates/wego-app.yaml
charts/weave-gitops/values.yaml

Closes https://github.com/weaveworks/weave-gitops/issues/1580

fix: Update sa role to include apps/deployments

---

.proxyrc
core/server/types/gitrepository.go
core/server/types/helmrepository.go
ui/components/Interval.tsx
ui/components/SourcesTable.tsx
ui/lib/time.ts

**UI**
* Utility function to convert `interval` to string, that way we have to
change only in one place if we want to change the format.
**Back-end**
* Fix interval calculation on `HelmRepository` and `GitRepository`.
The issues was: `.Minutes()` and `.Seconds()` return with the value of
the whole interval, not just the minutes/seconds parts.
Closes: #1589

fix: incorrect interval reported on the Sources list page

---

ui/lib/__tests__/graph.test.ts
ui/lib/graph.ts
ui/lib/test-utils.tsx

We've moved the endpoints required to render the graph to the core
proto, however two things hadn't been moved:
Graph was still using some type definitions from applications. This is
an easy fix of just changing the import.
The graph tests were using the plain Application mock, because that's
the only client mock we have. This copy-pastes the mock setup code so
that we can mock Core or Application.
Doing this will allow me to delete both the endpoints and their                 
types from the Applications proto.
This commit is intended to establish a pattern, not finish the work -
subsequent endpoints will be moved in the same commit that deletes the
endpoint in question.

ui: Port graph + tests away from using Applications types

---

ui/components/AutomationsTable.tsx
ui/components/DataTable.tsx
ui/components/KubeStatusIndicator.tsx
ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/SourceDetail.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap

Closes #1577 
Closes #1527 
Sets the page-width free for larger monitors and fixes the underlying table-cell overflow problem with `KubeStatusIndicator`:

Unset page width and affix nav bar to left

---

ui/components/AutomationsTable.tsx
ui/components/SourcesTable.tsx
ui/pages/v2/FluxRuntime.tsx

Closes: #1616 
Adds temporary solution for single cluster use case where we can't grab the cluster name

Make Cluster Name Default for Single Cluster

---

doc/release-process.md
website/docusaurus.config.js

- The 'Edit this page' link should now point to here.
- There is a Blog link as well, but I don't think we have a blog page
:shrug_emoji:.
Closes https://github.com/weaveworks/weave-gitops/issues/1641

docs: Fix old docs repo links in Website

---

ui/components/KubeStatusIndicator.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx

Closes https://github.com/weaveworks/weave-gitops/issues/1642
The `computeMessage` was returning nothing for Flux runtime objects
since those have `Available` conditions, not `Ready` ones. This PR
updates that.
Manually clocking the UI.
I also added a UI test, but I never got a clean run of those here so not sure if it actually works
**Random thought on UX:**
The `KubeStatusIndicator` takes a `short` bool, but would it make sense to have the `short` be set internally based on the value of `ready`? If the value is `False` (ie the pod is failing) then the message computed for that row will be shown in long-form (per [this](https://github.com/weaveworks/weave-gitops/blob/v2/ui/components/KubeStatusIndicator.tsx#L39)), with all the still `Ready` lines keeping it nice …

fix: Check for Available condition's message

---

cmd/gitops/root/cmd.go
cmd/gitops/root/cmd_test.go
test/acceptance/test/install_tests.go

Adds a global `--insecure-skip-tls-verify` flag to the cli to make requests to an api-server using self-signed TLS certs
**Why?**
API server serves on _only_ https by default now. This allows you to `gitops get clusters --insecure-skip-tls-verify` etc.
Manual so far

Adds a global `--insecure-skip-tls-verify` flag to the cli

---

core/server/fluxruntime_test.go
core/server/helm_release_test.go
core/server/kustomization_test.go
core/server/namespace_test.go
core/server/sources_test.go
core/server/suite_test.go

We use the `cleanup` function always in `defer`, which can be simplified
and let `makeGRPCServer` handle that part as it can already access `testing.T`.
Closes #1649

refactor: Simplify makeGRPCServer API in tests

---

core/server/events._test.go
core/server/namespace_test.go

Merging #1663 caused tests to fail. This should make them pass again.

Fix test build errors

---

.github/workflows/v2.yml

github.com/sclevine/agouti was accidentally left behind in the go.mod
after being removed from the code, which is now causing random changes
in random other PRs.
The first time I had one of these checks fail, the text was very
confusing to me, and I wrote it. "Check that fakes are updated" makes
me ask "how", so make sure the command you need to run is part of the
thing that goes red in your PR.

Add go mod tidy to static checks, clarify action when git diff fails

---

.dockerignore
.github/workflows/v2.yml
.gitignore
Makefile
gitops-server.dockerfile
gitops.dockerfile

Build the docker images in parallel with running the go unit tests and then upload the images to Google Artifact Registry for staging.
This is builds upon & replaces PR #1633 
```mermaid
flowchart TD;
build-gitops-image[build gitops image]-->gitops-image[/gitops image/]:::asset
gitops-image-->upload-images;
build-gitops-server-image[build gitops-server image]-->gitops-server-image[/gitops-server image/]:::asset
gitops-server-image-->upload-images;
go-tests[run go unit tests]-.->upload-images;
ui-tests[run ui tests]-.->upload-images;
lint[run linters etc.]-.->upload-images;
upload-images-->finish-ci;
classDef asset fill:#9f9,stroke:#363;
```

Improve ci

---

README.md
Tiltfile
charts/weave-gitops/templates/wego-app.yaml
dev.dockerfile

This saves users from having to do TLS things as part of regular dev
cycle. Plus it means we wont get used to having certs in the image which
is not something we want for prod.
Once https://github.com/weaveworks/weave-gitops/issues/1703 is played we
can add something back for dev.

Remove TLS certs from dev image and dev cycle

---

pkg/server/auth/server.go
pkg/server/auth/server_test.go

We want to leave early in the case that OIDC is not enabled and thus the
provider is not set.
Closes https://github.com/weaveworks/weave-gitops/issues/1658 see last comment for context.

fix: Return UserInfo{} if superuser not logged in

---

cmd/gitops-server/cmd/cmd.go
pkg/server/auth/auth_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go

It was starting to look a little hairy in `cmd/gitops-server/cmd/cmd.go` so I have:
- Removed a completely redundant type
- Shuffled some config generation under the auth package
- Streamlined a couple of signatures that were looking way too busy
- Updated some auth tests to match the rest of the repo

ref: Tidy up how we process OIDC config

---

cmd/gitops-server/cmd/cmd.go
pkg/kube/kubehttp.go
pkg/server/server.go

Additional changes:
`kube.inClusterConfigClusterName` is a public function now as
`InClusterConfigClusterName`, because `config.GetConfig()` does not
return with "cluster name", our system still uses it, it's a simple
`Getenv` with default value. Maybe we can move this function into a
utility function called `GetenvOr("CLUSTER_NAME", "default")` or
something.
Closes #1719

refactor: Clean up kube config getting refereces

---

pkg/services/auth/github.go
pkg/services/auth/github_test.go

Closes: 
GitHub now require an explicit Device Flow flag for Apps https://github.blog/changelog/2022-03-16-enable-oauth-device-authentication-flow-for-apps/
This logs out the response from GitHub in the event of an error making a request, which would likely help diagnose this.
**Why?**
With this change, the error makes it easy to diagnose the failures caused by GitHub's policy change.
```
Error: failed getting git clients: error creating auth service: error obtaining git provider token: could not complete auth flow: could not do code request: error doing code request: request failed with status code "{\"error\":\"device_flow_disabled\",\"error_description\":\"Device Flow must be explicitly enabled for this App\",\"error_uri\":\"https://docs.github.com\"}": 400
```
**How …

Log out response from GitHub when there's an error.

---

.github/workflows/pr.yaml

The old code used `$GITHUB_SHA` and worked, so I copied it. This
definitely did not work. `${{ github.sha }}` however is set.
So we've been uploading `gitops-{ubuntu,macOS}-latest-` instead of
`gitops-{ubuntu,macOS}-latest-$SHORTSHA`

Fix binary S3 upload

---

ui/components/KubeStatusIndicator.tsx

Otherwise the icon will always be red :(

fix: Check for readyText after it has been set

---

ui/components/Page.tsx
ui/components/PageStatus.tsx
ui/components/SourceDetail.tsx
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/lib/test-utils.tsx
ui/pages/v2/Automations.tsx
ui/pages/v2/BucketDetail.tsx
ui/pages/v2/FluxRuntime.tsx
ui/pages/v2/GitRepositoryDetail.tsx
ui/pages/v2/HelmChartDetail.tsx
ui/pages/v2/HelmReleaseDetail.tsx
ui/pages/v2/HelmRepositoryDetail.tsx
ui/pages/v2/KustomizationDetail.tsx
ui/pages/v2/Sources.tsx

Related to and might close: #1757
Source Detail pages now use the `Page` component to render their title, and `Page` holds the global is fetching state with the `useIsFetching` hook. I don't like that it's pushed the `PageStatus` component down, but there's no way to render that one outside of `SourceDetail`
`SourceDetail` errors appear under title - could set error state of page in parent component of source detail, or have all queries alter app context error state?

Switch isFetching to useIsFetching

---

cmd/gitops/add/cmd.go
cmd/gitops/delete/cmd.go
cmd/gitops/get/cmd.go
cmd/gitops/root/cmd.go

* Add, delete and get all assumed you want to add or delete an app. We
no longer have apps. Get also mentioned getting commits, which also
isn't available.
* The main command had many examples of how to install gitops and
manage applications. None of that is applicable any more, so remove
any mention of it - we'll probably want to do a _something_ with
installation instructions, but this clears the way to do so.

Remove actively misleading help texts

---

.github/workflows/pr.yaml

We want to use Flux's image policies to auto deploy the latest version
of main to a staging cluster. To do this the images need to be tagged
in a sortable manner. The easiest way to do this is using the unix time
so we'll add that as a prefix.

Add a date prefix to the docker tag for PR images

---

.github/workflows/pr.yaml

This needs to use parenthesis, not curly braces, for process substitution.
Fixes the error thrown here: https://github.com/weaveworks/weave-gitops/runs/5690575142?check_suite_focus=true#step:7:18

Fix date substitution in PR workflow

---

.github/workflows/docs.yaml
.github/workflows/release.yaml

This version matches the change made for the front-end code (see #1365).

Use Node 16 for the release and docs workflows

---

ui/components/AutomationsTable.tsx
ui/components/DataTable.tsx
ui/components/HashRouterTabs.tsx
ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/lib/theme.ts

Closes: #1761 
Fixes various spacing issues, and removes overflow: hidden from the body to allow overflowed pages to scroll. Adjusts nav and content to match.

Allow overflowed data to scroll

---

ui/components/Layout.tsx
ui/components/Logo.tsx
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap

Closes: #1796
Top title bar is now the correct height of 80px. Also aligns breadcrumbs and content title

Remove title bar padding and shrink logo

---

package-lock.json

package-lock.json had a newline problem that tripped up the `Check Git State` CI job.

Fix newline problem

---

.github/workflows/release.yaml

The gitops-server dockerfile name has been changed, and the release job didn't get changed to reflect that

Specify docker file in release job

---

README.md

We've not been using coveralls since merging v2, and the test workflow
is now part of the CI workflow.

README: Fix badges

---

tools/reboot.sh

_If nobody wants this, I don't care about merging, I was just having fun._
Well this one got away from me.
I have paired with a couple of people recently and given them my "turn
it off and on again script" and they were suitably impressed that I
thought I would refactor that script and bequeath it to the masses.
As what often happens when I write bash, it went a bit overboard. So now
I present to you: The Complete CLI experience:
```
Usage: ./tools/reboot.sh <COMMAND> <OPTIONS>
Script to tear down and reprovision a dev environment for weave-gitops.
WARN: will destroy and recreate the kind cluster.
Note: this script is deliberately bare-bones. It will not be extended.
ENV VARS:
GITHUB_TOKEN              With repo scope. Required for `bootstrap` command.
KIND_CLUSTER_NAME         Set to …
```

feat: Add over-engineered reboot script

---

ui/components/AutomationsTable.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/DataTable.test.tsx
ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
ui/lib/utils.ts
ui/pages/v2/FluxRuntime.tsx

Closes: #1763 
Clicking on the Status column of a data table will now sort by failing, then suspended, then ready
https://user-images.githubusercontent.com/65822698/160177547-83a615b1-b05a-4976-a829-dae828d6d230.mov

Sort by Status

---

.github/workflows/pr.yaml

This replaces the webhook, because the webhook does the
wrong thing:
* You can't get the code scan to run using the webhook.
* You also can't get snyk to look up go dependencies properly using the
webhook (it uses go mod graph, which lists lots of packages that
aren't part of your build, whereas the CLI uses go list, which only
lists ones that are)
Thus, run all the checks manually.
Rather than putting them in a separate scan workflow, just put it into
an appropriate part of the overall PR workflow - that is:
* The static check for all checks that don't require a built docker image
* A bit of extra logic dunked at the end of the docker build to scan
the built image
* A new, post-merge job that uploads all the things.
Unfortunately, you can't (as far as I can tell) make github actions …

Put explicit snyk scan workflow back

---

.github/workflows/chart.yaml
charts/gitops-server/Chart.yaml
charts/gitops-server/values.yaml
doc/release-process.md

This makes us publish our helm chart into the helm repository `helm.gitops.weave.works` - this is quite literally the same as the docs workflow, just into a different bucket, so we don't need to learn another workflow or tool or system.
This does _not_ prevent replacing old artifacts - if we're not careful, we can overwrite the same chart. Thus, I've added another step to the release process, but I've not added a check to see that we can't change the chart without changing the chart version.
This means you can now install gitops using:
```
--
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: ww-gitops
namespace: flux-system
spec:
chart:
spec:
chart: weave-gitops
sourceRef:
kind: HelmRepository
name: ww-gitops
interval: 1m0s
values:
additionalArgs:
- --insecure …
```

Release helm chart whenever it's changed

---

tools/tag-release

This is available either by running `tag-release current` or just `tag-release` with no arguments. I realized I wanted some way to ask "hey, where are we at right now?", and figured that this was a reasonable way to do it. It also seems more approachable than spitting out an error when no arguments are provided, which feels like a useful property to have in a potentially dangerous script.

Add a fallback option to output the latest tag

---

.github/workflows/release.yaml

When the code and the docs were stored in separate repos, this would happen by default, as the release workflow would [checkout the docs repo using its `main` branch][1], which the `create-pull-request` action would pull in as a default base. Now that we're running this workflow from a release tag (which has no concept of which branch it's on), we have to be explicit about where the documentation updates go.
[1]: https://github.com/weaveworks/weave-gitops/blob/e83c56bb2969a087679a9a3d7e163d2098696e57/.github/workflows/release.yaml#L122-L127

Generate documentation PRs against `main`

---

doc/adr/0012-acceptance-testing.md

Related to #1682
The PR adds ADR 0012, which details the immediate decision regarding acceptance testing within the Weave GitOps core product.

docs: add adr 0012-acceptance-testing document

---

doc/adr/0013-acceptance-testing-strategy.md

Related to https://github.com/weaveworks/weave-gitops/issues/1682
What changed?
The PR adds ADR 0013, which details the general strategy / philosophy that will be taken in regards to acceptance testing moving forward within the project.

docs: add adr 0013-acceptance-testing-strategy document

---

ui/components/FilterDialog.tsx

Approach: Sort filter options alphabetical
I don't know if react will reload things or not if the `options` list is
changed or not, so went with a immutable option using
`[...options].sort()`
Closes #1759

fix: Ordering within filter menu changes periodically

---

.github/workflows/pr.yaml

Without this, the merge flow still fails.

ci: Fix name of helm chart

---

ui/hooks/flux.ts
ui/lib/__tests__/graph.test.ts
ui/lib/graph.ts

Root cause:
The reconciled_objects request did not contain the automation type and
defaulted to 0 which is Kustomization.
Closes #1833

fix: Reconciled objects not appearing in a helm release

---

.github/workflows/pr.yaml

Stop trying to monitor IaC, it's not a feature that exist.
Don't run the whole pipeline twice just because there's 2 docker images.
We need to check out the code if we're to be able to monitor it.
Keep continuing on error, we want all the results.

Fix merge flow, take 4

---

charts/gitops-server/templates/service.yaml
charts/gitops-server/values.yaml

Add the option to annotate the service created by the helm chart
Because to enable IAP in GKE I need to be able to annotate the service with `cloud.google.com/backend-config: '{"default": "my-backendconfig"}'` (as per the [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_backendconfig_with_your_ingress))
By running `helm template` with a local values file and checking that the service was correctly annotated
```
$  helm template -f test_values.yaml --set service.annotations.foo=bar,service.annotations.bs=ohgods ./charts/gitops-server 
```

Add optional annotations to the charts's service

---

core/server/server.go
core/server/suite_test.go

If we fail to create a client, then we crash as soon as the namespace
cache runs for the first time with a nil pointer error. If we're sure
we won't be able to start properly, then we should abort, not log.

core/server: Error out if we can't create controller client

---

ui/components/ChipGroup.tsx
ui/components/SourcesTable.tsx
ui/pages/v2/Automations.tsx

Before (too close to the title and too much left margin):
After:

Adjust filter chip spacing

---

ui/images/SignInBackground.svg

There is apparently a bug in how firefox renders animated SVGs on Mac OS X that causes it to saturate the CPU.
This removes the animation tags and fixes the problem
Fixes #1788
Removed the animation from the `ui/images/SignInBackground.svg`
Because the signon page was un-useable on firefox.
Local testing that the page renders.

Remove animation from sign_on screen

---

ui/components/AutomationsTable.tsx
ui/components/DataTable.tsx
ui/components/FilterDialog.tsx
ui/components/FilterableTable.tsx
ui/components/Flex.tsx
ui/components/Footer.tsx
ui/components/HashRouterTabs.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/KustomizationDetail.tsx
ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/SourceDetail.tsx
ui/components/SourcesTable.tsx
ui/components/SyncButton.tsx
ui/components/__tests__/FilterDialog.test.tsx
ui/components/__tests__/FilterableTable.test.tsx
ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/lib/theme.ts
ui/pages/SignIn.tsx

Closes: #1708
BEFORE:
AFTER:
Gets the filter modal pretty close to what we want. Here's what's missing:
- ability to scroll data table horizontally when modal is open / shrink table (from #1708) 
- should filter modal always take up the entire content container? It probably needs SOME sort of max-height so that we can scroll when there are too many filter options.

Restyle Filter Modal

---

core/cache/container.go
core/cache/namespace.go
core/cache/namespace_test.go

It was possible to call `List()` before the first `update` finished and
populated the cache `map[string][]v1.Namespace{}`. Requests before the
first results arrived would return "default cluster not found" error.
Solution: Force sync update operation on `Start()` and move the `update`
call after the `select` for `Tick` to avoid multiple calls on `Start()`.
Closes #1919
---
feat: Force cacheContainer to maintain the order or cacheStores
Later on, some of our cache stores have dependencies between them.
Thinking of cluster clients and cluster list, these can be used in other
cache stores, so they should exists before the rest is initialised.
To achieve this, we can use a `[]cacheInfo` slice instead of a
`map[StorageType]Cache`, so the order we defined with `WithXXX`
functions will be the …

fix: Namespace cach can be called before the first results come back

---

README.md
tools/update-docs.sh
website/docs/cli-reference/_category_.json
website/docs/installation.mdx

* Fix the CLI download instructions - they were broken by the release.
* Improve a few things in the script that generates the CLI download instructions - they shouldn't break the download instructions every release.
* Restore the CLI reference's position back to lower down in the docs navigation.
* Update README to not suggest e.g. gitops install is a thing.
* Point README's cli-reference link to somewhere that doesn't 404.

docs: Fix manual download instructions, update readme

---

ui/components/AddGitRepoForm.tsx
ui/components/AutomationsTable.tsx
ui/components/EventsTable.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/KustomizationDetail.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourcesTable.tsx
ui/hooks/automations.ts
ui/hooks/flux.ts
ui/hooks/sources.ts
ui/lib/nav.ts
ui/lib/types.ts

The new default should be `NoNamepsace`, which is an empty string. Objects for all namespaces should be returned.

Remove flux-system as the default namespace from requests

---

Makefile

Do not delete `.idea` folder on `make clean` as that causes misconfiguration on Goland IDE

Do not delete `.idea` folder on `make clean`

---

ui/App.tsx
ui/components/AutomationsTable.tsx
ui/components/KustomizationDetail.tsx
ui/components/SourceLink.tsx
ui/hooks/automations.ts
ui/pages/v2/HelmReleaseDetail.tsx
ui/pages/v2/KustomizationDetail.tsx

Fixes an issue where the backend complained about a namespace not being populated. This only happens when the `k8s` client does a `.Get` instead of a `.List`

Populate namespace on automation detail screens

---

core/nsaccess/nsaccess_test.go

Closes #1915 
Show the `testEnv` who is boss.
Tested via:
```sh
$ make unit-tests
$ ps -a | grep api
```

Stop the testEnv

---

pkg/server/auth/server.go
ui/App.tsx
ui/contexts/AppContext.tsx
ui/contexts/AuthContext.tsx
ui/contexts/CoreClientContext.tsx
ui/hooks/automations.ts
ui/hooks/events.ts
ui/hooks/flux.ts
ui/hooks/sources.ts
ui/pages/SignIn.tsx

Closes #1894
Wraps the `Core` client to ensure that 401s always redirect the user to the `sign_in` page.

Redirect to sign in on AJAX requests

---

ui/components/AutomationsTable.tsx

This was causing a crash if the helm release didn't have a source ref defined

Make sourceRef namespace optional

---

website/docs/cluster-management/getting-started.mdx
website/docs/configuration/securing-access-to-the-dashboard.mdx
website/docs/getting-started.mdx
website/docs/guides/deploying-capa.mdx
website/docs/installation.mdx
website/docusaurus.config.js
website/versioned_docs/version-0.7.0/cluster-management/getting-started.mdx
website/versioned_docs/version-0.7.0/configuration/securing-access-to-the-dashboard.mdx
website/versioned_docs/version-0.7.0/getting-started.mdx
website/versioned_docs/version-0.7.0/guides/deploying-capa.mdx
website/versioned_docs/version-0.7.0/installation.mdx

This combines 3 different fixes to the manual:
* Make the bcrypt generation more straightforward, and applies a couple of small bug fixes to the getting started instructions regarding this step. This is done for both main and stable.
* Fix download link in stable. This takes the fixed link (as of fce5eab4) and applies it to stable.
* Adds slashes to all URLs. There's a lot of detail in the commit message for that fix - in essence this fixes relative links if you're linked to the manual, so to reproduce see [the installation page](https://docs.gitops.weave.works/docs/installation) and click on "Securing access to the dashboard" in the Pre-requisite section. This should fail now, but [the staging docs](https://staging.docs.gitops.weave.works/docs-fixes/docs/installation/) should pass the …

Docs fixes

---

ui/components/BucketDetail.tsx
ui/components/FluxRuntime.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/index.ts
ui/pages/v2/BucketDetail.tsx
ui/pages/v2/FluxRuntime.tsx
ui/pages/v2/GitRepositoryDetail.tsx
ui/pages/v2/HelmChartDetail.tsx
ui/pages/v2/HelmRepositoryDetail.tsx

This creates components for all of the gitops `SourceDetails`, which is what I took away from the suggestion [here](https://github.com/weaveworks/weave-gitops-enterprise/pull/601#discussion_r840672862)
It also exports `useListFluxRuntimeObjects` so we can show the flux runtime page as suggested [here](https://weaveworks.slack.com/archives/C03244W0C8H/p1649158559625549?thread_ts=1648749524.313119&cid=C03244W0C8H)
And finally, it exports the `CoreClientContextProvider` which seems to be purely a thing that's changed in core recently that I'm catching up with.

Add dedicated components for core details functionality, export flux hook

---

ui/components/AutomationsTable.tsx
ui/components/ConditionsTable.tsx
ui/components/DataTable.tsx
ui/components/EventsTable.tsx
ui/components/FilterDialog.tsx
ui/components/FilterableTable.tsx
ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap

Closes #1942 
Closes #1853
Setting some max-widths on parents and removing width constraints on table cells allows for horizontal scrolling of the data table. Also adjusts the filter bar animation to match - you can continue to scroll and see all data while the filter bar is open. 
https://user-images.githubusercontent.com/65822698/164079345-0b4173d0-fdb4-45b4-81de-507c4b3343a9.mov
How do we feel about this now that we are looking at it?

Remove width constraints from data tables to allow for horizontal scrolling

---

ui/contexts/CoreClientContext.tsx
ui/contexts/__tests__/CoreClientContext.test.tsx

I cannot figure out any way that this ever worked. Whenever
CoreClientContext was initialised, it tried to loop over the Core
object's iterable methods. However, it has none, so it just ignored
the API and returned an empty object. This then means that anything
trying to use the API will fail.
The fix here is to use `getOwnPropertyNames` instead - static methods
aren't iterable, so we have to use something more dramatic. However,
that also returns builtins like `prototype`, `name`, `length`, and we
don't want to monkeypatch those, so just monkeypatch methods.
I've written a test that fails with the old code and passes with the
new code.

ui: Make CoreClientContext monkeypatch work

---

ui/App.tsx
ui/components/DataTable.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap

Closes:
* #1939 
The routing logic needed to be changed to not be `exact` now that we are using path-based tabs.
Also fixes a double scrolly:

Fix sub page navigation

---

.github/workflows/prepare-release.yaml
doc/release-process.md

First, it fixes the prepare-release job so it actually triggers the release as an external user, so that CI actually runs. It then sets the exclude from release notes label, because this PR isn't doing anything interesting. And as a result, the whole PR actually turns green: #1977
Second, it rewrites the release process documentation to front-load more of my implicit knowledge.
* probably not actually final.

Final* small release process changes

---

Makefile
Tiltfile
cmd/gitops-server/cmd/cmd.go
gitops-server.dockerfile
package.json

The server binary now just loads files from disk, instead of
files embedded into the binary.
This has the advantage that the build process becomes slightly more
straightforward - we can compile the go binary without building
javascript, and we can refresh the javascript in docker images without
re-building the go binary.
I've hard-coded the server binary to look at the sub-directory
"dist" below the binary's directory, and dumped the generated files in
`bin/dist` - it's a bit of an odd place to put the dist files, but
`bin` is a directory of generated files already, and this makes it
very easy to accidentally get right.

Move javascript out of the server binary

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/admin-user.yaml
charts/gitops-server/values.yaml
website/docs/getting-started.mdx
website/docs/installation.mdx
website/versioned_docs/version-0.7.0/getting-started.mdx
website/versioned_docs/version-0.7.0/installation.mdx

Closes #1925
* `adminUser.password`->`adminUser.passwordHash` in chart which no longer calculates the password hash for the user
* added `adminUser.createSecret` toggle (so the password can be supplied via other methods without requiring manual `RoleBinding` creation
*NB* this builds upon PR #1944
To discourage users from (potentially) storing passwords in plain-text in git. This way, at worst, they're storing a bcrypt-hashed copy of it which is much harder to attack. This also allows us to simplify the getting started guide.
Helm changes were tested using `helm template` and various flags to check the k8s was appropriate. The changes to the guide were also checked through.
This is a …

Better bcrypt use

---

website/versioned_docs/version-0.7.0/installation.mdx

This effectively back-ports #1994 to the default 0.7.0 docs.

Fix mis-spelling of HelmRelease for stable documentation

---

ui/components/InfoList.tsx
ui/components/Layout.tsx
ui/components/Logo.tsx
ui/components/Page.tsx
ui/components/PageStatus.tsx
ui/components/SubRouterTabs.tsx
ui/components/UserSettings.tsx
ui/components/__tests__/Logo.test.tsx
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap

Closes #1971 
The page content title is now semi bold, as it should be. I also threw in some other small changes, such as aligning the title with the nav tabs and breadcrumbs, which was a huge pet peeve of mine, and adding a link to the logo that sends the user to the applications page. The extra padding on the user icon is so that the hover state doesn't brush up against the edge of the page.

Align titles, fix fonts, and link logo to applications page

---

ui/components/KustomizationDetail.tsx

Closes #1968 
Namespace was not being passed down from `KustomizationDetail`, leaving the table to run the request with no namespace specified.

Fix empty reconciled object tables

---

.github/changelog/changelog_configuration.json

Closes #1872 
The changelog generation configuration was updated to include the label "exclude from release notes" which indicates that a so-labeled issue should be ignored.
This was already supposed to work; this fixes it

Allow exclusion of issue from release notes via the "exclude from release notes" label

---

ui/components/GitRepositoryDetail.tsx
ui/components/HelmRepositoryDetail.tsx

Closes: #2009
We had a way to reformat ssh urls, it just never made its way into `GitRepositoryDetail` and `HelmRepositoryDetail`. Do we need to check the helm repo urls? If it's already http it will just return the url as is, so I'm not anticipating these changes breaking anything....is there any other way that a url for a helm repo might be broken/wrong?

Convert ssh urls to http

---

.github/workflows/prepare-release.yaml
.github/workflows/release.yaml

This puts the release notes into the PR body, so it can be edited
before the release happens. This lets us work on general advice on
e.g. breaking changes, without having to edit the release after it's
already been published. While not massively awful to have to make a
manual change, we ought to want to auto-publish the release to
e.g. social networks or even email, which means it's better to publish
the right thing in the first place.

release: Thread release notes into the PR, too

---

core/clustersmngr/factory.go

Closes
Waits for the initial load of clusters. Since we fire both, namespaces and clusters go routines to watch for changes, the namespace one can execute before the initial load of clusters, resulting in a empty namespace list for about 30 seconds until the next time it runs.

Waiting the initial load of clusters

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/deployment.yaml

We don't have the flag any more.

chart: Remove --helm-repo-namespace from flags

---

core/server/kustomization_test.go
pkg/testutils/testutils.go

While I was spiking on adding a full-blown cluster to our tests in an attempt to be able to delete resources, I realize we are actually capable of doing that right now. 
We probably were lead to believe we couldn't because we tried to delete `Namespaces`, and that is a special case that needs to be handled differently, I've found on the `controller-runtime` source code how to do it, so I added that to our repo.
Not all tests need to have a clean state, but if the ones you are working on need, make use of `testutils.DeleteAllOf` to delete all resources of a given type and `testutils.DeleteNamespace` to delete a single namespace.

Adding testutils methods to delete resources

---

.github/workflows/release.yaml
charts/gitops-server/Chart.yaml
tools/update-docs.sh
website/docs/installation.mdx
website/versioned_docs/version-0.8.0/installation.mdx

I had a bug in my release merge step - it wasn't triggering a deploy of docs & helm chart, because it wasn't using an external github token, and github actions can't trigger other actions through its actions.
This adds some newlines to the chart to get that deployed, and I found a bug in the CLI installation instructions (again!) which I fixed the cause of and then I fixed the docs.

Deploy new chart and docs for new release

---

core/server/events.go
ui/components/Timestamp.tsx

For some reason, Go formats strings weird with `String()`
```go
func (t Time) String() string {
s := t.Format("2006-01-02 15:04:05.999999999 -0700 MST")
```
Fixing by using `Format()` and use RFC3339, that can be parsed on client
side too.
Closes #2034

fix: Timestamp column is empty on Event list pages

---

ui/components/AutomationsTable.tsx
ui/components/BucketDetail.tsx
ui/components/DataTable.tsx
ui/components/DirectedGraph.tsx
ui/components/EventsTable.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/InfoList.tsx
ui/components/KustomizationDetail.tsx
ui/components/Layout.tsx
ui/components/Page.tsx
ui/components/PageStatus.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourceDetail.tsx
ui/components/SourceLink.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/pages/v2/Automations.tsx
ui/pages/v2/BucketDetail.tsx
ui/pages/v2/FluxRuntime.tsx
ui/pages/v2/GitRepositoryDetail.tsx
ui/pages/v2/HelmChartDetail.tsx
ui/pages/v2/HelmReleasePage.tsx
ui/pages/v2/HelmRepositoryDetail.tsx
ui/pages/v2/KustomizationPage.tsx
ui/pages/v2/Sources.tsx

Here's the big list of changes:
A `maxWidth` prop has been added to the `Field` type, allowing longer data table cells (message, name) to wrap. Additionally, the `SourceLink` component has a `short` prop in order to cut the url down inside the data table. One downside of these changes is that it becomes unclear that the table is scrollable/there are additional columns. 
The title bar in layout has been removed. Adjustments to the details pages make those look great, but the top level pages look a little empty at the top to me. This is all in service of decreasing the min-width of the app to 768px.
main page: 
detail page:
The top bar is now set to `position: fixed`. I also set the nav content to fixed but it looked clunky - I want to figure out how to add some kind of delay there or make …

UI Responsiveness Pass

---

charts/gitops-server/templates/admin-user.yaml
charts/gitops-server/values.yaml
website/docs/configuration/securing-access-to-the-dashboard.mdx

It's created by default if `adminUser.create` is true, but can be turned
off with `adminUser.createClusterRole`.
The clusterRole gets the same permissions as the role, but without namespace restrictions.
Closes #2053

feat: ClusterRole for default user

---

.github/workflows/pr.yaml

The issue says whitelist, but I think blacklisting is much better. With
whilelisting items would prevent future code to be scanned if we add new
root directories or move/rename existing ones, for example moving
internal Go code under `internal/` (to make it clear they are not
intended to be reused in external tools).
Ignored glob patterns:
- `doc/**` (everything under `doc/`)
- `website/**` (everything under `website/`)
- `*.md` (all markdown files in the of the repo)
Closes #2061

chore(ci): Skip CI runs if no code changes

---

.github/workflows/chart.yaml

If 2 different versions of the helm chart are released with the same
version number, then bad things happen: users won't upgrade, users
running the same version will run different revisions, and we won't be
able to debug things properly.
This step won't be part of the mandatory steps, but it'll light up
read, at least.

ci: Add step that fails if chart is changed but version isn't

---

.github/workflows/chart.yaml

This fixes a typo - `head` is the latest commit (just like e.g. git
show HEAD), `base` is the base branch (which is also what github calls
it when you open a PR). So in effect, the code was comparing the most
recent version to itself and somehow kept finding that the version was
the same.

ci: Fix check to see that chart version was bumped

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/admin-user-creds.yaml
charts/gitops-server/templates/admin-user-roles.yaml
charts/gitops-server/templates/admin-user.yaml
charts/gitops-server/templates/custom-admin-user.yaml
pkg/server/auth/server.go
pkg/server/auth/server_test.go
pkg/server/auth/token_signer_verifier.go

Create addition RoleBinding and ClusterRoleBinding based on the
username, and keep the original `wego-admin` there to maintain backward
compatibility.
`DevMode` with Tilt still uses `wego-admin` as a hard-coded user,
potentially we can even remove the `DevUser` maybe.
`DevMode` is used only to set `DevUser` on `HMACTokenSignerVerifier` and
the user is used only return with a static claim on `Verify()`.
Additional changes:
* Split up the admin-user.yaml into logical parts like
* Credentials as they will be created only once.
* Role and ClustreRole as they will be created only once
* Two files for RoleBinding and ClusterRoleBinding (as described above)
Fixes #2001

fix: Weave GitOps username is hard-coded

---

.github/workflows/pr.yaml

The quotes around LDFLAGS were also being passed (although this was only
obvious in the docker output rather than the command being called). The
inclusion of these quote marks meant that `go build` was ignoring the
`-ldflags` as one giant string that it didn't understand.
Removing the quotes seems to work and has hopefully fixed the problem.

Don't use quotes on flags to docker build action

---

.github/ISSUE_TEMPLATE/bug_report.md

There's now an endpoint for getting detailed version info, we should ask
people to use it when filing bug reports

Update bug report template with version info

---

ui/components/AutomationDetail.tsx

The UI responsiveness changes in https://github.com/weaveworks/weave-gitops/pull/2015 may not have been merged before this PR  https://github.com/weaveworks/weave-gitops/pull/2079, which nicely unifies HelmRelease and Kustomization Detail into AutomationDetail. I've carried over they styling changes from the old components to make sure that everything matches!

Match AutomationDetail styling to SourceDetail

---

core/clustersmngr/factory.go

- Right now we bail out if there's an error connecting to a leaf cluster
- This then requires a restart of the server to continue trying
We also tweak the userNamespace cache. This was previously 1h.
- When provisioning clusters the RBAC takes a minute to be configured
- We cache the permissions in an incomplete state for up to an hour
- This makes provisioning new clusters a bit awkward
- TODO: Follow up issue to discuss options
During cluster provisioning we run into many transitory errors like "cannot connect to cluster", we want to be resilient to these rough patches.
Tested in a MC environment

Continue processing and updating the clustermngr caches onError

---

.github/workflows/pr.yaml
website/README.md
website/docs/installation.mdx
website/docusaurus.config.js
website/package.json
website/versioned_docs/version-0.7.0/installation.mdx
website/versioned_docs/version-0.8.0/installation.mdx
website/yarn.lock

This has an API change for algolia where the App ID needs to be
specified. See
https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration and
in particular note that they say these parameters are safe to put into
git. How did I know what parameters to enter? They're plain text
parameters as part of the request, I just grabbed them.
This also has an API change that causes the inlinetoc comoponent to be
a flat array instead of a tree - done in facebook/docusaurus#729 - so
this replaces the hard-coded index with a function that looks for the
start and end of the relevant section.
This gets rid of all security vulnerability warnings except for two,
which aren't relevant - see facebook/docusaurus#6394.

Upgrade docusaurus to latest version

---

README.md
cmd/gitops/root/cmd.go
cmd/gitops/version/cmd.go
go.mod

We were apparently using logrus to
a) print that there is a new version of gitops available
b) error & exit if viper failed to the point where we can't start
c) set verbose logs
Now, there's no logs to make verbose, so remove that. Error & exit is
perfectly supported by the built-in log module. And as for printing
that there's a new version available, we can just use the same custom
log framework every other log line in this binary uses.
Logrus is still an indirect dependency, but at least our code is more
consistent.

Stop using logrus

---

ui/components/AutomationsTable.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/KustomizationDetail.tsx
ui/lib/utils.ts

Closes #2063 
Populate last updated from the `type:Ready` condition in the automations table and detail screens:

Use ready condition for automations table timestamp

---

ui/components/AutomationDetail.tsx
ui/components/AutomationsTable.tsx
ui/components/DataTable.tsx
ui/components/FilterDialog.tsx
ui/components/FilterableTable.tsx
ui/components/ReconciliationGraph.tsx
ui/components/SourcesTable.tsx
ui/components/URLAddressableTable.tsx
ui/components/__tests__/FilterDialog.test.tsx
ui/components/__tests__/FilterableTable.test.tsx

Re-work the DataTable URL logic to make it easily testable.
This also sneaks in a change to add the source to the ReconciliationGraph as I was pairing with @joshri  and I forgot to switch branches. It is in it's own commit, so keeping it in the PR.

Refactor table URL filtering for testability

---

.github/ISSUE_TEMPLATE/bug_report.md

Our bug report template had way too much boilerplate, leading to text-walls on bug reports.
Other notes:
* Bug reporters won't know if a bug is a server or UI bug; an eng will need to make that determination. Also better represented as a label, so that is removed.
* Severity is better represented as a label
* We really only care about k8s, flux, and wego versions: simplified

Simplify bug report template

---

cmd/gitops-server/cmd/cmd.go
core/logger/logger.go
pkg/server/handler.go
pkg/server/middleware/middleware.go

This changes 2 things: it starts to log all requests rather than just ones to `/v1/`, and makes it work to specify log levels in your config.
The log handler is now attached to the top HTTP server instead of just to the core handler, so you can see _all_ requests being served. Only non-OK requests are logged at above DEBUG level, so it shouldn't cause a massive increase in log sizes, but it does mean you can debug e.g. OIDC logins properly.
The log level specification is now correct - HTTP errors were logged as debug, debug messages were logged as errors, because zap and logr disagree on whether a bigger numuber is more important or more voluminous. This flips them so it works.

server: Start logging all requests, and fix specifying log levels to application

---

gitops-server.dockerfile

I _think_ this might have been the cause of the frontend being
compiled differently when built with the docker file compared to when
doing it outside - tsconfig specifies flags that sound like they could
affect the compiler output.
A reasonable response to this would be "should we stop trying to
enumerate all the files, because this sounds fragile?" to which my
response would be, yes, but, I really don't want to bust the js cache
because go code changed, so, no, I'm gonna continue doing it this way
for now.

Put tsconfig & parcelrc into UI build dockerfile

---

pkg/server/auth/auth.go
pkg/server/auth/auth_test.go
pkg/server/auth/server.go

We don't support using refresh_tokens, so stop requesting them.

Remove offline_access from OIDC token requests

---

ui/components/AutomationDetail.tsx

Closes #2016 
- Removed hardcoded kustomization kind value when hitting reconciled objects end point. This is now calculated dynamically based on the automation type.
- When hitting the reconciled objects end point, the parameter `automation kind` always had the value `Kustomization` even though the automation selected was a helm release.
- Manually and local using tilt

Dynamically pass in the right automation kind

---

ui/components/AutomationDetail.tsx

Closes #2160 
- We are now passing in the helm chart source to the `ReconciliationGraph` component if the automation is a HelmRelease.
- This was causing the UI to brake
- Locally using a kustomize app and and helm release app, make sure the graph works for both.
It looks like this now:

Pass in right source when automation is helm release

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/role.yaml
tools/helm-values-dev.yaml
website/docs/configuration/service-account-permissions.mdx

This was causing the error `Execution error at (weave-gitops/tempaltes/role.yaml:23:8). You've supplioed both rbac.viewSecrets and rbac.viewSecretsResourceName. please only use rbac.viewSecretsResourceName" failed`
Set the correct values in `tools/helm-values-dev.yaml`
Tested locally & checked helm output e.g.:
```console
$  helm template -f tools/helm-values-dev.yaml test charts/gitops-server
```
works vs on main:
```console
$ helm template -f tools/helm-values-dev.yaml test charts/gitops-server
Error: execution error at (weave-gitops/templates/role.yaml:23:8): You've supplied both rbac.viewSecrets and rbac.viewSecretsResourceName. Please only use rbac.viewSecretsResourceName
Use --debug flag to render out invalid YAML
```

Use 'viewSecretsResourceNames' no 'viewSecrets' in dev values.yaml

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/deployment.yaml

closes #2171 
If using the "new" helm chart (post https://github.com/weaveworks/weave-gitops/pull/1983) with v0.8.0, which still expects the env var to be set.

Provide auth compatibility for older images

---

ui/components/AutomationDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/ReconciliationGraph.tsx

Based on @jpellizzari 's suggestion to add optional chaining.
Accessing properties of undefined objects breaks UI when testing locally and on many pages in staging.

Fix helmChart error

---

ui/components/DataTable.tsx
ui/components/FilterDialog.tsx
ui/components/Text.tsx
ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/components/__tests__/__snapshots__/Text.test.tsx.snap
ui/lib/theme.ts
ui/typedefs/styled.d.ts

Closes #2164
Filter dialog should not render a checkbox on categories with no options (from #2147) :
Also adjusts global font sizes according to #2164

Handle empty filter dialog options + adjust font sizes

---

ui/components/AutomationsTable.tsx
ui/hooks/sources.ts

This makes links to kustomizations from the Automation table work again.
This also fixes opening the details page about sources.
This closes #2162, as the type property is no more.

ui: Fix a couple of problems displaying & linking to objects

---

core/server/types/helmrelease.go
core/server/types/helmrepository_test.go
core/server/types/kustomization.go
core/server/types/kustomization_test.go
ui/components/AutomationsTable.tsx

This is 2 commits: a small one that makes sure that the source namespace is always set correctly, and a big one that adds some pretty verbose test code.
The setting source namespace correctly bit is about making sure that the backend always sets a namespace - in flux, a sourceref doesn't have a namespace set if the automation is in the same namespace as the source (see e.g. https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta2.CrossNamespaceSourceReference ). However, that's a faff to remember, so this just sets them always in the protobuf message, so the frontend doesn't need to care.
Finally, this adds some tests to the type conversion code. It's a lot more verbose than the actual type conversion code, as it's intended more as regression testing - the …

Provide the correct source namespace in automations

---

go.mod
go.sum

I don't believe either is affecting us (we pulled in dgrijalva/jwt-go from mockoidc but that's test code, and docker/distribution had a vulnerability related to parsing OCI manifests which I don't think we do directly), but I also don't believe it hurts to stay up to date.

Upgrade a couple of dependencies with security warnings

---

core/server/helm_release.go

This just uses flux's built-in methods to use the correct
namespace/release name, instead of us trying to get it right
ourselves.
This fixes #2132.
I've tested this by creating objects with various combinations of `targetNamespace`, `storageNamespace` and `releaseName` to see that it failed before and is succeeding now. There are no automated tests however, given that the logic now lives in flux.

Fix getting a helm release's inventory when using targetNamespace

---

core/server/internal/adapters.go
core/server/sync.go

This fixes two copy-paste errors, plus removes one API request that we
don't need to do.
There fixes two copy-paste errors (chart vs repository, name vs
key).
This also removes a redundant extra request to read the source a
second time - the first thing requestReconciliation does is to read
the object again, and then use the result.
Finally, this does a bit of renaming for
consistency. types.NamespacedName and client.ObjectKey are the same
type, but we used both names, and thus we were using `name` for the
source key, and `key` for the automation name. Use `client.ObjectKey`
everywhere instead.
This fixes #2179.

Fix syncing sources

---

pkg/helm/charts.go
pkg/helm/charts_test.go

Support HelmRepository annotation for profiles.
This adds support for a new annotation on Flux HelmRepositories
weave.works/profiles: "true"
If the annotation exists, all charts discovered in the repository are considered to be Profiles.
Simplify getting profiles in from existing HelmCharts.
This is a fairly trivial change, expanding the predicate to accept the helm repository, and checking for either chart of repo annotation.

Allow filter repos

---

cmd/gitops/add/terraform/cmd.go
pkg/adapters/http.go
pkg/templates/templates.go
pkg/templates/templates_test.go

The template name changed on the last commit, but we didn't reflect that in this PR.
This is a fix to change that to the more recent name of the template.

Fix the template for TFTemplate

---

cmd/gitops/add/clusters/cmd.go
cmd/gitops/add/cmd.go
cmd/gitops/add/profiles/cmd.go
cmd/gitops/add/terraform/cmd.go
cmd/gitops/delete/clusters/cmd.go
cmd/gitops/delete/cmd.go
cmd/gitops/get/clusters/cmd.go
cmd/gitops/get/clusters/cmd_test.go
cmd/gitops/get/cmd.go
cmd/gitops/get/credentials/cmd.go
cmd/gitops/get/profiles/cmd.go
cmd/gitops/get/templates/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/update/cmd.go
cmd/gitops/update/profiles/profiles.go
pkg/adapters/http.go
pkg/adapters/http_test.go
pkg/templates/templates_test.go

Added functionality to specify username and password through command line(not recommended) or env variable
To add basic authentication against WGE for local development using kind clusters
Allow passing username and password to all command that contacts WGE endpoints. If they are specified the args are used to sign in before applying the command
Added unit tests and tested against a local WGE instance

add username and apssword cli auth to enterprise endpoint

---

ui/components/SourceDetail.tsx

You can have multiple Sources in the same cluster with the same
name, so we should find the requested Source by namespace.
We already link to sources with namespace, and it's already being
provided to the SourceDetail component, so this should Just Work™.

ui: Use namespaces for finding sources

---

.github/workflows/prepare-release.yaml
ui/components/__tests__/FilterableTable.test.tsx
ui/components/__tests__/__snapshots__/Footer.test.tsx.snap

We have a UI snapshot that contains a release number, so we need to
re-generate the UI snapshots whenever we update the JS version.
The reason I found this out was that I _did_ change the version number without re-generating the UI snapshots, so this also re-generates the UI snapshots.

Auto-update UI snapshots

---

website/docs/cluster-management/cluster-api-providers.mdx
website/docs/cluster-management/managing-existing-clusters.mdx
website/docs/cluster-management/provider-identities.mdx
website/docs/enterprise/intro.md
website/docs/installation.mdx
website/versioned_docs/version-0.8.0/cluster-management/cluster-api-providers.mdx
website/versioned_docs/version-0.8.0/cluster-management/managing-existing-clusters.mdx
website/versioned_docs/version-0.8.0/cluster-management/provider-identities.mdx
website/versioned_docs/version-0.8.0/enterprise/intro.md
website/versioned_docs/version-0.8.0/installation.mdx

Closes
Updated docs
The kind config in the installation guide for Weave GitOps Enterprise included port mappings that the rest of the guide did not use.
N/A
Viewed docs locally
N/A
N/A

Removed extra port mappings from kind config in installation guide

---

Tiltfile

Fix bug in our local tiltfile.
os.getenv returns a NoneType as a default value not an empty string so our
docker registry wasn't being populated by default.

Tilt: Fixed default value for local dev

---

core/clustersmngr/factory.go

Remove the client config from the error log since the wrapped error already contains the cluster name for which the connection couldn't be established.

Fix logging on cluster connection error

---

README.md
pkg/adapters/http.go
pkg/adapters/http_test.go
pkg/adapters/testdata/clusters.json
pkg/clusters/clusters.go
pkg/clusters/clusters_test.go

Closes #weaveworks/weave-gitops-enterprise#869
Updated `RetrieveClusters()` to use `/v1/clusters` endpoint for listing clusters
Endpoint changed in EE 
Manually tested it + unit tests

update `get clusters` to use the new endpoint

---

ui/components/AutomationsTable.tsx
ui/components/EventsTable.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourcesTable.tsx

Closes #2239 
Adds preserving newlines and auto-wrapping long lines of text for all table cells which contain messages.
Using `nth-child` for styling individual table cells based on @jpellizzari 's suggestion.
Code was autoformatted on save with Prettier.

Support multiline text and auto-wrap long lines in message table cells

---

tools/update-docs.sh

The CLI installation instructions have been deleted, so we can't
update the release number any longer.

release: Don't try to update non-existing CLI installation steps

---

cmd/gitops/check/cmd.go

It doesn't do anything at all - we always call `check.Pre()` - except
for trying to register a `-p` flag which has been stolen by
`--password` and now it crashed at startup.

cli: Remove gitops check --pre flag

---

.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
doc/development-process.md
package-lock.json
package.json

Remove manual resolutions from package.json - they were old,
and they were incorrect, because they used version ranges
rather than the resolved version. This caused npm 16.15 to throw
errors, so I've manually corrected them and re-built the lock file.
Remove the preinstall command from the package.json file, because
it causes npm ci to a) modify package-lock b) incorrectly. We should
use the package-lock file in CI, and we should error if it's not up to date,
which is what npm ci does by default, and should now do again for us.
We shouldn't use an older NPM version in CI and a newer version when
releasing. With a bit of luck, this'll let us know a few day in
advance if a new release breaks something.

Fix frontend build using node 16.15

---

ui/components/Button.tsx

Closes #2228 
When font sizes were changed recently, the loading icon on buttons became too large, which would adjust button size when it appeared. It wasn't tied to the theme so I didn't catch it, but now it is with the `useTheme` hook from styled components. Hooray!

Fix loading icon size inside buttons

---

ui/components/AutomationsTable.tsx
ui/components/BucketDetail.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/ReconciliationGraph.tsx
ui/components/SourceLink.tsx
ui/components/SourcesTable.tsx
ui/lib/nav.ts
ui/lib/utils.ts

Closes #2250
Adds links from a ReconciledObjectsTable name column cells on Kustomization or HelmRelease details page (checking the `automationKind` prop) to object detail pages for objects of types:
- Kustomization
- Helm Release
- Git Repository
- Helm Repository
- Bucket
If an object to which the row corresponds is not of a type above, the name of the object is displayed as plain text without a link.
Also renamed the `displayKind` function (which removes `Kind` prefix) to `removeKind` and added the `addKind` function for mapping `groupVersionKind.kind` string to `FluxObjectKind` enum values.
Renamed function `sourceTypeToRoute` to `objectTypeToRoute` and added mapping for `Kustomization` and `HelmRelease` to it.

Link to Flux resources in the details table for Kustomizations and Helm Releases

---

ui/components/YamlView.tsx

Closes #2229 
Adds a counter to the yaml view with CSS, based on this stack overflow post: https://stackoverflow.com/questions/41306797/html-how-to-add-line-numbers-to-a-source-code-block
The wrapping was getting a bit crazy, so I changed the view to `overflow: scroll` as well.

Add number lines to yaml tab

---

ui/components/ReconciledObjectsTable.tsx
ui/lib/utils.ts

Closes #2032 
The ReconciledObjectsTable now displays container images across multiple lines

Kustomizations and Helm Releases display images in tables

---

.github/workflows/prepare-release.yaml

This is a follow-up to f3e7230ff - that commit made sure that `npm ci`
stopped changing the lock file (as expected from that command), but
that means that when running `npm i` right now, package-lock.json
doesn't change, which means the lock file's version doesn't change.

Replace `npm ci` with `npm i` in releases

---

ui/components/InfoList.tsx
ui/components/Metadata.tsx
ui/components/SourcesTable.tsx

Closes #2224 
Closes #2280 
A couple styling changes allow for multiline support in metadata annotations, as well as a quick loop that supports http or https links. I wanted to put the loop into the info list component instead but we're already passing down non-strings in the pair.

Adds multiline and link support to metadata

---

ui/components/FilterableTable.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/SourceDetail.tsx
ui/components/URLAddressableTable.tsx
ui/components/__tests__/FilterableTable.test.tsx

Closes: #2284 
Massively simplifies the `filterSelectionsToQueryString` function and fixes an error where it would replace the entire query string with just the filter part - `query-string` allows for us to isolate just the filter section of the query string and change it, then put it all back together again with `stringify()`. 
Adds a `URLAddressableTable` to the `ReconciledObjectsTable` component, meaning urls will actually show up on Kustomization or HelmReleaseDetail.
Fixes another bug I found while working on this - the table in the source detail page was using data from the `useListAutomations` hook without checking for a loading value, which would pass down no data to the filters, which would ruin the config and leave checkboxes empty. At least now we're accounting for if the hook …

Fix invalid URL caused by filters

---

ui/components/InfoList.tsx
ui/components/Metadata.tsx
ui/components/__tests__/Metadata.test.tsx
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Closes #2269 
Closes #2301 
- Added capitalizing words in metadata keys if needed.
- Added sorting metadata key/value pairs by key (by original key value, not formatted) alphabetically.
- Minor improvements:
-- now we are mutating a local copy of Metadata props instead of the props themselves, it is considered unsafe to mutate props in React and can lead to hard-to-detect bugs when component complexity increases.
-- if we check for the `http` substring in the `isHTTP` function we don't need to check for `https` after that.
-- instead of metadata keys the `ImageList` component now uses `item` with index as item keys, because some of the formatted keys can be the same (to prevent the duplicate key React error).
-- changed the metadata prop type to match the input type.
- Added snapshot …

2269 Format metadata keys; 2301 Sort metadata key/value pairs by key

---

doc/adr/0014-k8s-client-api-fairness-and-rate-limits.md

This PR proposes a new ADR for Kubernetes API Priority and Fairness in Kube 1.24 and re-adjusts values of QPS and Burst for Kube <= 1.23.

ADR 0014 Kubernetes Client API Fairness and Rate Limits

---

.github/workflows/chart.yaml

We had implemented chart publication to `oci://ghcr.io/weaveworks/charts/weave-gitops`, which was the wrong place.
When doing `helm push`, Helm expects the 3rd parameter to be a chart location, not a chart image name.
The correct one should be `oci://ghcr.io/weaveworks/charts`. Helm then puts the chart image name and version for us.
Re Fixes #2300 
Improves PR #2327 

change chart image to chart location

---

gitops-server.dockerfile

When building locally, this means the go cache will stay hot, and
builds will be a lot faster.
I don't know how much the parcel cache mount help, but if it's worth
caching, it's probably worth keeping that cache for next time?
When not building locally, it shouldn't make any difference.

docker: Use cache mounts when building gitops-server

---

.github/workflows/release.yaml

Make dependencies doesn't exist, flux version is set by the make file already.

release: Don't run make dependencies, don't set flux version

---

core/server/fluxruntime.go

Closes #2324 
- Added de-duplicating reconciled objects by UID (based on @chanwit 's sample code).
- I haven't  been able to reproduce the same issue with child objects, so I've removed the de-duplication code I started adding for `GetChildObjects` and stored it. The current code fixes the original issue with the reconciled object table. If there is an additional issue with `GetChildObjects`, I can add the code back fast in another request.
- I thought of storing and sorting reconciled objects with the same ID within a pair to add only objects with bigger version numbers to the result (out of each pair of objects with the same UIDs), but noticed that v1beta2 objects come in first before v1beta1 objects, so there is no need to sort the objects in each pair. I hope this behavior is …

Duplicates on detail pages table view

---

website/docs/guides/using-terraform-templates.mdx

PR 1/2 for https://github.com/weaveworks/weave-gitops-enterprise/issues/724
Add a simple guide to the docs (`website/docs/guides`) with instructions on how to:
- add a Terraform-type `GitOpsTemplate` to a config repo so that Flux applies it to a cluster
- set values and translate this TF `GitOpsTemplate` to a TF manifest by using the `gitops` CLI and the WGE backend (no UI yet)
- list one or all TF templates
- list template parameters 
This Guide adds instructions on how to use the TF-Controller's matching features in WGE.
N/A
Tested these steps locally. Ideally, a reviewer would also go through the instructions to make sure it works for someone else as well and that …

Add `Using Terraform templates` Guide to docs

---

ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Closes #2386
Adds a check on the last piece of the image string to remove anything after and including the `:` character plus a test - the tag will still show in the table but it will not be a part of the link

Removes tags from image links

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/oidc-auth-secret.yaml
charts/gitops-server/values.yaml
cmd/gitops-server/cmd/cmd.go
core/server/featureflags.go
core/server/featureflags_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go
website/docs/configuration/securing-access-to-the-dashboard.mdx
website/versioned_docs/version-0.8.0/configuration/securing-access-to-the-dashboard.mdx
website/versioned_docs/version-0.8.1/configuration/securing-access-to-the-dashboard.mdx
website/versioned_docs/version-0.9.0/configuration/securing-access-to-the-dashboard.mdx

* Added `--oidc-secret-name` flag to allow alternate secrets to be provided to the server
* Enabled creation of the `oidc-auth` secret as part of the helm chart
* Improved logging around OIDC start up
* Fixed some typos in the docs
Because I ran into problems relating to these issues several times whilst setting up Dex (particularly around the logging not providing feedback on why OIDC wasn't working). The additional flag was mostly a "while I'm here".
This should also mean that providing OIDC configuration via CLI actually works now (I believe it didn't previously because `featureflag.go` would fail to find a secret and then mark `OIDC_AUTH` as disabled).
Mostly through adding a new flag. The only …

Allow the oidc secret to be named other than 'oidc-auth' and improve logging

---

ui/components/DirectedGraph.tsx
ui/components/Footer.tsx
ui/components/ReconciliationGraph.tsx
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Closes #2312 
- Fixed the initial zoom level and position of the graph.
- Improved graph positioning performance thanks to using d3 `translate` instead of the SVG `viewBox` attribute.
- Reduced graph zoom level (added custom mapping from slider scale to graph zoom percent).
- Added graph utility functions (for converting and mapping zoom-related values) to utils and added tests for them.
- Fixed version keys in the footer (because it produced a warning when running tests, I had wrapped the version elements with React fragments but had forgotten to move the keys to fragments).
- Reworked D3Graph props and types and zoom options.
- Improved graph positioning in general. Hopefully, other graph-related issues will be easier to handle in the future after this rework and refactoring.
- Added a …

Graph view hides resources with default zoom

---

ui/components/KubeStatusIndicator.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap

`computeReady` in `KubeStatusIndicator` was not using the status field of the `Condition` object - tests didn't catch this because without the `short` prop the component renders the message no matter what, even though the wrong icon could be displayed. Added the short prop in a couple tests and am correctly testing "Not Ready" instead of the full message.

Fixed bug in computeReady function

---

website/docs/installation.mdx
website/versioned_docs/version-0.9.0/installation.mdx

This upgrades stable and HEAD manuals, for new the new AWS Marketplace
integration that uses our helm chart.
This documents the changes from weaveworks/aws-marketplace#126 to

manual: Update AWS Marketplace installation instructions

---

cmd/gitops/beta/cmd.go
cmd/gitops/beta/run/cmd.go
cmd/gitops/cmderrors/errors.go
cmd/gitops/root/cmd.go

Closes #2356
- Added templates for the `beta` command with `run` subcommand.
- Added a short description for the `beta` command.
- Added a short and a long description for the `run` command.
- Added a positional argument requirement (this argument will be used for `filepath`) to the `run` command.
**Possible improvements/questions:**
1. There are `[flags]` mentioned in the `run` command help in #2356 , but I don't see specific flags in #2355 Probably it will be clarified what flags the `run` command can support when the actual command is added.
That's why, I've added an empty placeholder structure for flags (with suppressing the linter warning and a todo).
If the `run` command is supposed to be run with global flags only, I can remove the placeholder.
2. I've added checking for the …

Help command for gitops beta run

---

Makefile
cmd/gitops-bucket-server/main.go
gitops-bucket-server.dockerfile
go.mod
go.sum

This PR implements an S3-based bucket server to be used in a temporary development environment.
It is the server-side component for the GitOps Sync to talk to.
The server is implemented using the in-memory GoFakeS3 library. It accepts connections at port 9000. It is designed to run inside Kubernetes without touching the disk. To connect to this server, port forwarding is required.
Fixes #2398

add gitops bucket server

---

ui/contexts/AuthContext.tsx
ui/contexts/CoreClientContext.tsx

Closes #2361 
Saves the url under redirect in search params when the user doesn't pass the auth check. Navigates to that redirect url on sign in if it exists.
https://user-images.githubusercontent.com/65822698/177589208-80d41137-6243-4cc6-8814-b228ed8580eb.mov

Redirect to previous location on 401

---

cmd/gitops-server/cmd/cmd.go
core/server/featureflags.go
core/server/featureflags_test.go
pkg/featureflags/featureflags.go
pkg/featureflags/featureflags_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go

There is a bit of godoc in the new featureflags module - basically,
it's a static, global map. It is initialised automatically from server
startup by setting an env var starting with
`WEAVE_GITOPS_FEATURE_whatever`, and you can also call the `Set()`
function directly. The frontend featureflag endpoint now literally
just copies this map, so the backend and frontend are in sync.
To test it out, dump the following in `tools/helm-values-dev.yaml`:
```
envVars:
- name: WEAVE_GITOPS_FEATURE_FOO
value: it worked
```
Then visit the sign in page, and you'll see the frontend request
feature flags, which (after the backend pod restarted) now includes
this flag.
This changes the auth system to use the same flags - which has a
behaviour change: the pod will now refuse to start if there's no login …

Introduce BE featureflags, make the auth system use them

---

.github/workflows/release.yaml

When hitting `/v1/version` against a 0.9.0 image, it returns
`{"semver":"v0.0.0","commit":"","branch":"","buildTime":""}`. This is
incorrect.
This copy-pastes bits from the dev image build process that we use to
set these properly for the staging cluster.
The footer still prints the correct thing since the javascript does
have the right versions.
This fixes #2370

Set version flags when building release images, too

---

ui/components/Layout.tsx

Closes #2383 
Here's the new behavior - a cool trick with `transform: translate` allows for a half-fixed styling of the nav so the page overflows horizontally as expected. Also decreased top tool bar min width so that the user settings icon is visible more often
https://user-images.githubusercontent.com/65822698/176738109-7da2e54f-bd6c-46d6-89ed-a73df917631f.mov

Nav fixed vertically, but scrolls horizontally

---

cmd/gitops-server/cmd/cmd.go
core/clustersmngr/factory.go
core/clustersmngr/factory_test.go
core/server/fluxruntime_test.go
core/server/suite_test.go

What I want to achieve is to be able to inject a fake k8s client for
tests that bypasses the provided restconfig, since I want to be able
to run tests without having an API server running.
This is not just about the time it takes to start an API server
(although that is nice) - this means we get to set arbitrary object
state, and then test how that state is represented.
Right now, this just adds complexity for the purpose of tests -
although, not a lot of complexity. I think this level of separation
from the core clustersmngr might be a useful level of abstraction for
other code too, but I'm not going to try that out right now.

clustersmngr: Make it possible to inject another clusterpool

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/cmderrors/errors.go
pkg/run/forwarder/forwarder.go
pkg/run/install_dev_bucket.go
pkg/run/install_flux.go
pkg/run/run.go
pkg/version/version.go

Closes #2426 
- Added the following command-specific flags to the `run` command: `--flux-version`, `--allow-k8s-context`, `--components`, `--components-extra`, `--timeout`.
- Added using two global flags, `--namespace` and `--kubeconfig` by the `run` command.
- Hooked up the `--context` flag, auto-generated by `genericclioptions`, when creating `kubeConfigArgs`.
- Reworked creation of kube config args and kube client.
- Added passing the kube config to the `InstallBucketServer` and down the line.
- Renamed `kubeConfigOptions` to `kubeConfigArgs` back, for consistency with their purpose and  the Flux code.
Notes:
- If a `--kubeconfig` flag is provided a `--context` flag is required too, because in this case we are not able to call `RestConfig()` initially to get the current context name in …

Add flags to gitops run

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/deployment.yaml

I added the port of to the service, I made the pod start listening to the port, but I didn't put it in the deployment itself.

Enable the metrics port on the deployment if metrics are enabled

---

pkg/server/auth/auth.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go

Some OIDC providers (such as Keycloak) check the token type to match
"Bearer" which is not true for the ID token which holds the token type
"ID". Therefore, the ID token cannot (and supposedly should not) be
used to authorize requests to resource servers.
With this change the auth server stores the access token alongside the
ID token in the browser's cookies so that it can be used by the
weave-gitops server later on, e.g. to make requests against the
UserInfo endpoint of the OIDC provider.
A caveat of this change is that the mock OIDC server used in tests
doesn't check the token type so without further changes to the
upstream library we cannot really test usage of the access token
properly.
closes #2125

Use access token for UserInfo endpoint access

---

cmd/gitops/root/cmd.go

This PR adds the environment variable from the `endpoint` into the help message.
This helps users to realize that there is actually an environment variable for specifying the `endpoint`. Like this they can define the environment variable only once instead specifying endpoint with every `gitops` command.
Just added the name of the existing environment variable into the help message of the `gitops` command.
I have teste it by compiling the code and running it on the command line. This is the output:
```
$ ./gitops --help                                                      
Command line utility for managing Kubernetes applications via GitOps.
Usage:
gitops [command] …
```

Adding env var for the endpoint into the help message

---

.github/workflows/release.yaml

`actions/checkout` checks out a temporary merge commit of the PR, not
the commit in the PR.
This means our release tags ended up on identical but different
merges, compared to what then ended up in main. For example, v0.9.0 is
set on 5283dd5, not 6d0669e (as I expected) or 8aecaae (which is the
merge that's actually reachable from main).

release: Set tag on the correct commit

---

ui/index.ts

add exports for EE and ProgressiveDelivery to navigate from delivery components back to application and source pages.

export link nav components

---

charts/gitops-server/Chart.yaml
charts/gitops-server/values.yaml
website/docs/configuration/securing-access-to-the-dashboard.mdx
website/docs/getting-started.mdx
website/docs/installation.mdx

Closes #2290 
Updates docs and helm chart with the new `gitops get bcrypt-hash` command

Add gitops get bcrypt-hash command to relevant docs

---

.github/workflows/repostats.yaml

This changes the secret from one that doesn't have enough permissions,
to one that does.
Before: https://github.com/weaveworks/weave-gitops/actions/runs/2701109066
After (manually run on this branch): https://github.com/weaveworks/weave-gitops/actions/runs/2704406195
This fixes #2019

Fix repostats workflow

---

ui/components/HelmRepositoryDetail.tsx
ui/components/Link.tsx
ui/components/SourcesTable.tsx
ui/components/__tests__/Link.test.tsx
ui/index.ts
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

This stops `oci://` links from showing up anywhere in the UI.
This does not use `isHTTP`, because we actually use `<Link/>` for `mailto:`

Unify oci link handling

---

ui/components/SourcesTable.tsx

Closes #2428 
Placement of the cluster column now matches `AutomationsTable`

Move Cluster column forward on Sources page

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/token_review_crb.yaml
core/clustersmngr/clustersmngr.go
pkg/kube/config_getter.go
pkg/kube/kubehttp.go
pkg/server/auth/auth.go
pkg/server/auth/passthrough.go

Fix a bug where the `BearerToken` is being ignored because the `BearerTokenFile` is being used to authenticate the client as the InCluster service account.
Additionally, we now validate the token when it is received by utilising the `TokenReview` API. This requires additional permissions on the service account:
```
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: system:auth-delegator
```

fix: stop auth passthrough from ignoring token in favour of SA

---

cmd/gitops-server/cmd/cmd.go
core/clustersmngr/client_test.go
core/clustersmngr/factory_test.go
core/nsaccess/nsaccess_test.go
core/server/events_test.go
core/server/fluxruntime_test.go
core/server/helm_release_test.go
core/server/kustomization_test.go
core/server/objects_test.go
core/server/sources_test.go
core/server/suite_test.go
core/server/suspend_test.go
core/server/sync_test.go
core/server/version_test.go
pkg/kube/kubehttp.go
pkg/server/server_suite_test.go
pkg/server/server_test.go
pkg/services/auth/auth_suite_test.go
pkg/testutils/testutils.go

`AddToScheme` method errors was not handled previously. Move to a SchemeBuilder and handle errors. 
Amend usages of `kube.CreateScheme()` to handle error return.

refactor: move AddToScheme to scheme builder and handle errors

---

cmd/gitops/beta/run/cmd.go
pkg/run/forward_port.go
pkg/run/install_dashboard.go
pkg/run/install_dev_bucket_server.go

Closes #2489 
It looks like the bug was caused by a big "typo": when moving the "wait for dashboard ready"code to a separate file, I copied only the wait for reconciliation code, twice. 🤦 
So, I've added code to wait for the dashboard reconciliation and pod running properly. It is working as expected now.
Questions:
1) Is it OK to use the pod and wait for its status == running to wait for dashboard ready?
I also have some old code which seems to work for our purpose, but it uses a HelmRelease:
```
// wait for dashboard to be ready
if err := wait.Poll(interval, timeout, func() (bool, error) {
dashboard := &helmv2.HelmRelease{}
if err := kubeClient.Get(context.Background(), types.NamespacedName{
Namespace: namespace,
Name:      helmReleaseName,
}, dashboard); err != nil {
return false, err …
```

Port forwarding error immediately after installing the GitOps Dashboard not on the same run when installing Flux

---

cmd/gitops/beta/run/cmd.go
pkg/run/forward_port.go
pkg/run/install_bucket_source_and_ks.go
pkg/run/install_bucket_source_and_ks_test.go
pkg/run/install_dashboard.go
pkg/run/install_dev_bucket_server.go
pkg/run/install_flux.go
pkg/run/run_suite_test.go

display error messages when dev-ks fails

---

.github/workflows/release.yaml

The GitHub Actions "release" workflow now produces a multi-platform container image of Weave GitOps for AMD64 and ARM64.
closes #2055

build multi-platform container image upon release

---

ui/components/SubRouterTabs.tsx

Closes #2412
Tab styling now more consistent with Buttons

Add SubRouterTab Styles

---

cmd/gitops/add/profiles/cmd.go
cmd/gitops/beta/run/cmd.go
cmd/gitops/get/profiles/cmd.go
cmd/gitops/logger/logger.go
cmd/gitops/logger/logger_test.go
cmd/gitops/update/profiles/profiles.go
cmd/gitops/upgrade/cmd.go
cmd/gitops/version/cmd.go

This will allow commands to be moved around without getting blocked by
the logger being inside the internal module, which is a prerequisite
for #1992.

cli: Move CLI logger out of internal

---

cmd/gitops/beta/run/cmd.go
pkg/run/errors.go
pkg/run/forward_port.go
pkg/run/install_dashboard.go
pkg/run/install_dev_bucket_server.go
pkg/run/utils.go

Closes #2489 , finally. I tested it and am unable to reproduce the error anymore.
- Removed passing pod status phase to `GetPodFromSpecMap` (added in the previous PR). Now the code is simpler.
- Rolled back error messages to previous versions (without pod phase). Replaced "service" in deployment-related error messages in `GetPodFromSpecMap` with "deployment".
- Added properly waiting for getting the dashboard pod and making sure its pod Ready condition is true.
- Added constants for getting pod errors which are re-used in code or similar errors which could be re-used (also to make checking for specific errors easier). Other `run` pkg errors can be added later.
- Since I was on this, added passing namespace to some dashboard-related functions instead of using `wego.DefaultNamespace`.
- …

2489 gitops run port forwarding error follow up

---

website/docusaurus.config.js

We didn't follow this [migration](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration) when it happened, so our search has been completely broken for a bit.
This seems to fix it.

docs: Use new algolia to re-enable search

---

.github/workflows/chart.yaml

Before this, every time you changed `charts`, you had to bump the
chart version. Every time you bumped the chart version, the chart was
released. Thus, we effectively had deploy-on-merge for the chart,
straight to the users' systems.
This changes it so that you can choose whether you want to bump the
version or not - if you don't change it, it won't be released. The
action also posts a comment warning you that your merge is about to be
released as well, as it can be surprising.
This fixes #2180

Only release helm chart when the Chart version has changed

---

website/docs/getting-started.mdx
website/docs/installation.mdx

Revised all public-facing documentation to refer to the ghcr.io OCI registry for chart storage.
OCI is more efficient in terms of resource usage by Flux (no index to
be cached etc.) and in terms of maintenance as no index has to be
created and published.
The existing HTTPS Helm repository may also have led to issues with
caching as hinted to by the discussion in
https://github.com/fluxcd/flux2/discussions/2939.
Preview: https://staging.docs.gitops.weave.works/docs/next/installation

change docs to refer to the OCI registry for chart storage

---

package.json
tsconfig.json
ui/components/AutomationDetail.tsx
ui/components/BucketDetail.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/SourceDetail.tsx
ui/hooks/objects.ts
ui/lib/__tests__/objects.test.ts
ui/lib/objects.ts

The `getObject` endpoint already contains everything we need to display any details page - at least for source kinds (there's a complication related to helmreleases and secrets, but that's a problem we can solve when we get to it). So we can just unpack that response, and fill in all the data.
This commit simply ports some of the `core/server/types` code to the frontend. It uses getters in order to allow the display code to behave as if it's still operating on a plain object similar to the GRPC one, but all the fields are lazy-loaded so we're only paying for the fields that we use.
I've left the server-side code alone, and I've left every page other than the source details pages alone - this ports a significant chunk of the types code, but it's definitely not all of it. However, my goal …

Use getObject for all sources details

---

cmd/gitops/beta/run/cmd.go
pkg/run/get_kube_client_test.go
pkg/run/install_flux_test.go
pkg/run/run_suite_test.go
pkg/run/utils_test.go

Partial PR for 2512 (Write unit tests for GitOps Run: Flux and GitOps Dashboard installation).
- Added unit tests for simpler functions. Will cover `InstallFlux` and `InstallDashboard` in the second PR.
Notes:
- Had to pass test config `k8sEnv.Rest` to `GetKubeClient` in the test instead of the actual config created with `kubeConfigArgs.ToRESTConfig()` (which is used when running the `gitops run` command) because I was getting an "error initializing kube client". So, for the actual config I am only checking that no error occurs when calling `kubeConfigArgs.ToRESTConfig()`.

Write unit tests for GitOps Run: Flux and GitOps Dashboard installation Part 1

---

cmd/gitops-server/cmd/cmd.go
go.mod
go.sum

It was pointed out to me that weaveworks/weave-gitops-enterprise#989
had done this, and the results seemed promising (as, granted, adding
gzip usually does).
That PR only does it for static resources. I added it for API
endpoints too - the middleware is smart enough to check the response
size and only compress if it's large enough to make sense.

Add gzip compression

---

cmd/gitops/beta/run/cmd.go
go.mod

This moves the waiting for components so it only happens when we install flux, rewires the installation of extra components so it works, and then proceeds to wait for the components the user specified.
This fixes #2423

Install & wait for extra components when specified

---

Tiltfile
cmd/gitops-server/cmd/cmd.go
pkg/server/auth/init.go
pkg/server/auth/init_test.go
pkg/server/auth/token_signer_verifier.go

When I removed backwards compatibility in 75fbce6d, I also removed the
thing that made dev-mode work, since we were always overriding the
username with wego-admin in tilt.
This removes the dev-user altogether - it just replaces the username,
but we can just log in with a different username instead if we want -
and reimplements dev-mode to mean "use cookie, disable verification"

Fix local development

---

website/docs/getting-started.mdx

I followed this document, but I didn't sign-in because of invalid hash.
finally i found the problem. that's why i open a pr. 😸 
- X
- just added an '-n' option in this document.
- because this guide gives us a way to make an invalid hash.
- X
typed this command and finally i logged in!
- X
- Yes it just changed this documentation

add an `-n` option not to print a newline when generating hash

---

cmd/gitops/beta/run/cmd.go
pkg/run/install_dashboard.go

It looks like it was broken again with the following error  during the first run (if installing the dashboard right after installing Flux) or during the second run (if installing Flux during the first run and the dashboard during the second run):
```
macbook-pro:podinfo olga$ /Volumes/Macintosh_HD_Data/_job_ww/_src/weave-gitops-3/bin/gitops beta run ./deploy/overlays/dev --timeout=3m --port-forward namespace=dev,resource=svc/backend,port=9898:9898
► Checking for a cluster in the kube config ...
► Checking if Flux is already installed ...
► Getting Flux version ...
⚠️ Flux is not found: error getting Flux labels
► Installing Flux ...
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io created
CustomResourceDefinition/buckets.source.toolkit.fluxcd.io created …
```

Fix pod not found error.

---

cmd/gitops/get/bcrypt/cmd.go
website/docs/configuration/securing-access-to-the-dashboard.mdx
website/docs/installation.mdx
website/versioned_docs/version-0.9.1/configuration/securing-access-to-the-dashboard.mdx
website/versioned_docs/version-0.9.1/getting-started.mdx
website/versioned_docs/version-0.9.1/installation.mdx
website/versioned_docs/version-0.9.1/references/cli-reference/gitops_get_bcrypt-hash.md

This does the same fix as #2543, but to another few places, including
the stable docs and the command help text.

Fix bcrypt-hash example in more places

---

api/v1alpha1/application_types.go
charts/gitops-server/Chart.yaml
charts/gitops-server/templates/admin-user-creds.yaml
charts/gitops-server/templates/admin-user-roles.yaml
charts/gitops-server/templates/admin-user.yaml
cmd/gitops-server/cmd/cmd.go
cmd/gitops/beta/run/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/upgrade/cmd.go
pkg/flux/flux_test.go
pkg/run/get_kube_client_test.go
pkg/run/install_dashboard.go
pkg/server/auth/auth_test.go
pkg/server/auth/init.go
pkg/server/auth/init_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go
pkg/upgrade/upgrade_test.go
ui/lib/types.ts

Before this, we expected there to be a namespace `flux-system`. While
we supported running in any namespace, and supported finding flux
itself in any namespace, you couldn't log in unless there was a
pre-existing flux-system namespace.
This duplicates the helm chart so it installs both permissions and
secrets in both `flux-system` and wherever you install gitops.
The code is then adapted to look for secrets in the current namespace,
and all constants containing `flux-system` has finally been vanquished.
Because the helm chart still uses `flux-system` with this change in
place, you still actually need a `flux-system` namespace, so this
doesn't actually fix the problem. However, as soon as we've made a
release with this in place, we can remove the hard-coded `flux-system`
copies of all of …

(almost) Support running gitops without flux-system namespace

---

ui/hooks/automations.ts
ui/hooks/events.ts
ui/hooks/flux.ts
ui/hooks/objects.ts
ui/hooks/sources.ts
ui/lib/types.ts

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/1243
Adds a way for consumers of the Core hooks to control how and when they get run

Add options parameter for hooks

---

cmd/gitops/beta/run/cmd.go
pkg/run/apply_manifests.go
pkg/run/apply_manifests_test.go
pkg/run/forward_port_test.go
pkg/run/get_kube_client.go
pkg/run/get_kube_client_test.go
pkg/run/install_bucket_source_and_ks_test.go
pkg/run/install_dashboard.go
pkg/run/install_dashboard_test.go
pkg/run/install_flux.go
pkg/run/install_flux_test.go
pkg/run/run_suite_test.go
pkg/run/utils.go
pkg/run/utils_test.go

Closes #2512 
- Moved the `NewManager` function to `apply_manifests` and added passing the mocked `ssa.ResourceManager` to the `Apply` (and related `applySet` and `waitForSet`), `InstallDashboard`, and `InstallFlux` functions to make them more testable.
- Moved generating secret to a separate function (to simplify testing of the `InstallDashboard` function).
- Added very basic tests for the `Apply`, `InstallFlux`, and `InstallDashboard` functions (more like test prototypes for now).
- Added tests for the `MakeValues`, `MakeHelmRepository`, `MakeHelmRelease`, and `GenerateDashboardManifests` functions. I am very open to suggestions on how to improve these tests.
- Split `IsDashboardInstalled` functions to `GetDashboardHelmChart` and `IsDashboardInstalled` functions to be able to test …

Write unit tests for GitOps Run: Flux and GitOps Dashboard installation Part 2
