.github/coverage.sh, .github/workflows/test.yml, go.mod, go.sum, main.go, main_test.go
Apparently with the right coveralls permission you can just add the check in there. So I have removed my custom check.
=> add test so i can see if coverage works

.github/workflows/scan.yaml
A new GH action named `Scan` is added.
These jobs will help in scanning the source-code and docker images for vulnerabilities. 
FOSSA.- License compliance.
Snyk.- Vulnerabilities analysis on source-code and docker image.
Trivy.- Vulnerabilities analysis on docker image.
CodeQL.- Discovery of vulnerabilities.
These tools were chosen based on the fact that they are used in `fluxcd/flux2` and `weaveworks/wks`.
=> Added snyk sourcecode analysis

.github/workflows/deploy.yml, .github/workflows/scan.yaml, .github/workflows/test.yml, Dockerfile
I am using my own aws keys because i couldnt get the ones in 1password to work
=> basic version of docker and s3

.github/workflows/deploy.yml
I added the commit option for testing but i am removing it for now.
=> Forgot to remove push on commit 

.gitignore, Makefile, tools/dependencies.toml, tools/download-deps.sh, tools/functions.sh, tools/image-tag
I mostly brought the scripts from the wks repo.
=> Make target to download binaries dependencies

.github/workflows/deploy.yml, Makefile
fixes https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/47
=> fix push s3

.github/workflows/test.yml
I removed the delete fake flux because that gets taken care of when we get a new setup for each step
=> fix coverage test

test/acceptance/test/acceptance_suite_test.go, test/acceptance/test/smoke_tests.go
This test case will verify the help text that displays when the user hits "wego --help" command
=> Add 'wego --help' test case

pkg/fluxops/fluxops_test.go, pkg/status/status_test.go, pkg/utils/commands.go
=> Add test for status.GetClusterName()

.github/workflows/deploy.yml, .github/workflows/test.yml, test/acceptance/test/acceptance_helpers.go, test/acceptance/test/core_operations_test.go, test/acceptance/test/smoke_helpers.go, test/acceptance/test/testsuite_common_test.go, test/acceptance/test/utils.go
This PR will 
* Refactor the test suite so that a separation can be maintained between smoke and full suite going forward
* Report the results in the xUnit style XML format
* Integrate the Testspace.com dashboard for test and other metrics
=> setup-test-dashboard

pkg/cmdimpl/add.go
=> Using path param when adding a new repo

pkg/cmdimpl/add.go, test/acceptance/README.md, test/acceptance/test/core_operations_test.go
Bug fixes:
- Fixed kustomization file using path as name
- When running locally git init does not generate default main branch I added git checkout -b main without checking error.
- Fixed name kustomization name file.
Fix: #147
Fix: #148 
Fix: #149 
Fix: #150 
Fix: #151
=> Fixed acceptance tests

cmd/wego/install/cmd.go, cmd/wego/install/manifests/app-crd.yaml, pkg/cmdimpl/add.go
=> Moving app crd to install command

.github/workflows/release.yaml
Apparently that line is needed for changelog to work
=> Fix releasev2

.github/workflows/release.yaml
🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏
=> fix release try 3

test/acceptance/test/smoke_tests.go, test/acceptance/test/testsuite_common_test.go, test/acceptance/test/utils.go
Print the cluster pods on test failure.
=> Show cluster pods on failure

.github/workflows/deploy.yml, .github/workflows/test.yml, cmd/wego/install/cmd.go, pkg/cmdimpl/add_test.go, pkg/cmdimpl/common_test.go, pkg/cmdimpl/install.go, pkg/cmdimpl/install_test.go, pkg/cmdimpl/manifests/app-crd.yaml, test/acceptance/test/core_operations_test.go
- Fix acceptance tests
- enable acceptance test on pull requests
=> Installing wego instead of just flux

.github/workflows/deploy.yml, .github/workflows/test.yml
It's good practice to not use real email domains in tests/docs.
=> Switch to standard "example.com" example emails

cmd/wego/add/cmd.go, pkg/cmdimpl/add.go, pkg/cmdimpl/add_test.go, test/acceptance/test/core_operations_test.go
=> Added deployment flag to the add command

.github/workflows/test.yml, Makefile
Ensure that unit-tests will not trip on a syntax error for embedding of the UI
=> Add Makefile incantation to ensure the static assets directory always exists

.github/workflows/deploy.yml, .github/workflows/nightly.yaml
* After the addition of UI embedded component, UI needs building first before liniting and unit tests can be run
=> build ui before linting and unittests

Makefile
Fixes a circular dependency in the Makefile. Related to #180
=> Fix circular dep in Makefile

pkg/cmdimpl/add.go, pkg/cmdimpl/add_test.go, pkg/utils/commands.go
I changed the repoCreation call when DryRun is false.
I updated the createRepo tests so they could work when the DryRun flag is false.
=> Create repo only when DryRun is false

pkg/cmdimpl/manifests/app-crd.yaml
Added descriptions in the app crd for the URL and path fields.
**Why?**
Provides additional data for `kubectl explain`
1. `kubectl apply -f app-crd.yaml`
2. `kubectl explain apps.spec`
no
no
=> Add description for url and path fields.

test/acceptance/test/add_tests.go
* Some refactoring around add tests.
* Added/adapted the tests to cover more wego add scenarios for 
- deployment-type=kustomize
- where repo is linked first and the workload is added later
**Why?**
* To increase E2E tests coverage.
*These are the tests.
=> more add tests

.github/workflows/nightly.yaml, .github/workflows/test.yml, test/acceptance/test/add_tests.go
* Updated the missing test with new app command
* Make the controllers check flexible.
**Why?**
PR #250 missed this test case to update.
=> update the acceptance test as add command is changed

cmd/wego/install/cmd.go, cmd/wego/install/cmd_test.go, pkg/cmdimpl/install.go, pkg/cmdimpl/install_test.go, pkg/fluxops/fluxops.go, pkg/fluxops/fluxops_test.go, test/acceptance/test/install_tests.go, test/acceptance/test/utils.go
Using install as-is from flux.
the `dry-run` option is coming in another pr.
**Why?**
=> Using flux install without export

cmd/wego/add/cmd.go
We expand `~/` at the front of a key path to the user's home directory
**Why?**
User feedback
Tested locally
=> expand ~ using UserHomeDir

.github/workflows/nightly.yaml, .github/workflows/test.yml, test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
Try repeatable way of cleaning up the resources on wego flux uninstall.
**Why?**
To make it possible to run tests against a standing cluster without recreating.
=> Cluster reset

pkg/cmdimpl/add.go
We now generate the correct source type for upstream helm and we disallow using it in the user repo mode.
**Why?**
Upstream helm did not work due to an oversight when merging in change.
Tested locally
=> fix upstream helm support

.goreleaser.yml, Makefile
Flux binary was being overwritten
**Why?**
To fix other architectures
Building a release
=> correctly untar flux archive and stop overwriting flux binary in make

.goreleaser.yml
pre hook changed to correctly unpack flux tar
**Why?**
To fix the release process
=> fix pre-hook to correctly install flux

.goreleaser.yml
Tar command correctly extracts binary
=> Update tar command in .goreleaser.yml

.goreleaser.yml
=> Final tar fix

README.md
Signed-off-by: mewzherder <tamao@weave.works>
**Why?**
=> Cleaned up slack section and added link.

cmd/wego/add/cmd.go, pkg/cmdimpl/add.go
Removed owner flag
It is not needed anymore
=> Removed unused owner flag

test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
Automated `wego app add . --dry-run` test case
This is a test case
N/A
N/A
=> add wego -dry-run test case

README.md
=> Fix README merge

test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
**Why?**
To add test coverage for additional WeGO features
=> Automate test case for 'wego add --url' flag

test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
Reverts weaveworks/weave-gitops#301
Changes in this PR are causing acceptance suite failure
=> Revert "Automate test case for 'wego add --url' flag"

Makefile
Added a new target to the Makefile to generate a debuggable build.
**Why?**
To use for debugging in VS Code
Create a launch.json file similar to 
``` 
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"name": "Launch exe",
"type": "go",
"request": "launch",
"mode": "exec",
"program": "${workspaceFolder}/bin/wego",
"env": {"GITHUB_TOKEN":"your token"},
"args": ["app", "add", "--url", "a repo, "--name", "mynginx"]
}
]
}
```
Using this launch configuration you can step through the code in VS code.
No
No
=> Add target to build a debuggable exe

pkg/gitproviders/cache/github.yaml, pkg/gitproviders/cache/gitlab.yaml, pkg/gitproviders/common_test.go
=> Fixed flaky tests

Makefile, cmd/wego/version/cmd.go, pkg/utils/commands.go, test/acceptance/test/version_tests.go
Return flux version from the binary
running the command
=> flux version from binary and return wego version

.github/workflows/test.yml
Avoid using `-u` otherwise it picks up the latest version breaking the execution because that version is different from what is pinned in `go.mod`
**Why?**
=> Avoid getting ginkgo and gomega latest

.github/workflows/deploy.yml, .github/workflows/nightly.yaml, .github/workflows/test.yml
Removing `go get -u` call in all places
**Why?**
=> Fix ginkgo download round 2

pkg/git/gogit.go, pkg/git/gogit_test.go
Additional tests for the git client implementation.
**Why?**
Improve coverage.
This is adding additional tests...
=> Improve tests for git

pkg/services/app/add.go, pkg/services/app/add_test.go
We are creating git secrets per repository.
**Why?**
We were overwriting git secrets causing authentication problems when flux tries to clone the repository.
This was tested manually.
=> Generate secrets with unique name

test/acceptance/README.md
Updated the How to guide for acceptance tests.
**Why?**
So that team can setup it locally for an easy and fast run.
=> update the readme

.github/workflows/test.yml, test/acceptance/test/add_tests.go, test/acceptance/test/data/README.md, test/acceptance/test/install_tests.go, test/acceptance/test/utils.go
* Removal of the namespace created by test
* Add a new test for a scenario where the user has multiple app repos and single config repo.
**Why?**
Improved test coverage.
=> add a new test for single wego repo for multi apps

cmd/wego/add/cmd.go
- Fixes #365 
- Find the absolute path for the specified directory
**Why?**
- go to an app directory and `wego app add . --dry-run`
=> Fixing wego add --dry-run

package-lock.json, package.json, ui/App.tsx, ui/components/ErrorBoundary.tsx, ui/components/Layout.tsx, ui/components/LoadingPage.tsx, ui/components/Page.tsx, ui/contexts/AppContext.tsx, ui/hooks/__tests__/applications.test.tsx, ui/hooks/applications.ts, ui/hooks/common.ts, ui/lib/test-utils.tsx, ui/lib/utils.ts, ui/pages/ApplicationDetail.tsx, ui/pages/Applications.tsx, ui/pages/Error.tsx
Re-arranges the UI routing to wrap the page content with the navigation elements, and adds some async error message handling:
Note that the `<ErrorBoundary />` component handles "synchronous" errors in component render blocks
=> Re-arrange routing and add error handling

README.md
The release link now points to the current release
**Why?**
We want users to use the new release
=> Updated link in README.md to point to the latest release

.github/workflows/deploy.yml, .github/workflows/test.yml, test/acceptance/test/add_tests.go, test/acceptance/test/testsuite_common_test.go, test/acceptance/test/utils.go
* Pulling repo before checking the presence/absence of .wego folder
* @jpellizzari suggested moving the test setup-related initializations to a function to avoid repition.
* Update the kind and k8s version.
* 
**Why?**
Housekeeping as well as the current kind version seems to be incompatible with CI infra.
=> Update add test

tools/dependencies.toml
Version of Flux used for operations
fixes #404 
**Why?**
There have been a few critical fixes in flux we want to pick up.  Additionally, we want to track flux fairly closely to limit any potential drift.
ran the unit-tests locally and manually performed the steps in the getting started guide
no
no
=> Updated to the latest version of Flux

pkg/services/app/add.go, test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
A new test for upstream helm repositories with --app-config-url=NONE
**Why?**
To have a test for this use case
This is the test
No
No
=> Add test for upstream helm chart with app-config-url=NONE

cmd/wego/app/add/cmd.go, pkg/gitproviders/common.go, pkg/gitproviders/common_test.go, pkg/gitproviders/gitprovidersfakes/fake_git_provider_handler.go, pkg/kube/kube.go, pkg/kube/kube_test.go, pkg/kube/kubefakes/fake_kube.go, pkg/kube/kubehttp.go, pkg/services/app/add.go, pkg/services/app/add_test.go, pkg/utils/common.go, pkg/utils/common_test.go, test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
Add a new flag named auto-merge. If set to true add will not create a pr. Default is false
Creates a PR with a branch name that is a hash of url + path + branch to be merged to the branch specified in --branch. 
If a branch with that name already exists add will fail.
Adds a label with the same hash to the app in the cluster. 
If that label exists the add will fail.
removed extra manifests being applied
Added namespace to app manifest so app was created under the correct namespace
Added app goat to external repo apply
=> 187 add branch

test/acceptance/test/add_tests.go
Test added for adding a helm chart from a git repo with `--app-config-url=NONE`
**Why?**
This use case was not covered
This is the test
=> add test for helm chart from git repo with app-config-url=NONE

test/acceptance/test/add_tests.go
Added a test for `wego app add --url=<URL> --app-config-url=NONE`
**Why?**
We had no test for this use case
This is the test
No
No
=> Test passing URL instead of directory with app-config-url=NONE

pkg/kube/kube.go, test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
Added acceptance tests for creating a pr. Going to add more in another PR
**Why?**
=> add pr tests

test/acceptance/test/add_tests.go
A spurious error message was removed and one of the acceptance tests needed to be updated.
**Why?**
To fix the test runs.
This is the test
No
No
=> remove check for message that is no longer emitted

pkg/services/app/add.go, test/acceptance/test/add_tests.go, test/acceptance/test/utils.go
fixed the path for external pr creation.
**Why?**
=> fix external pr

.github/workflows/test.yml
Add option to manually trigger tests from github ui
**Why?**
=> trigger test in github actions ui

test/acceptance/test/help_tests.go, test/acceptance/test/version_tests.go
Refactored tests to be more flexible
**Why?**
I refactored the tests that are most likely to break due to constant changes:
- `wego -h`
- `wego app -h`
- `wego app add -h`
- `wego app list -h`
=> Refactor help-text tests

.github/workflows/test.yml, .gitignore, Makefile, package-lock.json
Adds some Makefile magic to ensure the `dependencies` target only runs once.
=> Add check to download deps only once

doc/adr/0003-cli-using-noun-verb-format.md
Added an ADR for the decision to use noun-verbs in our CLIs
**Why?**
To have documentation to refer back to
N/A
N/A
N/A
=> Document noun verb decision

README.md
New release reference in README.md
Yes. They are in a separate PR
=> Update README.md to reference the 0.2.1 version

doc/adr/0005-when-to-use-wego-weave-gitops-and-weave-gitops.md, doc/adr/0006-when-to-use-wego-weave-gitops-and-weave-gitops.md
New ADR to document when we use wego vs weave-gitops-Weave GitOps
**Why?**
Provide clarity
N/A
=> Doc when to use wego, weave-gitops, Weave GitOps

doc/release-process.md
Closes #525 
Added documentation describing how to create a new weave-gitops release
**Why?**
So others will know how to create releases
This was the process I followed for previous releases
No
No
=> Document release instructions

Makefile, tools/dependencies.toml, tools/download-deps.sh, tools/functions.sh
closes #115 Added a check in make to validate the flux binary.
=> validate flux binary

cmd/wego/app/cmd.go, cmd/wego/app/remove/cmd.go, pkg/git/gitfakes/fake_git.go, pkg/git/gogit.go, pkg/git/gogit_test.go, pkg/kube/kube.go, pkg/kube/kubefakes/fake_kube.go, pkg/kube/kubehttp.go, pkg/osys/osys.go, pkg/osys/osysfakes/fake_osys.go, pkg/services/app/add.go, pkg/services/app/add_test.go, pkg/services/app/app.go, pkg/services/app/remove.go, pkg/services/app/remove_test.go, pkg/utils/common.go, test/acceptance/test/add_tests.go
- Added initial `wego app remove` command (with auto-merge only)
- Refactored to share code across commands
**Why?**
It's in the plan
New unit tests
It will be when complete
Not yet
=> 250 more remove

pkg/gitproviders/cache/deploy_key_org.yaml, pkg/gitproviders/cache/deploy_key_user.yaml, pkg/gitproviders/provider.go, pkg/kube/kube.go, pkg/services/app/add.go, pkg/services/app/add_test.go
> Describe what has changed in this PR
Rename kubernetes obects from weave-gitops to wego. Also renamed the deploy key (it seemed like it also should be wego)
> Tell your future self why have you made these changes
To follow naming guide
=> update weave-gitops objects to wego

tools/functions.sh
fixed a sneaky error when running make all.  The if check on a checksum file was not valid.
removed checksum to see if validate doesnt run and put it back so it would run
=> fix flux validate check

.github/workflows/repostats.yaml
use the same github token secret that test.yml uses.
=> fix repostats

.github/workflows/test.yml, Makefile
> Describe what has changed in this PR 
Closes at #527 Added gofmt check to github action test section
> Tell your future self why have you made these changes
To make sure all code is formatted
> How have you verified this change? Tested locally? Added unit test/integration/acceptance test(s)? 
using github actions
=> add gofmt to test github action

.github/workflows/repostats.yaml
Replace github token with one that actually works. The old token didnt have push permissions. Created a new secret that has push and pull access 
**Why?**
Tested by running the workflow on this branch. It worked.
=> Replace github token with one that works

Makefile
Makefile 
**Why?**
make install was failing because it was trying to build a file that no longer existed in the repo
manually 
N/A
N/A
=> Change make cmd/ui to cmd/wego-server

.github/workflows/deploy.yml, .github/workflows/nightly.yaml
Copied the test.yaml fix into deploy and nightly yamls
**Why?**
to fix the pipeline
https://github.com/weaveworks/weave-gitops/actions/runs/1136723385
=> fix deploy

doc/adr/0007-embedding-weave-gitops-core.md, doc/adr/adr-template.md
Adds an ADR describing how we will embed the Weave GitOps UI and HTTP services in other applications
=> Add UI embedding ADR

cmd/wego/app/cmd.go, pkg/utils/common.go
closes #623 Remove extra spaces in commit cli output. Limit commit message to 50 char and use short commit hash.
**Why?**
Clean up the commit output
Looked at the output
=> clean up commit code

tools/get-flux-update-pr.sh
Using correct path to call stoml binary
=> Fixed stoml path

package.json
=> Update package.json for 0.2.3 release

.github/workflows/release.yaml, package-lock.json
The goreleaser job was failing because of missing assets
=> Run `make all` on release

cmd/wego/app/cmd.go, pkg/services/app/commit.go
Closes #640 Gives a clearer message when getting commits for a helm chart
**Why?**
manually
=> add helm check for git commits

package-lock.json, package.json
Updates the package.json to bring it in line with the latest release
=> Update package.json version

cmd/wego/app/cmd.go, pkg/server/server.go, pkg/server/server_test.go, pkg/services/app/app.go, pkg/services/app/commit.go
Closes: #621
Adds auth flow used in add to the commits flow
**Why?**
Manually tested it. acceptance tests to come in a different pr
=> add auth flow to get commits command

test/acceptance/test/utils.go
=> Revert create repo fixes

Makefile
Total nice to have, close if not interested 😄 . We have similar things in pitch-black Makefiles, gives a chill dev experience:
I have made up missing comments (probably nonsense) and put things in what seemed to me like logical groupings 🤷‍♀️  but obvs can arrange how you like.
=> Add `help` target to Makefile for coolness

package-lock.json, package.json
=> Updated version on package.json

.github/workflows/release.yaml
=> Updating tag name reference

Makefile
=> Added git diff to make all

package-lock.json
=> Updates on package-lock.json after running `npm ci`

README.md
=> Updated to v0.2.5

.github/workflows/release.yaml, Makefile
Closes: 
Added `git diff` to release workflow
**Why?**
To help on debugging. Initially GoReleaser was failing because we had a bad dirty state due to NPM modules being updated during the build.
=> Show git diff after running make all on release workflow instead

test/acceptance/test/ui_tests.go
Add skip tag for wego ui test
**Why?**
It broke the CI pipeline because other workflows couldn't support ui tests.
=> Add skip tag for ui tests

cmd/wego/app/remove/cmd.go
Merging this PR: https://github.com/weaveworks/weave-gitops/pull/726
Merging here because we can't currently run CI on public forks. Thanks @HassanAlsamahi
=> Merge #726

pkg/services/gitops/uninstall.go, pkg/services/gitops/uninstall_test.go
Closes: #729 
- Delete all weave gitops manifests
**Why?**
- to clean up the whole installation
- manual and automated test
=> Uninstalling Weave Gitops manifests

cmd/gitops/app/add/cmd.go, pkg/apputils/utils.go, pkg/gitproviders/dryrun.go, pkg/gitproviders/dryrun_test.go, pkg/services/app/add.go, pkg/services/app/remove.go, pkg/services/auth/auth.go
Closes: #601 
- Avoid auth flow and deployment keys upload when dryrun
- Renaming `err` vars to Go convention
**Why?**
- minimize user friction
=> Implementing DryRun gitprovider

cmd/gitops/app/cmd.go, pkg/gitproviders/provider.go, pkg/server/server.go, pkg/services/app/commit.go, pkg/services/app/commit_test.go
Add tests for get commits
**Why?**
Manually and added commit tests
=> Get Commits returns empty commit list instead of an error

cmd/gitops/app/add/cmd.go, cmd/gitops/app/remove/cmd.go, pkg/services/app/add.go, pkg/services/app/remove.go, test/acceptance/test/help_tests.go
Closes: #721 
Remove private key from cmd. SSH key is no longer used.
**Why?**
SSH key is no longer used
Updated tests
https://github.com/weaveworks/weave-gitops-docs/pull/91
=> Remove private key from the cli arguments

.github/workflows/test.yml
I added a setting in the test.yaml file for concurrent test runs. It seems to be invalid and is causing test run problems. I'm removing that setting in this PR.
**Why?**
To stop github action from failing.
=> Remove concurrent test run setting

cmd/gitops/delete/clusters/cmd.go, cmd/gitops/upgrade/cmd.go
Closes: weaveworks/weave-gitops-enterprise#238
Remove `pr-` prefix from flags
**Why?**
To ensure consistency with other flags used
Tested locally
N/A
Should be updated automatically
=> Remove pr- prefix from flags

pkg/adapters/http.go
Closes: weaveworks/weave-gitops-enterprise#254
Added json keys to CreatePullRequestRequest struct
**Why?**
To fix delete cluster request body not being passed
Teste locally
=> Fix delete cluster request body always being empty

.github/workflows/deploy.yml
Closes: #589 
Updated the deploy job to set the dependencies needed before running the unit tests, mainly kubebuilder.
**Why?**
Publishing the test results were failing.
By running the deploy job on branch
=> setup kubebuilder before running unit tests.

test/acceptance/test/add_tests.go
Closes: #808 
Added an acceptance test for testing adding a project thats in a subgroup. Turns out this was not much of an issue. I had an issue originally with env.
**Why?**
=> Adds acceptance test for a gitlab subgroup

cmd/gitops/ui/run/cmd.go, manifests/wego-app/deployment.yaml
Closes: #859 
Added a flag for ui logging. Also added logging on by default in deployment.yaml
**Why?**
manually
=> Add UI logging flag

cmd/gitops/beta/cmd/install.go
Restores the setup of the beta install command that was inadvertently removed in #768
**Why?**
To fix beta install
Installation by hand
No
No
=> Restore setup of beta install command

.github/workflows/release.yaml, .goreleaser.yml
Works on: #662 
Added the goreleaser settings for releasing to homebrew. I am unable to do the nightly test and manual testing until we have done a release.
**Why?**
=> Add homebrew to release

cmd/gitops/uninstall/cmd.go, test/acceptance/test/install_tests.go, test/acceptance/test/testsuite_common_test.go
Closes: #945 
- Ask for confirmation before running the command `gitops uninstall`
- Added optional `force` flag to skip the confirmation
**Why?**
- To explicitly inform the user that if continuing the execution, it will remove all applications and related cluster resources.
- Manually and by modifying acceptance tests to include changes
Yes
Example:
=> Ask for confirmation when running `gitops uninstall`.

.github/workflows/release.yaml, .goreleaser.yml
I was able to get a working version of this code tested. The issue I was having was that the releases were binaries and not tar.gz. This was making it so that brew could not find the binary named gitops.
**Why?**
Put this code on a test repo and got the brew install working.
=> Add missed changes to goreleaser for brew

package-lock.json, package.json
=> Update package.json for release

Dockerfile
Closes: 
Update the Docker file to include a known_hosts file and kubectl. 
**Why?**
These changes are needed for bootstrapping.
Followed the demo instructions for setting up bootstrapping.
N/A
N/A
=> Add known_hosts and kubectl for bootstrap

test/acceptance/test/ui_tests.go
Add skip tag for UI tests
**Why?**
UI tests are failing on CI. Since we have a collective agreement on pausing UI test additions anyway, I'll leave the skip tag on for now.
=> Skip GitOps Core UI Tests

README.md
Closes: #662 
Updated the docs to add in the install instructions for brew. Also changed the curl instruction because the release has been changed to use a .tar.
**Why?**
https://github.com/weaveworks/weave-gitops-docs/pull/167
=> Update Readme to add brew install instructions

package-lock.json, package.json
Closes: 
- Bumping version fo the release
**Why?**
=> Bump node package version

.github/workflows/release.yaml
=> Debug brew

.github/workflows/release.yaml, .goreleaser.yml
=> Remove token for pushing to homebrew tap

.github/workflows/release.yaml, .goreleaser.yml
=> Update brew commit author

ui/components/DirectedGraph.tsx
Closes: #1194 
Switched DagreD3 graph direction
=> Horizontal Distribution of Graph Nodes

.github/workflows/test.yml
Pending a test that isn't applicable currently
**Why?**
Changes to the code made in https://github.com/weaveworks/weave-gitops/pull/1148 cause this test to fail. However the test cannot be made to go green until after its merged. We need to refactor how this tests works before re-enabling. Context: https://weaveworks.slack.com/archives/C01M1BJQ7AT/p1638454899001600
=> comment out library-integration-test

CONTRIBUTING.md, Makefile
First pass after the learnings made through working on https://github.com/weaveworks/weave-gitops/pull/1148. Copied the intro from https://github.com/weaveworks/eksctl :smile:
=> contributing guide

ui/components/CommitsTable.tsx, ui/components/__tests__/CommitsTable.test.tsx, ui/lib/storage.ts, ui/pages/ApplicationDetail.tsx, ui/pages/ApplicationRemove.tsx
Closes: #1211 
GitLab auth flow was not implemented past the Application Add form - I added the context wrapper in ApplicationDetail and ApplicationRemove as well as the button in the AuthAlert component itself.
=> Add GitLab auth flow to application detail and remove

README.md, package-lock.json, package.json
Updated README and package.json to v0.6.0
=> Update docs for v0.6.0

ui/pages/ApplicationDetail.tsx
Fixes a breaking bug that prevented the user from opening the GitHub auth modal in the CommitsTable component.
=> Fixed bug in AuthAlert that prevented GithubDeviceAuthModal from opening

cmd/gitops/install/cmd.go
=> Moving generation up so dry run prints out the wego config manifest

pkg/kube/kubehttp.go
Forces kube manifest apply to avoid conflict with Flux due service side apply 
for reference: https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
**Why?**
=> Forcing kube apply

test/acceptance/test/testsuite_common_test.go
Closes:  
- #1164 
- Removed duplicate ginkgo failure registration
**Why?**
- When tests fail it doesn't show the exact line where the error occurred.
- CI
=> Removed duplicate fail register

.github/actions/run-acceptance-test/action.yml, .github/workflows/test.yml, test/acceptance/test/utils.go
Closes: 
Removed duplicated functionality to pass in providers names
Removed extra dollar sign
**Why?**
Easier to maintain
CI
=> Attempt to fix CI by removing include in smoke-tests-long job

test/acceptance/test/install_tests.go
Fixed some lint issues on the CI
**Why?**
It broke Deploy & PR jobs
=> Fix lint issues on CI

.github/workflows/release.yaml, .goreleaser.yml
Possibly fixes: #1123 
I am using a github user that has previously made changes to the homebrew-tap repo. Even though we ruled out the token I want to try this anyway.
**Why?**
I cant without doing a release.
=> Add brew back into release

ui/pages/ApplicationDetail.tsx
Closes: #1236 
The result of an application sync is now tied to refreshing the App details, remaking graph, commits table, etc.
=> Refresh AppDetail on Sync

cmd/gitops/add/app/cmd.go
Closes: #1205 
Changed help text to match what was suggested in the issue.
**Why?**
=> Reformat add app help text

package-lock.json, package.json
=> Updated version on package.json and package-lock.json files

README.md
=> Updated weave-gitops version on curl command in README.md

cmd/gitops/add/app/cmd.go, pkg/models/manifest.go, pkg/models/manifest_test.go, pkg/services/app/add.go, pkg/services/app/add_test.go
Closes: #1057 
Replaced the check for name length with a call to IsDNS1123Label().  Updated the help text for the --name parameter
**Why?**
Ensure the application name can be used as a label value.
Manually to review the help text.  Added new unit tests.
Yes
Yes.  Separate PR for updating the docs.
=> Validate app naming using IsDNS1123Label from k8s

.github/workflows/nightly.yaml
Changed nightly job
**Why?**
Syntax errors
=> Fix nightly syntax

tools/download-deps.sh
Closes https://github.com/weaveworks/weave-gitops/issues/1383
=> Fix the downloading of tilt on OSX

manifests/wego-app/role.yaml.tpl, ui/App.tsx, ui/components/AddGitRepoForm.tsx, ui/components/AutomationSelector.tsx, ui/components/AutomationsTable.tsx, ui/components/Layout.tsx, ui/components/Page.tsx, ui/components/SourcesTable.tsx, ui/hooks/kustomizations.ts, ui/hooks/sources.ts, ui/lib/types.ts, ui/lib/utils.ts, ui/pages/v2/AddAutomation.tsx, ui/pages/v2/AddGitRepo.tsx, ui/pages/v2/AddKustomization.tsx, ui/pages/v2/AddSource.tsx, ui/pages/v2/Application/Application.tsx, ui/pages/v2/KustomizationList.tsx
Adds some component and navigation wiring
=> Add new components and navigation wiring

core/server/sources.go, core/server/sources_test.go, ui/App.tsx, ui/components/AddGitRepoForm.tsx, ui/components/AddSourceButton.tsx, ui/components/Layout.tsx, ui/components/SourcesTable.tsx, ui/hooks/navigation.ts, ui/hooks/sources.ts, ui/lib/types.ts, ui/lib/utils.ts, ui/pages/v2/AddGitRepo.tsx, ui/pages/v2/Application/Application.tsx, ui/pages/v2/SourcesList.tsx
Adds a list of sources, source creation and some navigation:
=> Add git repo creation

go.mod, go.sum, pkg/kube/client_getter.go, pkg/kube/kubehttp.go, pkg/server/auth/auth.go, pkg/server/auth/server.go
Added `groups` scope so that OIDC returns this information if available during login.
**Why?**
To allow platform admins to set RBAC permissions using groups.
Tested manually
Not needed
Not needed
=> Add groups scope

go.mod, go.sum, pkg/services/profiles/add.go
```
Testing /github/workspace...
✗ Medium severity vulnerability found in github.com/go-yaml/yaml
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGOYAMLYAML-564236
Introduced through: github.com/go-yaml/yaml@2.1.0
From: github.com/go-yaml/yaml@2.1.0
Fixed in: 2.2.8
```
=> use gopkg.in/yaml.v2 2.4.0 to resolve snyk warning

Makefile, Tiltfile, pkg/models/manifest.go, test/acceptance/test/scripts/kind-cluster.sh, tools/deploy-local-registry.sh, tools/kind-with-registry.sh, tools/wego-app-dev.yaml
Fix the timeout on OSX
Closes https://github.com/weaveworks/weave-gitops/issues/1389
```
STEP 5/5 — Deploying
Applying YAML to cluster
Objects applied to cluster:
→ wego-app:deployment
Step 1 - 11.47s (Building Dockerfile: [localhost:5001/weaveworks/wego-app-tilt_docker_build_with_restart_base])
Step 2 - 0.00s (Pushing localhost:5001/weaveworks/wego-app-tilt_docker_build_with_restart_base:tilt-3f94c43cd0d832bb)
Step 3 - 2.63s (Building Dockerfile: [localhost:5001/weaveworks/wego-app])
Step 4 - 13.37s (Pushing localhost:5001/weaveworks/wego-app:tilt-629a9f829efb7ba1)
Step 5 - 0.04s (Deploying)
DONE IN: 27.53s 
```
Acceptance test also works:
```
=> => naming to localhost:5001/wego-app:latest                                                                                  0.0s
Use 'docker …
```
=> Fix the tilt build locally

test/acceptance/test/add_tests.go, test/acceptance/test/scripts/kind-cluster.sh, test/acceptance/test/scripts/kind-multi-cluster.sh, test/acceptance/test/utils.go
`kubectl wait` will wait for the resources to contain the ready == true condition
=> improve waiting for resources to exist

.github/actions/run-acceptance-test/action.yml, .github/workflows/deploy.yml
https://github.com/weaveworks/weave-gitops/pull/1392 appears to have broken this workflow, I've updated it to use the makefile to run the tests which should resolve the issue
=> fix deploy workflow

website/docs/enterprise/oidc.mdx
Added a page in the docs that explains how to setup OIDC in WGE
=> Add OIDC docs for WGE

cmd/gitops-server/main.go, cmd/gitops/ui/run/cmd.go
The default notification-controller endpoint is incorrect.
=> Fix the notification controller address

test/acceptance/test/add_tests.go
- Fixed a test step in the add tests
- Finished a TODO item
**Why?**
- Changes to the test step were necessary to avoid nightly failures
- Might as well finish the TODO instead of leaving it there
=> Fix nightly CI failures

pkg/helm/charts.go
Closes https://github.com/weaveworks/weave-gitops/issues/1166
=> Pass Credentials from the HelmRepository

.github/workflows/scan.yaml
After enabling the snyk pipeline, my reports weren't uploading from
"main branches" after all - sad!
So instead of guessing what to write in the conditional, just copy
from test.yaml.
=> github: Actually do snyk uploads

.github/workflows/scan.yaml
We've got a github integration for that.
=> ci: Don't need to run snyk test manually

website/docs/gitops-dashboard.md
Added docs for superuser login flow.
**Why?**
To assist end users.
N/A
N/A
N/A
=> Add docs for superuser flow

core/server/helm_release_test.go
Extra tests for #1534 
(Merged #1534 to make sure I'm not blocking any UI related works while I'm trying to figure out how to test this properly)
=> chore(test): Add inventory tests on GetHelmRelease

ui/components/Layout.tsx
=> Add docs page to left menu nav

ui/components/Breadcrumbs.tsx, ui/components/DataTable.tsx, ui/components/InfoList.tsx, ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap, ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap, ui/lib/nav.ts, ui/lib/types.ts
Closes: #1576 
Closes: #1542 
Closes: #1578 
/applications route correction:
detail text color:
data table link text size:
=> Add text style fixes and V2Route correction

ui/components/Breadcrumbs.tsx, ui/components/__tests__/Breadcrumbs.test.tsx, ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
Fixes a bad idea that I had. Navigating to `/` blows things up.
=> Fix Breadcrumbs routing issue

core/server/types/helmrelease.go
=> fix: Incorrect interval in HelmRelase response

Tiltfile, charts/weave-gitops/templates/admin.yaml, tools/dependencies.toml, tools/download-deps.sh, tools/functions.sh, tools/helm-values-dev.yaml
- Use this local helm in the Tiltfile
- Also tidy up the dependencies script to make it easier to read and
silence some shellcheck violations
=> deps: Add helm to dependencies

README.md
I got confused for a second when my UI would not load, after I threw an `https` in the url all was good. Adding this note for others.
=> Update the readme with TLS info

ui/components/PageStatus.tsx, ui/components/SourceDetail.tsx, ui/pages/v2/HelmReleaseDetail.tsx, ui/pages/v2/KustomizationDetail.tsx
Closes: #1621
Changed structure of the header area of `SourceDetail` to clean things up and get a spicy border around that error message
=> Add Border to Source Detail Error Message

ui/components/ChipGroup.tsx, ui/components/ControlledForm.tsx, ui/components/FilterDialog.tsx, ui/components/FilterableTable.tsx, ui/components/Form.tsx, ui/components/FormInput.tsx, ui/components/__tests__/ChipGroup.test.tsx, ui/components/__tests__/FilterDialog.test.tsx, ui/components/__tests__/FilterableTable.test.tsx
Closes #1618
Video: https://drive.google.com/file/d/1TGyD9E2F8DnLN_dGlDn1070M5be8iXN_/view?usp=sharing
=> Re-work table filtering to match designs

website/docs/enterprise/oidc.mdx, website/docs/gitops-dashboard.md
Added docs for cluster user/oidc auth.
**Why?**
To assist end users when setting up auth.
N/A
N/A
N/A
=> Update auth docs

cmd/gitops-server/cmd/cmd.go, core/server/events_test.go, core/server/fluxruntime_test.go, core/server/helm_release_test.go, core/server/kustomization_test.go, core/server/namespace_test.go, core/server/sources_test.go
=> refactor: Clean up kube client initialization references

ui/components/Layout.tsx, ui/components/Page.tsx, ui/components/PollingIndicator.tsx, ui/components/SourceDetail.tsx, ui/components/__tests__/__snapshots__/Page.test.tsx.snap, ui/hooks/automations.ts, ui/hooks/events.ts, ui/hooks/flux.ts, ui/hooks/sources.ts, ui/pages/v2/Automations.tsx, ui/pages/v2/BucketDetail.tsx, ui/pages/v2/FluxRuntime.tsx, ui/pages/v2/GitRepositoryDetail.tsx, ui/pages/v2/HelmChartDetail.tsx, ui/pages/v2/HelmReleaseDetail.tsx, ui/pages/v2/HelmRepositoryDetail.tsx, ui/pages/v2/KustomizationDetail.tsx, ui/pages/v2/Sources.tsx
Closes: #1706
Adds the polling indicator component to all pages where requests will refresh every 5 seconds 
https://user-images.githubusercontent.com/65822698/158902347-f55f0cc2-1199-42bd-a0bf-fd9f97f3e705.mov
=> Add polling through react-query

go.mod, go.sum
=> Upgrade prometheus client

.github/workflows/pr.yaml
Further fixes for the CI docker image push step because I keep getting it wrong
=> More fix date images

package-lock.json, package.json, ui/components/AutomationsTable.tsx, ui/components/Page.tsx, ui/components/ReconciledObjectsTable.tsx, ui/hooks/events.ts, ui/hooks/flux.ts, ui/pages/v2/KustomizationDetail.tsx
Bump for a release. This has expanded to include various bug fixes; see the commits for more info. The main visual one is the alerts:
=> Update package.json for rc3

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/spike.md, .github/pull_request_template.md
They were slightly dated. I imagine more will need to change, but this
makes them more relevant for now.
Closes #1735
=> chore: Update PR/Issue templates

ui/pages/v2/HelmReleaseDetail.tsx
=> Add Tabs for Helm Release Detail

ui/components/DirectedGraph.tsx
Our `DirectedGraph` was a bit clunky after polling was added. This splits the imperative `d3` logic out from the declarative `react` logic to ensure zoom/scale/pan settings are preserved between polls.
=> Convert DirectedGraph d3 logic into class

.github/workflows/pr.yaml
The previous version wasn't working because I wasn't loading the
freshly built image properly, it used the wrong image tag, and I had a
couple of copy-paste errors in the names of steps, too.
=> ci: Fix snyk image monitor command

.github/workflows/pr.yaml
This time, it all works, but I forgot a "monitor" command. Ugh!
=> Fix snyk CLI pipeline, take 5

core/server/types/helmrelease.go, core/server/types/helmrepository.go, core/server/types/utils.go
=> fix: LastUpdatedAt value is always an empty string

package-lock.json, package.json
This is mainly for use inside enterprise.
=> Update package.json for rc11

core/server/types/bucket.go, core/server/types/gitrepository.go, core/server/types/helmchart.go, core/server/types/helmrelease.go, core/server/types/helmrepository.go, core/server/types/kustomization.go, core/server/types/utils.go
=> refactor: Remove unused ProtoToSomething functions

.parcelrc, ui/components/Icon.tsx
Closes #1886 
Fixes the broken UI from SVG loading issues
=> Fix svg loading

ui/components/KustomizationDetail.tsx, ui/pages/v2/KustomizationDetail.tsx
=> Fix width and height of Kustomization Detail

ui/components/ReconciliationGraph.tsx, ui/index.ts
This is a small follow up to #1896 that missed a couple of image references due to some merge timing.
I didn't double check the state of `main` before merging. A merge landed just prior that changed some things.
Just `npm start` this time. More testing was done in #1896
=> Fixes a couple of broken images when using UI as a module

.github/workflows/release.yaml, gitops-server.dockerfile, package-lock.json, package.json, tools/update-docs.sh
Closes #1685 
Closes #1858
* Pinned npm version in workflow to avoid reformats
* Removed broken flag from gitops-server build
* Fixed issue with doc generation when CLI reference directory needs to be deleted
To make the release process work in the new model
Made a fork of weave-gitops and built releases
=> final changes to generate a release

core/server/fluxruntime.go, core/server/fluxruntime_test.go, core/server/helm_release.go, core/server/helm_release_test.go, core/server/kustomization_test.go, core/server/list.go, core/server/sources.go, core/server/sources_test.go, core/server/suite_test.go
=> feat: Add cross-namespace querying to all listing endpoints

ui/components/Page.tsx, ui/components/__tests__/__snapshots__/Page.test.tsx.snap
CURRENT - filter bar grey line visible
FIXED - note visible background
=> Fix Spacing in Page Component

core/cache/namespace.go, core/cache/namespace_test.go, core/server/namespace_test.go, core/server/suite_test.go
Additional changes:
- Add mutex to namespace cache to avoid race conditions.
Closes #1911
=> refactor: Make namespace force recache a sync operation

README.md, charts/gitops-server/Chart.yaml, charts/gitops-server/values.yaml
* Point helm chart at 0.7.0 stable
* Update version of chart itself
* Change version in README
=> Update helm chart + CLI release version

website/docs/installation.mdx
=> Added missing version prefix. Command was broken.

ui/components/AutomationsTable.tsx, ui/components/FilterDialog.tsx, ui/components/FilterableTable.tsx, ui/components/ReconciledObjectsTable.tsx, ui/components/SourcesTable.tsx, ui/components/__tests__/FilterableTable.test.tsx
Closes #1810 
Adds a bunch of columns to the filter bar. Will create a follow-up issue to improve the code and add the select all boxes
=> Add Filtering Options

ui/components/FilterDialog.tsx, ui/components/FilterDialogButton.tsx, ui/components/FilterableTable.tsx
Adds `left` property to transition, padding and active state to hamburger button, and removes X button. I think it looks nice. 
https://user-images.githubusercontent.com/65822698/163601578-2b5f858c-4be7-402f-8536-7164dd9500b7.mov
=> Improve Filter Animation

Tiltfile, cmd/gitops-server/cmd/cmd.go, tools/charts/dev/.helmignore, tools/charts/dev/Chart.yaml, tools/charts/dev/templates/_helpers.tpl, tools/charts/dev/templates/limited-user.yaml, tools/charts/dev/values.yaml, tools/helm-values-dev.yaml
Closes #1671 
When doing developing we might need to test with users with limited power, simulating a more real-world environment, this PR introduces the `limited` user. It basically can do all the necessary operations but only in the `team-a` namespace.
Important note, there is no concept of login with this user here, we are basically forcing the `limited` user to be returned as the authenticated user, no matter the credentials you type on the login page.
To use this you should just set the `DEV_USE` as an environment variable so tilt can execute the server with the proper value.
```sh
$ DEV_USER=limited tilt up
```
> Given that currently, we are passing `flux-system` as the namespace to query the objects if you run with a limited user you won't be able to load …
=> Introducing limited user

ui/App.tsx, ui/components/HelmReleaseDetail.tsx, ui/pages/v2/HelmReleasePage.tsx, ui/pages/v2/KustomizationPage.tsx
Closes:
* #1933 
* #1947 
* #1939 
Before:
After:
=> Fix HelmRelease nav and styling

.github/workflows/release.yaml
I copy-pasted this from prepare-release.yaml. Don't do that. Instead, this copy-pastes from this file.
=> release: Fix condition to skip brew tap generation

ui/contexts/AuthContext.tsx, ui/contexts/CoreClientContext.tsx
Switch to checking user info instead of loading to stop flickering when navigating
=> Update auth check

tools/helm-values-dev.yaml
Fix missing values in dev helm chart
=> Fix dev chart values

ui/components/ChipGroup.tsx, ui/components/FilterDialog.tsx, ui/components/SourcesTable.tsx, ui/components/__tests__/FilterableTable.test.tsx
Closes #1927 
Closes #1965
The checkbox next to the category headers makes it easier to remove a single option from the category. Also adds the namespace column to the filtering options in the sources table.  Co-authored without credit by the great @jpellizzari - his name shall be etched on the stone of this PR for all eternity. 
https://user-images.githubusercontent.com/65822698/164556802-a7fa0cc8-040e-4f74-a434-aba685f46ec6.mov
=> Add Select All box to filter bar categories

website/docs/installation.mdx
Typo fix in docs - I am not certain if this will merge or if there are other generated entries that must be updates together as well!
=> Fix HelmRlease typo in docs

website/versioned_docs/version-0.7.0/getting-started.mdx
=> Some light changes

website/docs/getting-started.mdx, website/versioned_docs/version-0.7.0/getting-started.mdx
We want the next release to contain these changes too, so copy them
there.
=> docs: Copy the changes from #1985 to the unstable docs

go.mod, go.sum, pkg/utils/common.go, pkg/utils/common_test.go
This removes a few generic functions that aren't used, as well as one
small dependency.
=> Remove unused code in pkg/utils

website/docs/getting-started.mdx, website/versioned_docs/version-0.7.0/getting-started.mdx
Small documentation change to fill up missing information.
For better user experience. 
This is a documentation change.
=> Add missing url in getting started guide

.github/workflows/pr.yaml
I am not sure if the `if` syntax is correct, running some tests now but if anyone sees an obvious mistake, plz lmk.
=> chore: Alert Slack when CI fails on main

website/docs/getting-started.mdx, website/versioned_docs/version-0.7.0/getting-started.mdx
=> Fix: getting started missing admin user values

ui/components/FilterDialog.tsx, ui/components/FilterableTable.tsx, ui/components/__tests__/FilterableTable.test.tsx
Closes: #1868 
https://user-images.githubusercontent.com/65822698/166031539-aa21790e-0ae8-4687-b283-444ebc7cf6d8.mov
Filter state is now preserved through the url with the `setUrl` function. Context added to tests, but I need help mocking useLocation. Will create follow up issue.
=> Make filter state url addressable

README.md
This is an updated opening for Weave GitOps to give users a better sense of the project and the goals we are trying to accomplish.
=> Update README.md for a better overview

pkg/services/profiles/get.go
Social distancing required
The return statement was not at least 2m from the `if` statement
=> fix: socially distanced if blocks are required, no touching please

website/versioned_docs/version-0.8.0/_components/CurlCodeBlock.jsx, website/versioned_docs/version-0.8.0/assets/example-enterprise-helm.yaml, website/versioned_docs/version-0.8.0/cluster-management/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml, website/versioned_docs/version-0.8.0/cluster-management/assets/profiles/profile-repo.yaml, website/versioned_docs/version-0.8.0/cluster-management/assets/templates/capd-template.yaml, website/versioned_docs/version-0.8.0/cluster-management/deleting-a-cluster.mdx, website/versioned_docs/version-0.8.0/cluster-management/getting-started.mdx, website/versioned_docs/version-0.8.0/cluster-management/templates.mdx, website/versioned_docs/version-0.8.0/configuration/securing-access-to-the-dashboard.mdx, website/versioned_docs/version-0.8.0/configuration/tls.md, website/versioned_docs/version-0.8.0/guides/deploying-capa.mdx, website/versioned_docs/version-0.8.0/installation.mdx
- To avoid confusion when people are looking at main
Brings in docs from #2025 to 0.8.0
=> Backport WGE 0.8.0 docs

core/server/fluxruntime.go
=> fix: Missing deployments on Kustomization detail page

.github/snyk_delta_all_projects.sh, .github/workflows/pr.yaml, package-lock.json
Change snyk so it's using snyk-delta for PRs.
Change snyk so the merge pipeline distinguishes between errors and failures.
Manually rewrite the package-lock.json until it was no longer stopping snyk from running.
=> Try to fix snyk, again

website/docs/installation.mdx
Fixed a documentation typo
This is a documentation change
=> Fix documentation typo

cmd/gitops/add/terraform/cmd.go, pkg/adapters/http.go, pkg/templates/templates.go, pkg/templates/templates_test.go
Update to follow https://github.com/weaveworks/weave-gitops-enterprise/pull/836
=> Rename GitopsTemplate to GitOpsTemplate

Tiltfile
This PR parameterizes the dev image repository of Tiltfile. It also allows `wego-dev` as a k8s context for Tilt in addition to KinD clusters.
So that we can run Tilt with a remote cluster, like EKS.
- Parameterize the dev image repository with the environment variable `IMAGE_REPO`
- Override the image repository of the dev Helm chart with the above value
- Allow `wego-dev` as an addition K8s context.
- Set up an EKS cluster, name it `wego-dev`.
- Set up a remote repository
- Run Tilt with the following command, for example:
```shell
IMAGE_REPO=ghcr.io/chanwit/weave-gitops/wego-app FAST_AND_FURIOUSER=1 make …
```
=> parameterize dev image repository so that we can run Tilt with a remote cluster

core/clustersmngr/middleware.go
Closes
This clarifies the error message in the client middleware.
The current message doesn't appear to be relevant.
Textual change
=> Improve cluster middleware error message.

ui/components/AutomationDetail.tsx, ui/components/Icon.tsx, ui/components/SourceDetail.tsx, ui/components/YamlView.tsx
Closes #2231
Get command header added to the yaml tab!
https://user-images.githubusercontent.com/65822698/172657917-8e83b970-b94d-4ae0-b042-a16d0f506e92.mov
=> Add copyable kubectl get command to yaml tab

.github/workflows/pr.yaml, Makefile, package-lock.json, package.json
It seems I didn't add yaml to package.json - but everything worked
anyway, until we tried to publish a npm package, and that was the
point at which it broke. Let's run the command that discovered a
problem on every PR, to make sure I don't screw this up again.
=> js: Test that all dependencies are listed, add yaml dependency

package-lock.json, package.json
=> Fix the reference error by rolling `yaml` back to the stable version.

core/server/fluxruntime.go, core/server/fluxruntime_test.go
=> graph: Hide ReplicaSets with zero pods

ui/components/ReconciledObjectsTable.tsx
=> Fix filtering by name (searching) on Automation details tab

.github/workflows/chart.yaml
=> granted permissions for chart publication

core/server/types/gitrepository.go, core/server/types/gitrepository_test.go
=> fix nil pointer deref in GitRepositoryToProto

pkg/server/auth/jwt.go, pkg/server/middleware/middleware.go
=> reduce logging verbosity

ui/index.ts
Exports the `YamlView` component for use elsewhere. Related to https://github.com/weaveworks/weave-gitops-enterprise/issues/1111
=> Export YamlView

Makefile, pkg/run/install_dev_bucket_server.go
Closes #2461
@chanwit @ozamosi is setting the image name like this enough or should I add this variable elsewhere (Docker args, GitHub Actions workflows)?
=> GitOps Run - add compile-time variable for the Dev Bucket container image

.github/workflows/release.yaml
c84ee6019 copy-pasted the right thing, but to the wrong place.
=> release: Fix setting build-args when building the release image

cmd/gitops/get/bcrypt/cmd.go, cmd/gitops/get/cmd.go
=> cli: Remove client from bcrypt command

pkg/run/forward_port.go, pkg/run/forward_port_test.go, pkg/run/install_bucket_source_and_ks_test.go
=> add unit tests for get pod from spec map

website/docs/assets/example-enterprise-helm.yaml, website/docs/getting-started.mdx, website/docs/installation.mdx
All reconciliation intervals mentioned in the docs for Flux-managed resources are increased.
The previous intervals were much too low and did nothing really
outside of putting load on the cluster.
=> increase Flux resource intervals

website/docs/getting-started.mdx
With this change, the resulting HTML page will use proper "ol" tags so
it's easier to add/remove an item without taking care for the order
(as all items are just preceded with "1.").
Before:
After:
=> use proper numbered lists

pkg/server/auth/auth.go
We now seem to have 2 systems for specifying allowed login methods,
and they were clashing - if you don't have an issuerURL but you
haven't removed oidc from the legal auth types, the server crashes
with a nil pointer exception.
=> Don't allow login method unless _both_ cli arg _and_ feature flag is set

website/docs/guides/delivery.mdx, website/versioned_docs/version-0.9.1/guides/delivery.mdx
fixes issue where wrapping had broken display of note block
=> fix styling

website/docs/guides/delivery.mdx, website/versioned_docs/version-0.9.1/guides/delivery.mdx
this time... this time it fixes it...
=> avoid line breaks

ui/components/AutomationDetail.tsx, ui/components/SubRouterTabs.tsx, ui/hooks/automations.ts
Fixes `SubRouterTabs` iteration issue with key & remove extra tag of `SubRouterTabs`
=> extend-automation-details-with-tabs

cmd/gitops/beta/run/cmd.go
=> Improve watcher and file walker when a directory is added or removed

ui/components/Page.tsx
=> Fix empty error component adding whitespace

website/docs/installation.mdx, website/docs/policy/getting-started.mdx, website/docs/policy/weave-policy-profile.mdx
Closes
Fixed values used to set up policy profile in the documentation and documented how to install policy agent with WGE
To explain how to add the agent on the management cluster in a WGE installation 
Updated documentation
=> document installing agent with WGE and update agent docs

pkg/server/auth/auth.go
We used to always try first local user, then passthrough, then
oidc. The OIDC methods have therefore grown accustomed to returning
errors which shuts down the auth flow completely, even when it wasn't strictly an error.
This effectively reverts to the hard-coded order, so that OIDC can be
made to behave in peace and quiet.
=> auth: Revert to the old auth method order

website/docs/cluster-management/managing-existing-clusters.mdx, website/versioned_docs/version-0.9.1/cluster-management/managing-existing-clusters.mdx, website/versioned_docs/version-0.9.2/cluster-management/managing-existing-clusters.mdx, website/versioned_docs/version-0.9.3/cluster-management/managing-existing-clusters.mdx
Documentation
Aligning existing secret creation with CAPI, so the same bootstrap configuration can b e used 
N/A
=> docs: Aligning creation docs for existing cluster with CAPI

core/server/helm_release.go, core/server/kustomization.go, core/server/objects.go, core/server/sources.go, core/server/utils.go
Update `getTenant` to `GetTenant` to be able to use it in EE also
=> Update getTenant to GetTenant

ui/components/EventsTable.tsx
=> ui: Fix sort by Reason or Timestamp in the Events table

doc/adr/0005-wego-core-auth-strategy.md, doc/adr/0015-current-api-authentication-strategy.md
Add documentation to try and capture the current state of the authentication system. Ideally this should act as a baseline from which we can further improve it as well as aid those who need to get up to speed on how the system works
The current documentation is out of date and this is a security critical system
This represents my best effort reading and interpretation of the code.
Where possible I've verified the statements I've made by experimentation/testing (e.g. #2522, or by using the [go-client](https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration) to test the effect of an empty impersonation configuration).
=> Add ADR-15 summarising current auth strategy

ui/components/DataTable.tsx
Closes #2643 
- Switched to passing all fields and field indices instead of individual field objects to the `SortableLabel` to fix sort direction not always reversed bug. 
- Removed second instance of the field we are sorting on from the listpassed to `_.orderBy` to sort on, one is enough.
=> ui: Fix sort direction not reversed sometimes when clicking on the header of a selected sort column

.gitignore
- updating gitignore  to include vscode settings folder
=> add vscode setting folder to gitignore

website/docs/enterprise/multi-tenancy.mdx
Closes
Added multi tenancy doc
=> doc: add multi tenancy

core/clustersmngr/clustersmngr.go, core/clustersmngr/factory.go
This tries to make clustersmngr slightly more consistent with
itself.
* Every client now always uses the same base settings (with timeouts
and rate limiting). It used to be that user connections used the
"good" settings, and server connections usually didn't.
* Then, every code path now creates clients in parallel. Everything
already did except GetServerClient.
* Then, remove any workarounds so all code here uses the same few
code paths. There used to be private functions in factory that
duplicated functionality that there was already public functions
for - no more. Even namespace caching uses the cluster client.
This still leaves additional implementations in pkg/kube, but one
thing at a time.
=> clustersmngr: Reduce the number of ways we create cluster configs

core/clustersmngr/factory.go, core/clustersmngr/factory_test.go
- Don't bail if a single cluster is unreachable for some reason
- Also add in some logging to begin tracking down why we get empty
responses from apps/sources sometimes (that recover on next poll)
Instead of returning an err, continue updating namespace for other cluster we are able to connect to
So apps/sources work if a single cluster is temporarily unreachable
- Unit tests
- Manually testing by `replace`ing in WGE
=> Fixes apps/sources working for clusters that are reachable

Makefile, core/clustersmngr/clustersmngr_test.go
This required fixing a clustermngr test to work with flowcontrol
=> Update envtest tests to use 1.24

pkg/fluxinstall/product_test.go
=> fix unit tests failure on mac OS

pkg/run/install_bucket_source_and_ks.go
Before this, if any upload threw any error, we stopped uploading - we didn't shut anything down, we just stopped. When using this repository as an example, running gitops run just prints:
```
► Refreshing bucket dev-bucket ...
Handling connection for 9000
....Handling connection for 9000
Handling connection for 9000
Handling connection for 9000
....
► Uploaded 88 files
✗ Error syncing directory: MissingContentLength
✗ Error syncing dir: MissingContentLength
► Request reconciliation of dev-bucket, and dev-ks (timeout 30s) ...
✗ Error requesting reconciliation: inventory is nil
✔ Reconciliation is done.
```
which is very confusing - I have about 100,000 files here.
This adds the filename to any failed upload - that way I can debug what failed to upload.
This also completely swallows …
=> gitops run: Don't abort uploading on error

charts/gitops-server/Chart.yaml
Is this what you meant when you said bump the chart?
=> Bump the Helm Chart

website/docs/enterprise/multi-tenancy.mdx
Closes
Updated documentation for tenancy to include the `deploymentRBAC` section.
=> update tenancy doc with deployment RBAC

website/docs/assets/example-enterprise-helm.yaml, website/docs/enterprise/releases.mdx, website/docs/installation.mdx, website/versioned_docs/version-0.9.5/assets/example-enterprise-helm.yaml, website/versioned_docs/version-0.9.5/enterprise/multi-tenancy.mdx, website/versioned_docs/version-0.9.5/enterprise/releases.mdx, website/versioned_docs/version-0.9.5/installation.mdx
Public facing release notes for weave-gitops-enterprise v0.9.5
To show customers whats changed in the latest version of WGE
Manually copy our internal release notes into the page. In the future we'd like to do this more automatically somehow.
=> Weave Gitops Enterprise v0.9.5 release notes

ui/index.ts
Just need to add the hook to the exports to be able to show the new Notifications sections in EE. Thanks!
=> Add useListProviders to exports for EE

ui/components/__tests__/Flex.test.tsx, ui/components/__tests__/__snapshots__/Flex.test.tsx.snap
Add more snapshot tests for `Flex`. This was prompted by an upcoming presentation I am giving on the subject.
=> Add additional Flex snapshot tests

ui/index.ts
export `useListFluxCrds` function to help fix bug in WGE  https://github.com/weaveworks/weave-gitops-enterprise/issues/1621
=> export useListFluxCrds function

README.md
replaces reference to Core with OSS
=> minor rewording

pkg/run/bootstrap/bootstrap_wizard.go, pkg/run/bootstrap/bootstrap_wizard_ui.go
=> gitops run bootstrap: Render PATs and passwords as '***'

website/docs/enterprise/releases.mdx, website/versioned_docs/version-0.10.0/enterprise/releases.mdx, website/versioned_docs/version-0.9.6/enterprise/releases.mdx
Add WGE v0.9.6 release notes to docs
=> Add WGE v0.9.6 release notes to docs

website/docs/cluster-management/_category_.json, website/docs/enterprise/_category_.json, website/docs/enterprise/user-permissions.mdx, website/docs/feedback-and-telemetry.md, website/docs/gitops-run.mdx, website/docs/gitops-run/_category_.json, website/docs/gitops-run/get-started.mdx, website/docs/gitops-run/overview.mdx, website/docs/help-and-support.md, website/docs/policy/_category_.json, website/docs/references/_category_.json, website/versioned_docs/version-0.10.0/cluster-management/_category_.json, website/versioned_docs/version-0.10.0/enterprise/_category_.json, website/versioned_docs/version-0.10.0/enterprise/user-permissions.mdx, website/versioned_docs/version-0.10.0/feedback-and-telemetry.md, website/versioned_docs/version-0.10.0/gitops-run/_category_.json, website/versioned_docs/version-0.10.0/gitops-run/get-started.mdx, website/versioned_docs/version-0.10.0/gitops-run/overview.mdx, website/versioned_docs/version-0.10.0/help-and-support.md, website/versioned_docs/version-0.10.0/policy/_category_.json, website/versioned_docs/version-0.10.0/references/_category_.json
Documentation for gitops run.  This has an introduction, terminology, and getting started.
=> gitops run getting started

pkg/run/install/session.go
=> reset signal in session

.goreleaser.yml, Makefile, cmd/gitops-bucket-server/main.go, cmd/gitops/beta/run/cmd.go, gitops-bucket-server.dockerfile, gitops-server.dockerfile, gitops.dockerfile, pkg/run/install/install_vcluster.go, pkg/run/unused_ports.go, pkg/run/watch/install_bucket_source_and_ks.go, pkg/run/watch/install_dev_bucket_server.go
=> implement random port for bucket

pkg/run/bootstrap/bootstrap_wizard_ui.go
Followup to #2870
- Fixed the last input not highlighted on focus properly (that loop strikes again!).
- Fixed panic on pressing space on the Submit button.
=> Fix the last input not highlighted on focus properly.

ui/components/AutomationsTable.tsx, ui/components/DataTable.tsx, ui/hooks/automations.ts, ui/hooks/objects.ts, ui/lib/objects.ts, ui/lib/test-utils.tsx, ui/pages/__tests__/Automations.test.tsx
Closes #2915
^^ first sample integration test - holding off on detail pages for now as tabs are not rendering, will handle more tests on an individual PR basis
Adds a folder for page tests, and adds an initial example for ListAutomations - the test dug up some bugs related to results coming back undefined, so those have been fixed here as well.
=> Add test for ListAutomations

.github/ISSUE_TEMPLATE/feature_request.md
Proposes new issue template for community members to share their ideas on improving the project.
=> new issue template - feature request

ui/components/ReconciledObjectsTable.tsx, ui/contexts/AppContext.tsx, ui/contexts/LinkResolverContext.tsx, ui/index.ts, ui/pages/OAuthCallback.tsx
Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/1661
Re-try of https://github.com/weaveworks/weave-gitops/pull/2845
=> Add LinkResolver to allow for customizable navigation

charts/gitops-server/values.yaml, website/docs/references/helm-reference.md
Fixes https://github.com/weaveworks/weave-gitops/issues/2856
=> update guidance for adminUser.username

website/docs/assets/templates/capd-template.yaml
Small edit to change control planes to worker machines in description
Documentation fix
To ensure documentation is correct
Amended documentation
Change control plane nodes to worker nodes in description
=> Documentation update: small fix to change control planes to worker nodes in description

ui/components/Footer.tsx, ui/components/__tests__/__snapshots__/Footer.test.tsx.snap, ui/components/__tests__/__snapshots__/Page.test.tsx.snap, website/docusaurus.config.js
Closes #2648 
Quick fix PR to remove a defunct commercial email address with one where the user can discuss commercial support needs.
We _may_ want to revisit particular wordings later.
Includes doc changes as well
=> changes support email to sales email

Tiltfile, ui/components/Icon.tsx, ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap, ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap, ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap, ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap, ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Closes https://github.com/weaveworks/weave-gitops/issues/2957
Before: 
After:
=> Make custom icons obey size prop

cmd/gitops/beta/run/cmd.go
=> fix error when parsing port-forward in session mode

ui/components/AutomationsTable.tsx, ui/components/BucketDetail.tsx, ui/components/GitRepositoryDetail.tsx, ui/components/HelmChartDetail.tsx, ui/components/HelmRepositoryDetail.tsx, ui/components/OCIRepositoryDetail.tsx, ui/components/ReconciledObjectsTable.tsx, ui/components/SourcesTable.tsx
=> Change `type` to `kind` on detail `<Info />` components

website/versioned_docs/version-0.10.2/policy/commit-time-checks.mdx, website/versioned_docs/version-0.10.2/policy/configuration.mdx, website/versioned_docs/version-0.10.2/policy/getting-started.mdx, website/versioned_docs/version-0.10.2/policy/policy-configuration.mdx, website/versioned_docs/version-0.10.2/policy/policy-set.mdx, website/versioned_docs/version-0.10.2/policy/policy.mdx, website/versioned_docs/version-0.10.2/policy/releases.mdx, website/versioned_docs/version-0.10.2/policy/weave-policy-profile.mdx
Add the latest policy docs to 0.10.2
=> Add the latest policy docs to 0.10.2

website/docs/enterprise/releases.mdx, website/versioned_docs/version-0.10.1/enterprise/releases.mdx, website/versioned_docs/version-0.10.2/enterprise/releases.mdx
Closes
add releases `v0.10.1` and  `v0.10.2` to docs
=> add missing wge releases

website/docs/gitops-run/get-started.mdx, website/versioned_docs/version-0.10.0/gitops-run/get-started.mdx, website/versioned_docs/version-0.10.1/gitops-run/get-started.mdx, website/versioned_docs/version-0.10.2/gitops-run/get-started.mdx
closes #3028
Previews:
- [next](https://staging.docs.gitops.weave.works/fix-tab-formatting/docs/next/gitops-run/get-started/#start-modifying)
- [0.10.2](https://staging.docs.gitops.weave.works/fix-tab-formatting/docs/gitops-run/get-started/#start-modifying)
- [0.10.1](https://staging.docs.gitops.weave.works/fix-tab-formatting/docs/0.10.1/gitops-run/get-started/#start-modifying)
- [0.10.0](https://staging.docs.gitops.weave.works/fix-tab-formatting/docs/0.10.0/gitops-run/get-started/#start-modifying)
=> Fix formatting of tab

cmd/gitops/beta/run/cmd.go, pkg/logger/logger.go, pkg/logger/s3_log_writer.go, pkg/run/install/install_dashboard.go, pkg/run/watch/dashboard.go, pkg/run/watch/install_dev_bucket_server.go
=> implement s3 log writer

website/docs/enterprise/pipelines/getting-started.mdx, website/versioned_docs/version-0.10.2/enterprise/pipelines/getting-started.mdx
Closes
Updates docs to reference the feature flag for Pipelines in WGE
Local build
=> advise on flag usage

website/package.json, website/yarn.lock
update to docusaurus 2.2.0
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update to docusaurus 2.2.0

website/docs/assets/example-enterprise-helm.yaml, website/docs/installation/weave-gitops-enterprise.mdx, website/versioned_docs/version-0.11.0/assets/example-enterprise-helm.yaml, website/versioned_docs/version-0.11.0/installation/weave-gitops-enterprise.mdx
Update release versions in docs
To reflect the new version
N/A
N/A
N/A
N/A
=> fix: Update versions in code snippets

website/docs/enterprise/releases.mdx
Update release notes.
To reflect the new release.
N/A
N/A
N/A
N/A
=> docs: Update release notes

website/docusaurus.config.js, website/versioned_docs/version-0.11.0/cluster-management/getting-started.mdx, website/versioned_docs/version-0.11.0/getting-started.mdx, website/versioned_docs/version-0.11.0/gitops-run/get-started.mdx, website/versioned_docs/version-0.11.0/guides/cert-manager.md, website/versioned_docs/version-0.11.0/guides/deploying-capa.mdx, website/versioned_docs/version-0.11.0/guides/setting-up-dex.md, website/versioned_docs/version-0.11.0/guides/using-terraform-templates.mdx, website/versioned_docs/version-0.11.0/installation.mdx, website/versioned_docs/version-0.11.0/installation/index.mdx, website/versioned_docs/version-0.11.0/installation/weave-gitops.mdx, website/versioned_docs/version-0.11.0/intro.md
=> backport the installation page fixes from #3058

pkg/run/watch/setup_dev_ks.go, pkg/run/watch/setup_dev_ks_test.go
=> run: Create directories recursively

website/docs/policy/commit-time-checks.mdx, website/versioned_docs/version-0.11.0/policy/commit-time-checks.mdx
Closes
- Added azure devops commit time checks docs
=> add azure image to website docs

website/docs/policy/commit-time-checks.mdx, website/versioned_docs/version-0.11.0/policy/commit-time-checks.mdx
Closes
- update the commit time checks image
=> update commit time docs

ui/components/NotificationsTable.tsx
Closes #3082 
Navigating to the notifications view results in an error message:
=> [fix] Navigating to the notifications view results in an error message:

cmd/gitops/beta/run/cmd.go, pkg/run/install/install_vcluster.go, pkg/run/install/session.go
By doing this, it's possible to get all the information we need to link directly to the automation.
=> run: Add annotation on vcluster for the automation kind created

website/docs/gitops-templates/templates.mdx, website/versioned_docs/version-0.11.0/gitops-templates/templates.mdx
=> Update template docs

ui/components/FluxObjectsTable.tsx, ui/components/ReconciledObjectsTable.tsx, ui/components/__tests__/FluxObjectsTable.test.tsx, ui/lib/fixtures/objects_table.ts, ui/lib/nav.ts
Closes #3103 
I think @joshri had the right idea on this: we have certain types that we know about (`Alerts`, etc), but they don't have dedicated detail pages. This PR corrects that assumption.
=> Return empty string on unknown route

website/docs/enterprise/pipelines/promoting-applications.mdx, website/docs/enterprise/pipelines/spec/v1alpha1/pipeline.mdx
=> docs: Update pipeline docs

website/docs/releases.mdx, website/versioned_docs/version-0.12.0/releases.mdx
Follow up to https://github.com/weaveworks/weave-gitops/pull/3133
=> guidance on oss release notes

website/docs/assets/example-enterprise-helm.yaml, website/docs/installation/weave-gitops-enterprise.mdx, website/docs/releases.mdx, website/versioned_docs/version-0.12.0/assets/example-enterprise-helm.yaml, website/versioned_docs/version-0.12.0/installation/weave-gitops-enterprise.mdx, website/versioned_docs/version-0.12.0/releases.mdx
=> Update release docs

website/docs/pipelines/promoting-applications.mdx, website/docs/pipelines/spec/v1alpha1/pipeline.mdx, website/versioned_docs/version-0.12.0/pipelines/promoting-applications.mdx, website/versioned_docs/version-0.12.0/pipelines/spec/v1alpha1/pipeline.mdx
**What changed?** Added documentation for pipelines pull request git providers 
=> updated pipeline pull request git provider type docs

website/versioned_docs/version-0.12.0/pipelines/promoting-applications.mdx, website/versioned_docs/version-0.12.0/pipelines/spec/v1alpha1/pipeline.mdx
@sympatheticmoose  at the back of 
https://github.com/weaveworks/weave-gitops/pull/3132#issuecomment-1348161844
raised this PR as already merged the other one
=> removing from docs as it was not from v0.12

website/docs/gitops-templates/templates.mdx, website/versioned_docs/version-0.12.0/gitops-templates/templates.mdx
=> Adds `template.spec.charts` section to the user-guide

website/docs/releases.mdx, website/versioned_docs/version-0.12.0/releases.mdx
=> fix formatting

charts/gitops-server/templates/deployment.yaml, charts/gitops-server/values.yaml
Closes
Added extraVolumes and extraVolumesMounts values to be able to mount extra volumes.
We use the Secret Store CSI Driver (https://secrets-store-csi-driver.sigs.k8s.io/introduction.html) to mount the OIDC client secret from Azure Keyvault.
To be able to use this driver a volume needs to be added to the deployment with reference to the driver and the SecretProviderClass.
Change has been tested locallly with specifying the extraVolumes and extraVolumesMounts values and verifying the resulting deployment definition and tested with no value for extraVolumes and extraVolumesMounts.
=> Added extraVolumes and extraVolumesMounts.

doc/release-process.md
Add versioning section to release docs
=> Add versioning section to docs

pkg/s3/auth_middleware.go, pkg/s3/auth_middleware_test.go
This mitigates a potential XSS attack raised in
https://app.snyk.io/org/product-engineering-ly9/project/fc4de543-d193-4285-810e-c33e07075f0d#issue-3aa3074c-582e-48fd-a37d-d28f9f2b56e2.
=> sanitize input when processing S3 authorization header

website/docs/terraform/overview.mdx
=> improve tf-c overview

website/docs/gitops-run/get-started.mdx
=> clarify the getting started doc

cmd/gitops/beta/run/cmd.go
=> fix asking dashboard twice

website/docs/workspaces/view-workspaces.mdx, website/versioned_docs/version-0.13.0/workspaces/view-workspaces.mdx
Fix typo `Detais` to `Details` in workspaces docs (docs and versioned docs v0.13.0)
=> Fix typo in Workspace docs

cmd/gitops/beta/run/cmd.go
=> Fix irrelevant error messages about log upload during shutdown for gitops run

website/docs/releases.mdx, website/versioned_docs/version-0.14.1/releases.mdx
=> Add Weave GitOps 0.14.1 release notes to the website

website/docs/feedback-and-telemetry.md, website/versioned_docs/version-0.14.1/feedback-and-telemetry.md
Removes myself from the feedback page.
=> update calendly links

website/docs/terraform/environment-variables.mdx, website/docs/terraform/overview.mdx
=> tf-doc add logging env variables for the terraform runner

ui/components/Footer.tsx, ui/components/__tests__/__snapshots__/Footer.test.tsx.snap, ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Updating Year in the footer to match current Year
=> update year in footer to the current year

cmd/gitops/beta/run/cmd.go, pkg/run/install/install_fluent_bit.go, pkg/run/install/install_fluent_bit_test.go
Fixes #3267 
1. Run GitOps Run
2. Open the dashboard
3. You would see Fluent-Bit installed as a HelmRelease, see its DaemonSet on the detail page, and everything being green.
=> install and configure fluent-bit for vcluster

core/server/session_logs.go, core/server/session_logs_test.go, pkg/run/install/install_vcluster.go
=> expose bucket service from a vcluster to host

core/server/session_logs.go
Fixes #3334
To test it, simply:
- bump this branch to @joshri WGE `logs-test` branch.
- clone any Git repo, cd into it, run `gitops beta run --skip-dashboard-install ./test`
- click name of the session, you'll see the logs listed there.
=> fix flux namespace discovery in session_logs endpoint

pkg/gitproviders/factory.go, pkg/gitproviders/factory_test.go
Closes #3306
Added BitBucket git provider
To be able to support BitBucket
Most of the code used is part of fluxcd/go-git-providers
Manually
N/A
N/A
=> feat: Add support for BitBucket Server

website/package.json, website/yarn.lock
=> bump docusaurus to 2.3.1

doc/release-process.md
=> add artifact list to release guide

ui/components/Icon.tsx
=> Handle undefined icon type

Tiltfile, core/clustersmngr/client.go, core/clustersmngr/client_test.go, core/clustersmngr/factory.go, core/server/fluxruntime.go, ui/components/ReconciliationGraph.tsx, ui/lib/__fixtures__/graph.ts, ui/lib/__tests__/graph.test.ts, ui/lib/graph.ts
Closes #3302
Adds some streamlining to the back-end to make results more consistent, as well as some sorting logic on the front-end to avoid dancing nodes. 
Shoutout to @luizbafilho for the help on the request simplification.
=> Fix graph nodes hopping around

pkg/server/auth/server.go, website/docs/configuration/securing-access-to-the-dashboard.mdx, website/docs/gitopssets/intro.mdx, website/versioned_docs/version-0.16.0/configuration/securing-access-to-the-dashboard.mdx, website/versioned_docs/version-0.16.0/gitopssets/intro.mdx
Added documentation on scopes and claims.
So that users can understand how to use the features.
Ummm...documentation?
Applied the instructions
Not notable
This is a documentation change.
=> Add documentation on custom claims and scopes.

website/README.md
An initial docs writing guide
Closes #3351
=> docs: Expand the website readme

website/docs/pipelines/promoting-applications.mdx
Small docs improvements to include some steps on creating secrets.
=> Make Pipeline PR/secret docs more specific

website/docs/installation/weave-gitops-enterprise/index.mdx
install WGE CLI example use latest version
=> fix enterprise installation docs

core/server/session_logs.go, core/server/session_logs_int_test.go
Follow-up to https://github.com/weaveworks/weave-gitops/issues/3379
- Lifted the checks for the logs secret up.
=> Error getting GitOps Run logs before GitOps Run objects are ready

cmd/gitops/beta/run/cmd.go
=> skip reconciliation of dotfiles in GitOps Run

website/docs/terraform/get-started.mdx, website/docs/terraform/overview.mdx
=> update docs for tf-controller v0.14.0 on WG website

website/docs/installation/weave-gitops-enterprise/index.mdx, website/docs/releases.mdx, website/versioned_docs/version-0.18.0/releases.mdx
Updates #3473
Bump download version, small lint fixes
Because we want to advertise the correct version on new releases
vim
Trivial mdx fixes
=> Bump 0.17 to 0.18

website/docs/configuration/oidc-access.mdx, website/versioned_docs/version-0.18.0/configuration/oidc-access.mdx
=> Update SSO button customization for EE

pkg/gitproviders/repo_url.go, pkg/gitproviders/repo_url_test.go
Updated `NewRepoURL` function to parse Azure DevOps URLs correctly
To be able to support parsing of Azure DevOps repository URLs
N/A
Unit tests
N/A
N/A
=> feat: Parse Azure DevOps repository URLs

ui/index.ts
Needed for some query stuff in EE
=> Export ChipGroup

ui/index.ts
=> Add DetailModal for Yaml display in EE

ui/components/AutomationDetail.tsx, ui/components/ReconciledObjectsTable.tsx, ui/components/ReconciliationGraph.tsx, ui/hooks/inventory.ts
Closes
Updates the Props for `ReconciliationGraph` and `ReconciledObjectsTable` to be more readable and easy to use in EE .
=> Updating the props to meet what EE needs

website/docs/secrets/bootstraping-secrets.mdx, website/docs/secrets/spec/index.mdx, website/docs/secrets/spec/v1alpha1/secretSync.mdx, website/sidebars.js
Closes https://github.com/weaveworks/weave-gitops/pull/3476
Docs added for bootstrapping secrets
=> add bootstrapping secrets page

cmd/gitops/beta/run/cmd.go, cmd/gitops/create/dashboard/cmd.go, pkg/run/install/apply_manifests.go, pkg/run/install/install_dashboard.go, pkg/run/install/install_dashboard_test.go
Fixes #3571
How to test:
1. Start the normal `gitops run` with a proper set of parameters
2. Use it to install the dashboard, and the dashboard installation process should start normally
=> use client-side apply for better interactivity

website/docs/cluster-management/assets/profiles/profile-repo.yaml, website/docs/cluster-management/getting-started.mdx, website/docs/gitops-templates/profiles.mdx, website/docs/gitops-templates/repo-rendered-paths.mdx, website/docs/gitops-templates/resource-templates.mdx, website/sidebars.js, website/versioned_docs/version-0.20.0/cluster-management/assets/profiles/profile-repo.yaml, website/versioned_docs/version-0.20.0/cluster-management/getting-started.mdx, website/versioned_docs/version-0.20.0/gitops-templates/profiles.mdx, website/versioned_docs/version-0.20.0/gitops-templates/repo-rendered-paths.mdx, website/versioned_docs/version-0.20.0/gitops-templates/resource-templates.mdx, website/versioned_sidebars/version-0.20.0-sidebars.json
Adds a user-guide section for
- raw templates
- template.spec.chart.items and helmrelease paths
=> Adds user-guide for raw templates and chart paths

website/docs/secrets/manage-secrets-ui.mdx, website/docs/secrets/managing-secrets-with-sops.mdx, website/docs/secrets/setup-secrets-operator.mdx
Closes
- review hotfixes and typo fixes for docs
=> review hotfixes and typo fixes for docs

Tiltfile, charts/gitops-server/templates/_helpers.tpl, charts/gitops-server/templates/admin-user-creds.yaml, charts/gitops-server/templates/deployment.yaml, charts/gitops-server/templates/role.yaml, charts/gitops-server/values.yaml, cmd/gitops-server/cmd/cmd.go, pkg/server/auth/auth_test.go, pkg/server/auth/init.go, pkg/server/auth/init_test.go, pkg/server/auth/server.go, pkg/server/auth/server_test.go, tools/helm-values-dev.yaml, website/docs/configuration/emergency-user.mdx, website/docs/configuration/service-account-permissions.mdx
Closes #3616 
Revert PR https://github.com/weaveworks/weave-gitops/pull/3542
Let's revert it for now and re-merge it after fixing this issue related to secret names.
=> Revert PR #3542

website/docs/gitopssets/guide.mdx, website/docs/gitopssets/releases.mdx, website/docs/releases.mdx, website/versioned_docs/version-0.21.2/gitopssets/guide.mdx, website/versioned_docs/version-0.21.2/gitopssets/releases.mdx, website/versioned_docs/version-0.21.2/releases.mdx
- Add the docs for the cluster generator
=> [user-guide] Adds the 0.21.2 EE and 0.8.0 gitopssets-controller releases

pkg/server/auth/auth_test.go, pkg/server/auth/claims.go
Changes a call in a test to work with current main.
Make tests pass on `main` again.
Tweaked the test
=> Fix broken test.

doc/development-process.md
Closes #3607 
Docs were outdated in terms of the bash variables needed - added `FAST_AND_FURIOUSER` as well as `SKIP_UI_BUILD`.
=> Update frontend dev process docs

website/docs/assets/example-enterprise-helm.yaml, website/docs/installation/weave-gitops-enterprise/index.mdx, website/docs/releases.mdx, website/versioned_docs/version-0.22.0/assets/example-enterprise-helm.yaml, website/versioned_docs/version-0.22.0/installation/weave-gitops-enterprise/index.mdx, website/versioned_docs/version-0.22.0/releases.mdx
Added WGE 0.22.0 release notes to the website's release page.
=> Add WGE 0.22.0 release notes

package-lock.json, package.json, ui/components/YamlView.tsx, ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Closes #3513
Changes:
- Added syntax highlighting to the YamlView with `react-syntax-highlighter`.
- Added support for light and dark modes in the YAML view (with passing the mode prop for now).
- Updated snapshots.
Notes:
- When copying YAML directly from browser (from the highlighted view) — after enabled the option to wrap long lines in the view — newlines are inserted into each line after key and after colon because of `display: flex` added to lines, so in Chrome it's copied like that:
```
id
:
value
```
In the original unstyled view no newlines were inserted at all, so the copied YAML was not formatted properly and was copied like `id1:    value1  id2:    value2`.
So, copying formatted YAML directly from browser does not look feasible without using a text component.
Testing:
To test …
=> Add syntax highlighting to the YamlView

website/docs/pipelines/promoting-applications.mdx
Minor update to the pipeline docs.
To make it more clear how the token is being used.
N/A
N/A
N/A
N/A
=> docs: Minor addition to mention PAT usage

ui/components/AutomationDetail.tsx, ui/components/KubeStatusIndicator.tsx, ui/hooks/__tests__/inventory.test.tsx, ui/hooks/inventory.ts
Closes [EE issue](https://github.com/weaveworks/weave-gitops-enterprise/issues/2572)
* We should display the canary status on the top of the application details page alongside the reconciliation status, and it needs to convey a summarized status of all canaries in the application. 
* We should display the canary status only if there is a canary object in the application, otherwise we shouldn't show the status at all. 
* Application Canary Status should be one of the following:
- **[error icon] One or more canaries have failed** >> if any of the canaries in the application is in the following states: (Failed, Terminating, Terminated)
- **[inProgress icon] One or more canaries are in progress** >> If any of the canaries in the application is in the following states: …
=> App Observability - Surface Flagger Status

core/nsaccess/nsaccess.go, core/nsaccess/nsaccess_test.go
Reverts a previous change. We need more time to test this change.
=> Revert fix for #3702

.github/workflows/chart.yaml, .github/workflows/docs.yaml, .github/workflows/nightly.yaml, .github/workflows/pr.yaml, .github/workflows/prepare-release.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .github/workflows/upgrade-flux.yaml
Updated CI workflows with the most recent versions of the following actions:
- actions/checkout@v3
- actions/download-artifact@v3
- actions/setup-go@v4
- actions/setup-node@v3
- actions/upload-artifact@v3
- docker/login-action@v2
- google-github-actions/auth@v1
- google-github-actions/upload-cloud-storage@v1
To keep actions up to date.
N/A
CI
N/A
N/A
=> Update GitHub actions to their latest versions

.github/workflows/docs.yaml
Closes https://github.com/weaveworks/weave-gitops/issues/3741
Updated step according to https://github.com/google-github-actions/upload-cloud-storage/issues/323 and https://github.com/google-github-actions/upload-cloud-storage/pull/312/files
To fix docs building
Tested https://github.com/weaveworks/weave-gitops/actions/runs/5141898222/jobs/9254971059
Not Required
Not Required
=> updated cache-control  upload-file staging-release step according to readme recommendations

ui/lib/nav.ts
Closes #3766 
Highlight right navParent while navigating back and forth to policy details 
https://github.com/weaveworks/weave-gitops/assets/4614360/61c3d500-f7df-4e97-9cae-55e589694f8d
=> Update Nav highlight for Policy-details

core/server/policies.go, core/server/policies_test.go
- Return ClusterName on the Policy List Response.
- To fix the PolicyList & PolicyDetails clusterName bug on WGE.
- Unit-Test
=> Add clusterName to policies list

charts/gitops-server/README.md.gotmpl
Closes
- Fix template for helm-docs to align with the new paths
- Manual local test
=> fix getting started location for helm-docs

website/docusaurus.config.js
continue on https://github.com/weaveworks/weave-gitops/pull/3771
=> fix main page index

website/docusaurus.config.js
continue on https://github.com/weaveworks/weave-gitops/pull/3773
=> fix config file

website/docs/enterprise/getting-started/install-enterprise.mdx, website/versioned_docs/version-0.25.0/enterprise/getting-started/install-enterprise.mdx
Updated TOC widget to use correct header name
Currently the TOC is missing, this change fixes that.
N/A
N/A
N/A
N/A
=> docs: Fix TOC for WGE

cmd/gitops/create/dashboard/cmd.go
Closes https://github.com/weaveworks/weave-gitops/issues/3072
- Added detecting installed dashboard to the `gitops create dashboard` command.
Testing:
- Just install the dashboard once with `gitops create dashboard` to a clean cluster. It should install successfully.
- After that, try to install the dashboard again with `gitops create dashboard` on the same cluster. The installed dashboard should be detected and the command should exit with a log message and an error without applying dashboard manifests.
- You can also run OSS or enterprise UI with tilt as usual and, after is it built completely (Tilt is all green), try running `gitops create dashboard`. It should detect the dashboard running with Tilt as already installed and exit the command with a log message and an error.
=> Warn users if Weave GitOps is already installed

core/server/policies.go
Closes
- https://github.com/weaveworks/weave-gitops-enterprise/issues/2966
- PoilcyList endpoint will return full details for each policy.
- PolicyConfigs on WGE depends on policyList to get the full details.
- Remove the details flag from policyToPolicyRespone.
=> Add policy full details to list endpoint

ui/App.tsx, ui/components/Layout.tsx
Update the Layout component to accept components (`<Nav />` and `<Logo />`) so we can use the EE custom Nav temporarily
=> Update layout to accept components

website/docs/enterprise/getting-started/releases-enterprise.mdx, website/versioned_docs/version-0.28.0/enterprise/getting-started/releases-enterprise.mdx
Lauri added an extra line to the release notes.
=> docs: add missing entry for v0.28.0 release notes

website/versioned_docs/version-0.25.0/guides/fluxga-upgrade.mdx, website/versioned_docs/version-0.26.0/guides/fluxga-upgrade.mdx, website/versioned_docs/version-0.27.0/guides/fluxga-upgrade.mdx, website/versioned_docs/version-0.28.0/guides/fluxga-upgrade.mdx
Related to https://github.com/weaveworks/weave-gitops/pull/3882
The PR fixes the old `/releases` link with new `/enterprise/getting-started/releases-enterprise/` urls. 
Current versions of doc goes to wrong versions due to doc structure changes
Local testing
Update release page urls
=> Update old `/releases` link with new `/enterprise/getting-started/releases-enterprise/` urls

website/docs/guides/fluxga-upgrade.mdx
Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/2710 
Updated upgrade fluxga docs to get ready for v0.29 release as it drops flux beta support. Also changed 
the upgrade process to ensure that when used in the context of v0.29 it does not break.
To ensure we have updated documentation when releasing v0.29
Documentation
Manually 
No
Yes
=> update upgrade fluxga docs to get ready for v0.29 release

website/src/components/HomepageFeatures/index.js
Closes
Remove GitOps Run demo video and replace with a newer video featuring Terraform Controller.
To provide fresher and more relevant content for users.
=> Update video on main docs page

website/docs/guides/fluxga-upgrade.mdx
Small fixes to the Flux GA user guide page.
=> Update Flux GA guide

website/docs/enterprise/getting-started/install-enterprise.mdx
Closes
Implements the change suggested [here](https://github.com/weaveworks/weave-gitops/pull/3924#discussion_r1287264627), which didn't get resolved due to a minor mix-up in communication.
The image link was broken.
I replaced the broken link with the suggested one. 
The prod-release run failed 30 mins prior because of this issue.
N/A
It's a documentation-related change.
=> Fixes github-oauth link in Install WGE page

website/docs/enterprise/getting-started/releases-enterprise.mdx, website/docs/gitops-templates/versions.mdx, website/docs/gitopssets/_api-toc.json, website/docs/gitopssets/_api.mdx, website/docs/gitopssets/gitopssets-installation.mdx, website/versioned_docs/version-0.30.0/enterprise/getting-started/releases-enterprise.mdx, website/versioned_docs/version-0.30.0/gitops-templates/versions.mdx, website/versioned_docs/version-0.30.0/gitopssets/_api-toc.json, website/versioned_docs/version-0.30.0/gitopssets/_api.mdx, website/versioned_docs/version-0.30.0/gitopssets/gitopssets-installation.mdx
Adds release notes for Weave GitOps Enterprise v0.30.0
=> Weave GitOps Enterprise v0.30.0 Release Notes

website/SECURITY.md
Added Security policy.
To let users know how to report security vulnerabilities.
=> docs: Add SECURITY.md

Makefile
- Add timeout for yarn in the makefile
- To avoid network timeout in building on github actions
Manual testing
=> add timeout for yarn

ui/App.tsx
Closes #4003 
Policies is added to side nav Items
=> Add Policies nav-item to the side nav

.github/workflows/ossf.yaml
Closes #4017 
Added OpenSSF GitHub Action
To enable code scanning.
https://github.com/ossf/scorecard-action#manual-action-setup
CI
N/A
N/A
=> ci: Add OpenSSF GH action

ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx, ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx, ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx, ui/components/ImageAutomation/repositories/ImageRepositoriesTable.tsx, ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx, ui/components/ImageAutomation/updates/ImageAutomationUpdatesTable.tsx, ui/index.ts
Part of [3339]( https://github.com/weaveworks/weave-gitops-enterprise/issues/3339)
Import `ImageAutomation` components to be used in EE also added a cluster info conditional to `WEAVE_GITOPS_FEATURE_CLUSTER`
=> Import `ImageAutomation` components to be used in EE

website/docs/open-source/getting-started/ui-OSS.mdx, website/docs/progressive-delivery/progressive-delivery-flagger-install.mdx
Fixes an error on a progressive delivery user docs page and adds more context to the page about the OSS UI.
To provide accurate and clear information to users.
This change involves no page rearrangements or link replacements so it should be fine.
Same as above. 
It's a doc change.
=> Removes error on Progressive Delivery page and adds info about UI views

website/README.md, website/docs/explorer/configuration.mdx
supports https://github.com/weaveworks/weave-gitops-enterprise/issues/2957
- Add templates to explorer supported kinds docs
- Add hint in development docs to include next to show local changes
update docs
N/A
starting local server to view docs
Templates added to explorer supported kinds docs
=> Add templates to explorer supported kinds docs

ui/components/AutomationDetail.tsx
Closes [#4057](https://app.zenhub.com/workspaces/team-pesto-6127680175876a0014fc5657/issues/gh/weaveworks/weave-gitops/4057)
=> Fix hr related message appearing on ks

Makefile, yarn.lock
Run `make ui-audit-fix` to fix audit errors.
=> Fix UI audit

.github/workflows/pr.yaml
[Previous fix](https://github.com/weaveworks/weave-gitops/pull/4083) didn't seem to work.
https://github.com/orgs/community/discussions/25217
=> fix: Do not run for forks

.github/workflows/release.yaml
Closes #4076 
To ensure that the pull request body is shown in the Slack notification we sent after a new release is created.
=> fix: Partially revert #4046

website/docusaurus.config.js
These redirects are for pages linked from https://www.weave.works/docs/.
=> Add some more redirects

website/docs/enterprise/getting-started/install-enterprise-cli.mdx
Some more suggestions after second review
=> Add cli docs eneko2

.goreleaser.yml
Removed flag from `.goreleaser.yml`
The file was removed as part of https://github.com/weaveworks/weave-gitops/pull/4116
N/A
N/A
=> fix: Remove flag as source file has been deleted

.github/workflows/docs.yaml
Simplified CI workflow that deploys user guide docs.
Some of the commands were not used/necessary.
=> ci: Simplify docs creation

.github/dependabot.yml
- Added dependabot support for github actions
- To avoid vulnerable actions being run on CI
- Followed existing code and [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions)
=> added dependabot support for github actions

website/docs/enterprise/getting-started/releases-enterprise.mdx, website/versioned_docs/version-0.36.0/enterprise/getting-started/releases-enterprise.mdx
Closes https://github.com/weaveworks/weave-gitops-enterprise/issues/3645
Added missing release notes. 
Updated release notes that were not updated during the release cycle
=> add wge release notes for v0.32 to v0.3.60

.goreleaser.brew.yml
Part: https://github.com/weaveworks/homebrew-tap/issues/36
Updated tap install to address `TypeError: no implicit conversion of Hash into String`
This change is based on the PR https://github.com/weaveworks/homebrew-tap/pull/37/files 
Otherwise, the error in the ticket would appear for latest brew versions
Change validated in this PR https://github.com/weaveworks/homebrew-tap/pull/37/files 
No
No
=> update homebrew configuration for ruby 3

LICENSE
This is simply a relicensing to ASL2.
=> Update LICENSE to Apache 2

.github/workflows/docs.yaml, .github/workflows/prepare-release.yaml
=> charles | temporarily disable docs until algolia key issue is addressed

Makefile, core/clustersmngr/factory_test.go, core/server/objects_test.go
I managed to fix (or "fix") a couple of unit test, but I don't understand what we need to do now. I have a hunch it might have something to do with the proto adapters, but not sure.
/cc @casibbald
=> Fix some unit test failing with Flux 2.3

.github/workflows/ossf.yaml
=> renable osf

pkg/run/install/install_dashboard.go, pkg/run/install/install_dashboard_test.go
This fixes the tests commented out in https://github.com/weaveworks/weave-gitops/pull/4230.
/cc @casibbald
=> fix: GetInstalledDashboard should support nil Chart

README.md
=> Update badge links for new free FOSSA account

README.md
=> Add go report

package.json, yarn.lock
=> Adding parcel and commander

.github/workflows/docs.yaml, .github/workflows/pr.yaml, .github/workflows/prepare-release.yaml, website/docusaurus.config.js, website/package-lock.json, website/yarn.lock
=> Make docs great again

.github/workflows/docs.yaml
=> Update to use github pages

.github/workflows/docs.yaml
=> test removal of extra slash

.github/workflows/docs.yaml
=> Fix extra slash

yarn.lock
Dependency resolution in `yarn.lock`
`commander` is overridden i `package.json`. Don't think it should be changed in the `dependencies` of `d3-dsv` as well, as the change is reverted on `yarn install`
So that next change to `yarn.lock` won't have this unrelated change in it
Ran `yarn install`
=> chore: run yarn install to update yarn.lock

package.json, yarn.lock
Remove dependencies not needed in main package.json. Added in https://github.com/weaveworks/weave-gitops/pull/4251  
If added, I think it should be in `resolutions` of `website/package.json`, as that is where they are used.
Suggest to not add them to `resolutions` now, as many of the dependencies will be updated in https://github.com/weaveworks/weave-gitops/pull/4270 anyways, and might then not need `resolutions` at all.
=> chore: cleanup package.json

.github/workflows/docs.yaml
Closes
Quoting on workflow confitional
=> fix workflow

website/yarn.lock
Fixes bad lock file from https://github.com/weaveworks/weave-gitops/pull/4270
In the previous PR, I decided to change the react versions to `.0.0`, as that is what is bootstrapped by the docusaurus init script, and forgot to run `yarn install` again.
=> chore: fix yarn lock file

.github/workflows/docs.yaml, website/docs/intro-weave-gitops.mdx
=> build from branch

.github/workflows/docs.yaml
Closes
fix last pinned dependency alert
=> chore: address pinned dependencies error

.github/workflows/pr.yaml
Closes
Use the cache feature provided by [actions/setup-node](https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data).
Less grumpy CI details to maintain.
=> ci: simplify Node.js cache

.github/workflows/pr.yaml
Closes
Corrects the order of steps in the Upload Binary CI job.
The setup Go step is now obtaining the Go version from go.mod file, which requires the file to be present when attempting to setup Go.
=> ci: correct order of Upload Binary job steps

website/package.json, website/yarn.lock
➤ YN0002: │ weave-gitops-docs@workspace:. doesn't provide @mdx-js/react (p3b880), requested by @docusaurus/core.
➤ YN0002: │ weave-gitops-docs@workspace:. doesn't provide @types/react (pf4791), requested by @docusaurus/core and other dependencies.
Installed peer deps warned missing by yarn
=> chore(deps): install website peer deps

website/package.json, website/yarn.lock
> If you have installed @docusaurus/preset-classic, you don't need to install it as a dependency.
https://docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia
Remvoes @docusaurus/theme-search-algolia as @docusaurus/preset-classic is installed
Avoid having to maintain a separate version of this dep
=> chore(deps): rm redundant @docusaurus/theme-search-algolia

website/package.json, website/yarn.lock
Built in dev mode and tested player
=> chore(deps): upgrade react player

website/package.json, website/yarn.lock
Seems to not be in use, and is included by @docusaurus/bundler anyways.
No need to maintain this dep separately from docusaurus
=> chore(deps): remove unused url-loader

website/docusaurus.config.js
Formatted the file with prettier
To avoid other changes causing unnecessary fmt diffs
=> chore: format docusaurus config

.github/workflows/docs.yaml
Closes
GH seems to provide a maximum retention of 90 days for this project now. So no point asking for 365 days.
=> ci: don't ask for longer retention that GH provides

website/babel.config.js
> Warning:  Docusaurus site warnings:
> - Your site is using the SWC js loader. You can safely remove the Babel config file at `babel.config.js`.
=> chore: remove unused website babel config

website/package.json, website/yarn.lock
Included in https://github.com/weaveworks/weave-gitops/pull/3348/files
Cannot see that it's used, and it's deprecated https://www.npmjs.com/package/trim
=> chore(deps): remove unused and deprecated trim

.github/dependabot.yml
Closes
Simplifies the Dependabot configuration to just include GHA upgrades.
For some reason, Dependabot is failing, and I want to attempt this cleanup to see if it suddenly starts working.
=> ci: cleanup dependabot.yml to see if it starts working

Makefile
Closes
Bump envtest to the latest release https://github.com/kubernetes-sigs/controller-tools/releases/tag/envtest-v1.32.0.
Always good to ensure we are compatible with the latest K8s versions.
=> test(deps): bump envtest to 1.32.0

.golangci.yaml, core/server/fluxruntime_test.go
Closes
Enable the `tenv` linter.
More compact and better quality test code.
=> chore: enable tenv linter

.golangci.yaml, cmd/gitops/get/config/cmd.go, pkg/config/config.go, pkg/logger/s3_log_writer.go, pkg/server/auth/server.go, pkg/server/auth/server_test.go
Closes
Enable the `errchkjson` linter (again). The `errcheck` is already configured to match is companion.
As can be seen in the modified code, this linter avoids extra error handling for errors that will never happen.
=> chore: enable errchkjson linter

.github/workflows/chart.yaml, .github/workflows/docs.yaml, .github/workflows/ossf.yaml, .github/workflows/pr.yaml, .github/workflows/prepare-release.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .github/workflows/trigger.yaml, .github/workflows/upgrade-flux.yaml
Closes
Upgrading all GHA to their latest releases in an attempt to make Dependabot workflow great again.
It might have been the Flux action that made it fail, but let's see how it goes.
Some are upgraded to new major versions, so we might need to fix eventual issues in follow-up PRs.
To enable Dependabot upgrades.
=> ci: renovate GHA versions manually

ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
Updates snapshots to the year 2025
=> chore: generate new snapshots for 2025

.github/dependabot.yml
Closes
Enable Dependabot to suggest upgrades for all relevant packages. Start with a daily schedule, but consider a less frequent schedule if it creates too much noise.
Easier to ensure our dependencies are up-to-date.
=> ci: configure Dependabot for all relevant upgrades

.github/workflows/scan.yaml
Closes
Don't run FOSSA scan action on pull requests.
Hopefully mending all the currently failing pull requests from Dependabot.
=> ci: don't run FOSSA actions for pull requests

website/package.json, website/yarn.lock
Closes
bump react, react-dom to 19.0.0. Dependabot fails to do both at the same time
=> bump react react-dom to 19.0.0 in /website

.github/workflows/docs.yaml
Closes
return workflow rule for docs publish/deploy
=> Taking out a bad change on docs rule

website/package.json, website/yarn.lock
Reverts weaveworks/weave-gitops#4353
=> Revert "bump react react-dom to 19.0.0 in /website"

CODE_OF_CONDUCT.md, website/src/pages/feedback-and-telemetry/index.md, website/versioned_docs/version-0.16.0/feedback-and-telemetry.md
Closes
updated links for support
=> Update support link

README.md
Closes
Publish OpenSSF Scorecard badge.
Badges are nice to show that we care for quality, and we already publish our OpenSSF Scorecard results.
=> chore: add OpenSSF Scorecard badge

README.md
Closes
Remove the following from the bottom of the Readme
Comment out/Remove Fossa report as it no longer updates due to paid plan expiry.
=> Remove report as it no longer updates due to paid plan expiry

.github/dependabot.yml
Closes
Attempt to create grouped Dependabot upgrade PRs for react dependencies.
Different react must typically be upgraded simultaneously.
=> ci: react Dependabot group

.github/workflows/prepare-release.yaml
Closes
Update release test to correctly pick tests
=> Fix: release test snapshots

core/server/types/objects.go
Closes
Migrate away from the deprecated `NewSerializer` function.
Avoid using deprecated code.
=> refactor: migrate calls to deprecated NewSerializer

.github/dependabot.yml
Closes
Correct invalid YAML syntax. 😊 
=> ci(deps): mend corrupt Dependabot config

.github/dependabot.yml
Closes
Raise Dependabot open-pull-requests-limit for frontend deps. Temporarily?
Some of the dependency upgrades seems interconnected, and I would like to see all.
=> ci(deps): raise open-pull-requests-limit for Dependabot frontend deps

.github/dependabot.yml
Closes
Add some more Dependabot groups to group related dependencies with same/similar release cycle.
Smoother Dependabot upgrades and less PRs from Dependabot.
=> ci(deps): add more Dependabot groups

.github/dependabot.yml
Closes
New Dependabot group for parcel dependencies.
Smoother Dependabot upgrades.
=> ci(deps): new Dependabot group for parcel deps

.devcontainer/devcontainer.json
Closes
Add initial devcontainer container configuration with some of the tools/version required to work on Weave GitOps.
Because I sit on a dumb enterprise network, I am unable to work with frontend. I just tried the default devcontainer, and while not perfect, I can do stuff with it.
=> chore: initial devcontainer configuration

tsconfig.json
Closes
Bump typescript config target to `ES2018`.
To unblock Typescript upgrade, ref. https://github.com/weaveworks/weave-gitops/pull/4394.
=> fix: bump ts config target to ES2018

.github/dependabot.yml
Closes
Create new go Dependabot group for `golang.org/x/*` dependencies. Seems to have a similar release cycle.
Smoother Dependabot upgrade PRs.
=> ci: go Dependabot group for golang.org/x/* deps

.github/workflows/repostats.yaml
Closes
Avoid running the repostats scheduled job in forks.
Similar issue as described in https://github.com/weaveworks/weave-gitops/pull/4439.
=> ci: don't run repostats schedule job in forks

.github/workflows/pr.yaml
Closes
Correcting a bug in https://github.com/weaveworks/weave-gitops/pull/4483. Also remove the `rekor-url` flag, which has the default value.
Build is currently failing on main.
=> ci: fix typo in cosign commands

.github/workflows/build-push-image.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml
Closes
This deduplicates the image build jobs for CI/PR and release.
Duplication is something we should try to avoid, but in this case it's even more important: I want to add image signing to the (existing) release workflow.
=> ci: reusable workflow for build-push image

.github/dependabot.yml
Closes
Dependabot ignore changes to `react-router-dom`
`react-router-dom` is removed in `react-router >= 7` and requires a more extensive rework to upgrade to `react-router`
=> Remove react-router-dom from dependencies and mark it ignored

.github/workflows/release.yaml
Closes
In-line the image env variables in the release workflow. Fix-up after https://github.com/weaveworks/weave-gitops/pull/4491.
It seems like the `env` context is not supported for `with`. Failing workflow: https://github.com/weaveworks/weave-gitops/actions/runs/12733935255/workflow
=> ci(release): in-line ENVs as not supported in with

.github/workflows/build-push-image.yaml
Closes
Debug metadata output from docker/build-push-action, ref. https://github.com/docker/build-push-action?tab=readme-ov-file#outputs
I want to see if image signing workflow can be simplified even more.
=> ci: debug docker/build-push-action metadata output

.github/workflows/build-push-image.yaml
Closes
Remove the image sign debug info, as it seems unnecessary.
Somehow the latest debug broke the workflow: https://github.com/weaveworks/weave-gitops/actions/runs/12745382062/job/35522827203
=> ci: remove image sign debug info

.github/dependabot.yml
Closes
New Dependabot group for kustomize Go dependencies.
We seems to have more than one dependency to kustomize, and usually coordinated releases must be upgraded in sync.
=> ci(dependabot): new group for kustomize deps

package.json, ui/components/DagGraph.tsx, yarn.lock
Reverts weaveworks/weave-gitops#4525
=> Revert "Revert "build(deps): Bump d3-dag from 0.11.5 to 1.1.0""

.github/workflows/nightly.yaml
Closes
Disable playwright till purne down and clean up of enterprise tests
=> ci: disable playwright till prunedown and cleanup

.github/dependabot.yml
Closes
New Dependabot Go group for k8s deps.
We just got a k8s patch release and we have dependencies to multiple of them.
=> ci(dependabot): new group for k8s deps

pkg/http/server_test.go
=> fix: clashing httptest ports

tools/dev-resources/image-policy/podinfo-image-update-automation.yaml
Closes
correct policy branch, to make way for deployment of the same with violations in order to show updates
=> fix: correct automation branch

.github/dependabot.yml
Closes
Tune the correct react Dependabot group.
This was the intent in https://github.com/weaveworks/weave-gitops/pull/4559, but I did a mistake and modified only the docs/website group. 😒 
=> ci(dependabot): really fix react group

.github/workflows/dependabot-automerge.yaml
Closes
Add new workflow for Dependabot auto-merge. Suggesting auto-merge for minor (and lower) version bumps.
I am pretty sure this won't work on first attempt. We probably need to adjust the project settings.
Avoid manual approve/merge of "trivial" dependency upgrades. Required checks are enabled and we can always revert PRs that breaks anything.
=> ci(dependabot): enable auto-merge for upgrades

eslint.config.mjs, ui/components/DependenciesView.tsx
Closes
Fix violations an enable the recommended rule.
Try adhere to recommended lint configuration.
=> chore(lint): fix react/no-unescaped-entities violations

.golangci.yaml, core/clustersmngr/factory_caches_test.go, core/clustersmngr/suite_test.go, core/logger/logger_test.go, core/nsaccess/nsaccess_test.go, core/server/crd_test.go, core/server/events_test.go, core/server/fluxruntime_test.go, core/server/inventory_test.go, core/server/objects_test.go, core/server/policies_test.go, core/server/policy_violations_test.go, core/server/suite_test.go, core/server/suspend_test.go, core/server/sync_test.go, core/server/version_test.go, pkg/server/auth/jwt_test.go, pkg/server/auth/server_test.go
Closes
Enable useful linter currently disabled.
Improve quality and more automated code reviews.
=> ci(lint): enable thelper linter

.golangci.yaml, core/server/suspend_test.go, pkg/git/gogit_test.go, pkg/gitproviders/dryrun_test.go, pkg/gitproviders/repo_url.go, pkg/kube/kubehttp.go
Closes
Enable useful linter currently disabled.
Improve quality and more automated code reviews.
=> ci(lint): enable misspell linter

.golangci.yaml, core/clustersmngr/client.go, core/fluxsync/adapters.go, core/server/policies.go, core/server/policy_violations.go, core/server/session_logs.go, pkg/sourceignore/sourceignore.go
Closes
Enable useful linter currently disabled.
Improve quality and more automated code reviews.
=> ci(lint): enable prealloc linter

.golangci.yaml, core/server/session_logs_test.go
Closes
Enable useful linter currently disabled.
Improve quality and more automated code reviews.
=> ci(lint): enable containedctx linter

go.mod, go.sum, pkg/utils/common.go, pkg/utils/common_test.go
Closes
Upgrade github.com/tomwright/dasel to v2, which is the latest/maintained version of dasel. Also fixing a bug - which can be seen in the single changed line in the test. From the description of the test, I am pretty confident that this is actually a bugfix.
This upgrade represents a pretty significant cleanup of our Go dependencies. And as always, we should try to keep up with releases of our dependencies.
=> build(deps): bump github.com/tomwright/dasel to v2

charts/gitops-server/templates/deployment.yaml, charts/gitops-server/templates/ingress.yaml, charts/gitops-server/templates/network-policy.yaml, charts/gitops-server/templates/oidc-auth-secret.yaml, charts/gitops-server/templates/service.yaml, charts/gitops-server/templates/serviceaccount.yaml
Closes
Add namespaces to helm chart 
To fully conform with helm chart spec
=> fix: add namespaces to helmchart

.github/dependabot.yml
Closes
New Dependabot group for the babel dependencies wth coordinated releases.
Coordinate version bumps, which are often interconnected.
=> ci(dependabot): new babel group

.github/dependabot.yml
Closes
New Dependabot group for coordinated Google grpc releases.
Less PRs from Dependabot, while still tracking concrete bumps.
=> ci(dependabot): new golang-grpc group

.github/workflows/release.yaml
Closes
Replace removed `rm-dist` flag with the replacement: `clean`.
Release workflow is failing and https://goreleaser.com/deprecations/#-rm-dist.
=> ci(release): replace removed goreleaser flag

.github/workflows/prepare-release.yaml
Closes
But Flux version in the release PR draft.
Avoid manual and error-prone changes to the draft.
=> ci(release): bump Flux compatibility

gitops-server.dockerfile
Closes
Remove Docker caching parcel files.
Our attempt to cut a release was failing on something which seems related to this: https://github.com/weaveworks/weave-gitops/actions/runs/12977927908/job/36192352559. I think we should remove this optimization to hopefully make it work.
=> ci(release): remove parcel cache from Dockerfile

package.json, yarn.lock
Closes
Removed the dependency to the apparently unused (and abandoned) library https://www.npmjs.com/package/@testing-library/react-hooks. There is a note about the code migrated to other packages:
I saw https://github.com/weaveworks/weave-gitops/pull/4624, and decided to look closer into this.
=> chore(fe): remove dependency to unused @testing-library/react-hooks

.github/workflows/nightly.yaml
Closes
Use Flux GHA to install Flux CLI in nightly workflow.
The current install is marked as non-secure by our security scanner.
=> ci: better Flux CLI install in nightly workflow

.github/workflows/pr.yaml
Closes
New job in PR workflow including https://github.com/actions/dependency-review-action.
Will allow detection of vulnerable dependencies, and could potentially be used to check licenses. Inspired by a StepSecurity analyze of our repo.
=> ci: add dependency review job to PR workflow

.github/dependabot.yml
Closes
Enable Dependabot updates for pip (Python) dependencies.
I am planning to reconfigure the other updates in a follow-up PR - following a similar pattern.
Keep Playwright test dependencies up-to-date.
=> ci(dependabot): enable weekly job for pip dependencies

.yarnrc.yml
Closes #4672 
Added additional supported architecture for arm64
=> chore: Add Arm64 build support for Parcel

.goreleaser.yml, gitops-server.dockerfile, package.json
=> chore: fix issue with watcher building on arm64

package.json, ui/components/__tests__/__snapshots__/Footer.test.tsx.snap, website/docs/references/helm-reference.md
Reverts weaveworks/weave-gitops#4674
=> Revert "Updates for 0.39.0-rc.1"

.github/workflows/release.yaml
=> ci: fix go releaser args

package.json, ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
=> chore: reset incomplete release changes

.goreleaser.yml
=> ci: fix goreleaser arch template

CONTRIBUTING.md
=> docs: correct license reference in contrib docs

package.json, yarn.lock
=> chore: remove unused @mui/lab dependency

ui/lib/utils.ts
Closes #4688 
Semver display code
Version does not show correctly in RC's
=> chore: fix version tag in UI

.github/workflows/lint-pr.yaml, CONTRIBUTING.md, README.md
Closes
The main change in this PR is to introduce a new workflow to enforce pull requests with a PR title following the [Conventional Commits specification](https://conventionalcommits.org).
Also :
- Updated the contribution documentation to address this new requirement
- Added a new badge to the repository to inform users that we use Conventional Commits.
I want to introduce https://github.com/googleapis/release-please-action for better release automation, including automation of Helm chart releases. We use this (including the PR lint workflow) in all the projects I work on for my company, and I like it a lot! It will allow us to cut releases when we want. The automation will create a PR whenever there are any unreleased user-facing changes …
=> ci: enforce Conventional Commits PRs

.github/workflows/lint-pr.yaml
Closes
Changes enforced Conventional Commits subject pattern from initial lowercase to uppercase.
While Conventional Commits specification doesn't mandate the casing in commit subject, it recommends consistency. I was in doubt when adding this, and the latest PRs from Depedabot proves that I did a bad choice.
=> ci(release): change pull request subject pattern to init caps

release-please-config.json
Closes
Adjust release-please config to get it bootstrapped more correctly.
I was not too happy with https://github.com/weaveworks/weave-gitops/pull/4824, and I see various errors in the workflow logs.
=> ci(release): Better release-please bootstrap config

release-please-config.json
Closes
Configure release-please to search for the correct tags. This is documented here: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#subsequent-versions
From the [release-please workflow log](https://github.com/weaveworks/weave-gitops/actions/runs/13883295331/job/38844674755), we can read `looking for tagName: weave-gitops-v0.39.0-rc.2`. This is not the tag format we use.
=> ci(release): release-please should look for correct tags

package.json, ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
Closes
Bump occurrences of `0.39.0-rc.1` to `0.39.0-rc.2` (our latest release). Somehow these weren't updated on the latest release.
I discovered this when working on release-please releases. These coordinates must be in sync.
=> chore: fix references not updated on latest release

release-please-config.json
Closes
Instruct release-please of the next release as the prerelease strategy in release-please does not seem to support our use case, ref. https://github.com/weaveworks/weave-gitops/pull/4834
We want to cut new release candidates until we know that things are working.
=> ci(release): set release-please release-as for now

release-please-config.json
Closes
Try changing release-please configuration to create a shared release PR.
Separate pull requests do not work, since the Node and Helm package names are the same. It seems like the Helm package "wins", ref. https://github.com/weaveworks/weave-gitops/pull/4868. This is cause by a shortcoming in release-please with an ancient issue: https://github.com/googleapis/release-please/issues/997.
=> ci(release): try combined release pull requests

README.md, charts/gitops-server/Chart.yaml, charts/gitops-server/values.yaml, release-please-config.json
Closes
Further improvement of the release-please configuration.
To get a proper Helm chart release, we also need to bump the `appVersion` property in `Chart.yaml`.
=> chore(release): prepare release-please configuration for RC

.github/workflows/scan.yaml
Closes
This adds https://github.com/actions/dependency-review-action as a light alternative to FOSSA for pull requests.
To hopefully get quality PRs.
=> ci: add dependency review scanning to pull requests

.github/dependabot.yml
Closes
This is a minor adjustment to the Dependabot configuration allowing Dependabot to suggest upgrades to the website Dockerfile.
I had a look if StepSecurity could help us harden the project, and this was a nice find!
=> ci: make Dependabot suggest upgrades for website images

.github/workflows/release-please.yaml
Closes
Add missing required workflow job field.
Bug introduced in https://github.com/weaveworks/weave-gitops/pull/4917.
=> ci: add missing required runs-on workflow job field

website/docusaurus.config.js
Fixes #5012
-->
Closes
Disabled Docusaurus 4 future feature flags
Failing builds due to v4 early feature flags
=> Disable docusauraus v4 flags

.github/dependabot.yml
Closes
Add new Depedabot group for jest dependencies which seems to have the same release schedule.
Fewer Dependabot PRs handling cross-projecr changes.
=> ci: new dependabot group for jest dependencies
