.github/workflows/chart.yaml

My recent change to only publish the chart when the version is changed was broken, as it used a pull request only event to determine the old version. So in practice, when discovering the old version it just ran `git checkout` which leaves git at the most recent commit, and thus the check if the version had changed always returned false when PRs are merged.
Because of this problem, I put workflow_dispatch in there as well, as I'd like to force-publish the most recent chart.

Fix chart publishing

---

.github/workflows/pr.yaml

This publishes a package each time we hit merge, so it's easier to try out unreleased frontend changes. It's pushed to a
`-main` package name to distinguish it from the regular repo.

Publish NPM package each merge

---

cmd/gitops/beta/run/cmd.go
pkg/run/install_bucket_source_and_ks.go
pkg/run/install_bucket_source_and_ks_test.go
pkg/run/install_dashboard.go
pkg/run/install_flux.go
pkg/run/utils.go

- Removed unused function `WatchAndSync`.
- Moved some functions from  `gitops/beta/run/cmd.go` to appropriate files. This will make `cmd.go` file 140 lines shorter. It was getting huge.
- Also moved several functions from `pkg/run/utils.go` to corresponding files (depending on whether they are related to flux install, devbucket, or dashboard install).
Notes:
- Now `pkg/run/utils.go` contains functions which are used by both devbucket- and dashboard-related bit of code or the command itself. Only `isPodStatusConditionPresentAndEqual` is used by the dashboard only, but it's very generic.
If you would like to get rid of `pkg/run/utils` completely, please let me know which location is more suitable for the remaining utility functions.

Move some functions from `gitops/beta/run/cmd` and `pkg/run/utils` to more appropriate files

---

charts/gitops-server/templates/admin-user-roles.yaml
charts/gitops-server/templates/deployment.yaml
charts/gitops-server/values.yaml
core/server/sources.go
ui/components/SourceDetail.tsx

This fixes a whole bunch of errors:
* Adds question marks to the source detail page. I reset my cluster and was swamped in errors, and went through them all.
* Fix the rendering of errors on the source detail page. This was broken by a recent commit that got the parenthesis backwards.
* Fix merge error in permissions for OCI repositories - they would only have worked if gitops was installed inside the flux-system namespace.
* Add a feature flag that is turned off by default, that unless enabled makes the list OCI repositories endpoint just return nothing. This stops it returning errors when flux is < 0.32 - since this is not released yet, I've opted to make it a manual opt in/out, in case something changes that would break this completely.

Make OCI repositories opt-in, fix OCI repository permissions, fix rendering errors for sources

---

website/docs/getting-started.mdx
website/docs/installation.mdx

As this is turned off by default right now (to avoid errors), it needs
to be very visible how to turn it on.

doc: Add oci repository feature flags to to manual

---

website/docusaurus.config.js

Algolia has indexed our whole docs website twice, and is returning all
search results twice (#2561). I suspect this is related to how the
generated source code contains an incorrect double-slash:
```
<link data-rh="true" rel="canonical" href="https://docs.gitops.weave.works//docs/installation/">
```
This change appears to make the double-slash go away but still leave
links working, which should fix the problem. Maybe.

website: Remove extra slash from website URLs

---

.github/changelog/changelog_configuration.json
.github/workflows/prepare-release.yaml

The changelog generation doesn't use the local git repository to find
the final tag, it uses the github API, so setting a tag in the local
repo doesn't help. Explicitly specify the toTag to be the current
commit instead.
However, doing that breaks the ignorePrereleases option so that the
release changelog only contains the changes since the last RC. Fix
that by adding a regex to filter out prereleases.

Fix the changelog generation

---

cmd/gitops/get/bcrypt/cmd.go

Fixes #2597
Fix detection of data being piped into `gitops get bcrypt-hash` on linux systems.
Fixes an issue where the `gitops get bcrypt-hash` call doesn't properly read from stdin on linux machines because the size property of the stdin file is 0.
Instead of checking the size of stdin, check the mode on stdin to determine whether to read from stdin or get user input.
Locally tested on ubuntu.
Stdin from pipe:
```
$2a$10$n3Waub.Sz.1BKao/8226x.Vsd3nayfeGKeQmjGiKpnPWGf37FX4tm
```
Getting user input:
```
Enter Password: 
$2a$10$K9PNrYXxRg/ZyMvHcm/0Uer45R3WPoCujiEb0Pwb04iUeyxb/V./e
```
Redirecting stdin from a file:
```
$2a$10$HLoQ0F/gzvf6Bdqhw1H69.2ZPfSAbStr3xTSIlT2RLbHOytRdNG.W
```
Here string:
```
$2a$10$aPUM5C.E.vO4ckJLoW5BMuoJgjrCa0VZCKfugi/VWxBX7KCMwWH.2
```

Fix `get bycrypt-hash` reading of stdin

---

.github/workflows/pr.yaml

This is one part of #2216, so we don't miss things being broken.

Report broken main branch in #team-denim

---

ui/components/ReconciliationGraph.tsx

Closes #2506 
Made all nodes (with or without children) have the same "horizontal separation".
The fix is based on:
https://github.com/d3/d3-hierarchy/blob/v3.1.2/README.md#tree_separation
```
tree.separation([separation])
If separation is specified, sets the separation accessor to the specified function and returns this tree layout. If separation is not specified, returns the current separation accessor, which defaults to:
function separation(a, b) {
return a.parent == b.parent ? 1 : 2;
}
```
By default, d3.js separates nodes with children into "clusters". Instead of the default horizontal separation, we just return 1 for all nodes, so the horizontal distance between neighboring nodes will be the same.
Before:
After:
During testing, a different issue was discovered: #2614

Fix spacing of nodes with child nodes

---

core/server/suspend.go
core/server/sync.go

When we patch an object (via sync or suspend), we now log an info
level message (thus enabled by default) that describes the action
(suspend, resume or sync), with structured fields containing the kind,
namespace and name of the resource, as well as the user ID (e.g. oidc
email, or just the local username) that performed the action.
This means that the message field itself is static and easy to search
for, and a specific object is easy to index and filter out.
For this "searching for" reason, I've chosen to implement "sync with
source" as 2 messages - there should be an entry for each object that
we patch.
This resolves #2436.

Log when a resource is suspended or synced

---

core/clustersmngr/factory_caches.go
core/clustersmngr/factory_caches_test.go

Part of: https://github.com/weaveworks/weave-gitops-enterprise/issues/1282
Updated Set() method to return added and removed clusters.
To allow `GetProfiles` and `GetProfileValues` to work with any HelmRepository CR and on any cluster, in order to allow a user to select a Chart from a HelmRepository on a leaf cluster.
Added unit tests.

Return Added and Removed Clusters in Clusters.Set()

---

ui/components/BucketDetail.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/OCIRepositoryDetail.tsx
ui/components/SourceDetail.tsx
ui/hooks/objects.ts
ui/lib/__tests__/utils.test.ts
ui/lib/objects.ts
ui/lib/utils.ts
ui/pages/v2/BucketDetail.tsx
ui/pages/v2/GitRepositoryDetail.tsx
ui/pages/v2/HelmChartDetail.tsx
ui/pages/v2/HelmRepositoryDetail.tsx
ui/pages/v2/OCIRepositoryPage.tsx

We always try to resolve HTTP requests at the page, so that we
can wrap them in the Page component, and that will handle displaying
loading state and errors so we don't have to.
We do this for automation details, and then we pass in the info prop
as a map of label and value.
However, sources was different - instead of an object and a map of
info, we passed down information about the object we wanted, and a
bunch of callbacks.
This makes source pages behave more like automation
pages, and like the table views.
While I'm at it, set an empty object of the right type as initial
data, and that way we don't need question marks.

ui: Make source details do http requests from the top, too

---

core/clustersmngr/client_test.go
core/clustersmngr/clustersmngr.go
core/clustersmngr/clustersmngr_test.go
core/server/suite_test.go
pkg/server/auth/auth.go
pkg/server/auth/auth_test.go

Raise an error if an empty `UserPrincipal` is passed to `ClientConfigWithUser`. 
Most callers of `ClientConfigWithUser` check that the user principal they're about to pass isn't `nil` but this doesn't protect against the case when both the `Token` and `ID` are empty strings. If this happens then any calls to the Kubernetes API are made with the application's service account rather than the (incorrectly configured) user.
This is (unlikely) to pose a significant risk as other layers ensure that a principal is set correctly but this provides strength in depth against potential miss-configuration or future extensions.
A check for empty strings.
Extended the unit tests and …

Raise an error if an empty `UserPrincipal` is passed to `ClientConfigWithUser`

---

.github/workflows/release.yaml

I fixed this for the CLI binary in d9a07b437, and that worked - but I
didn't fix it for e.g. docker images, so now the released version of
the images are tagged with the wrong commit, even though they're built
from an identical commit to the release.
Check out the right one everywhere.

Make the whole release flow use the release commit

---

cmd/gitops-server/cmd/cmd.go

Before:
```
{"level":"info","ts":1660831632.8747694,"logger":"gitops","caller":"cmd/cmd.go:325","msg":"Using TLS from %q and %q","/home/max/dev/local-ca/ca.pem":"/home/max/dev/local-ca/ca.key"}
```
After:
```
{"level":"info","ts":1660831799.359499,"logger":"gitops","caller":"cmd/cmd.go:325","msg":"Using TLS","cert_file":"/home/max/dev/local-ca/ca.pem","key_file":"/home/max/dev/local-ca/ca.key"}
```

fix log message

---

.eslintrc
ui/components/PageStatus.tsx
ui/components/SourcesTable.tsx

This checked if the return value was truthy or falsy to determine
whether to show a green or a red icon - however, the return value
these days is an enum, so it's always truthy.
Use a good, ol' fashioned switch case, because we need to test every
case it can return.

ui: PageStatus should display Failed when state is bad

---

pkg/server/auth/server.go

This adds the groups scope from the user principal to the response of the /oauth2/userinfo endpoint.
Currently, the /oauth2/userinfo will return `null` as the value of the groups key. When debugging user permission issues, it's useful to have an endpoint to quickly see what groups have been mapped to the current authenticated user.
The change is minor. I have introduced a new variable called `userPrincipal` which is of type `UserPrincipal`. We can then extract the claims from the user provider into this struct to then populate the response JSON.
The changes have been validated by deploying this to a functioning Kubernetes environment with Flux installed, and testing it with a known-good OIDC provider.
I don't believe this is notable for a release.
N/A

Populate the groups field in the oauth2/userinfo API response

---

.prettierignore
cmd/gitops/beta/run/cmd.go
cmd/gitops/cmderrors/errors.go
cmd/gitops/create/cmd.go
cmd/gitops/create/dashboard/cmd.go
cmd/gitops/root/cmd.go
go.mod
pkg/run/forward_port.go
pkg/run/forward_port_test.go
pkg/run/install_dashboard.go
pkg/run/install_dashboard_test.go
pkg/run/install_dev_bucket_server.go
website/docs/getting-started.mdx

Closes #2414 
- Added the `gitops create dashboard` command and command flags.
- Reworked generation of dashboard manifests, made it more flexible and configurable.
- Reworked dashboard manifests generation tests to make them easier to maintain based on @ozamosi 's suggestion.
- Split some functions into two:` GenerateSecret` into `ReadPassword` and `GenerateSecret` (to be able to generate secret programmatically without displaying a prompt) and `InstallDashboard` into `CreateDashboardObjects` and `InstallDashboard` for easier export of manifests without dashboard installation.
- Slightly refactored passing params to dashboard functions to make it more consistent (for example with `name` always passed before the `namespace` argument).
Notes:
- How should users install Flux in case of …

CLI command for creating GitOps Dashboard

---

website/docs/installation.mdx
website/versioned_docs/version-0.9.3/installation.mdx

When updating intervals we accidentally added spec rather than interval 🤦 we will double check whether to have both spec.interval and spec.chart.interval and update again as necessary. This fixes broken docs and consolidates with what you'd get from the getting started guide.

Fix install

---

charts/gitops-server/values.yaml
tools/helm-values-dev.yaml
ui/components/AutomationsTable.tsx
ui/components/BucketDetail.tsx
ui/components/ControllersTable.tsx
ui/components/CrdsTable.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/KustomizationDetail.tsx
ui/components/OCIRepositoryDetail.tsx
ui/components/SourcesTable.tsx
ui/hooks/featureflags.ts

Closes #2456
- Added `WEAVE_GITOPS_FEATURE_CLUSTER` feature flag.
- Added hiding the Cluster column by default in WG OSS.
Notes:
- Is the name of the flag OK or should it be more generic? (Similar to what @joshri mentioned, WEAVE_GITOPS_FEATURE_ENTERPRISE ). I created a separate flag for this feature only based on an assumption that we need more granular control.
- I could also rename the flag to `WEAVE_GITOPS_FEATURE_CLUSTER` or `WEAVE_GITOPS_FEATURE_CLUSTER_INFO` if it needs to be more specific.
- The flag `WEAVE_GITOPS_FEATURE_CLUSTER` is set to `false` by default in `charts/gitops-server/values.yaml` and `tools/helm-values-dev.yaml`. Is it the expected behavior? Or should I make it `true` in one of these files?

Hide the cluster column in WG OSS

---

ui/components/__tests__/Page.test.tsx
ui/contexts/CoreClientContext.tsx
ui/contexts/__tests__/CoreClientContext.test.tsx
ui/hooks/featureflags.ts

This way they are loaded at page load time, so they're instantly
available at any page. They won't change dynamically, so they don't
need to be refetched. Contexts are "slow", but network requests are
slower.
This should fix optional frontend features jumping out after the rest
of the page has already loaded.
I've implemented this in a "funny" way - I left the API from
`useFeatureFlags` the same, so it looks a bit silly. It's failing
silently - if feature flags are broken, you get no feature flags. I
think I'd rather that happened than a crash.

Make feature flags part of context

---

ui/components/DataTable.tsx
ui/components/EventsTable.tsx

Closes #2534 
- Added support for the secondary sort.
- Added sorting the Events table by timestamp by default (earliest events first).
- Added secondary sort by timestamp to the Events table. If sorting on another column where some values are the same, values with the earlier timestamp will come first (no matter what direction the first column is sorted on).

ui: Sort events by newest first

---

cmd/gitops-server/cmd/cmd.go
core/server/server.go
package-lock.json
package.json
pkg/server/auth/init.go
pkg/server/auth/init_test.go
pkg/telemetry/telemetry.go
tools/helm-values-dev.yaml
ui/App.tsx
ui/components/Pendo.tsx

This first of all turns dev-mode into a feature flag, because I wanted it available on the front end to tag traffic from developer machines separately from end-users - anyway, we might want to flash something if someone has turned off cookie verification that they really shouldn't.
Then, it adds an inital pendo integration for extra telemetry data. It is completely, 100% turned off by default - the javascript isn't even loaded unless the user opts in.
This turns on the feature in tilt, so we can see that it actually works - but I expect we'll turn it off eventually.
The frontend integration is done using a "component" that does nothing - I don't think this is good react, and I'm happy to try something else, but I need it to run after contexts have been initialized so the feature flags are …

Initial pendo integration

---

ui/components/Layout.tsx
ui/components/UserSettings.tsx

Closes #2598
The new header background meant we could get rid of some padding above the main content and nav - here's a vid showing the result:
https://user-images.githubusercontent.com/65822698/186760572-b3962e4c-d54f-4ffd-b589-9e5b3530b378.mov
Currently on main:

Remove extra top padding

---

ui/components/GraphNode.tsx
ui/lib/theme.ts

Closes #2614
"The text-overflow property only affects content that is overflowing a block container element in its inline progression direction (not text overflowing at the bottom of a box, for example)."
I shamefully broke this rule when carrying over my old node styling to the new graph node component
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
adding spans was also convenient for the MUI tooltip which expects a component that's not customized

Fix titles overflowing graph nodes

---

core/server/helm_release.go
core/server/helm_release_test.go

Fixes #2664 (kind of, see below)
In #2664, @amulyakish and I show how a missing Helm release causes WGO to render _no_ applications.
This patch will cause the HelmRelease listing in WGO Applications to omit the missing release in its list view.
As explained in #2664 , this is an error view that should not be shown to users.
We disabled an early-return in `ListHelmReleases`, and instead send errors to the `respErrors` accumulator. Note again that this has the effect of *hiding* releases that are misconfigured. This patch, therefore, is a stop-gap in hope of a more comprehensive review of error handling, also noted in #2664 .
We included a unit test that simulates the behavior that we saw in #2664 . …

Exit more gracefully in ListHelmReleases when a HelmRelease revision is missing

---

package-lock.json
package.json
ui/contexts/CoreClientContext.tsx
ui/lib/test-utils.tsx

This fixes a few errors that were logged but didn't cause failures in the UI tests. The cause was that by making feature flags part of the context, I triggered requests to happen where they weren't allowed in tests. My solution is to make the tests initialize the parameters directly (e.g. use the `CoreContext.Provider` directly instead of the `CoreContextProvider` helper). While I was messing with types, I also removed a couple of `any`.
This also makes the UI tests fail the next time this happens, so I don't make this mistake again.

Fix error logs in UI tests

---

cmd/gitops-server/cmd/cmd.go
core/clustersmngr/clustersmngr_test.go
core/clustersmngr/factory.go
core/clustersmngr/factory_test.go
core/clustersmngr/suite_test.go
core/server/suite_test.go

- Don't try to continue updating namespaces if we cannot create a kubeconfig.
- This exposed some errors being raised when using the fake kubeclient, so refactored flowcontrol so it doesn't need to run on those tests.
To stop the occasional panic popping up and bring down the server.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103ee3420]
goroutine 91965 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x13c?)
/Users/simon/go/pkg/mod/k8s.io/client-go@v0.25.0/kubernetes/clientset.go:422 +0x20
github.com/weaveworks/weave-gitops/core/nsaccess.newAuthClient(0x0?)
/Users/simon/weave/weave-gitops/core/nsaccess/nsaccess.go:176 +0x1c …
```

Fixes occasional panic when leaf cluster unreachable

---

ui/hooks/sources.ts

It seems I tried to be more clever than I am, and as a result when
there was an error all you'd see was the header "Error" with nothing
in it.
Replace the code with less clever code, so we can now once again see
errors in sources.

Fix displaying errors with useListSources

---

go.mod
pkg/fluxexec/README.md
pkg/fluxexec/bootstrap.go
pkg/fluxexec/bootstrap_github.go
pkg/fluxexec/bootstrap_github_test.go
pkg/fluxexec/cmd.go
pkg/fluxexec/cmd_default.go
pkg/fluxexec/errors.go
pkg/fluxexec/exit_errors.go
pkg/fluxexec/fluxexec.go
pkg/fluxexec/fluxexec_suite_test.go
pkg/fluxexec/install.go
pkg/fluxexec/install_test.go
pkg/fluxexec/option_consts.go
pkg/fluxexec/options.go
pkg/fluxinstall/errors/errors.go
pkg/fluxinstall/fluxinstall_suite_test.go
pkg/fluxinstall/installer.go
pkg/fluxinstall/installer_test.go
pkg/fluxinstall/internal/httpclient/httpclient.go
pkg/fluxinstall/internal/src/src.go
pkg/fluxinstall/product.go
pkg/fluxinstall/product_test.go
pkg/fluxinstall/src/src.go

This PR implements two packages, Flux's installer and Flux's exec.
Flux installer is a package for installing a specific version of Flux. It downloads a Flux binary to a cached directory. It checksums during the process to ensure that we get the correct binary.
Flux exec is a type-safe wrapper to execute Flux binary. It has an option that implements each flag one by one.
Fixes #2610 
Fixes #2592

implement installer and exec packages for flux cli

---

charts/gitops-server/Chart.yaml
charts/gitops-server/templates/admin-user-creds.yaml
charts/gitops-server/templates/admin-user-roles.yaml
charts/gitops-server/templates/admin-user.yaml
charts/gitops-server/values.yaml

There's been a few weeks of backwards compatibility. Let's remove
that - if you're upgrading the chart, upgrade the image.
This makes no difference to any user who installs weave-gitops into
flux-system. This makes a difference to anybody who installs it in a
different namespace - the new chart will not be compatible with images
0.9.1 or before, however it will install half the number of roles,
bindings and secrets for anybody running a newer version than that.
This closes #2415.

Stop creating resources in the hard-coded flux-system namespace

---

pkg/fluxexec/bootstrap_github.go
pkg/fluxexec/bootstrap_github_test.go
pkg/fluxexec/bootstrap_gitlab.go
pkg/fluxexec/bootstrap_gitlab_test.go
pkg/fluxexec/global.go
pkg/fluxexec/options_for_global.go

This PR implements a wrapper of `bootstrap gitlab` command and also supports missing global flags in the flux-exec package.
Partially fix #2689

flux-exec: implement bootstrap gitlab and global flags

---

README.md

This fixes a weird quirk. 
The old link went to https://docs.gitops.weave.works/docs/cli-reference/gitops/index.html
Which then traps you in the past where `0.8.0` was latest.
Even navigating to a page which has the same positioning now, you're still trapped

update CLI ref link in readme

---

pkg/fluxexec/bootstrap_git.go
pkg/fluxexec/bootstrap_git_test.go
pkg/fluxexec/options.go

This PR implements a wrapper for `flux bootstrap git` command.
Partially resolves #2689 
It is blocked by #2709 to merge.

flux-exec: add wrapper for bootstrap git

---

pkg/run/install_bucket_source_and_ks.go

When we can't create a bucket or kustomization, nothing will work. Before this, when you for example specify a namespace that doesn't exist, we didn't abort, instead the output was:
```
► Checking secret dev-bucket-credentials ...
✗ Error creating secret dev-bucket-credentials: namespaces "this-doesnt-exist" not found
► Checking bucket source dev-bucket ...
✗ Error creating source dev-bucket: namespaces "this-doesnt-exist" not found
► Checking Kustomization dev-ks ...
✗ Error creating ks dev-ks: namespaces "this-doesnt-exist" not found
✔ Setup Bucket Source and Kustomization successfully
◎ Press Ctrl+C to stop GitOps Run ...
► 1 change events detected
► Refreshing bucket dev-bucket ...
Handling connection for 9000
...............
► Uploaded 152 files
► Request reconciliation of …
```

gitops run: Abort if dev-bucket resources couldn't be installed

---

cmd/gitops/beta/run/cmd.go
go.mod
go.sum
pkg/run/install_bucket_source_and_ks.go
pkg/run/install_bucket_source_and_ks_test.go

Many modern tools pick up ignore files automatically - tilt for example automatically picks up your dockerignore files, and rg & fd uses your gitignore files. I chose gitignore, because we're doing gitops, not dockerops.
This is somewhat half-arsed: it doesn't pick up gitignore files in subdirectories, and it doesn't re-read the gitignore file properly.
I assume we'll need to make this optional one day, and I assume we'll need a custom .gitopsignore one day.
However until that day, this lets me run `gitops run` in the weave-gitops repository. The reason I need something like this is that my whole checkout is several GB, which made the upload take forever, and made flux refuse to do anything with it. Just parsing `.gitignore` to remove all `node_modules` quickly makes it "kinda" work.

gitops run: Use .gitignore automatically

---

core/nsaccess/nsaccess.go
core/nsaccess/nsaccess_test.go
pkg/fluxinstall/product_test.go

Fixes allowing `cluster-admin` and other users with `*` permissions in their RBAC rules from using the UI.
Prior to this our rule engine determined that `cluster-admin` couldn't see _any_ namespaces as we didn't take `*` into account.
Adds support for evaluating `*` in the various positions it can appear (`{ "verbs": ["*"], "apiGroups": ["*"], "resources": ["*"] }`) when evaluating the rules that determine which Namespaces we think a user has access to.
Its common for people to use `cluster-admin` when debugging permissions as `cluster-admin` should be able to see everything.
Updates to our rules engine.
Only with unit tests so far.

Fixes cluster-admin seeing a completely empty UI

---

cmd/gitops/beta/run/cmd.go
pkg/run/install_bucket_source_and_ks.go
pkg/run/install_bucket_source_and_ks_test.go

If I run `gitops beta run ./this-is-a-new-directory`, I will now end up with a kustomization that turns green in flux. The same thing happens if I run `mkdir directory && gitops beta run ./directory`.
I chose to hard-code the kustomization as text instead of as an object to marshal, because I wanted to put comments in there.
This closes #2698

gitops run: Create empty kustomization if target directory doesn't exist

---

website/docs/cluster-management/getting-started.mdx

Fixes https://github.com/weaveworks/weave-gitops-enterprise/issues/1165
Add cluster kind annotations supported in getting started docs (cluster-management)

Add cluster kind annotations in getting started docs

---

.github/workflows/upgrade-flux.yaml

I got bored of trying to remember to upgrade flux every release, so
let's do it all the time.
This will run once a day (in the morning-ish EU time, because that way
when it breaks spectacularly someone's more likely to be around) and
check if there's a new flux release. If there is, it will raise a PR
that upgrades:
* The flux version we specify in our go mod dependencies
* The flux version we use when we do a `gitops beta run` bootstrap
* And, if it's a feature release, add it to the list of tested flux
releases.

Automate upgrading flux

---

.github/workflows/upgrade-flux.yaml

We need to remember to remove the old versions from go.sum, or the PR job will complain at us.

ci: Run go mod tidy when upgrading flux

---

.github/workflows/release.yaml
.goreleaser.yml
Makefile
charts/gitops-server/templates/deployment.yaml
charts/gitops-server/values.yaml
cmd/gitops/beta/run/cmd.go
website/docs/getting-started.mdx
website/docs/installation.mdx

I broke the fallback flux 0.31 feature flag the last release. I'm not going to put it back, so I updated the manual instead.
I don't want to be updating the helm chart that gitops run installs all the time, so automate that.

Automate updating the helm chart in gitops run, remove mentions of flux 0.31

---

ui/components/NotificationsTable.tsx
ui/pages/v2/Notifications.tsx

Closes #2563 
If the ListNotifications request is a success but returns no notifications, a nice little helpful message will be displayed with a link to the flux docs:

Add help message when user has no notifications

---

ui/components/AlertsTable.tsx
ui/components/__tests__/AlertsTable.test.tsx

Closes #2734 
- Event sources are now links to either the automations or sources table depending on the `kind`
- If any field values are falsy, a `li` is shown rather than a `Link`
- The asterisk wildcard character means no filters are added for that key (name and namespace are implemented, although it's unclear to me whether namespace should be in there or not based on https://github.com/fluxcd/notification-controller/issues/71 - it seems like it's not implemented but I figured I'd future proof things.)

Link to filtered tables from alert event sources

---

charts/gitops-server/templates/service.yaml
charts/gitops-server/values.yaml

add an option to explicitly specify the nodePort value when service's type is nodePort.

Add an optional choice of NodePort

---

.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/upgrade-flux.yaml
cmd/gitops-server/cmd/cmd.go
core/clustersmngr/clustersmngr.go
core/logger/logger_test.go
doc/development-process.md
pkg/api/applications/applications_grpc.pb.go
pkg/api/core/core_grpc.pb.go
pkg/fluxexec/cmd.go
pkg/fluxinstall/product.go
pkg/fluxinstall/product_test.go
pkg/git/git.go
pkg/git/gogit_test.go
pkg/gitproviders/provider.go
pkg/helm/watcher/cache/cache.go
pkg/helm/watcher/controller/helm_watcher.go
pkg/helm/watcher/server.go
pkg/kube/kubehttp_test.go
pkg/runner/runner.go
pkg/server/auth/server_test.go
pkg/services/auth/jwt.go
pkg/services/auth/types/flow.go
pkg/utils/common_test.go

The change mostly consists of a bunch of `//` having been inserted by
the upgraded `go fmt`,  and remove ioutil all over.
For compatibility's sake, I've left go.mod still supporting 1.18, but
all lint rules and the like are now using 1.19.
This resolves #2681.

Use go 1.19

---

.gitignore

Since `.DS_Store` are temporary files which keep folder configs on macOS, they sometimes get created for me in the project if I examine a project folder with Finder. So, I've finally got to add `.DS_Store` to gitignore.

Add `.DS_Store` files to `.gitignore`.

---

ui/components/DataTable.tsx

Follow up from the discussion on https://github.com/weaveworks/weave-gitops-enterprise/pull/1400 
We need the flag to hide the Search and Filters menu in Data Table as we're using this in EE in some contexts where it doesn't make sense having the options

Add flag to hide search and filters menu in DataTable

---

core/server/fluxruntime.go

We didn't filter by namespace at all. This meant that we display all automations in all namespaces that have been created by an automation that matches this automation's name - e.g., the details page for the helm release `weave-gitops` in namespace `prod` will show the resources created by the helm release `weave-gitops` in namespace `staging`. That's incorrect.
This was introduced in e8c89fb - before that we did filter by namespace. That commit claims that it's done to make sure `targetNamespace` works properly - I've created both kustomizations and helm releases with targetNamespace set, and both of them work fine.
The reason is that e8c89fb contained 2 different changes - it also stopped restricting the query to the namespace the automation was installed into, which is what actually …

Use the correct labels to get reconciled objects

---

ui/hooks/__tests__/flux.test.tsx
ui/hooks/flux.ts

Since we made the graph a tree structure internally, we've not displayed e.g. pods and replicasets on the details page, because they weren't being returned as a flat list.
This changes it to work again.
I've tried to _not_ make the implementation handle unexpected input, to act as a booby trap if the API were to change again. The test won't catch it, but it should make the details page break so bad you can't avoid spotting it.

Fix including pods in details pages

---

.github/workflows/pr.yaml
.github/workflows/release.yaml

This adds 2 places to raise 2 different PRs: one for releases, one for merges.
In each case, this will
* Check out the latest main of EE
* Merge with the latest OSS tracking branch, if there is one. The branch name is always the same, so it knows which one it is.
* This means I can push other changes to the tracking branch to make it green, and have this thing collaborate with me. 
* This will fail the pipeline and stop if there's merge conflicts. This is on purpose - this is supposed to be an assistant, so if you've taken control of the process this will stop. You can choose to rebase the PR manually, or you can close the PR - either way, this'll start back up next time.
For complicated permission reasons, this uses two different bot accounts - one for accessing EE, and a different one …

Automatically raise PRs against EE when PRs are merged, released

---

ui/components/ChipGroup.tsx
ui/components/__tests__/ChipGroup.test.tsx

Closes #2725 
a new boolean value for each chip searches for the first occurrence of the `filterSeparator` to see if it is the end of the chip string. If it is, it adds the string 'null' to the end without altering the original chip value
`const isUndefined = chip.search(filterSeparator) === chip.length - filterSeparator.length;`

Adds 'null' to undefined values in chips

---

go.mod
go.sum
pkg/gitproviders/provider_org_test.go
pkg/gitproviders/provider_user_test.go
pkg/vendorfakes/fakegitprovider/file_client.go
pkg/vendorfakes/fakegitprovider/org_repository.go
pkg/vendorfakes/fakegitprovider/user_repository.go

This gets EE and Core on the same version of `go-git-providers` (v0.9.0). This came out of trying to get both Core and EE to work in a single `go` workspace.

Upgrade go-git-providers to v0.9.0 for EE compatibility

---

pkg/run/install_dashboard.go

We changed the installation instructions to use the OCI repository instead in 0.9.2, however we were still using the HTTP repository in the source code, and that's what we ended up using for the rewritten installation instructions.
Change it to once again point at the OCI helm source.

Change dashboard installation to use OCI

---

charts/gitops-server/templates/network-policy.yaml
charts/gitops-server/values.yaml

Our default installation steps tells you to install weave-gitops in flux-system. Flux-system already contains network policies, and weave-gitops doesn't extend them to work, so if you enable network policies and follow our manual, gitops wouldn't work.
This creates enough network policies for weave gitops to work, even if your system default is to deny everything.
This creates network policies for
* Ingress access to the regular dashboard port, and optionally the metrics port - no other ingress should be required.
* Unrestricted egress access - when installed into flux-system this is redundant (flux already provides all pods in the namespace unrestricted egress), but in case it's installed into other namespaces this would make gitops work.
We could look into shrinking the egress …

helm: Add network policy

---

charts/gitops-server/values.yaml

I was browsing logs and came across warnings about pod security, which is new in 1.25. We clearly didn't pass the default `restricted` policy.
After putting the policy into place, I don't believe there's anything we do that isn't allowed by this policy, so let's run it with security turned on from now on.
To test that we pass this pod security policy, try setting `kubectl label namespace <namespace> pod-security.kubernetes.io/enforce=restricted` against the namespace where weave-gitops is running. Before this PR, that would make weave-gitops be rejected.
To test that these pod restrictions work, you shouldn't need to do anything - they're always enabled, so if it ever works, it should work both with and without pod security policy enforcement.

Set security context that passes enforce:restricted pod security

---

ui/components/HelmChartDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/lib/objects.ts

Closes #2706 
The HelmChart class has two new getters which are displayed in the details view - Version, and Revision (should this be artifact revision?)
The HelmRelease class has three - Version, Last Applied Revision, and Last Attempted Revision
Screenshots below - yes, there's a couple unfortunate bugs I found here with the overflow styling of chip group...and a chip will be created if you just press enter on the search input with no content...........issue incoming :(

Add version and revision info to Helm detail pages

---

cmd/gitops/beta/run/cmd.go
pkg/run/bootstrap_wizard.go
pkg/run/bootstrap_wizard_ui.go

Closes #2789 
As discussed with @ozamosi , exporting/returning the options as flux-exec options from the wizard is too much hassle for now. So, instead I
- exported the options (flags) as part of the result object which will also contain the git provider.
- added constants for all bootstrap wizard option keys to make creating configs from generated options easier.
Also, applying the focused style initially to all flag text inputs was changed to styling only the actual focused input (the first one) as focused.
Notes:
- Suggestions on naming objects and types are most welcome.
- Are the fields in `BootstrapWizardCmd` enough to use these options for the flux-exec bootstrap command? is anything else needed?

Export the bootstrap wizard commands as flux-exec options

---

.github/workflows/release.yaml
.goreleaser.yml
Makefile

This should also fix setting a proper tag for the current release.
This should be refactored, but I don't want to do that today. I just want releases to have a release number in the web UI.
To test, I plan to tag another RC with this in it, and check that it works.

Set more ldflags when making a release

---

ui/components/ReconciliationGraph.tsx
ui/hooks/flux.ts

I added the flattenChildren in da33a4b, where I assumed that ReconciliationGraph used getChildren directly. Which it doesn't.
flattenChildren thus did it's thing of copying the children out to the top layer so they show up in the top level of the array so they show up in the Details view. But that also created copies at the wrong depth in the graph.
This fixes it by introducing two different ways to get reconciled objects - one that is flat and one that isn't.
I'm hoping we'll change from the tree structure to the d3-dag structure one of these days, at which point it won't need to be nested and this code can be removed.
This fixes #2808

ui: Don't flatten children for the graph

---

.github/workflows/release.yaml
ui/components/Footer.tsx

Remove the event name filter for making an enterprise PR - I copy-pasted this line, but the release flow doesn't run on push, so it doesn't work.
Fix detecting in the footer whether the current release is stable - the git tag and thus the returned value from go has a leading `v`, but the npm version doesn't - just strip out 'v's and it works. I've tested this by installing the latest RC and doing `npm start` against that package.

Fix displaying release version in footer + tiny other release fix

---

ui/components/ChipGroup.tsx
ui/components/DataTable.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap

Closes #2784
- ChipGroup properly overflows without pushing CheckboxActions or the icon buttons off the screen
- A bug where a one character text search could meet the requirements for an undefined filter has been fixed
- An empty text search is not able to be submitted as a valid filter
https://user-images.githubusercontent.com/65822698/194111349-33b058ba-0dbb-40e1-9748-973ac9aae02c.mov

Fix styling bug on filter chips

---

ui/components/ReconciledObjectsTable.tsx
ui/contexts/AppContext.tsx
ui/contexts/LinkResolverContext.tsx
ui/contexts/__tests__/LinkResolverContext.test.tsx
ui/index.ts
ui/pages/OAuthCallback.tsx

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/1661
Allows us to override links in specific instances from "outside" the component tree:
```jsx
const MyComponent = () => {
const linkResolver = useLinkResolver();
return (
<a data-testid="link" href={linkResolver("")}>
My Link
</a>
);
};
//...
<LinkResolverProvider
resolver={() => {
return "/some/path";
}}
>
<MyComponent />
</LinkResolverProvider>
// ^^ This will result in `a href="/some/path" />` allowing us to add custom routing in Enterprise
```

Add LinkResolver for customized routing when running as "embedded"

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/create/dashboard/cmd.go
pkg/run/install/install_dashboard.go

A password hash is not a secret in the k8s sense, and it's a less descriptive name for a password hash than "passwordHash".
This was triggered by me seeing `GenerateSecret` and being surprised that we create k8s secrets directly.  Five times in a row.

Rename places that call the password hash "secret"

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/create/dashboard/cmd.go
pkg/run/install/install_dashboard.go
pkg/run/utils.go
pkg/run/utils_test.go
pkg/run/watch/dashboard.go
pkg/run/watch/install_bucket_source_and_ks.go
pkg/run/watch/install_bucket_source_and_ks_test.go
pkg/run/watch/install_dev_bucket_server.go

This contains 2 changes:
* It makes all of pkg/run take a context, rather than make up its own.
This allows us to do proper context handling. This PR doesn't do very good context handling, but it does sufficient context handling so that file uploads stop when hitting ctrl+c.
In other words, once you hit ctrl+c, the watcher's context will immediately abort, and thus no more transfers will happen. We might still print a warning or two about the closed context which can be improved with follow-up patches, but this means I no longer need to wait a long time for the watcher to finish before I can use the bootstrap UI.
* It moves the signal handler as early as possible. If I hit ctrl+c before everything is booted up we would before just exit, which when I'm impatient would leave me with a …

Improve gitops run context handling

---

cmd/gitops/beta/run/cmd.go

The instructions and the implementation didn't line up - we claimed yes was default, but just hitting enter caused the value to be "" which meant we didn't actually install it.
This is caused by using `IsConfirm`, where it doesn't set the default as the default value, but rather uses the error value as `nil` if the user agreed, and promptui.ErrAbort (which is `errors.New("")`) if the user didn't.

Actually default-yes for installing dashboard

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install.go
pkg/run/paths.go

I'm not sure how much of a good idea this actually is - it's definitely under-developed. However, I had a small breakdown while trying to get paths right and had to try something to sort some paths out.
Basically, we expect the git repo to be "somewhere". Inside that git repository, there's a manifests directory, which is the same as the current working directory. Inside that directory, there's a clusters directory. Somewhere, probably but not necessarily inside the manifests directory but definitely inside the git directory, there's a workload directory. All of these paths can be refered to as relative paths, absolute paths, and some of them (in flux) should be prefixed with `./`.
This bans all somethingPath variables, and puts a paths variable instead. That variable is a struct that has …

gitops run: Add silly little struct for paths

---

cmd/gitops/cmderrors/errors.go
cmd/gitops/get/bcrypt/cmd.go
cmd/gitops/get/cmd.go
cmd/gitops/get/config/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/set/cmd.go
cmd/gitops/set/config/cmd.go
pkg/config/config.go
pkg/config/config_suite_test.go
pkg/config/config_test.go

Part of #2772
Part of #2811
- Added the `gitops set`, `gitops set config`, and `gitops get config` GitOps CLI commands.
- Added the `pkg/config` package with functions to read and write the CLI configuration for Weave GitOps and generate a user ID for analytics.
- Added tests for selected (where it makes sense) functions from the `pkg/config` package.
- Tested that new commands work with WG Enterprise. Will raise a PR in the enterprise repo with the `add-gitops-set-config-and-get-config-commands` branch when I get the write access.
- Removed enterprise examples from the `gitops get` command.
Notes and questions:
- The existing options type at `github.com/weaveworks/weave-gitops/cmd/gitops/config` can be mixed up with the new `github.com/weaveworks/weave-gitops/pkg/config` package …

Add `gitops set config` and `gitops get config` GitOps CLI commands.

---

pkg/fluxexec/bootstrap_bitbucket.go
pkg/fluxexec/bootstrap_github.go
pkg/fluxexec/bootstrap_gitlab.go
pkg/fluxexec/fluxexec.go

I want the wizard to ask you for your PAT, instead of flux, so I need to set the env var before running flux-exec
This makes the bootstrap flags pass on the flux env vars. It also initializes them to an empty map instead of nil - either way, we always merge the env vars.

Make it possible to set env vars for flux exec & bootstrap

---

cmd/gitops/beta/run/cmd.go
pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/bootstrap/bootstrap_wizard_ui.go

This removes a few of the questions.
I removed the path, because I couldn't decide which path it should be - cluster, "current", or workload? If you change it, what happens to all the other ones, do they adjust "automatically" or not?
For ssh-hostname and token-auth, it just looked like extra work to figure out how it works.
For teams, I'm unsure how to test them, so leaving that as out of scope.
On the other hand, it does add a question for your PAT. Because if we don't ask for a PAT, then flux will, and I don't want it to, so now we ask for it.
Meanwhile, for defaults, I've added defaults everywhere, and removed the old isRequired because everything we ask is really required.
For defaults, I've made the code highly opportunistic - if it guesses wrong, that's OK, you can just change it, …

Change wizard's questions, defaults

---

pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/bootstrap/bootstrap_wizard_ui.go

Right now every field in the wizard is mandatory. Therefore, I've made it refuse to accept an empty field.
At some point, we'll probably have to re-introduce optional fields and isRequired, and add some kind of type validation. That day is not today.
Also change the return value to be a map instead of a list.

gitops run: Stop the wizard accepting missing values

---

cmd/gitops/beta/run/cmd.go
pkg/run/bootstrap/bootstrap.go
pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go
pkg/run/install/session.go
pkg/run/paths.go

This is a first version of gitops run bootstrap.
This only supports github, gitlab and bitbucket - I haven't implemented plain git, and I haven't implemented "write to disk instead".
This is poorly tested, with nothing automatic and little manual testing.
I added a question before bootstrapping, so that a user has a chance to understand that the shutdown finished and something else is starting. I also wrapped it in a loop, because I keep forgetting to put the correct values into place and then I have to delete my cluster and recreate it and if I'm annoyed I'm sure a user would be, too.
There is a limitation where this right now runs on _every_ run - this will be fixed by the fix for #2863.
This closes #2700.
This closes #2702.

gitops run bootstrapping

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/session.go

This PR fixes the bootstrap process after closing a session by:
- Making GitOps Run aware of bootstrapping after closing a session
- Adding `--dashboard-hashed-password`. The outer process is now responsible for asking the dashboard question and it passes the hashed password into the inner process.
Fixes #2863

fix bootstrapping process in the session mode

---

cmd/gitops/beta/run/cmd.go

This contains 2 fixes:
* Remove question mark from questions - promptui already adds them.
* Don't forward errors from promptui - error is how it signals a negative answer, and that's OK.
This addresses comments from #2871

Improve gitops run bootstrap questions

---

cmd/gitops/beta/run/cmd.go

If you manage to generate a session name that isn't lower-case - e.g., if you've not got a branch checked out - then the session can't be created.

gitops-run: Session names have to be lower-case

---

cmd/gitops/beta/run/cmd.go

The idea is, if your text editor is auto-saving backup files, then we'll still give it 10 seconds to pass on its own before retrying - it probably won't the first time, but it probably will the next few tries if no important files have changed. On the other hand, if you wrote something that was broken, then every 10 seconds we'll re-upload and re-try.
This cancels the wait when
* Files are changing
* Nothing is getting reconciled for a (short) period
We never cancel the file upload - that wouldn't help here. But we do cancel waiting for the automatic reconciliation, as flux will still try and continue in the background.
This timeout (10s) is much too aggressive, really. But, flux will still continue reconciling - as long as it occasionally get far enough to trigger the kustomization …

gitops run: Stop waiting for reconciliation sooner

---

core/clustersmngr/clustersmngrfakes/fake_clusters_manager.go
core/clustersmngr/factory.go
core/clustersmngr/factory_test.go

- Expose the known clusters in the clusters-manager API
- We already have subscribe, this allows you to query the existing clusters if you subscribe after some have been added.
- Allows us to get the `config` for clusters in case we need to make other kind of queries against them that the controller-runtime client does not support. For example `ProxyGet`ing via the client-go.
- Add a getter method to expose the internal clusters list.
- Manually

Expose known clusters from the clusters-manager

---

package-lock.json
pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/bootstrap/bootstrap_wizard_ui.go

Closes #2920 
- Wrapped CLI UI elements of the Git providers table and the main bootstrap wizard screen with a Bubble Tea viewport component. If the terminal height is insufficient, the viewport can be scrolled with up and down arrow buttons or mouse wheel.
- Removed selecting items in the Git providers table with arrow keys and enter. The git providers table is not focusable now, only the text input is.
- Slightly reworked message handling, returning Bubble Tea commands, and getting view content in the `Update` functions.
- Removed some unneeded comments.
- Ran `npm audit fix` because the JS tests were failing because of a critical vulnerability.
Notes:
- The Bubble Tea programs now run in the CLI alt screen buffer/"fullscreen" (`WithAltScreen()` Bubble Tea program option). As far as I …

Fix overlapping UI elements in bootstrap wizard if height of terminal window is insufficient

---

pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/bootstrap/bootstrap_wizard_ui.go

Followup to https://github.com/weaveworks/weave-gitops/pull/2924
Forgot to update the viewport after setting the bootstrap on submit error message (had to trigger a viewport update, for example, with an arrow button, to see the error message)
- Added updating the viewport after setting the on submit bootstrap error message.
- Also removed the unused `err` field of the Git providers view model.

Fix displaying bootstrap wizard error message

---

pkg/run/bootstrap/bootstrap_wizard.go
pkg/run/bootstrap/bootstrap_wizard_ui.go

Closes #2870 
- Added type `bootstrapWizardInput` and related types.
- Replaced text fields with checkboxes for Boolean values in the bootstrap wizard. Checkboxes can be toggles with the Space key when focused.
- Minor refactoring:
-- added local variables for input lookup (`input := inputs[i]`) for readability
-- removed unnecessary copying of styles. I previously copied it from Bubble Tea examples, so I'm not sure why `style.Copy()` was used not only when creating new styles based on old styles but also when just rendering elements with in this style. So, removed it and tested it locally, it seems to work fine without the redundant copying. If anything goes wrong, we can always put it back, but it should work fine.
Questions:
- Maybe some type names could be shorter? But they were …

Replace text inputs with checkboxes in the bootstrap wizard UI

---

core/clustersmngr/factory.go

- Some cases 30mins might be too long
- Can experiment
Allows overriding of the user-clients-cache TTL via an env var
This is a new feature and 30mins _might_ be a bit long in some cases. Its nice to have a var to tweak to debug in some circumstances.
Follows a similar pre-existing pattern to read the duration from an env var
- Tested manually

Allow overriding the user-clients-cache TTL from env var

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/cmderrors/errors.go
cmd/gitops/remove/cmd.go
cmd/gitops/remove/run/cmd.go
cmd/gitops/root/cmd.go
pkg/run/install/install_vcluster.go
pkg/run/install/session.go
pkg/run/session/list.go
pkg/run/session/remove.go

Fixes #2858 
Fixes #2907 
How to test this PR
1. Start a GitOps session, for example `gitops beta run ./manifests --port-forward port=8080:5000,resource=svc/app`
2. Wait until it starts the reconciliation loop
3. Open another terminal, and run `killall -9 gitops` to kill all `gitops` process so that the session becomes dangling.
4. `gitops remove run --namespace default --all-sessions` to remove all sessions or you can try specify the session name.

implement gitops-run metadata and the remove run command

---

cmd/gitops-server/cmd/cmd.go
core/clustersmngr/factory.go

Add the built-in controller runtime metrics (which are pretty sparse), and some manual, higher level ones.

Add more k8s related metrics

---

ui/components/ControllersTable.tsx

Closes #2963
So I'm pretty sure this was just because I hadn't refreshed my backend in Tilt....but hey - it's good to protect against undefined anyway right? The FluxRuntime api requests should probably be returning FluxObjects at this point, but that can be addressed in a separate issue

Protect against undefined labels in ControllersTable

---

cmd/gitops/beta/run/cmd.go
go.mod
go.sum
pkg/validate/validate.go

This PR adds yaml validation at an early stage before uploading YAML files to the bucket.
It validates yaml files under the `targetDir` only.
Fixes #2887 

add yaml validation

---

website/docs/cluster-management/deleting-a-cluster.mdx
website/docs/cluster-management/profiles.mdx
website/docs/enterprise/multi-tenancy.mdx
website/docs/gitops-run/overview.mdx
website/docs/gitops-templates/templates.mdx
website/docs/installation.mdx
website/docs/intro.md
website/docs/policy/commit-time-checks.mdx
website/docs/policy/releases.mdx
website/docs/policy/weave-policy-profile.mdx

Also fix some readability by altering the code language in fenced blocks (Using "console" vs "bash" when things were hilighted the wrong way).
Signed-off-by: Daniel Holbach <daniel@weave.works>

docs: More typo fixes

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/session.go
pkg/run/watch/install_bucket_source_and_ks.go
pkg/run/watch/install_dev_bucket_server.go

Fixes #2813 
- rename objects to run-dev-bucket, and run-dev-ks
- add metadata to run-dev-bucket and run-dev-ks
- rename dev-bucket server namespace to gitops-run
- add a hidden flag --x-session-name to pass down the session name to the sub-process

rename gitops run objects and add metadata

---

ui/hooks/objects.ts

Part of #2898
The request type for `ListObjects` and `convertResponse` needs to allow for strings, not just `Kind` enum members. This allows enterprise to request object types needed to display GitOps Run sessions.

Open up ListObjects to allow for non-Kinds

---

ui/components/HelmReleaseDetail.tsx
ui/components/KustomizationDetail.tsx

Closes #2965 
Adds a `Kind` key/value to Kustomization and HelmRelease detail pages:

Add kind field to HelmRelease and Kustomization detail

---

ui/lib/objects.ts

Fixes #2981 (probably?)
We assumed a returned object has a `.spec.containers`, which may not be correct.

Do not assume template.spec in images() call

---

ui/components/DataTable.tsx
ui/components/FilterDialog.tsx
ui/components/__tests__/DataTableFilters.test.tsx
ui/components/__tests__/FilterDialog.test.tsx

Part of #2898 
This PR allows you to supply your own custom filter-value-getter to `filterConfig` without ALSO hard-coding it into the `filterRows` function (you can see this on line 137 of DataTable in the changes).
Removing the hard-coded version from `filterRows` just means we have to pass it through everything else, hence the changes to the `FilterConfig` type.
Doing this lets me provide a custom function to filterConfig inside enterprise without hard-coding it inside core.

Add transformFunc argument to filterConfig function

---

charts/gitops-server/templates/admin-user-roles.yaml
ui/components/KubeStatusIndicator.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx

Closes #2967 
Adds support for `DaemonSets` and a (hopefully) future-proof pattern for supporting other objects.

Add DaemonSet support to KubeStatusIndicator

---

ui/components/AutomationsTable.tsx

Closes #2958 
The `Revision` column appears to be working correctly, but I added a `maxWidth` parameter to ensure the revision gets ellips-ified:

Constrain Revision column width on the automations table

---

ui/components/KubeStatusIndicator.tsx
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap

The colors were renamed in #3019, but the colors returned from this function wasn't updated.

Fix status icon colors

---

website/docs/installation.mdx

Signed-off-by: Daniel Holbach <daniel@weave.works>
docs/installation: use tabs for gitops cli installation

docs/installation: use tabs for gitops cli installation

---

website/docs/feedback-and-telemetry.md

Closes #3035 
- Replaced the section labeled telemetry and the section labeled gitops CLI with the new documentation (as stated in the issue description).
Notes:
- I've tried to match the original document formatting, so, when there were commands but just in bold font instead of backticks, I've just used bold markdown formatting. Also preserved all spaces (where there are two spaces in the doc I kept them).
- I've only changed "Weave Gitops CLI analytics" to "Weave GitOps CLI analytics" because this is how we usually capitalize it and how it is capitalized throughout the doc.

3035 update docs with pendo info

---

cmd/gitops/get/config/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/set/config/cmd.go
pkg/config/config.go

Part of #2843 
all commands now attempt to read the config file before running, and create a config file if it doesn't exist - with a user prompt for analytics!

Create config file on CLI action with user prompt for analytics

---

.goreleaser.yml
Makefile
cmd/gitops/get/config/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/set/config/cmd.go
go.mod
go.sum
pkg/analytics/analytics.go
pkg/analytics/analytics_suite_test.go
pkg/analytics/analytics_test.go

Part of #2452 
- Added tracking command events with Pendo.
-  Added a test for the `getCommandPath` function.
- Refactored imports where both `cmd/gitops/import` and `pkg/config` are imported for consistency.
Notes:
- I've rebased on @joshri 's branch `auto-analytics` ( https://github.com/weaveworks/weave-gitops/pull/2868 ), so I'll need to wait until it is merged and rebase on `main` before merging the current PR.
- You can view tracked events in Product > Track Events in the Pendo dashboard, but there is a delay before the events are displayed there.

Add Pendo Track Events for Weave GitOps CLI

---

cmd/gitops/root/cmd.go
pkg/config/config.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go

Closes #2771 
When creating the Helm Chart for the dashboard, we will now check the user's config file and set analytics accordingly

Add analytics to helm chart on dashboard installation

---

website/docs/cluster-management/getting-started.mdx
website/docs/getting-started.mdx
website/docs/gitops-run/get-started.mdx
website/docs/guides/cert-manager.md
website/docs/guides/deploying-capa.mdx
website/docs/guides/setting-up-dex.md
website/docs/guides/using-terraform-templates.mdx
website/docs/installation.mdx
website/docs/installation/index.mdx
website/docs/installation/weave-gitops.mdx
website/docs/intro.md

As they were two "installation" pages in the final site, the left navigation had two entries for it. The new structure in this change fixes this by adding an index page to the "installation" folder that is rendered for the '/installation' URL path.

docs: remove duplicate "installation" entry from left nav

---

cmd/gitops-server/cmd/cmd.go
core/clustersmngr/clustersmngr.go
core/clustersmngr/factory.go
core/clustersmngr/factory_test.go
core/clustersmngr/fetcher/single.go
core/clustersmngr/fetcher/single_test.go
core/server/suite_test.go

We want to be able to create multiple fetchers, for multiple sources of clusters - such as for gitops run sessions.
To allow this, the manager needs to accept an array of fetchers, and combine the output of all of them when invoked.

Support supplying multiple fetchers

---

pkg/run/install/install_dashboard_test.go

A followup tot he analytics PRs. I was going to add this minor refactoring yesterday while adding analytics-related fixes to the dashboard manifests generation tests, but got distracted and forgot about it.
We are using a password hash not a secret for dashboard installation, so I think the variable name should match it.

Rename `testSecret` to `testPasswordHash` in the install dashboard tests.

---

ui/components/Pendo.tsx
ui/pages/SignIn.tsx

Closes #3046 
- Refactored the Pendo agent initialization code (mostly early exit the telemetry flag is is not "true").
- Fixed the issue with multiple Pendo scripts added to the page (your suggestion with wrapping code with `useEffect` worked like a charm, @ozamosi ✨ ).
- Added calling `identify` vs `initialize` if the Pendo agent has been initialized already (`Pendo.initialize` initializes the whole Pendo agent from scratch, `Pendo.identify` only updates `visitorId` and `accountId` based on the following explanation https://support.pendo.io/hc/en-us/community/posts/360077999992/comments/360015452792 ).
- Added switching from an anonymous Pendo user to a user with a generated `visitorId` on login (with `identify`).
- Added `window.localStorage` cleanup for Pendo after switching to the …

Pendo during signup screen

---

core/server/fluxruntime.go
core/server/fluxruntime_test.go
core/server/objects_test.go

If flux was installed through mechanisms other than the flux CLI (operatorhub, aws marketplace, microsoft.flux, etc), then the namespace usually doesn't have the part-of=flux label.
As a workaround, this still prefers the part-of label if it's set, but if we can't find one then we fall back to the namespace "flux-system". I hope this will be harmless - it's only used when the "proper" way has already failed, so I expect it'll either "fix" the feature, or do nothing.
However, the default in those third party installers might be to install flux somewhere else - e.g. operatorhub defaults to "operators". For that case I made a random undocumented environment variable that a user could set so that they get a different default than flux-system. I don't expect end users to do anything with that, …

dashboard: Use fallback namespace if no part-of=flux label

---

ui/components/DataTable.tsx
ui/components/FluxRuntime.tsx

Closes #3074 
```
FilterConfig = {
[key: string]: {
options: string[];
transformFunc?: (option: any) => string;
};
}
```
filterConfig now has an `options` instead of setting the value directly to the `key` and that was the issue to not display chips and selected filters.
changing the `initialFormState` to bind to the new field solves it

[fix] Chip filters are lost on refresh

---

website/docs/enterprise/releases.mdx
website/docs/gitops-templates/templates.mdx
website/versioned_docs/version-0.11.0/enterprise/releases.mdx
website/versioned_docs/version-0.11.0/gitops-templates/templates.mdx

This:
- backports release notes to versioned docs
- Provides summary of new features
- Simplifies breaking changing guidance
- clarifies use of pipeline template-type

Update Release Notes

---

charts/gitops-server/templates/admin-user-roles.yaml
core/server/fluxruntime.go
package-lock.json
website/docs/configuration/user-permissions.mdx

Closes #2966 
After this change, the default service account for the WeGO UI will have read access to all `apiGroups` and all `resources`. This allows objects that we have not enumerated to show up in the list of reconciled objects. Note the `ValidatingWebhookConfiguration` and `Task` objects (`Task` is a Tekton object, which WeGO UI doesn't "understand"):

Allow the wego-admin user read access to all objects

---

cmd/gitops/beta/run/cmd.go

This flag skips the question whether the user wants to install the dashboard and provides for a more convenient experience as the flow isn't interrupted.
closes #3083

Add `--skip-dashboard-install` flag to GitOps Run

---

.github/workflows/pr.yaml

This will publish one package for every successful CI run, including from non-main branches. Because the version is the full `git describe` output, they should all have unique and orderable names.

Publish non-release NPM packages from PRs too

---

core/clustersmngr/factory.go
core/server/fluxruntime.go
core/server/fluxruntime_test.go
ui/components/FluxRuntime.tsx

Closes #2910 
*Short description*
As a platform operator I want to see all Flux controllers on my cluster, when running multiple instances of Flux for multi-tenancy resource isolation, so that I can monitor their health and check their versions.
*Acceptance criteria*
- Flux Runtime Controller view shows controllers from multiple namespaces with the part-of: flux label
- New namespace column is added to the Controller tab

Flux Runtime Controller view shows controllers from multiple namespaces

---

go.mod
go.sum
pkg/kube/kubehttp.go

Closes #3082 
Adds a missing scheme to the `kube` client for notifications.

Add notification scheme to kube client

---

cmd/gitops-server/cmd/cmd.go
core/server/server.go
package.json
pkg/telemetry/telemetry.go
tools/helm-values-dev.yaml
ui/App.tsx
ui/components/AlertsTable.tsx
ui/components/AutomationsTable.tsx
ui/components/BucketDetail.tsx
ui/components/ControllersTable.tsx
ui/components/CrdsTable.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/KustomizationDetail.tsx
ui/components/NotificationsTable.tsx
ui/components/OCIRepositoryDetail.tsx
ui/components/Pendo.tsx
ui/components/SourcesTable.tsx
ui/contexts/CoreClientContext.tsx
ui/hooks/featureflags.ts
ui/index.ts
ui/pages/SignIn.tsx

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/1941
- Added the `Pendo` component to exports.
- Added the `defaultTelemetryFlag` prop to the `Pendo` component.
- Added the `js-sha3` package to the dependencies.
- Turned telemetry off in Tilt by default.
- Reworked the logic for detecting if Pendo should be initialized (in order to initialize it only after the feature flags are available in enterprise).
- Moved providing the default value for feature flags from `CoreClientContext` to `useFeatureFlags`.
- Removed unneeded default values and optional chaining for data returned by `useFeatureFlags` (it looks like they were not needed even before the latest change).
- Moved initializing telemetry to the gitops server cmd.
- Moved the check if should initialize telemetry …

Pendo Agent for Enterprise

---

cmd/gitops-bucket-server/main.go
pkg/s3/auth_middleware.go
pkg/s3/auth_middleware_test.go

implement auth middleware for s3

---

core/server/sync_test.go

The panic obfuscated the actual reason the test failed.

test: fix occasional panic sending on a closed channel

---

Makefile
cmd/gitops/beta/run/cmd.go
pkg/logger/s3_log_writer.go
pkg/run/watch/install_dev_bucket_server.go
pkg/s3/minio.go
pkg/tls/certs.go
pkg/tls/certs_test.go

When installing the dev bucket server on the cluster, it is now configured with a self-signed certificate generated on demand. The certificate is valid for 3 days which should be enough for a typical `gitops run` use case.
Instead of using HTTP in the forwarding from the host machine into the bucket server pod, the CLI now uses HTTPS so that traffic can't be intercepted on its way between the developer's machine and the cluster.
The certificate, after being generated, is put into a Kubernetes Secret which is in turn mounted into the bucket server pod.

use HTTPS in `gitops run` S3 bucket server

---

ui/components/ReconciledObjectsTable.tsx

Closes #3109 
If we always display the message of the first conditions object, we sometimes don't prioritize conditions with types of `Ready` or `Available`. It looks like if conditions are not undefined, don't have types of ready or available, and don't have a condition with a status of false, `computeMessage` will return the first condition's message anyway, even without the code I've removed here in `ReconciledObjectsTable`.
@jpellizzari Am I missing something related to the `DaemonSets` here that require the message of the first condition?
before:
after:

Fix incorrect message display for reconciled objects

---

charts/gitops-server/templates/deployment.yaml

Update the helm chart to configure the liveness/readiness probe to use HTTPS scheme when `serverTLS.enable` is `true`.
When I deployed weave-gitops using the helm chart with `serverTLS` configured, the Deployment never reached the ready state. Upon inspection, I noticed the readiness/liveness probes were failing with the following error:
```
Warning  Unhealthy  2s (x2 over 9s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 400
Warning  Unhealthy  2s               kubelet            Liveness probe failed: HTTP probe failed with statuscode: 400
```
Manually patching the deployment to adjust the scheme to `HTTPS` as I am doing here resolved the issue.
N/A: the change should be …

helm: Use HTTPS scheme for liveness/readiness probe when serverTLS is enabled

---

.github/workflows/pr.yaml

- We derive the name of the npm artifact from the git ref.
- on.pull_request creates an intermediate merge commit and messes this up
Updates the actions/checkout step to avoid a quirk of `on.pull_request` checking out the code to a "non-existant" merge commit. 
We use the ref from the commit to name the npm package. This should reflect the actual commit and not the temporary merge commit actions/checkout creates.
Straight up yaml engineering.
Checked the _publish js library_ CI output which now shows:
> `npm notice 📦  @weaveworks/weave-gitops-main@0.12.0-20-g116fd4bc`
For the head of this PR as of writing which matches the last commit.
**Documentation …

Fixes the PR commit hash we publish npm modules under

---

cmd/gitops/remove/run/cmd.go
pkg/run/install/install_vcluster.go
pkg/run/install/install_vcluster_test.go
pkg/run/session/get.go
pkg/run/session/get_test.go
pkg/run/session/list.go
pkg/run/session/list_test.go
pkg/run/session/remove.go

This PR adds the annotation `run.weave.works/namespace` to session objects.
The value of this annotation is taken from `--namespace` (flags.Namespace) of GitOps Run (default to `flux-system`).
Fixes #3126

add namespace annotation to gitops run sessions

---

pkg/http/server_test.go

The HTTP server might take some time to boot up so the `http.Get` call
failed sometimes. This race condition is now fixed by using
`g.Eventually` to try the request until it succeeds.
```
$ (pass=0; fail=0; for i in $(seq 1 1000) ; do go test -count=1 -v -run '^TestMultiServerServesOverBothProtocols$' ./pkg/http/ && pass=$(($pass+1)) || fail=$(($fail+1)) ; done; echo -e "Pass: $pass\nFail: $fail")
[...]
Pass: 1000
Fail: 0
```
closes #3144

fix flaky multi-server test

---

ui/components/Pendo.tsx
ui/pages/SignIn.tsx

Closes https://github.com/weaveworks/weave-gitops/issues/3153
- Removed clean-up of Pendo user data stored in browser's `localStorage`.
- Added returning without initializing Pendo if there is no user email available and no Pendo user stored in the local storage (to prevent logging anonymous users to Pendo on the Signin page).
**Testing**
Tested it in OSS and in enterprise against this branch, works as expected.
Set `WEAVE_GITOPS_FEATURE_TELEMETRY` to "true" before testing, it's turned off in development environments by default.
Helpful browser console commands for testing:
- Clear browser local storage to delete a stored Pendo user info.
```
window.localStorage.clear()
```
- Check if there is a Pendo user stored in the browser's `localStorage` (see if there are any Pendo-related keys in …

Pendo: Get rid of anonymous visitors on sign in page

---

cmd/gitops/root/cmd.go

Closes: #2982
Add `-n` flag alias for `--namespace`
The short `-n` flag for `--namespace` is a common practice in the Kuberneres world, not having that and working in multiple namespaces can cause user pain, a lot.
Changed `PersistentFlags().String(...)` to `PersistentFlags().StringP(...)`.
Run the following command:
```
go run ./cmd/gitops --help
```

feat: support for -n flag for --namespace

---

charts/gitops-server/templates/deployment.yaml
charts/gitops-server/values.yaml

Closes
Added podLabels value to be able to add additional labels to the pod template.
We use Azure AD pod identity to be able to assign an Azure AD identity 
which requires to set a specific label on the pod, in this case a label with key "aadpodidbinding".
Change has been tested locallly with specifying the podLabels value and verifying the resulting deployment definition and tested with no value for podLabels.

Added podLabels value.

---

ui/App.tsx
ui/components/Footer.tsx
ui/components/Pendo.tsx
ui/components/PendoContainer.tsx
ui/components/Version.tsx
ui/components/__tests__/Version.test.tsx
ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts
ui/pages/SignIn.tsx

Part of #3154
- Added tier and version to the `Pendo` component props.
- Added analytics as an optional `Signin` component prop.
- Added tracking tier and version as Pendo visitor metadata.
- Switched to initializing and re-identifying Pendo with objects instead of strings.
- Added the `PendoContainer` component to provide the version to Pendo (it should be used where using `useVersion` hook/calling the API in general is possible, within `AuthCheck`, because hooks can be called only at the top level in a function component and not conditionally).
- Switched to rendering the `Pendo` component twice: at the Signin page without the version (= without the `PendoContainer` component) and at other pages with the version.
- Reworked props of the `Footer`, and `Version` components.
- Moved …

Pendo: Track if users are coming from OSS or Ent and latest version

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/create/dashboard/cmd.go
pkg/run/install/apply_manifests.go
pkg/run/install/apply_manifests_test.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go
pkg/run/install/install_flux.go
pkg/run/install/install_flux_test.go
pkg/server/server_test.go

Closes #3165 
- Made any params of type `context.Context` the first param.
Notes:
- Did not touch the `contextName` params, because they are related to Kubernetes contexts not the context form the standard package.
- Tested imported WG OSS in enterprise, have not found anything to fix there, related to this refactoring.

Make context the first param of Go functions

---

ui/lib/objects.ts

Closes #3188 
Certain objects can have a `spec.template` with no images and still be valid - we were half-checking this, but returning `false` instead of `[]`

Fix return of false on images getter

---

ui/App.tsx
ui/pages/SignIn.tsx

Closes #3191 
- Removed Pendo initialization/re-identification (= removed the Pendo component) from the Signin page.

Remove Pendo init from the Signin page

---

.goreleaser.brew.yml
cmd/gitops/config/options.go
cmd/gitops/root/cmd.go

Closes #3193
- Replaced `popen_read` with `safe_popen_read` (the way it's recommended in the HomeBrew docs and issues). The actual thing that fixes brew upgrade or install hanging is adding `{ :err => :err }`.
- Added a hidden `no-analytics` flag to the root command in gitops to disable displaying analytics prompt (which runs in PersistentPreRun) when running the auto-generated `completion` command, in the brew formula. After I fixed install hanging, the analytics prompt started displaying while running the formula (maybe it's related to the hanging, like the prompt could be blocking smth. without an error message).
Testing:
I tested it by
- downloading the generated formula (the URL to which is visible when adding the `--verbose` and `--debug` options) from (in my case, …

Fix brew hanging

---

.npmrc
gitops-server.dockerfile

We've been experiencing an increased number of build failures in the
release GitHub workflow, manifested by error messages like this:
```
> [linux/arm64 ui  9/11] RUN make node_modules:
ERR! network Socket timeout
```
These failures only happen in the ARM64 builds which are executed in
a qemu emulation that apparently is so slow that it causes these
network timeouts. This is just a hypothesis, though, and this commit
is supposed to mitigate these timeouts by increasing npm's HTTP
timeouts.
See https://docs.npmjs.com/cli/v9/using-npm/config#fetch-timeout for
further documentation of the configuration parameter changed in this
commit.
closes #3229

fix npm timeouts in docker builds

---

cmd/gitops/beta/run/cmd.go

Fixes #3210 
```
Name:               run-master-8615cb75-dirty
Namespace:          default
CreationTimestamp:  Thu, 05 Jan 2023 20:08:27 +0700
Selector:           app=vcluster,release=run-master-8615cb75-dirty
Labels:             app=vcluster
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/part-of=gitops-run
chart=vcluster-0.13.0
helm.toolkit.fluxcd.io/name=run-master-8615cb75-dirty
helm.toolkit.fluxcd.io/namespace=default
heritage=Helm
release=run-master-8615cb75-dirty
Annotations:        meta.helm.sh/release-name: run-master-8615cb75-dirty
meta.helm.sh/release-namespace: default
run.weave.works/automation-kind: helm
run.weave.works/cli-version: v0.13.0-43-gda6a1cf1
run.weave.works/command: gitops beta run ./charts/podinfo …
```

Fix Gitops run automation-kind annotation shows incorrect kind 

---

cmd/gitops-server/cmd/cmd.go
package-lock.json
pkg/server/auth/auth_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go

This provides a mechanism for customising the requested scopes from an upstream OIDC server.
Some customers need to be able to customise the set of scopes that are requested, perhaps because they need specialised ones for a claim.
It's a pretty trivial change, defaults to the existing defaults, can be parsed from the OIDC Secret (as the other related values can) and it drops the "must have email and groups", retaining "must have openid" because we must have that.
Tests and got James to test it against Okta
Support for custom OIDC scopes when authenticating with an upstream server.
We need documentation on how to configure the …

Allow customisation of the scopes.

---

.gitignore
pkg/run/watch/setup_bucket_source.go
pkg/run/watch/setup_dev_ks_test.go
pkg/run/watch/watch_suite_test.go
pkg/testutils/testutils.go

- SetupBucketSourceAndKS returned a nil error even when some API calls
would have failed. I fixed this and added regression tests for the
behavior.
- The envtest setup and cleanup code was buggy and is fixed now (e.g.
it wasn't able to properly stop the envtest server because the
controller-runtime manager was still running).

add tests for SetupBucketSourceAndKS

---

.golangci.yaml

This configuration enables all the same linters that have been enabled
so far except for wsl which is more a distraction than anything else
and does not add to the code's readability.
The new configuration lists all of those linters that we should enable
gradually going forward.
This allows for us to enable the linters one-by-one any time we have
some leeway to do so.
refs #3119

add explicit linter configuration; disable wsl

---

core/server/events_test.go
core/server/fluxruntime.go
core/server/fluxruntime_test.go
core/server/suite_test.go
core/server/suspend_test.go
core/server/sync_test.go
core/server/version_test.go

Fixes #3231 
When getting reconciled objects, instead of just looping over kinds and retrieving all objects cluster-wide, loop over only namespaces which the current user has access to, as well as kinds as before.
When an OIDC impersonated user does not have cluster-wide privileges, the weave-gitops UI will not show any resources that are reconciled as part of kustomize/helmrelease etc objects. This change means that only objects in namespaces which the user has permissions in will be listed.
Simply providing another option to the client when calling List(), which specifies the namespace to list from, and looping over the namespaces which the user has access to. The list of user-accessible namespaces was …

Loop over namespaces when listing reconciled objects

---

Makefile

- remove unused variables
- allow for specifying a custom image name and tag when building
container images:
```
DOCKER_IMAGE_NAME=myreg:5000/foo/bar DOCKER_IMAGE_TAG=baz make docker-gitops-server
```
The changes are made in a backwards-compatible way so that running the
targets without specifying a custom name and/or tag will result in the
exact same images being built as before this change.
closes #3264

clean up Docker targets in Makefile

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/create/dashboard/cmd.go
pkg/run/install/install_flux.go
pkg/run/install/install_flux_test.go

Fixes #3235
Fixes #3049
The changes in this PR are used to determine the version of Flux that is currently being used in a Kubernetes cluster. 
- It does this by first searching through the namespaces in the cluster for one that is labeled as being part of Flux and has a version label.
- If it finds such a namespace, it returns the version specified in the label.
- If it doesn't find such a namespace, it then tries to get a hard-coded namespace called "flux-system" and checks its labels for the version.
- If it still can't find the version, it looks for a deployment called "source-controller" in the found namespace and tries to extract the version label if it exists, and guess the flux version from the version from the image used in …

improve detection of flux version

---

cmd/gitops/beta/run/cmd.go
core/server/session_logs.go
core/server/session_logs_int_test.go
pkg/logger/s3_log_writer.go

Closes #3268 
- Added passing a MinIO client to the `NewS3LogWriter` function and removed some other params. The difference between the secure and insecure S3 logger is determined by the MinIO client which is passed to `NewS3LogWriter`. So, I removed the `NewInsecureS3LogWriter` function.
-  Added a new `CreateBucket` function which also accepts a MinIO client (generally, the same client which is used for creating the S3 logger.).
- Add constants for log bucket names.
- Added creating a bucket for pod logs in addition to the existing bucket for session logs.

Set up a new bucket for gitops run logs

---

website/docs/releases.mdx
website/versioned_docs/version-0.15.0/releases.mdx

Release docs for WGE v.0.15.0

---

website/package.json
website/yarn.lock

fixes https://security.snyk.io/vuln/SNYK-JS-UAPARSERJS-3244450
closes #3304

use ua-parser-js 0.7.33 to fix vulnerability

---

pkg/run/watch/forward_port.go

Closes #3164 
- Add building the list of port forward shortcuts based on sorted keys.
Testing:
To test it locally with a hardcoded portforwards list, you can replace the following lines in `cmd/gitops/beta/run/cmd.go`
```
portForwards := map[rune]watch.PortForwardShortcut{}
if dashboardInstalled {
portForwardKey, err := watch.GetNextPortForwardKey(portForwards)
if err != nil {
log.Failuref("Error adding a portForward: %v", err)
} else {
portForwards[portForwardKey] = watch.PortForwardShortcut{
Name:     dashboardName,
HostPort: flags.DashboardPort,
}
}
}
var specMap *watch.PortForwardSpec
if flags.PortForward != "" {
specMap, err = watch.ParsePortForwardSpec(flags.PortForward)
if err != nil {
log.Failuref("Error parsing port forward spec: %v", err)
} else {
serviceName := specMap.Name
if …
```

Sort port forward shortcuts

---

doc/development-process.md
website/README.md
website/docs/releases.mdx
website/docusaurus.config.js
website/versioned_docs/version-0.15.0/releases.mdx

- fixed the broken links to email on the releases page
- added a link to the website README in the Contributing section and added some more info in the readme for running the documentation commands.
- added social links in the footer similar to the Weaveworks website footer
- The footer looks less empty and more in sync with our company site.
- It took some time for me to find the website readme so I added an extra link in the contribution section for people like me 😛 Also added some helpful links and text for people who might be new to Docusaurus.
Before: 
After:

Minor updates to user docs

---

ui/components/DagGraph.tsx

Closes [#2223](https://github.com/weaveworks/weave-gitops-enterprise/issues/2223): Enterprise issue
Long story short is that adding `linkStrokeWidth * 2` to the path was the cause of a little extra space between the nodes. HOWEVER. The screenshots here seem to indicate that this is necessary in the OSS DagGraph component, and somehow the Enterprise styling effects this svg code. How? Not sure. I'm also noticing there's an extra scroll bar in the graph on Enterprise exclusively in the Terraform version of the graph, which I hate, but that's a conversation for a follow up issue. 
Enterprise Terraform DagGraph (extra scroll bar :(((( ):
Enterprise Automation DagGraph:
OSS Automation DagGraph:

Fix spacing between graph nodes and lines

---

pkg/gitproviders/factory.go
pkg/gitproviders/repo_url.go
pkg/gitproviders/repo_url_test.go
website/package.json
website/yarn.lock

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/2271
Adds repo URL parsing support for BitBucket using a simple path match.

Add initial (naive) BitBucket Server support

---

cmd/gitops/root/cmd.go

Closes #3317 
- Added the `run` command to  the root (`gitops`) command. So, calls to `gitops beta run` and `gitops run` will work exactly the same.
Notes:
The only limitation: usage examples in help for `gitops run` will display `gitops beta run`, because they are hardcoded strings, but for our purposes it should work. We can update help after we move GitOps Run our of beta.
Testing that both commands work the same:
`gitops run`
`gitops beta run`

Add gitops run command as an alias to gitops beta run

---

ui/index.ts
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/2319
- Add the `formatLogTimestamp` function to format log timestamp with a custom format string with a UTC timezone offset.
- Add unit tests for `formatLogTimestamp`.
Notes:
- There is a technical problem with importing the luxon package directly into enterprise (a type-related error message which is unresolvable for now, so I decided to export this function from OSS and import in the other PR to enterprise, because luxon is already imported in OSS).
Design from Figma:
Results of formatting with this function (in enterprise UI), the only difference with Figma is, as @josefaworks  suggested, it should display local UI user's time, not time in +0 UTC timezone (we can change exact UTC format later):
- I also applied the …

Improve formatting of log message timestamp in the log UI

---

website/docs/releases.mdx
website/versioned_docs/version-0.16.0/releases.mdx

Removing empty Minor Fixes section and add missing update in the highlights section that was done in the main docs but not the versioned ones.

Update 0.16 website docs

---

ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Follow-up fix for https://github.com/weaveworks/weave-gitops/pull/3355
Noticed I had copied a wrong format token from Luxon table.
Updated the token and the tests.

Fix log timestamp format string

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go

Closes https://github.com/weaveworks/weave-gitops/issues/3337
- Switched from using a HelmChart to detect OSS dashboard to using a HelmRelease.
- Added a `helmChartName` parameter to `IsDashboardInstalled` and `getDashboardHelmRelease` functions (with the hope to reuse the dashboard detection code in https://github.com/weaveworks/weave-gitops/issues/2891 ).
- Removed unused function parameters.
- Updated tests for `getDashboardHelmRelease`.
Testing:
Tested it on both regular Kind and enterprise (created with the `./tools/reboot.sh` script) clusters.
To install the OSS dashboard via a HelmChart, please use the following instructions:
https://docs.gitops.weave.works/docs/installation/weave-gitops/#deploying-weave-gitops
Notes:
- I kept the same error-handling logic for getting a list of …

Improve detection of OSS dashboard

---

ui/components/DataTable.tsx
ui/components/__tests__/DataTableFilters.test.tsx

Closes #3359 
Out of the two proposed ideas in 3359, adding the text search to urls gave the most value - as I was coding this it got a little scary to start slapping these query-string and history.replace actions everywhere. It's fewer clicks to sort by a column/reverse sort and I don't think the hit to the code/performance is worth adding it to the url.

Add text search to table urls

---

ui/components/AutomationsTable.tsx
ui/components/Timestamp.tsx

Part of #3152 
This tooltip prop is currently only going to be used in the GitOps Run table in Enterprise, hence the specificity on localeString, but it's easy to open it up for different formats if we want it to be more flexible and implemented in other tables/components.
Example:

Add optional tooltip to Timestamp component

---

cmd/gitops/beta/run/cmd.go
pkg/run/watch/setup_dev_helm.go

Fixes #3376
This PR introduces changes to the `SetupBucketSourceAndHelm` function in the `watch` package.
The PR makes the following changes to the code:
-  We set the value of the field `ReconcileStrategy` to "Revision" in the `HelmChartTemplateSpec` struct. According to the CRD docs, this field determines the strategy used to create a new artifact, and it is an optional field. The possible values are "ChartVersion" and "Revision", with "ChartVersion" being the default value when omitted.  This change was made to specify the desired strategy used to create a new artifact.  By setting the value of `ReconcileStrategy` to "Revision", we ensure that a new artifact will be created based on the revision of the chart, rather than the version …

change strategy to revision, and add values.yaml to the chart spec

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go

Closes https://github.com/weaveworks/weave-gitops/issues/2891
- Reworked the `IsDashboardInstalled` function into `GetInstalledDashboard` which returns the type (none, OSS or enterprise dashboard) and name of installed dashboard.
- Updated unit tests for the `GetInstalledDashboard` function.
- Added passing the actual dashboard name to `ReconcileDashboard`.
- Removed `getDashboardHelmRelease` (before it was needed for more granular testing, because `IsDashboardInstalled` returned a boolean value; now we can test based on returned dashboard type).

GitOps Run cannot detect Enterprise Dashboard

---

.npmrc

We're still seeing socket timeouts in CI and the interwebs suggest
reducing the maximum number of open sockets. Let's see if that helps
anything.
refs #3229

another attempt to fix ARM builds

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/session.go

Fixes #3038
The reason for these changes is that the previous implementation of the GitOps Dashboard installation process had a flaw in the dashboard prompt. When the prompt was answered with "no," it was still asked again by the sub-process, resulting in a redundant prompt. 
This PR makes changes in two files. In the `cmd/gitops/beta/run/cmd.go` file, the `dashboardStep` function is modified by adding a constant block with three possible values, `unknown`, `wantToInstall`, and `doNotWantToInstall`. The function handles these values and updates the `wantToInstallTheDashboard` variable accordingly.  If the user chooses not to install the dashboard, it sets the `flags.SkipDashboardInstall` to true.
In the `pkg/run/install/session.go` file, the "NewSession" function, and the "Session" struct …

address GitOps Run "ask twice" issue by handling "no" answer correctly

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install_fluent_bit.go

The source of the issues was that a signal handler was installed
before the setup phase but the signal was not actually handled until
after the setup phase has successfully completed.
Now we spawn a goroutine handling the subscribed signals right after
subscribing to them. The goroutine then cancels the context used
throughout the function so that any action is immediately cancelled
during the setup phase. After the setup phase we now wait for the
context do be done instead of handling the actual signal.
I also changed the `InstallFluentBit` function so that it re-uses the
passed-in context when creating and waiting for the Fluent Bit
HelmRelease so that it is interruptible by Ctrl+C as well.
One caveat that is not handled in this commit is that in the case
where a user hits Ctrl+C during …

fix: Ctrl+C not working during GitOps Run setup phase

---

core/server/session_logs.go
core/server/session_logs_int_test.go
ui/components/AutomationDetail.tsx
ui/components/DataTable.tsx

Closes https://github.com/weaveworks/weave-gitops/issues/3379
- Updated the error message for getting a scoped client.
- Added a check for the log secret already existing.
- Added unit tests for `isSecretCreated`.
- Removed unneeded comments.
Testing:
- Pull in the current PR branch, GitOps Run and go to the session details page before the session is completely ready (you should see the "cluster not found" error in the UI, this is expected behavior).
- 
When the session objects get ready and polling logs succeeds, logs are displayed without errors.

Error getting GitOps Run logs before GitOps Run objects are ready

---

core/server/fluxruntime.go
core/server/fluxruntime_test.go

This ensures the active version stored in etcd is showed in the UI, instead of the first version on the list. Providing a more accurate view of the current version existing in the cluster.
Fixes #3446

Take "storage" version into account for Flux CRDs

---

cmd/gitops/beta/run/cleanup.go
cmd/gitops/beta/run/cleanup_test.go
cmd/gitops/beta/run/cmd.go
core/server/session_logs_test.go
pkg/run/install/install_fluent_bit.go

The Fluent Bit HelmRelease is not removed from the cluster as soon as
the GitOps Run session terminates. Prior to this you weren't able to
start another session after terminating the first one.
This commit introduces the `CleanupFunc` type that `fluentBitStep`
returns. This function is pushed onto a stack and at session
termination each function on that stack is popped and executed,
guaranteeing a reverse rollup of any resources created by GitOps Run itself.
We should gradually add the `CleanupFunc` type to the other steps,
too so that cleanup is done in a standardized manner.
Before:
```
$ gitops run --no-session ./kustomize/
► Checking for a cluster in the kube config ...
[...]
► Request reconciliation of GitOps Run resources (timeout 5m0s) ...
✔ Reconciliation is done.
^C► Received …
```

Uninstall Fluent Bit when stopping a GitOps Run session

---

website/docs/references/helm-reference.md
website/docusaurus.config.js
website/sidebars.js

Also make it very clear that the current Chart ref is for OSS only (I would love to change the heading of the doc itself, but I cannot find which bit to configure in the autogen to make that happen).
I have switched the `Getting Started` link to `Docs`. I don't want the nav bar getting too crowded, and the `Getting Started` is _right there_ when you click on the `Docs` link. Plus people will return to `Docs` and realistically only go to `Getting Started` once. That said, I can put both there if that is preferred, LMK.

Add clear docs link to navbar

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install_vcluster.go
pkg/run/install/install_vcluster_test.go

When the dashboard is not installed during the GitOps Run session
(either interactively or by providing the `--skip-dashboard-install`
flag), then no `run.weave.works/port-forward` annotation is placed in
the session's StatefulSet.
Apparently the UI still renders a link in the session table so this
commit is part of a two-part fix and the UI part is addressed in the
Enterprise UI code next.
refs weaveworks/weave-gitops-enterprise#2392

skip port-forward annotation when no port-forward is setup

---

ui/components/AlertsTable.tsx
ui/components/AutomationDetail.tsx
ui/components/DetailModal.tsx
ui/components/FluxObjectsTable.tsx
ui/components/GraphNode.tsx
ui/components/Layout.tsx
ui/components/ReconciledObjectsTable.tsx
ui/components/YamlView.tsx
ui/contexts/AppContext.tsx
ui/lib/theme.ts

Closes #3439 
UPDATE:
As far as I understand this is actually only going to contain a more generic details screen. So it doesn't need to be as flexible as I made it before. We wanted a header thing in there as well which I've added in this screen: 
OLD PR DESCRIPTION BELOW:
The main purpose of this PR is to create a multi-purpose drawer component - the pop-up YamlViews have been converted to use it to start out, but the idea is that _anything_ will be able to go in there. Because we want to be able to trigger it from anywhere, I added it to AppContext. This makes the typing a little tricky since we're using components + props, when before it was just yaml so I always knew what to expect. 
Adding a new component would entail:  
- Adding the name to the `DetailOptions` enum
- Exporting the …

Add DetailModal component, and convert pop up YamlViews to use it

---

ui/components/Logo.tsx
ui/components/Nav.tsx
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
ui/lib/utils.ts

Closes #3497 
New `Fade` styled component wraps collapse text and logo image - I didn't want to use the MUI version because it is super annoying about refs ala Popovers.
https://user-images.githubusercontent.com/65822698/224410517-16cfdba1-5a39-4eb6-ac3d-9d9f861a598b.mov

Expand area that is clickable for logo and collapse in nav

---

website/package.json
website/yarn.lock

Closes #3509 
- Upgraded Webpack to version 5.76.0, as recommended below to fix the sandbox bypass vulnerabilty:
https://security.snyk.io/vuln/SNYK-JS-WEBPACK-3358798
The vulnerability disappeared from the Snyk scans for some reason now (it was reported by the Snyk check before), but it is still reported on the Snyk website. So, I decided to upgrade Webpack (because there is no release of Docusaurus with this fix yet) to be on the safe side.

Fix Sandbox Bypass vulnerability in Docusaurus

---

cmd/gitops/beta/run/cmd.go
pkg/run/install/install_dashboard.go

Closes #3237 
- Added trimming the password string after reading it.
- Added returning an error and existing GitOps Run if the trimmed dashboard password string entered during a GitOpsRun run is empty.
Testing:
- Please run a `gitops run` command without the `--skip-dashboard-install` flag and when prompted to install the dashboard, enter `y` and then, when prompted for a password, please enter either an empty string or a string which consists of whitespaces only. You should see the error returned and the GitOps run run should be terminated.
Sample run logs:
```
olga@macbook-pro podinfo % gitops beta run ./deploy/overlays/dev --timeout=3m --port-forward namespace=dev,resource=svc/backend,port=9898:9898 
► Checking for a cluster in the kube config ...
► Preparing the cluster for GitOps Run …
```

Fix dashboard password prompt accepting an empty string as a 

---

.github/workflows/pr.yaml

Closes #3197 
- Replaced the install script to install the Flux CLI with the `Setup Flux CLI` action.
Based on discussion with @kingdonb  and @chanwit (thank you both!), switched to using the following GitHub action for installing Flux CLI (with the GITHUB_TOKEN to prevent the calls from being rate-limited):
https://github.com/fluxcd/flux2/blob/main/action/README.md
Sample run:
Notes:
I kept the commented out install.sh script which was used previously — just in case. If everything works as expected, we can remove this comment later. Or I can remove it now, whichever you prefer.

Flaky test when running curl to a Flux URL

---

ui/components/Nav.tsx

Adds a label prop to non-tab items in navItems to avoid a lint error in enterprise (items in lists should all have a `key` prop)

Add key to text labels in Nav

---

ui/components/FormCheckbox.tsx
ui/components/YamlView.tsx
ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
ui/index.ts
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Refs #3530 
Creates a utility function that is exportable for the yaml command. Will import in enterprise once this is merged.

Support yaml commands for objects without a namespace

---

ui/components/Nav.tsx

Part of #3480 
Adds two mui props to the nav to allow for scrolling at small screen heights.
Also equally spaces header text in nav for enterprise section headers

Scroll nav at small screen heights

---

core/clustersmngr/factory_caches.go

Fixes #3536 
How to confirm the fix:
```
KUBEBUILDER_ASSETS=$(setup-envtest use -p path 1.24.2) go test -race -v ./core/clustersmngr/...
```
Test logs:
```
❯ KUBEBUILDER_ASSETS=$(setup-envtest use -p path 1.24.2) go test -race -v ./core/clustersmngr/...
=== RUN   TestClientGet
--- PASS: TestClientGet (2.04s)
=== RUN   TestClientClusteredList
--- PASS: TestClientClusteredList (0.04s)
=== RUN   TestClientClusteredListPagination
--- PASS: TestClientClusteredListPagination (0.02s)
=== RUN   TestClientClusteredListClusterScoped
--- PASS: TestClientClusteredListClusterScoped (0.02s)
=== RUN   TestClientCLusteredListErrors
--- PASS: TestClientCLusteredListErrors (0.02s)
=== RUN   TestClientList
--- PASS: TestClientList (0.02s)
=== RUN   TestClientCreate
--- PASS: TestClientCreate (0.02s)
=== RUN …
```

add rlock to clustermgr hash to avoid a race condition

---

pkg/run/watch/forward_port.go

Fixes #3548
This PR is the follow up for #3557.
Please merge #3557 first.
To test this,
1. Compile the `gitops` binary with `CGO_ENABLED=1 go build -race ...`
2. Run `gitops run`
The buffer race condition for port forwarding should not appear there.

Fix race condition of byte buffer in port forwarding

---

ui/components/Nav.tsx

Quick fix for enterprise nav. Setting line-height to equal height vertically centers text

Vertically center enterprise nav header text

---

ui/components/Pendo.tsx

Part of #3566 
- Restored getting the value of the `WEAVE_GITOPS_FEATURE_TELEMETRY` flag as a string instead of a Boolean value.
Testing:
Tested it locally.
- To test that Pendo is initialized or not, set desired value to `WEAVE_GITOPS_FEATURE_TELEMETRY` flag in `tools/helm-values-dev.yaml` and run:
```
console.log(window.pendo.getSerializedMetadata())
```
in the browser console.
If Pendo was initialized, there will be some data displayed. If not, an error will be thrown.
I am not able to test the fix in enterprise, because after I pull in the current branch from OSS to enterprise, I see errors related to feature flags. Will raised the couterpart PR for enterprise later after enterprise is updated with the new feature flag logic.

Fix Pendo initialization

---

.prettierignore
charts/gitops-server/templates/_helpers.tpl
charts/gitops-server/templates/admin-user-creds.yaml
charts/gitops-server/templates/deployment.yaml
charts/gitops-server/templates/role.yaml
charts/gitops-server/values.yaml
cmd/gitops-server/cmd/cmd.go
pkg/server/auth/auth_test.go
pkg/server/auth/init.go
pkg/server/auth/init_test.go
pkg/server/auth/server.go
pkg/server/auth/server_test.go
tools/helm-values-dev.yaml
website/docs/configuration/emergency-user.mdx
website/docs/configuration/service-account-permissions.mdx
website/docs/references/helm-reference.md

Closes #2237 
- Added support for the dynamic admin secret user name to the gitops-server code.
- Updated unit tests.
- Updated documentation related to admin user credentials secret.
Notes:
- Transferred code from the old PR (3149) here because it was outdated and caused merging conflicts + it was easier to understand the changes this way.
- Added minimal updates to the documentation. Adding more minor updates is fine but if any major updates/changes/a new guide on how to configure smth. are needed, they should be covered in a separate issue.
**Questions:**
- I just removed the old hardcoded secret name from `viewSecretsResourceNames`? Is it OK? Will the users be able to add the actual dynamically generated secret name to this array manually, if needed?
- @foot @stefanprodan  Enterprise …

Use dynamic Secret name for admin credentials

---

ui/components/DataTable/DataTable.tsx
ui/components/DataTable/SortableLabel.tsx
ui/components/DataTable/__tests__/DataTable.test.tsx
ui/components/DataTable/__tests__/DataTableFilters.test.tsx
ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/DataTable/helpers.ts
ui/components/DataTable/index.ts
ui/components/DataTable/types.ts
ui/components/__tests__/FilterDialog.test.tsx

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/2609
**Save until after the release**
Breaks up the `DataTable` component without affecting the modules that import it. Also adds some sort skipping logic for when we want to sort elsewhere.
I had originally intended to break up `DataTable` further but it was too high-risk.

Split up DataTable component and add column click handler (v2)

---

charts/gitops-server/templates/_helpers.tpl
charts/gitops-server/templates/deployment.yaml
cmd/gitops/beta/run/cmd.go
core/server/fluxruntime_test.go
core/server/inventory_test.go
core/server/objects.go
core/server/objects_test.go
core/server/session_logs.go
core/server/types/app.go
core/server/version.go
core/server/version_test.go
pkg/flux/flux.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go
pkg/run/install/install_flux.go
pkg/run/install/install_flux_test.go
pkg/run/install/install_vcluster.go
pkg/run/session/get.go
pkg/run/session/list.go
pkg/run/utils_test.go
pkg/run/watch/install_dev_bucket_server.go

Part of #3546 
- Added exiting the dashboard type switch statement earlier for readability.
- Added reconciling the OSS dashboard only if it was installed by GitOps Run.
**- Added app selector labels to be able to identify the dashboard deployment and pods. The same labels will be added to the enterprise Helm chart.**
- Added a constant for the app selector label.
- Replaced hardcoded label key strings with constants for consistency (we already had many of those constants but we we not using them in many places).
- Improved dashboard detection.
- Updated tests for `GetInstalledDashboard`.
Tested it locally for the following cases (that the dashboard is installed, if no other dashboard is found, or the dashboard already installed is detected):
without dashboard:
- test with no dashboard …

Dashboard reconciliation stuck when running GitOps Run in the no session mode with OSS dashboard already installed

---

website/docs/gitopssets/installation.mdx
website/docs/gitopssets/releases.mdx
website/sidebars.js
website/versioned_docs/version-0.20.0/gitopssets/installation.mdx
website/versioned_docs/version-0.20.0/gitopssets/releases.mdx
website/versioned_sidebars/version-0.20.0-sidebars.json

Now that we publish the gitopssets-controller as a standalone helm chart, we provide away to install it in a more standalone mode
- Also add a releases page to track new releases

Adds installation instructions for the gitopssets-controller

---

cmd/gitops/remove/run/cmd.go
pkg/run/install/install_fluent_bit.go
pkg/run/watch/install_dev_bucket_server.go
pkg/run/watch/setup_bucket_source.go
pkg/run/watch/setup_dev_helm.go
pkg/run/watch/setup_dev_ks.go

Fixes #3545 
- In file `cmd/gitops/remove/run/cmd.go`, this PR adds support for a new command line flag to remove all resources from a failed GitOps Run when running in no session mode, enhancing usability by improving the user experience.
- The `--no-session` flag is added to the `RunCommandFlags` struct, and if the flag is set, session name or `--all-sessions` flag is ignored.
- The `removeRunPreRunE` function is updated to return early if the `--no-session` flag is set.
- The `removeRunRunE` function is updated to remove all resources related to a failed GitOps Run in no session mode if the `--no-session` flag is set.
- In file `setup_bucket_source.go`, this PR changes to the `cleanupBucketAndSecretObjects()` function to log errors only if the error is caused by something other than …

implement remove run for non-session mode

---

Tiltfile

Closes #3604
The fix is based on @foot 's suggestion ✨ 
Test it locally in the following mode `FAST_AND_FURIOUSER=1 SKIP_UI_BUILD=1 tilt up`. Works as expected.

Add a hardcoded secret name for the Tilt auth

---

ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

Fixes #3601
- In file `ui/lib/__tests__/utils.test.ts`, this PR adds more test cases to the `isHTTP` function to accurately distinguish between HTTP and HTTPS URLs, improving the reliability and functionality of the function.
- The added test cases cover scenarios that were previously uncovered, including localhost and private IPs.
- In file `ui/lib/utils.ts`, this PR updates the regular expression used for validating HTTP and HTTPS URIs.
- The regular expression is now multiline, uses double quotes for consistency, and uses `\\` to escape special characters.
- The regular expression has been simplified and organized to improve readability, understandability, and maintainability.

fix url checking reg exp and make it readable

---

website/docs/cluster-management/getting-started.mdx
website/docs/cluster-management/profiles.mdx

Closes https://github.com/weaveworks/weave-gitops-enterprise/issues/2649
Documentation for using private helm repository to retrieve profiles. SecretSync is to be used to sync the secret.
Document the steps regarding the ability to use private helm repositories as the current usage assumption is of public repos only.
N/A
N/A
N/A

Add docs for using a private helm repository in wge-profiles

---

pkg/server/auth/claims.go
pkg/server/auth/claims_test.go

Closes
No open issue exists for this PR.
When using an OIDC Provider that filters the groups associated with the user principal,
for instance Jumpcloud, it is possible for the groups claim* to have a single string value, and not a list of strings or a list of one string, i.e:
claims[groupsKey] = ["group1"]
claims[groupsKey] = "group1"
This can occur when the user is only assigned to a single group in the OIDC Directory relevant to the Weave Gitops OIDC Application.
\* no matter the attribute name [groups | memberOf | other custom key]
I encountered this issue with the error message:
`failed to query user info endpoint: invalid groups claim "groups" in response Flux-Admins`
and so, in order to tix the issue, I have changed it so that when the …

Allow group claim to be string, not only []string

---

cmd/gitops/beta/run/cleanup.go
cmd/gitops/beta/run/cleanup_test.go
cmd/gitops/beta/run/cmd.go
cmd/gitops/remove/run/cmd.go
pkg/run/install/install_fluent_bit.go
pkg/run/watch/dashboard.go
pkg/run/watch/install_dev_bucket_server.go
pkg/run/watch/setup_dev_helm.go

Fixes #3428
- In file `cmd/gitops/beta/run/cleanup.go`, this PR changes the signature of the `CleanupFunc` interface to include an additional `logger.Logger` parameter, allowing each cleanup function to log independently.
- It also adds a check to ensure that the passed function is not `nil` to avoid resources being left in a dirty state during cleanup.
- In file `cleanup_test.go`, this PR modifies the `CleanupFuncs` stack to include the `Logger` object and adds test cases to ensure the stack behaves as expected.
- In file `cmd/gitops/beta/run/cmd.go`, this PR makes several changes including adding a `sync` package, modifying various functions to enable better logging and error handling during execution, and adding a new cleanup function to properly cancel the context and clean up …

fix the clean-up process

---

package-lock.json
package.json
website/package.json
website/yarn.lock

Closes https://github.com/weaveworks/weave-gitops/issues/3637
- Upgraded the `yaml` package to version 2.2.2 to resolve the vulnerability, reported by Snyk.
- Added an alias for the `yaml` package in `package.json` to resolve the ReferenceError happening in v2.2.2 with the default import. Parcel chokes on mixed types of exports (probably where export all/export with rename are mixed, as stated in the following issue https://github.com/parcel-bundler/parcel/issues/8792 ).
- Updated the `@docusaurus` package and its dependencies. Added a custom resolution to `yaml` v2.2.2 for website subdependencies.
Tested:
- Tested it in Tilt with regular mode and in the FAST_AND_FURIOUSER mode.
- Also ran `npm run build` to make sure it builds successfully.
- Ran the documentation with `yarn start`. …

Fix the vulnerability in the `yaml` NPM package

---

website/docs/explorer/configuration.mdx
website/docs/releases.mdx
website/versioned_docs/version-0.22.0/explorer/configuration.mdx
website/versioned_docs/version-0.22.0/releases.mdx

We have released https://github.com/weaveworks/weave-gitops-enterprise/releases/tag/v0.22.0 
but there was no documentation for `useQueryServiceBackend`
This PR adds it and updates release notes too.

Update docs for explorer v22 configuration on `useQueryServiceBackend`

---

doc/release-process.md

As discussed in x-team sync, add a couple steps to the release process doc to prepare other teams to handle release. 
Added step about notifying weave-gitops-dev channel in slack
Added step about moving issues out of Uncategorized in PR description
Anything else you two feel we should add?

Improve release process docs

---

ui/components/ReconciliationGraph.tsx

Closes #3672 
It appears that this is tricking `parcel` into correctly importing `d3` by including a reference to the library in the module syntax-tree (I guess).
The library is referenced, but no calls are made.

Trick bundler into correctly building D3

---

ui/components/YamlView.tsx
ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap

Follow-up to https://github.com/weaveworks/weave-gitops/pull/3676

Fix code tag style of `react-syntax-highlighter`

---

.github/workflows/docs.yaml
README.md
ui/pages/SignIn.tsx
website/docs/installation/aws-marketplace.mdx
website/docusaurus.config.js
website/package.json
website/versioned_docs/version-0.22.0/installation/aws-marketplace.mdx
website/yarn.lock

Fixes https://github.com/weaveworks/weave-gitops-interlock/issues/414
This pr adds a redirect for old page which no longer exists. Also removed redundant info from marketplace docs.
The page link https://docs.gitops.weave.works/docs/getting-started/ currently goes to older versions of docs with outdated information causing confusion. 
When the new getting started page was introduced https://docs.gitops.weave.works/docs/getting-started/intro we must have missed updating outdated links.
Adding a redirect plugin https://docusaurus.io/docs/using-plugins
Staging build and local testing
This pr adds a redirect for the old page …

Added a redirect for getting started page

---

website/docs/policy/policy.mdx
website/versioned_docs/version-0.22.0/policy/policy.mdx
website/versioned_docs/version-0.23.0/policy/policy.mdx

Closes https://github.com/weaveworks/weave-gitops-interlock/issues/414
Fixed old enterprise urls with new ones.
Old url https://docs.gitops.weave.works/docs/enterprise/intro/ goes to the wrong version `0.12.0`
Local testing
Fixed old enterprise urls with new ones.

Fix url for enterprise intro page

---

website/docs/secrets/setup-sops.mdx
website/versioned_docs/version-0.20.0/secrets/setup-sops.mdx
website/versioned_docs/version-0.21.1/secrets/setup-sops.mdx
website/versioned_docs/version-0.21.2/secrets/setup-sops.mdx
website/versioned_docs/version-0.22.0/secrets/setup-sops.mdx
website/versioned_docs/version-0.23.0/secrets/setup-sops.mdx

One of the commands in the Setup SOPS website doc was missing the namespace which would make it crash for the user. This PR adds it in all versions.

Adding missing namespace in sops doc command

---

ui/components/Logo.tsx
ui/components/UserSettings.tsx
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap

Enterprise imports UserSettings from OSS, and needs to be able to disable the dark mode switch for now.
When running tests, I found a random console error where the `to` prop on Link was undefined in the Logo component, so I fixed that as well

Add prop to hide dark mode switch

---

ui/pages/SignIn.tsx

@yiannistri spotted a ui bug, which I have just now gotten around to fixing. Removed the MUI Divider and replaced with a styled component + prop
before:
after:

Fix Divider styling on Sign In page

---

ui/components/Link.tsx
ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/components/__tests__/__snapshots__/Version.test.tsx.snap

Some usage of the Link component in Enterprise (see Breadcrumbs) had to create a lot of custom styling when the url passed was invalid. I'd like to delete those styles and allow the use of `${Link} {...}` inside another styled component.

Properly set up Link styled-component

---

ui/components/DataTable/DataTable.tsx
ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/SyncButton.tsx

Closes #3682 
Closes #3683
This PR fixes two requests made during the Dark Mode work:
https://github.com/weaveworks/weave-gitops/assets/65822698/e8906d6e-c1b7-495a-8618-3038eb533d9b
- Sync and ArrowDropDown buttons are now the same height, with their right and left borders removed respectively. 
- Border radius was being applied to each `th` cell - now it's only the first and last as intended.

Dark Mode UI bug follow ups

---

ui/App.tsx
ui/components/DarkModeSwitch.tsx
ui/components/UserSettings.tsx
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/pages/SignIn.tsx

Closes #3737 
Separates out dark mode switch into separate component for reuse in sign in page - will need immediate followup in enterprise to set prop to disable dark mode for now
https://github.com/weaveworks/weave-gitops/assets/65822698/4057c39f-e00a-4910-963d-e7a08fba8c2d

Add dark mode switch to sign in page

---

charts/gitops-server/templates/deployment.yaml

Closes
This PR puts a conditional `with` block around the `securityContext` properties in the Deployment Helm template. This will ensure that the element is not rendered if the corresponding value is empty. This seems to be the pattern used in this, and other templates of the Helm chart.
This allows installation on Openshift without elevated SCC permissions. This is a common problem when provisioning community software to Openshift. The intentions of default security contexts are good, but sadly Openshift does not allow it. Here's a random goog explanation: https://github.com/bitnami/charts/issues/4884#issuecomment-754648273
n/a (trivial change)
n/a (trivial change) …

Openshift: Allow removal of securityContext with Helm values

---

ui/components/Logo.tsx
ui/components/Nav.tsx
ui/components/Page.tsx
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap

Somewhere along the way, the nav and content stopped lining up. I've exported the `topBarHeight` variable and made sure that the nav container stops shrinking the logo component height. Also lines up logo with nav icons
This branch (aka good) -
Main (aka bad) -

Consistent use of topBarHeight variable

---

ui/lib/theme.ts

Closes: #3805 
If no autofill styles are set by extensions or browser, we will set it so it doesn't come out while in dark mode. 
Extensions like 1password have their own stylesheets with `!important` set on attributes like this, which helps users understand that their autofill worked as expected. Screenshot is from firefox with a saved login

Prevent white background on input autofill in dark mode

---

.github/workflows/pr.yaml

Part of https://github.com/weaveworks/corp/issues/3627
Given our Snyk subscription ends today, 
This PR disables Snyk checks to avoid CI builds to fail. 
Dependabot will be enabled next
See more info in the ticket

disabled snyk checks for both PRs and main

---

ui/components/CheckboxActions.tsx
ui/components/DataTable/DataTable.tsx
ui/components/SyncButton.tsx
ui/hooks/automations.ts
ui/lib/types.ts

Part of: [#3034](https://github.com/weaveworks/weave-gitops-enterprise/issues/3034)
Draft because I want to make sure this does not conflict with @opudrovs current image automation work

Allow for custom actions for data table checkboxes

---

ui/components/CheckboxActions.tsx

Follow up to: #3829 
Getting Typescript errors when actually trying to apply these changes in EE.
The props in `createElement` have to be typed otherwise whatever you're passing down is going to conflict - in this case since we want them to be custom I've given it the sad `any` type. But at least now we know that it's `any`.

Enhance types in checkbox actions for EE terraform sync/suspend all

---

website/docs/enterprise/getting-started/install-enterprise.mdx
website/docs/enterprise/getting-started/releases-enterprise.mdx
website/docs/gitopssets/_api-toc.json
website/docs/gitopssets/_api.mdx
website/docs/gitopssets/guide.mdx

Update the user-guide for the v0.27.0 weave-gitops-enterprise release
Also
- Update some older releases that were missing
- Update gitopssets-controller guide and api for the Config generator

Update docs for weave-gitops-enterprise 0.27.0 release

---

.github/dependabot.yml

Part of https://github.com/weaveworks/corp/issues/3627 
This PR adds a baseline configuration file for Dependabot to setup both interval to daily (as starting point) and reviewers to prod-eng teams as maintainers
As part of our switch to [Dependabot](https://github.com/weaveworks/corp/issues/3627 ) we have enabled it in the repo.It gives us vulnerability detection and remediation however PRs are not assigned so could be missed. 
Validated with another repo but it would be needed to validate the whole flow once merged
Using dependabot for vulnerability management
Not required

enabled dependabot with daily schedule and eng teams as reviewers

---

.github/dependabot.yml

Tweaking dependabot to just raise PRs for security updates not version updates. 
To have version updates managed by dependabot was not in scope so it is an unintended consequence. This PR tries to revert this behaviour as the documentation [suggests](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit)

Tweaking dependabot to just raise PRs for security updates. 

---

core/fluxsync/adapters.go
core/server/sync.go
core/server/sync_test.go
tools/testcrds/source.toolkit.fluxcd.io_ocirepositories.yaml

Closes https://github.com/weaveworks/weave-gitops/issues/3852
- Added HelmChart to known object Kinds when getting Flux objects for syncing.
- Added missing sync tests to cover all source objects.
- Reordered tests for consistency (automations first, then sources).

Fix error when syncing HelmChart

---

ui/components/LargeInfo.tsx

- Fixes a console error in tests on a missing key prop in checkbox actions
- Fixes a case in EE where the new large info component could be empty when tf objects have no last updated time - now a hyphen will be displayed by default without extra code in EE + causing the tooltip to render a hyphen

Fix missing key prop in checkbox actions, and provide "-" default text for large info

---

core/fluxsync/adapters.go
core/server/suspend_test.go
core/server/sync.go
core/server/sync_test.go
pkg/kube/kubehttp.go
tools/testcrds/image.toolkit.fluxcd.io_imageupdateautomations.yaml
ui/components/CheckboxActions.tsx
ui/components/ImageAutomation/ImageAutomationDetails.tsx
ui/components/ImageAutomation/updates/ImageAutomationUpdatesTable.tsx

Allows sync and suspend for image update automations + fixes a bug where buttons were not disabled when un-checking the last checked button (having variable outside of useEffect prevented update -> see CheckboxActions component)
https://github.com/weaveworks/weave-gitops/assets/65822698/abdb7cc5-1670-45f7-a535-ae51955837a3

Add sync and suspend for image update automations

---

website/docs/assets/dashboards/explorer.json
website/docs/explorer/operations.mdx

Docs for 
https://github.com/weaveworks/weave-gitops-enterprise/pull/3134
Collecting:
Explorer monitoring documentation extended with indexer write metrics
Dashboard:
Added indexer writes panels to explorer grafana dashboard
Increase observability for datastore and monitor RED metrics for write operations
Manual test
added docs for indexer write metrics

ad docs and dashboard for indexer RED metrics

---

website/docs/enterprise/getting-started/releases-enterprise.mdx
website/versioned_docs/version-0.29.0/enterprise/getting-started/releases-enterprise.mdx

Added WGE [v0.29 release notes](https://github.com/weaveworks/weave-gitops-enterprise/releases) to docs site

added wge v0.29 release notes documentation

---

website/versioned_docs/version-0.28.0/pipelines/promoting-applications.mdx

Fix doc ci job

---

website/docusaurus.config.js

closes weaveworks/weave-gitops-enterprise#3192
Redirects added:
- https://staging.docs.gitops.weave.works/3192-redirects/docs/intro-weave-gitops
- https://staging.docs.gitops.weave.works/3192-redirects/docs/releases
- https://staging.docs.gitops.weave.works/3192-redirects/docs/enterprise/releases

Add redirects for orphaned website pages

---

ui/components/Page.tsx

[Closes #3139](https://github.com/weaveworks/weave-gitops-enterprise/issues/3139)
Quick fix for OSS errors displaying the same error like seven or eight times. It would be useful for OSS to adopt Enterprise's cleaner error handling in the future

Filter duplicate error messages

---

website/docusaurus.config.js

This page is being linked to from some publicly available Weaveworks presentations so we better have that one covered.
Affected page: https://staging.docs.gitops.weave.works/3192-redirects/docs/intro should redirect to https://staging.docs.gitops.weave.works/3192-redirects/docs/intro-weave-gitops
refs weaveworks/weave-gitops-enterprise#3192

Add redirect for another orphaned docs page

---

ui/components/Alert.tsx
ui/components/ErrorList.tsx
ui/index.ts
ui/pages/v2/Notifications.tsx

Closes #3634 
Adds an `ErrorList` component to Core, heavily inspired by the one used in EE. This also exports the `ErrorList` component so that it may be imported in EE and eventually subsume the `AlertListErrors` component (there is nothing wrong with that component currently, but this will enforce Consistency:tm:).
There are now two error "classes" on the page:
Error when we can't reach the backend:
Batched errors from various clusters (backend returns lots of errors):
Simulated the error state using this:
```diff
core/server/objects.go | 10 ++++++++++
1 file changed, 10 insertions(+)
diff --git a/core/server/objects.go b/core/server/objects.go
index 0bb6e26d5..f99290bbc 100644
--- a/core/server/objects.go
+++ b/core/server/objects.go
@@ -14,6 +14,7 @@ import (
pb …
```

Add batch error handling to Notifications page

---

ui/components/AutomationDetail.tsx
ui/components/ImageAutomation/ImageAutomationDetails.tsx
ui/components/PageStatus.tsx
ui/components/PodDetail.tsx
ui/components/SourceDetail.tsx

Part of: #3890 
Checked detail pages in OSS and removed detail page titles accordingly - also adjusted a common override on PageStatus to be the default. This does not close the titles issue, as I'd like to check EE as well

Remove titles from detail pages for consistency 

---

.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
doc/release-process.md

Closes https://github.com/weaveworks/weave-gitops/issues/3907
Implements locking action as suggested [here](https://github.com/weaveworks/weave-gitops/tree/main/doc/incidents/issues-3907#prevention)
To reduce chances of release incident happened in [v0.29](https://github.com/weaveworks/weave-gitops/tree/main/doc/incidents/issues-3907) to happen in future release and simplify the releaser job.
Added status check called 'release' with locking semantics around release and non-release workflows. It also includes 
other enhancements from the original proposal like error prograpation while doing status checks update in github actions steps. 
The following scenarios has been …

Implement release locking to avoid publishing helm chart before container image 

---

ui/pages/SignIn.tsx

Closes #3210 
Sets a static height on the footer to ignore the "wheel" image height. I chose `300px` because it was roughly what both images were resolving to naturally.

Set static height on signin footer

---

pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go

Closes https://github.com/weaveworks/weave-gitops/issues/3957
Changes generated dashboard helmrepository apiVersion from v1 to v1beta2
HelmRepository still not yet in v1 so creating in v1 will end in the resource not been created
- Adjusted unit test expectation 
- Executed the command [too](https://github.com/weaveworks/weave-gitops/issues/3957#issuecomment-1687693817)
No
No

dashboard helmrepository apiVersion should be v1beta2 not v1

---

core/server/inventory.go
core/server/inventory_test.go

fix npe when inventory object is nil

---

ui/components/AutomationDetail.tsx
ui/components/Flex.tsx
ui/components/ImageAutomation/ImageAutomationDetails.tsx
ui/components/LargeInfo.tsx
ui/components/SourceDetail.tsx
ui/components/SyncActions.tsx
ui/components/__tests__/SyncActions.test.tsx
ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap

Closes: [#2907](https://github.com/weaveworks/weave-gitops-enterprise/issues/2907)
Creates styled component extension of Flex with a breakpoint prop to swap `flex-direction` when below a certain screen width
laggy video here:
https://github.com/weaveworks/weave-gitops/assets/65822698/2fb955b0-feaf-4326-91bb-f0e61578ab06

Add Flex with breakpoint prop

---

.github/workflows/prepare-release.yaml

Added flux compatibility version to the release notes 
two main reasons:
- help our users understand compatibility 
- reinforcing our dependency to flux 
Pending

adding flux compatibility section to the release notes 

---

website/docs/terraform/get-started-terraform.mdx

Addresses a recent question about event messages and behavior.
Adds a Troubleshooting section to the [TF Getting Started page](https://docs.gitops.weave.works/docs/terraform/get-started-terraform/) along with a tip about event messages.
To help clear up confusion for others who might ask and to create a resource where we can point them. 
Tiny doc change.
Tiny doc change. 
Adds Troubleshooting section to WGE TF-controller page
It's a doc change.

Adds Troubleshooting section to WGE TF-Controller docs

---

core/server/primarykinds.go
core/server/primarykinds_test.go

Closes https://github.com/weaveworks/weave-gitops/issues/3626
Adjusted weights to avoid the ranking function computes v1 and v1beta2 with the same value.
We noticed that sometimes gvk resolution for gitrepositories was returning `v1beta2` instead of `v1` which was expected. The reason was that both `v1` and `v1beta2` level had the same ranking value. 
Therefore v1 or v1beta2 was returned depending on which one was first introduced in primaryKinds. Given  `AllKnownTypes ` was randomly returning either of them, we got to that unpredictable behavior.
Adjusted weights to avoid the ranking function computes v1 and v1beta2 with the same value.
Added test case for supporting …

predictable resolution for gitrepository gvk when v1 and v1beta2 exist

---

package.json
yarn.lock

Closes #3986
Fixes the following error preventing to build the UI:
```
[go-build 13/13] RUN --mount=type=cache,target=/root/.cache/go-build LDFLAGS=${LDFLAGS##-X localbuild=true} GIT_COMMIT=$GIT_COMMIT make gitops-server [cached]
→ yarn build
→ yarn run v1.22.19
→ warning package.json: No license field
→ $ parcel build --target default
→ Building...
→ Bundling...
→ Packaging & Optimizing...
→ 🚨 Build failed.
→ 
→ @parcel/optimizer-htmlnano: Could not resolve module "node:os" from 
→ "/home/app/node_modules/cosmiconfig/dist/index.js"
→ 
→ 
→   Error: Could not resolve module "node:os" from 
→   "/home/app/node_modules/cosmiconfig/dist/index.js"
→       at NodePackageManager.resolveInternal 
→   (/home/app/node_modules/@parcel/package-manager/lib/index.js:3672:21)
→       at …
```

Fix the error could not not resolve module "node:os" from cosmiconfig preventing to build the UI

---

website/versioned_docs/version-0.24.0/guides/deploying-capa.mdx

before the change capa warning
```bash
✔ Client
Compiled successfully in 57.12s
[WARNING] Docs markdown link couldn't be resolved: (installation/weave-gitops-enterprise/index.mdx) in "/Users/enekofb/projects/github.com/weaveworks/weave-gitops/website/versioned_docs/version-0.24.0/guides/deploying-capa.mdx" for version 0.24.0
...
```
after the warning is fixed

adjusted link to enterprise install

---

ui/components/Metadata.tsx
ui/components/OCIRepositoryDetail.tsx
ui/components/SourceDetail.tsx
ui/components/__tests__/Metadata.test.tsx
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/lib/__tests__/objects.test.ts
ui/lib/objects.ts

Closes: https://github.com/weaveworks/weave-gitops-enterprise/issues/3341
Adds a new section to the Metadata component for OCI Repositories for clarity - we were previously displaying revision and source in the info list, but folks were expecting to see it in Metadata (which only recognizes our metadata.weaveworks prefix).

Add Artifact Metadata section to OCI Repository detail pages

---

website/docs/enterprise/getting-started/install-enterprise.mdx

Closes: #4024
This adds documentation on the way we prefix users and groups, in the same way as the Kubernetes kube-apiserver does.
Missing documentation

Document group and user prefix configuration.

---

website/docs/explorer/configuration.mdx

updating explorer kind docs to reflect latest changes: added gitopssets and policy audit violations

updating explorer kind docs to reflect latest changes

---

ui/components/AutomationsTable.tsx
ui/components/UserSettings.tsx
ui/components/VerifiedStatus.tsx
ui/components/__tests__/__snapshots__/Page.test.tsx.snap

Closes #4019 
The request for an automation's source was using the `sourceRef` field, which doesn't have a namespace if the source is in the same one as an automation, and NEVER has a cluster name. This PR uses the automation's namespace and cluster name to actually get the source back on these requests. 
Also fixes not actually opening a new tab on the new docs button - careful when using the `as` prop for styles with a styled component, because it actually changed the `a` element into a button as well

Fix 'cluster not found' error when requesting source from automation `sourceRef`

---

ui/components/AutomationsTable.tsx
ui/components/KubeStatusIndicator.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap

Related: https://github.com/weaveworks/weave-gitops-enterprise/issues/3309
There is a case in EE where we'd like the `KubeStatusIndicator` component to render the correct status icon without text - right now there's a bit of a hack in place to set `display: none` to the `span` in the component, but I think this functionality is worth having in the component itself. I also changed the code a bit so we don't run `computeMessage` unless we have to.

Add noText prop to kubeStatusIndicator

---

ui/components/SyncActions.tsx
ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap

Closes https://github.com/weaveworks/weave-gitops/issues/4001
- Added `min-width: fit-content` to the `SyncActions` component to prevent Suspend button being to narrow on Source details pages in the status message is too short.
Notes:
- The padding on the Suspend button stays the same, but the button's with is forced to be too narrow because of the `width: 50%` specified in the `SyncActions` component. As discussed with @joshri, this width setting was added to make  the buttons play nicely with Applied Revision and Last Updated elements on Application details pages.
Testing:
- The original issue can be seen in staging on a HelmChart page with a short status message:
https://gitops.euw1.wego-gke.weave.works/helm_chart/details?clusterName=Default&name=dex-dex&namespace=flux-system
At least …

Fix Suspend button width on Source details pages with short status message

---

ui/components/ImageAutomation/ImageAutomationDetails.tsx
ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx
ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx
ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx
ui/components/Policies/Utils/HeaderRows.tsx

part of ee [3339](https://github.com/weaveworks/weave-gitops-enterprise/issues/3339
)
- Link `clusterName` in ImageAutomation detail page 
- Filter `HeaderRows` visible items before looping over its items

Link clusterName in image automation details

---

.github/workflows/chart.yaml
.github/workflows/docs.yaml
.github/workflows/nightly.yaml
.github/workflows/ossf.yaml
.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/upgrade-flux.yaml

Closes #4023 
Pinned GitHub Actions versions.
To ensure we use a specific version of each GitHub Action. Also to address warnings such as https://github.com/weaveworks/weave-gitops/security/code-scanning/3794 
N/A
CI
N/A
N/A

Pin GitHub Actions versions

---

.github/workflows/docs.yaml
.github/workflows/release.yaml
.github/workflows/upgrade-flux.yaml

Introduced an intermediate environment variable to prevent script injection in CI workflows. See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable for more details.
To prevent script injection in CI. Also to address issues such as https://github.com/weaveworks/weave-gitops/security/code-scanning/3781
By introducing an intermediate environment variable.
CI
N/A
N/A

ci: Fix CI workflows to prevent script injection

---

.github/workflows/scan.yaml

Added CodeQL CI workflow.
To perform CodeQL analysis and discover potential vulnerabilities.
N/A
N/A
N/A
N/A

ci: Run CodeQL analysis as part of CI

---

CONTRIBUTING.md

Updated Acceptance policy.
To make PR requirements more explicit.
N/A
N/A
N/A
N/A

docs: Update Acceptance policy

---

ui/components/EventsTable.tsx

Closes [EE-3376](https://github.com/weaveworks/weave-gitops-enterprise/issues/3376)
Currently some of our Events tabs use wording that is different from other Events tabs. But there's just one schema for Event objects. To prevent user confusion, let's standardize so that every Events tab includes these four column names:
- Reason
- Message
- From 
- Last Updated
This change will affect :

Standardize the column names on Events tabs

---

.github/workflows/chart.yaml
.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
.github/workflows/repostats.yaml
.github/workflows/trigger.yaml
.github/workflows/upgrade-flux.yaml

Closes https://github.com/weaveworks/weave-gitops/issues/4023
To ensure we use a specific version of each GitHub Action. 
This is a follow-up PR to https://github.com/weaveworks/weave-gitops/pull/4044 to ensure all GitHub Actions are pinned to a commit SHA.
N/A
N/A
N/A
N/A

ci: Pin GitHub Actions versions

---

package.json

upgrade postcss to fix found vulnerability
```
➜  weave-gitops git:(main) make ui-audit                                                                                                                                                                                                                                                                                
yarn audit --production
yarn audit v1.22.19
warning ../../../../package.json: No license field
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ PostCSS line return parsing error                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ postcss …
```

upgrades postcss to address https://www.npmjs.com/advisories/1094239

---

website/docs/enterprise/getting-started/install-enterprise.mdx

Fixed #4040
Updated the chart version of Dex that was referenced in our docs to 0.15.3. Also removed hard-coded image version to defer instead to the chart values (currently pulls in v2.37.0 which is the latest as of now).
Note that this was also tested on a GKE cluster along with these chart versions:
- cert-manager 1.13.1
- ingress-ngix 4.8.0
- Weave GitOps 0.33.0
The previous version (0.6.5) was too old.
N/A
N/A
N/A
N/A

docs: Bump dex chart version

---

ui/components/AutomationDetail.tsx
ui/components/DetailModal.tsx
ui/components/ImageAutomation/ImageAutomationDetails.tsx
ui/components/PodDetail.tsx
ui/components/ProviderDetail.tsx
ui/components/SourceDetail.tsx
ui/components/YamlView.tsx
ui/components/__tests__/YamlView.test.tsx
ui/lib/__tests__/utils.test.ts
ui/lib/utils.ts

We would like to use the DetailModal component for the PR Preview in the upcoming add source UI in EE - part of this means replacing the `kubectl get` command from the YamlView header with the path of your potential resource, so I moved the creation of the header up a level in the component tree, and added `path` as an option in the the createYamlHeader function.

Move header creation outside yaml view to allow for custom text

---

.github/workflows/docs.yaml
website/docusaurus.config.js

- var interpolation wasn't working with single quotes
- also introduce env var into docusaurus so you can optionally disable versioning (`DISABLE_VERSIONING=true yarn build` to dramatically speed up builds when testing things..)
Some of the github action code, switch from single `''` to double `""` quoted strings so we can do the var interpolation
Switch to env vars which relied on the variable expansion made in https://github.com/weaveworks/weave-gitops/pull/4046
So staging docs works
- Use heredoc for JSON payloads.. seems to work okay and avoids having to escape all the double quoted key names in JSON..
Checked that the staging docs now works

Fixes staging-docs

---

ui/components/SubRouterTabs.tsx

Closes #[3392](https://github.com/weaveworks/weave-gitops-enterprise/issues/3392)
- update the tab min-width to be auto and update the size on larger screen size.
- This change made to make the tabs component being usable on smaller screen size.
- Tested locally

override default tabs min-width at (600px) media query

---

.github/workflows/docs.yaml

The `staging-release` CI job builds and pushes docs to a staging environment and therefore fails when run on forks.
Example of a failure: https://github.com/weaveworks/weave-gitops/actions/runs/6546412572/job/17776816192?pr=3990

fix: Skip running job on forks

---

cmd/gitops/beta/run/cmd.go
cmd/gitops/create/dashboard/cmd.go
pkg/run/install/install_dashboard.go
pkg/run/install/install_dashboard_test.go
website/docs/open-source/getting-started/install-OSS.mdx

flags `--values` added to `create dashboard` and `beta run` so we can provide additional helm values  when generating HelmRelease from the `gitops`cli
Didn't wanted to have to deal with editing the yaml HelmRelease file to add values 
This is has been inspired by how it is implemented in flux for creating HelmRelease
with this yaml
``` yaml
service:
type: nodePort
nodePort: 30000
```
we have this export from the below command
``` yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
annotations:
metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
a simple way to get insights into your GitOps workloads.
name: …
```

Add helm 'values' flags to create dashboard

---

website/docs/open-source/getting-started/ui-OSS.mdx

Fixes #4092 
Adds a half-line clarification to explain why we link to WGE docs content from the OSS section.
To address the connection for users.
Added some text.
It's a very minor change, so I didn't test.
Nope
It's a doc change.

Adds clarification to WGE docs links from OSS

---

website/docs/operations/monitoring.mdx

Fixes formatting for monitoring docs. Now the table of contents look better:

fixed format for monitoring docs

---

website/docs/explorer/getting-started.mdx

Related to https://github.com/weaveworks/weave-gitops-enterprise/pull/3485

update explorer docs with granular configuration

---

website/docusaurus.config.js

Part https://github.com/weaveworks/weave-gitops/issues/4102
- removed metadata config to generate sitemap
- algolia key as env
suspect that the indexing issue in algolia would go away with this
```bash
➜  website git:(main) ✗ cat ./build/sitemap.xml|grep run-ui-subpath                                                                                                           <aws:sts>
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.
```

generate sitemap

---

gitops-server.dockerfile

FIxes an issues where dependencies will get upgraded unintentionally in container builds.
We originally had a `package-lock.json` that was being used to ensure consistent builds, but #3592 converted to `yarn` which has a separate `yarn.lock` file that needs to be copied.

Ensure the yarn.lock file is being used in container images

---

.github/workflows/pr.yaml

Removed Slack notification job as the target Slack channel has been archived.
To ensure our CI workflows are up-to-date.

ci: Remove Slack notification to archived channel

---

website/README.md

The new environment variable ALGOLIA_API_KEY hasn't been added to the documentation in the README so I added it and also simplified the command to run the dev server.

Fix website README

---

website/docs/explorer/operations.mdx

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/3043
- Updated Explorer monitoring documentation to include the object cleaner metrics.
- Updated the Explorer dashboard screenshot.
Notes:
- Not sure if we need such a large screenshot which shows all parts of the Explorer dashboard. If not, I can restore the old screenshot.
- Naming suggestions are welcome.
**Questions:**
- Do we agree on calling the cleaner component officially everywhere Objects Cleaner or Object Cleaner?
I saw it called differently in different places. For now, I am calling it Objects Cleaner.

Add monitoring to object cleaner

---

core/server/suspend.go
core/server/suspend_test.go

Closes #[3546](https://github.com/weaveworks/weave-gitops-enterprise/issues/3546)
- Refactor suspended by annotations to have prefix "metadata".
- After adding the prefix metadata that makes the suspended to show up at the metadata component at the details page view
- Update the Tests

show suspended by annotations to metadata component

---

ui/components/Policies/Utils/MarkdownEditor.tsx

UI | fix markdown editor overflow style

---

website/docs/enterprise/getting-started/install-enterprise.mdx
website/docs/open-source/getting-started/install-OSS.mdx

Closes
This just documents our current lack of persistent storage for sessions.
We are trying to figure out what we're going to support, but we don't currently support it, this just makes that clear in the documentation.

Add note about lack of persistent storage.

---

website/docs/enterprise/getting-started/install-enterprise-cli.mdx
website/versioned_docs/version-0.36.0/enterprise/getting-started/install-enterprise-cli.mdx

Part of https://github.com/weaveworks/weave-gitops-enterprise/issues/3659

 added repo url examples in cli bootstrapping docs

---

website/docs/enterprise/getting-started/releases-enterprise.mdx
website/versioned_docs/version-0.37.0/enterprise/getting-started/releases-enterprise.mdx

Closes
Added release notes for enterprise version 0.37.0
update the release notes in the public docs.
changed the docs.
Reviewed it locally w/ yarn

Add release notes for version-0.37.0

---

website/docs/enterprise/getting-started/releases-enterprise.mdx
website/versioned_docs/version-0.37.0/enterprise/getting-started/releases-enterprise.mdx

to help out ee customers to have the info more easily accessible temp for this version. we should find a long-term solution to the problem.

add weave gitops oss release notes links for v0.37 

---

website/docs/enterprise/getting-started/install-enterprise-cli.mdx
website/versioned_docs/version-0.38.0/enterprise/getting-started/install-enterprise-cli.mdx

Closes https://github.com/weaveworks/weave-gitops-enterprise/issues/3276
- add docs for extra controllers for WGE onboarding CLI
- updating the docs for the new version of CLI

add docs for extra controllers for WGE onboarding CLI

---

website/docs/enterprise/getting-started/install-enterprise-cli.mdx

Documents https://github.com/weaveworks/weave-gitops-enterprise/issues/3420
Added documentation for cli bootstrapping `export` flag
No

adding export documentation to bootstrapping command

---

website/docs/enterprise/getting-started/install-enterprise-cli.mdx

removed blanks for install cli docs flags when no short flag
Before:
Now: 
https://staging.docs.gitops.weave.works/update-cli-docs/docs/next/enterprise/getting-started/install-enterprise-cli/#cli-configurations

removed blanks for install cli docs flags when no short flag

---

website/docs/enterprise/getting-started/releases-enterprise.mdx

Update docs for recent WGE releases 0.38.0 and 0.38.1.
https://staging.docs.gitops.weave.works/update-docs-for-0.38/docs/next/enterprise/getting-started/releases-enterprise/

docs: Update docs for new releases

---

website/versioned_docs/version-0.38.0/enterprise/getting-started/releases-enterprise.mdx

backported enterprise release changes to v0.38 so it has 0.38 and 0.38.1

backported enterprise release changes to v0.38 so it has 0.38 and 0.38.1

---

ui/App.tsx

A suggestion for:
https://github.com/weaveworks/weave-gitops/pull/4162

Flux Runtime config draft

---

website/docs/explorer/configuration.mdx

Part of https://github.com/weaveworks/weave-gitops-enterprise/pull/3682
Adds namespaces to the example configuration for Explorer.

Add namespaces to explorer configuration example

---

ui/lib/nav.ts

Fixes the issue of the nav item menu not being highlighted:

Add support for V2Routes.Runtime in navigation getParentNavRouteValue

---

core/server/objects_test.go

I did a mistake and thought I fixed the test by starting to use v1 Bucket, but the newest Bucket API in Flux 2.3 is v1beta2. But the fact that I managed to get the test in question to pass by changing to Bucket v1 makes me believe there is something wrong "deeper".
/cc @casibbald

Revert "test: migrate TestGetObjectSessionObjects to Flux 2.3"

---

Makefile
tools/testcrds/helm.toolkit.fluxcd.io_helmreleases.yaml
tools/testcrds/kustomize.toolkit.fluxcd.io_kustomizations.yaml
tools/testcrds/source.toolkit.fluxcd.io_buckets.yaml
tools/testcrds/source.toolkit.fluxcd.io_gitrepositories.yaml
tools/testcrds/source.toolkit.fluxcd.io_helmcharts.yaml
tools/testcrds/source.toolkit.fluxcd.io_helmrepositories.yaml
tools/testcrds/source.toolkit.fluxcd.io_ocirepositories.yaml

It seems like most of the Go tests passes when Flux CRDs are bumped to Flux 2.4. I see that we already have moved into "Flux 2.4 land" in the go.mod file. What if we try to head directly for Flux 2.4? We use ww-gitops with Flux 2.4 in our clusters, so at least for the main parts, it works.
/cc @casibbald

Bump Flux CRDs to Flux 2.4

---

dev.dockerfile
gitops-bucket-server.dockerfile
gitops-server.dockerfile
gitops.dockerfile
test/library/libtest.dockerfile
website/Dockerfile

fix: test pinned dependencies

---

.golangci.yaml
Makefile
gitops-bucket-server.dockerfile
gitops-server.dockerfile
go.mod
test/library/libtest.dockerfile

Closes
update to 1.M.P syntax for go version
fix CodeQL warnings

Codeql adhere to1.n.p syntax fixes

---

.github/workflows/scan.yaml

The FOSSA API key secret is not available in forks, which makes the job fail. To avoid "green" PRs, I suggest adding a conditional to only run this job when in upstream org.

ci: don't run FOSSA job in forks

---

.github/workflows/scan.yaml

Since the FOSSA scanner is just partially working, I suggest introducing Trivy as an alternative.

ci: enable Trivy vulnerability scanning

---

.github/dependabot.yml

Dependabot is currently only configured for security updates, and some of the used GH actions are lagging on upgrades. Proposing to enable upgrades of GH actions in general and see how it works. Also removing the assigned reviewers which I think are abandoned Weaveworks teams.

ci: enable Dependabot for GH actions upgrades

---

package.json
yarn.lock

Removing jest 29 resolution as project is using jest 27 and it seems to just add a unused jest install.
Modifying to `"test": "jest --version",` in `package.json` confirms using 27.
Should upgrade 27 -> 29, but I'm then getting `SyntaxError: Cannot use import statement outside a module`.

chore: remove jest 29 resolution

---

.gitignore
Makefile

I have now ruined my IDEA Goland setup multiple times because `make clean` deletes the IDEA module file. This adds `*.iml` files to .gitignore and also excludes it when running `make clean`.

chore: don't delete *.iml (IDEA module) files on 'make clean'

---

go.mod
pkg/kube/kubehttp.go
pkg/services/auth/jwt.go

The https://github.com/pkg/errors project has been archived for some time in favor of the proposals that landed in the stdlib. We have very few references to this module so I took a stab at migrating it.

chore: remove direct dependency to github.com/pkg/errors

---

.github/workflows/scan.yaml

Hopefully, this should fix the current error on the main branch:
````
RequestError [HttpError]: Resource not accessible by integration
at /home/runner/work/_actions/github/codeql-action/04daf0[14](https://github.com/weaveworks/weave-gitops/actions/runs/12536344145/job/34959246645#step:4:15)b50eaf774287bf3f0f1869d4b4c4b913/node_modules/@octokit/request/dist-node/index.js:86:21
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/github/codeql-action/04daf014b50eaf774287bf3f0f1869d4b4c4b913/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/04daf014b50eaf774287bf3f0f1869d4b4c4b913/node_modules/bottleneck/light.js:405:1 …
```

ci: add missing permission to Trivy scan job

---

.github/workflows/docs.yaml
.github/workflows/pr.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/upgrade-flux.yaml

Closes
Setup build tools from versions specified in go.mod and package.json files.
Makes it easier to maintain versions, as there should be no need to update CI config when versions are bumped.

ci: setup Go/Node from file

---

website/package.json
website/yarn.lock

chore(deps): upgrade path-to-regexp

---

.dockerignore

`.yarn/install-state.gz` is an optimization file that you shouldn't ever have to commit. It simply stores the exact state of your project so that the next commands can boot without having to resolve your workspaces all over again.  
https://yarnpkg.com/getting-started/qa
To get clean docker build

chore: docker ingore yarn install state

---

jest.config.js
package.json
yarn.lock

Instead of https://github.com/weaveworks/weave-gitops/pull/4310
Converts jest conf from ts to js, to avoid @types/node and ts-node

chore: avoid ts deps with js jest conf

---

.golangci.yaml
Makefile

Closes
While running `make lint` I noticed a couple of deprecation warnings that I wanted to fix. In addition, I removed the hard-coded Go version from the lint config. golangci-lint will by default use the Go version specified in `go.mod`.
Eliminate warnings when running lint. Deprecated features will eventually be removed. Also nice to avoid having to bump Go version in multiple files.

ci: improve/fix golangci-lint config

---

website/docusaurus.config.js
website/package.json
website/yarn.lock

https://docusaurus.io/blog/releases/3.6#docusaurus-faster
> Experimental but safe
> Don't be afraid to turn this feature on. What's experimental is the config options.
>
> The new infrastructure is robust and well-tested by our CI pipeline. The [Docusaurus site](https://docusaurus.io/) already uses it in production, and we plan to use it on other Meta docs sites as well.
Started using _faster_ for faster builcs.
webpack kept as dep due to  
> ➤ YN0002: │ weave-gitops-docs@workspace:. doesn't provide webpack (pd0468), requested by file-loader and other dependencies.
To reduce build time from 6m to 2m20s
https://github.com/weaveworks/weave-gitops/actions/runs/12546069919/job/34981281244 …

chore: use rspack for faster builds

---

babel.config.js
babel.config.json
jest.config.js

> @parcel/transformer-babel: It looks like you're using a JavaScript Babel config file. This means the config cannot be watched for changes, and Babel transformations cannot be cached. You'll need to restart Parcel for changes to this config to take effect. Try using a babel.config.json file instead.

chore: use json babel

---

.golangci.yaml
core/clustersmngr/cluster/delegating_cache_test.go
pkg/run/install/apply_manifests.go

Closes
Enable the `nolintlint` linter.
There is no point in having `nolint` statements without effect in the codebase.

chore: enable nolintlint linter

---

.github/workflows/chart.yaml
.github/workflows/pr.yaml
.github/workflows/release.yaml
.github/workflows/upgrade-flux.yaml

Closes
Migrate use of the deprecated GHA set-output commands. Ref. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
While looking through the CI logs, I noticed warnings around this:

ci: migrate deprecated set-output commands

---

Makefile
go.mod
go.sum

Closes
Also removing the version specifier for Ginkgo in the Makefile. As described in https://onsi.github.io/ginkgo/#installing-ginkgo, this specifier should not be required if installing Ginkgo from within our main Go module.
Will allow future upgrades of Ginkgo by just merging Depedanbot PRs like https://github.com/weaveworks/weave-gitops/pull/4342.

test(deps): bump Ginkgo to version 2.22.2

---

.github/workflows/docs.yaml
.github/workflows/prepare-release.yaml

Closes
Update docs deploy rule to fix dependabot PR's

Update docs deploy rule

---

core/server/suite_test.go
pkg/services/check/check_test.go

Closes
Migrate calls to the deprecated `NewSimpleClientset `function.
Avoid using deprecated functionality.

refactor: migrate calls to deprecated NewSimpleClientset

---

core/clustersmngr/factory.go
core/fluxsync/fluxsync.go
core/server/crd.go
core/server/crd_test.go
core/server/events_test.go
core/server/featureflags_test.go
core/server/fluxruntime_test.go
core/server/inventory_test.go
core/server/objects_test.go
core/server/policies_test.go
core/server/policy_violations_test.go
core/server/server.go
core/server/suite_test.go
core/server/suspend_test.go
core/server/sync_test.go
core/server/version_test.go
pkg/services/crd/fetcher.go
pkg/services/crd/fetcher_test.go
pkg/services/crd/nocachefetcher.go
pkg/services/crd/suite_test.go

Closes #3812
Migrate to Poll* functions to the new ones accepting `context.Context`. 
Avoid using deprecated functions.

refactor: migrate calls to deprecated Poll* functions

---

core/server/suite_test.go

Closes
Migrate the use of the deprecated `Dial` function to the `NewClient` replacement.
Avoid using deprecated code.

refactor: migrate calls to deprecated grpc.Dial

---

.github/dependabot.yml

Closes
The current react Dependabot group is too wide, making https://github.com/weaveworks/weave-gitops/pull/4363 worthless.
This PR improves the group definition by looking at the proposed versions in https://github.com/weaveworks/weave-gitops/pull/4363. Over time, I think that will be a better approach. I will try to follow up deps that might be missing from the group.
Create mergeable Dependabot PRs.

ci(deps): improve react Dependabot group

---

.github/dependabot.yml

Closes
https://github.com/weaveworks/weave-gitops/pull/4363 is still borked, and I think Depedabot group patterns are matching on prefix and not exact. Which means we need to use exclude-patterns to ungroup deps we don't want to group with React upgrades.

ci(deps): Dependabot group patterns match prefix

---

.github/dependabot.yml

Closes
Extand YAML aliases since they are not yet supported by Dependabot, ref. https://github.com/dependabot/dependabot-core/issues/1582
Working Dependabot configuration.

ci(deps): no YAML alias support in Dependabot config

---

.github/dependabot.yml

Closes
Yet another attempt to create working Dependabot groups.
I am pretty sure ChartGPT is wrong about the Dependabot matching on prefix. It seems like it matches exact and that we have to use `*` to get any wildcard functionality.

ci(deps): yet another attempt to fix Dependabot grouping

---

babel.config.json
package.json
yarn.lock

Closes
Tune direct dependencies to babel packages:
- Replaced `@babel/preset-env` with `@parcel/babel-preset-env`.
- Removed dependency to `@babel/preset-react` as it seems unused.
The current build is generating warnings, which I think might block upgrades of dependencies.
Before:
````
@parcel/transformer-babel: Parcel includes transpilation by default. Babel 
config babel.config.json includes the following redundant presets: 
@babel/preset-env. Removing these may improve build performance.
/home/runner/work/weave-gitops/weave-gitops/babel.config.json:4:[13](https://github.com/weaveworks/weave-gitops/actions/runs/12616980125/job/35158760634#step:7:14)
3 |         [
> 4 |             "@babel/preset-env",
>   |             ^^^^^^^^^^^^^^^^^^^ …
```

fix: babel/parcel build warnings

---

.github/workflows/pr.yaml

Closes
The default retention time for upload action is 90 days. This is not required for image tar's - which are also currently unused.
Reduce storage use.

ci: reduce retention to minimum for uploaded image tar's

---

.github/workflows/docs.yaml
.github/workflows/pr.yaml
.github/workflows/trigger.yaml

Closes
Tuning conditions for specific jobs that should only run on the `main` branch in the upstream repo.
Since I've now started using codespaces, I need to keep my fork up-to-date. Every time I resync my fork, I get emails about failing jobs. This is annoying.

ci: avoid failing jobs when syncing fork

---

package.json
website/package.json
website/yarn.lock
yarn.lock

Closes
An attempt to clean up yarn "resolutions" as much as possible. Hopefully this change won't break anything. I wonder why @casibbald locked commander to version 11.0.0 in https://github.com/weaveworks/weave-gitops/pull/4258, and not the latest version?
The initial motivation was this Dependabot error:
````
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------+
| Dependencies failed to update |
+---------------+---------------+
| commander     | unknown_error |
+---------------+---------------+
Failure running container a34eb083ffc9c00a60c42dd811a8aeec342944b5d2345b3eb26461f3002bd78d
Cleaned up container a34eb083ffc9c00a60c42dd811a8aeec342944b5d2345b3eb26461f3002bd78 …
```

fix: clean up inefficient resolutions

---

tsconfig.json

Reverts weaveworks/weave-gitops#4437
`
@parcel/core: ui/components/Input.tsx does not export 'InputProps'
/home/runner/work/weave-gitops/weave-gitops/ui/index.ts:100:890
99 |   useListFluxRuntimeObjects,
> 100 |   useListRuntimeObjects,
>     |                         ^
101 |   useListRuntimeCrds,
102 |   useToggleSuspend,
`

Revert "fix: bump ts config target to ES2018"

---

.golangci.yaml
Makefile

Closes
Add a new Makefile target to facilitate fixing lint issues in Go and Proto (API). Also refactoring the setup of these tools a bit. I am not a big fan of one project "dictating" my global installation of tools, so from now on we will use a local bin directory for golangci-lint and protolint binaries. 😉 
Triggered by https://github.com/weaveworks/weave-gitops/pull/4466. Especially for the GCI linter, an auto-fix target is useful for contributors to get imports organized according to the spec.

ci: new lint-fix make target

---

.github/workflows/build-image.yaml
.github/workflows/pr.yaml

Closes
This replaces the image-build jobs in the PR workflow. We need to find a new home for our images anyway, and GHCR seems like our best option. After merging this PR, we should expect images pushed to our GHCR with the default branch name tag (`main`).
Future work:
- Review dockerfiles with regards to caching. I have a feeling that it's not optimal now. I would expect better performance, but appears to be an improvement already now.
- Add keyless signature to images using Cosign.
Prepare CI for our first community release.

ci: init new workflow to build images

---

core/clustersmngr/cluster/single.go
core/clustersmngr/factory.go

Closes
initializing logger earlier on in start process
`
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 434 [running]:
>  runtime/debug.Stack()
>  	/usr/local/go/src/runtime/debug/stack.go:26 +0x64
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/log/log.go:60 +0xa0
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0x4000132580, {0x3291787, 0x14})
>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/log/deleg.go:147 +0x34
>  github.com/go-logr/logr.Logger.WithName({{0x3600dc8, 0x4000132580}, 0x0}, {0x3291787, 0x14})
>  	/go/pkg/mod/github.com/go-logr/logr@v1.4.2/logr.go:345 …

Logger initialization issue

---

.golangci.yaml
core/server/inventory.go

Closes https://github.com/weaveworks/weave-gitops/pull/4193
Fix bug with odd number of key/value pairs sent to logger. There is already an open PR to fix this, but we got no response from the author: https://github.com/weaveworks/weave-gitops/pull/4193.
I am also adding a linter to avoid this from happening again: https://github.com/timonwong/loggercheck
Without fixing the bug, but enabling the new linter, it fails:
````
$ make lint
/home/erikbo/projects/github/weave-gitops/bin/golangci-lint run
core/server/inventory.go:290:74: odd number of arguments passed as key-value pairs for logging (loggercheck)
logger.Error(err, "failed to determine if %s is namespace scoped", obj.GetObjectKind().GroupVersionKind().Kind)
^
make: *** [Makefile:113: lint] Error 1
````
**Why was …

fix: call to logger with odd number of key/value params

---

.github/workflows/pr.yaml

Closes
Adds keyless signing (and verification) of images to the PR workflow. We obviously want to sign our release images, but let's start somewhere. The work here is based on [this blog post](https://blog.saintmalik.me/keyless-signing-container-images-github-oidc/). This might need a couple of iterations, but we have to start somewhere. The blog states that the file workflow file must be named `*keyless.yaml`. Let's find out. 😉 
Supply chain attacks are a serious challenge for the software industry, and image signing can help.

ci: first cut on signing images with Cosign

---

.github/workflows/pr.yaml

Closes
Another fix to https://github.com/weaveworks/weave-gitops/pull/4483. This tries to supply the full image digest to the cosign commands. Extract from the last attempt to sign the image on the `main` branch:
````
Generating ephemeral keys...
Retrieving signed certificate...
Successfully verified SCT...
WARNING: Image reference sha256:d611992eaadc602663757af08eba581126d6f518184fe66ec45198aba84cf7dd uses a tag, not a digest, to identify the image to sign.
This can lead you to sign a different image than the intended one. Please use a
digest (example.com/ubuntu@sha256:abc123...) rather than tag
(example.com/ubuntu:latest) for the input to cosign. The ability to refer to
images by tag will be removed in a future release.
Error: signing …
```

ci: correct image input to sign command

---

.github/workflows/pr.yaml

Closes
Now the signing seems to work, but there is an error in the sign verification command which is corrected in this PR.
Make the `main` branch CI green again.

ci: correct image sign verify command

---

.github/dependabot.yml

Closes
Include `@eslint/*` in `eslint` Dependabot group.
https://github.com/weaveworks/weave-gitops/pull/4497 and https://github.com/weaveworks/weave-gitops/pull/4495 indicates that `@eslint/js` should be included into the group - since the releases seems corrdinated.

ci(dependabot): extend eslint group

---

.golangci.yaml
cmd/gitops-server/cmd/cmd.go
cmd/gitops/root/cmd.go
cmd/gitops/set/config/cmd.go
core/server/inventory.go
pkg/analytics/analytics.go
pkg/config/config.go
pkg/config/config_test.go
pkg/http/server.go
pkg/http/server_test.go
pkg/kube/kube_suite_test.go
pkg/names/names.go
pkg/oidc/check/flow_test.go
pkg/oidc/check/server.go
pkg/s3/auth_middleware_test.go
pkg/s3/secret_test.go
pkg/server/auth/auth.go
pkg/server/auth/server.go
pkg/services/auth/github.go
pkg/services/auth/internal/gitlab.go
pkg/services/auth/types/token_test.go
pkg/utils/string.go

Closes
Introduced the gosec linter. Some issue are fixed, and some rules are excluded.
Improve code quality and put awareness on code security issues.

chore(go): introduce gosec linter

---

gitops-server.dockerfile
gitops.dockerfile

Closes
Improves the [cache mounts](https://docs.docker.com/build/cache/optimize/#use-cache-mounts) already present in our Dockerfiles. I have a feeling they were configured before Go got it's own cache for modules.
Better performance on container builds.

ci: improve caching in Dockerfiles even more

---

.github/workflows/pr.yaml

Closes
Slightly improve the upload binary CI job. Since I couldn't find a way to create a "generic" GH package, I suggest starting by replacing the out-commented AWS S3 upload with upload-artifact-action. This will keep the binaries available for the default project retention period (30 days)?
I have accidentally reformatted this code several times in other PR, and in general I am not a big fan of out-commented code. We can always find old things in the Git history. 

ci: upload binaries as workflow artifacts

---

pkg/oidc/check/flow_test.go

Closes https://github.com/weaveworks/weave-gitops/issues/4503
Replace the use of `http.Server` with `httptest.Server` in `flow_test.go`. Also removing the need for a new goroutine.
I believe this should fix https://github.com/weaveworks/weave-gitops/issues/4503, but since the tests only stall occasionally, I am not 100% sure. But I was able to reproduce the issue locally before this change, and not able after. 🙏 

test: replace http.Server with httptest.Server

---

.github/workflows/release.yaml
.goreleaser.yml

Closes
Configure Cosign keyless signing of all release artifacts to the (Goreleaser) release workflow. I am not sure this will work, but there is a fair chance it will. Goreleaser docs: https://goreleaser.com/customization/sign/. I searched the Internet for references, and it seems like Chainguard has done something around this. I just copied https://github.com/chainguard-dev/apko/blob/64e3ae0d1cf09e2e83dd384cd5a4f9c06d48e0a4/.goreleaser.yaml#L34-L39, which should end up like this (Assets; example): https://github.com/chainguard-dev/apko/releases/tag/v0.22.6.
Allow our users to verify release artifacts before actually using/installing them. …

ci(release): keyless sign of release artifacts with Cosign

---

package.json
ui/components/DagGraph.tsx
yarn.lock

Reverts weaveworks/weave-gitops#4407
`
2025-01-15T10:47:41.225Z	INFO	gitops	cmd/cmd.go:301	Starting server	{"address": "0.0.0.0:9001"}
2025-01-15T10:47:41.225Z	INFO	gitops	cmd/cmd.go:358	TLS connections disabled
2025-01-15T10:47:41.230Z	INFO	gitops	cmd/cmd.go:326	Starting metrics endpoint	{"address": ":2112"}
2025-01-15T10:47:42.132Z	DEBUG	gitops	middleware/middleware.go:59	request success	{"uri": "/", "status": 200}
2025-01-15T10:47:42.165Z	ERROR	gitops	cmd/cmd.go:304	server exited	{"error": "http: Server closed"}
2025-01-15T10:47:50.814Z	DEBUG	gitops	middleware/middleware.go:59	request success	{"uri": "/", "status": 200}
2025-01-15T10:56:19.908Z	DEBUG	gitops	middleware/middleware.go:59	request success	{"uri": "/", "status": 200}
→ 🚨 Build failed.
→
→
→ @parcel/core: …

Revert "build(deps): Bump d3-dag from 0.11.5 to 1.1.0"

---

tools/dev-resources/image-policy/podinfo-image-update-automation.yaml

Closes
Image automation refers to incorrect details
to correct image automation in the dev-resources

fix: correct image automation git repository for podinfo

---

.github/workflows/nightly.yaml
.github/workflows/ossf.yaml
.github/workflows/pr.yaml

Closes
Issues with commit hashes after dependabot update
failing security checks

ci: fix scorecard errors

---

ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx

Whilst testing the react router change, I observed that links to container images on docker.io, ghcr and others resulted in a broken URL that didn't resolve to anywhere.
It is likely that this functionality never worked as the image URL was never resolved back to its upstream counterpart as implemented in the `convertImage` function.
This change is necessary to ensure container images link out to the correct location to engineers can better understand the continers running inside their cluster workloads.
This change addresses the need by: wrapping container image links in the `convertImage` function

Fix: Broken image links for container images

---

.github/dependabot.yml

Closes
Replace excluded dependency from the react Depedabot group.
After https://github.com/weaveworks/weave-gitops/pull/4540, we depend on react-router instead of react-router-dom.

ci(dependabot): replace excluded dep in react group

---

eslint.config.mjs
package.json
yarn.lock

Closes
I tried to merge in the changes performed in https://github.com/weaveworks/weave-gitops/pull/4182, but there were some massive conflicts. So I decided not to risk breaking the application and instead turned off the new recommended rules currently broken. We should try to fix this in follow-up PRs.
Increase code quality.

ci(lint): add react and react-hook eslinters

---

go.mod
go.sum
pkg/testutils/testutils.go

Closes
Replace use of go-jose v2 (deprecated) with v4.
During a "tour" in the many Go dependencies, I noticed this section: https://github.com/go-jose/go-jose?tab=readme-ov-file#versions. We should try to use maintained software.

chore(go): use maintained go-jose v4

---

eslint.config.mjs
ui/components/BucketDetail.tsx
ui/components/GitRepositoryDetail.tsx
ui/components/HelmChartDetail.tsx
ui/components/HelmReleaseDetail.tsx
ui/components/HelmRepositoryDetail.tsx
ui/components/KustomizationDetail.tsx
ui/components/OCIRepositoryDetail.tsx
ui/components/PodDetail.tsx

Closes
Fix violations and enable the recommended lint rule.
Mainly to enable the recommended lint rule.

chore(lint): fix react/jsx-key violations

---

eslint.config.mjs
ui/lib/__tests__/graph.test.ts
ui/lib/fonts.ts
ui/lib/test-utils.tsx

Closes
Enable `@typescript-eslint/ban-ts-comment` rule, one of the the` typescript-eslint` recommended rules.
Besides being recommended, I think the rule makes a lot of sense. Now a developer must add a comment to why Typescript error is ignored.

ci(lint): enable @typescript-eslint/ban-ts-comment eslint rule

---

.golangci.yaml
cmd/gitops-server/cmd/cmd.go
core/clustersmngr/factory.go
core/server/fluxruntime.go
core/server/inventory.go
core/server/objects.go
core/server/policies.go
core/server/policy_violations.go
pkg/fluxexec/exit_errors.go
pkg/fluxexec/fluxexec.go
pkg/fluxinstall/errors/errors.go
pkg/fluxinstall/installer.go
pkg/gitproviders/provider.go
pkg/gitproviders/provider_org.go
pkg/http/server.go
pkg/kube/kubehttp.go
pkg/oidc/check/server.go
pkg/run/utils.go
pkg/services/gitrepo/service.go
pkg/testutils/testutils.go
pkg/utils/common.go
pkg/validate/validate.go

Closes
Enable errorlint linter to detect code that will not work with wrapped errors.
Allow safe use of wrapped errors in our codebase.

ci(lint): enable errorlint linter

---

ui/components/Alert.tsx
ui/components/AlertListErrors.tsx
ui/components/Button.tsx
ui/components/DagGraph.tsx
ui/components/DarkModeSwitch.tsx
ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/ErrorList.tsx
ui/components/Nav.tsx
ui/components/ReconciliationGraph.tsx
ui/components/SearchField.tsx
ui/components/SubRouterTabs.tsx
ui/components/Sync/ResumeIcon.tsx
ui/components/Sync/SyncControls.tsx
ui/components/Sync/__tests__/__snapshots__/SyncActions.test.tsx.snap
ui/components/Sync/__tests__/__snapshots__/SyncControls.test.tsx.snap
ui/components/UserSettings.tsx
ui/components/YamlView.tsx
ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
ui/components/__tests__/__snapshots__/MessageBox.test.tsx.snap
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
ui/lib/theme.ts

This PR cleans up a number of stylistic issues I have noticed in the UI.
Each style change is a distinct commit on the PR to aid in isolation and be able to describe what each change is as part of its commit rather than trying to raise each one as a separate PR.
Whilst browsing the UI I have noticed a number of stylistic issues, particularly in Dark mode that in some cases are the result of the switch from Material UI 4 to Material UI 5.
* `6b19b10a6` Button styling fixes
* `2f4024ef1` Link hover states for sidebar and tabs
* `5c8c3ce4f` Search field showed as wrapper to filter button
* `9121cd8a6` Styling changes for light mode to make it less harsh
* `54e909083` YAML sidebar in dark mode
* `d9e5edb43` Fix alerts import and styling
* …

Styling cleanup

---

jest.config.js
package.json
ui/components/DarkModeSwitch.tsx
ui/components/DataTable/__tests__/DataTable.test.tsx
ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
ui/components/Sync/__tests__/SyncActions.test.tsx
ui/components/Sync/__tests__/SyncControls.test.tsx
ui/components/Sync/__tests__/__snapshots__/SyncActions.test.tsx.snap
ui/components/Sync/__tests__/__snapshots__/SyncControls.test.tsx.snap
ui/components/__tests__/Flex.test.tsx
ui/components/__tests__/KubeStatusIndicator.test.tsx
ui/components/__tests__/Logo.test.tsx
ui/components/__tests__/MessageBox.test.tsx
ui/components/__tests__/Metadata.test.tsx
ui/components/__tests__/Page.test.tsx
ui/components/__tests__/Text.test.tsx
ui/components/__tests__/Version.test.tsx
ui/components/__tests__/YamlView.test.tsx
ui/components/__tests__/__snapshots__/Flex.test.tsx.snap
ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
ui/components/__tests__/__snapshots__/MessageBox.test.tsx.snap
ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
ui/components/__tests__/__snapshots__/Page.test.tsx.snap
ui/components/__tests__/__snapshots__/Text.test.tsx.snap
ui/components/__tests__/__snapshots__/Version.test.tsx.snap
ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
ui/contexts/__tests__/CoreClientContext.test.tsx
ui/lib/utils.ts
yarn.lock

This commit upgrades the testing library from `react-test-renderer` to `@testing-library/react`.
This largely results in changes to `renderer.create().toJSON()` becoming `render().asFragment()`. To ensure minimal snapshot changes were recorded, I used `firstChild` from the fragment so the fragment wrapper was not added to the snapshots.
This change was made to replace the deprecated `react-test-renderer` with a more modern equivelent which is compatible with future versions of React framework
**Side effects**
During testing, a large number of failure messages such as:
```plaintext
An empty string ("") was passed to the src attribute
```
This message would cause tests to fail and is the result of `svg` images being passed to the fileMock in …

Replace deprecated testing library in unit tests

---

eslint.config.mjs
ui/components/DagGraph.tsx
ui/components/DirectedGraph.tsx

Closes
Fix and enable the react/no-unknown-property eslint rule.
Follow-up after introducing react eslint. The react/no-unknown-property rule is a recommended rule.

ci(lint): fix react/no-unknown-property eslint violations

---

eslint.config.mjs
ui/components/InfoModal.tsx
ui/components/Policies/PolicyDetails/PolicyDetails.tsx
ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
ui/components/Sync/SuspendMessageModal.tsx
ui/contexts/GithubAuthContext.tsx

Closes
Fixed react/no-children-prop eslint violations and enabled the rule.
Follow-up after introducing react eslinter. The react/no-children-prop rule is a recommended rule.

ci(lint): fix react/no-children-prop eslint violations

---

.github/workflows/helm.yaml
website/update-screenshots.js

Closes
This removes the publishing of the Helm chart to the https Helm repository, leaving OCI as the only option for installing the Helm chart. Also updated the Helm install example in the docs.
We no longer have access to the `helm.gitops.weave.works` domain, and OCI is now the preferred mechanism for publishing Helm charts.

ci(release): remove publish to https Helm repository

---

.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
.github/workflows/upgrade-flux.yaml
.goreleaser.brew.yml
README.md
pkg/services/gitrepo/service.go
website/src/pages/security/cve/enterprise/CVE-2022-38790.md

Closes
Remove last identified emails and few other links that are non API related
move away from commercial identity

remove remaining weave.works email addresses

---

.github/workflows/nightly.yaml
requirements.txt

Closes
- Create a pip requirements file to manage Python dependencies required for the nightly (Playwright) workflow.
- Upgrade Python to 3.12 (not the latest, but pretty stable).
- Introduce caching of pip dependencies in the workflow.
This change was triggered by alerts about unpinned dependencies from our security scanner. But I also believe this setup is cleaner and more performant (caching).

ci: improve python setup in nightly workflow

---

Makefile
core/clustersmngr/factory.go
core/clustersmngr/factory_caches.go

Closes
- Enable Go [race detector](https://go.dev/doc/articles/race_detector) for Go testing (which requires `CGO_ENABLED=1`)
- Fix a race detected by the detector when running tests.
I am trying to figure out why the Go tests sometimes blocks "forever" in CI. Example: https://github.com/weaveworks/weave-gitops/actions/runs/12973902776/job/36183126193. And I have a feeling this problem is related to Goroutines, missing error handling and/or races. I want to eliminate the latter, so I suggest we enable the race detector for the tests.

chore(go): enable race detector in tests

---

.github/dependabot.yml

Closes
- Merge the Dependabot npm sections for F/E app and docs.
- Remove "obvious" comments.
As we are now aligned with dependency upgrades, I don't see the need to duplicate Dependabot groups for app and docs.

ci(dependabot): deduplicate configuration

---

.github/workflows/nightly.yaml

Closes
Pin all actions in the nightly workflow to use SHA.
Reported by our security scanner.

ci: pin actions in nightly workflow

---

core/server/suite_test.go
pkg/run/install/install_suite_test.go
pkg/run/run_suite_test.go
pkg/server/auth/auth_test.go
pkg/testutils/testutils.go

Closes
The primary change in this PR is removing an unused controller-runtime `Manager`. I have no idea why the test setup was created this way, but we don't need to create a Manager (heavy) just to create a controller-runtime `Client`.
In addition, I made all use of the test-helper consistent (stopping testEnv).
Also improving a flaky test with Ginkgo `Eventually` - as it was bugging me while verifying this change. 🤠 
Still trying to dig into the occasionally blocked tests.

test(go): remove unused controller-runtime Manager

---

.github/dependabot.yml

Closes
"Smart" revert of https://github.com/weaveworks/weave-gitops/pull/4621: Reintroduce a dedicated Dependabot group for website upgrades, but one PR for all upgrades.
I was not very happy with the way Dependabot supports multiple directories. We should not mix F/E app and doc updates the way Dependabot does.

ci(dependabot): reintroduce website group

---

pkg/server/auth/auth_test.go

Closes
Refactor a test that is flaky, at least on my workstation, to something more "bullet proof".
I was struggling with this when working on https://github.com/weaveworks/weave-gitops/pull/4626. I tried to fix it in that PR, but the test still fails occasionally.

test(go): refactor flaky auth test

---

.github/workflows/pr.yaml

Reverts weaveworks/weave-gitops#4631
It seems like this action is made to only run on pull requests, and it's failing on the main branch now.

Revert "ci: add dependency review job to PR workflow"

---

charts/gitops-server/templates/role.yaml
charts/gitops-server/values.yaml

Relates to https://github.com/weaveworks/weave-gitops/issues/3702
This adds a new value to the Helm chart that allows opting out from cluster-wide read access to secrets.
It seems like this permission isn't required, at least not in the current community-only version. Let's see what is required when we eventually fold in the enterprise features later on.

feat(helm): new value to opt-out from cluster-wide view access to secrets

---

core/nsaccess/nsaccess.go

Relates to https://github.com/weaveworks/weave-gitops/issues/3702
The primary change in this PR is to add `ocirepositories` to the `source.toolkit.fluxcd.io` in the required RBAC rules. This should be part of the requirements alongside the other Flux source types - as weave-gitops is able to list source resources. I did **not** add any requirement for access to the Flux API groups `notification.toolkit.fluxcd.io` or `image.toolkit.fluxcd.io` - even if I think it's strange that this is not a requirement.
I have also organized the required rules better:
- Grouped by API group in list of requirements.
- Fixed the semi-duplicated requirements for events.
- Sorted resources in rules alphabetically.
Before starting on the simpler nsaccess checker …

fix: add ocirepositories to nsaccess rules

---

.github/dependabot.yml

Closes
Standardize the Dependabot configuration for all package-types to a weekly schedule and default max open pull requests (5).
We had a huge backlog of dependency updates, but we are now up-to-date. And no need to run dependency checks as often. We can always force check for dependency updates manually - if required.

ci(dependabot): normalize Dependabot configuration

---

.goreleaser.brew.yml
.goreleaser.yml

Closes
Fixes issues reported by `goreleaser check`.
Before:
````
$ goreleaser check
• failed to set GOMAXPROCS                         error=open /mnt/wsl/var/lib/docker/overlay2/23566a852a3049a969d29135dcd72d6ea1666428956eb4497f3b3f6ecfdeb13c/merged/sys/fs/cgroup/cpu/cpu.cfs_quota_us: permission denied
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
• checking                                 path=.goreleaser.yml
• DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed …
```

ci(release): improve goreleaser configuration file

---

.github/workflows/upgrade-flux.yaml

Closes
Disable the upgrade-flux workflow in forks. It should only run in the main repo, as it will fail in "any" fork.
I was getting failing runs in my fork after Flux 2.5 was released.

ci: Disable upgrade-flux workflow in forks

---

.github/workflows/lint-pr.yaml

Closes
This PR removes the strict requirement for an initial uppercase character in the (convention commit) PR title.
This will add less "fuzz" to the general contribution process, which has already annoyed me. 😉 But after discovering that release-please has a [plugin to ensure nice release notes](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#sentence-case), even with mixed case subjects, I don't think this strict requirement is required anymore.
Relates to https://github.com/weaveworks/weave-gitops/pull/4824.

ci: Don't require specific casing in PR title

---

ui/components/__tests__/Footer.test.tsx
ui/components/__tests__/__snapshots__/Footer.test.tsx.snap

Closes
Add mocking of the `package.json` version in the footer snapshot UI test.
Done to fix CI in release-please PRs like https://github.com/weaveworks/weave-gitops/pull/4834.

test(ui): make footer snapshot test independent of npm module version

---

.github/workflows/release-please.yaml

Closes
Configure release-please workflow to not run in forks.
I just resynced my fork which made the release-please workflow run and fail.

ci(release): don't run release-please workflow in forks

---

.github/dependabot.yml

Closes
Tune Dependabot configuration with the following goals:
- Conventional commits better aligned with automated release notes generated by release-please.
- More efficient upgrade process. This includes more grouping for non-user-facing dependency upgrades.
I want release-please to propose a new release whenever a production dependency is bumped. I also want the production dependency upgrades to be included in the release notes - without the noise from other dependency upgrades. In addition, I want a bit more efficient dependency upgrade PR process.

ci(dependabot): improve config for release-please

---

.golangci.yaml
Makefile
core/server/events.go
pkg/run/watch/forward_port.go
pkg/s3/auth_middleware.go
pkg/services/auth/jwt.go
pkg/sourceignore/sourceignore_test.go

Closes
Upgrade golangci-lint to v2 by first running the provided migration `golangci-lint migrate`, but since this migration doesn't port comments, I have tried to port them manually to the correct location. The set of linters available has changed a little with v2. As an example, `tenv` is removed and replaced by `usetesting`. I didn't want to change too much code, so I disabled some checks in this new linter. These should probably be enabled as a follow-up.
To follow the evolution of golangci-lint. I had plans adding some new linters first, but figured out they required golangci-lint v2.

ci: upgrade golangci-lint to v2

---

.github/workflows/docs.yaml
.github/workflows/helm.yaml
.github/workflows/pr.yaml
.github/workflows/scan.yaml

Closes
This change should ensure all PR workflows are cancelled when new commits are added to the PR branch. This improvement is already suggested in https://github.com/weaveworks/weave-gitops/pull/3733, but I think the proposed syntax in that PR is incorrect. The PR also has conflicts that need to be resolved.
Close https://github.com/weaveworks/weave-gitops/pull/3733 
I want to add CI that eventually will update release-please PR branches to include doc updates in the release PR. This seems to be the suggested approach, ref. https://github.com/googleapis/release-please/issues/2022#issuecomment-1650651529.
Not wasting workflow resources appears like a good idea. …

ci: cancel PR workflows on new commits

---

ui/components/ProviderDetail.tsx
ui/components/__tests__/ProviderDetail.test.tsx

Fixes #4723
I think the alerts should be filtering on provider name instead of type.
In fact, users can configure another provider's name than the type's name of Flux provided (e.g. Name: discord-bot, type: discord)
Unit test is added
The alerts are not shown on the table
No

fix: Filter alerts on name (was type)

---

release-please-config.json

Closes
The main change in this PR, is to configure release-please to create separate release PRs per package (app and Helm). The grouped release PR (https://github.com/weaveworks/weave-gitops/pull/4870) is wrong, and I haven't found a way to fix it. So I will attempt to create a more suboptimal workflow that actually does things right.
Because of a buggy grouped release PR, see https://github.com/weaveworks/weave-gitops/pull/4870/files#r2118236318.

ci: another round of adjustments to release-please configuration
